
=  Slint Handbook (14.2.1)
:toc: left
:toclevels: 2
:toc-title: Περιεχόμενα
:pdf-themesdir: themes
:pdf-theme: default
:sectnums:

==  Εισαγωγή στο Slint

=== Σχετικά Με Slint

Το Slint είναι μια https://en.wikipedia.org/wiki/Linux_distribution[διανομή Linux], βασισμένη στο http://www.slackware.com/[Slackware], polyglot, εύκολο στην εγκατάσταση, ευέλικτο, αρχάριος φιλικό και προσβάσιμο με τα άτομα με προβλήματα όρασης.

Ένα σύστημα Slint είναι λειτουργικό έξω από το κουτί και μπορεί να προσαρμοστεί για να χωρέσει τις περισσότερες απαιτήσεις υπολογιστών.

==== Χαρακτηριστικά

Προτείνονται δύο τρόποι εγκατάστασης: Αυτόματη (δεν υπάρχει εντολή Linux για να πληκτρολογήσετε) και Εγχειρίδιο για το ποιος θέλει περισσότερη προσαρμογή. Ο εγκαταστάτης περιλαμβάνει μια τεκμηρίωση.

Το Slint είναι προσβάσιμο σε χρήστες με προβλήματα όρασης, με ομιλία και braille, από την εγκατάσταση έως τη χρήση σε μια κονσόλα όπως σε γραφικά περιβάλλοντα.

Μια ευρεία ποικιλία λογισμικού για διακομιστές, επιτραπέζιους υπολογιστές, και φορητούς υπολογιστές είναι εγκατεστημένο σε όλα τα συστήματα Slint, που περιλαμβάνουν διάφορα γραφικά περιβάλλοντα γραφείου: KDE (προαιρετικά), LXDE, MATE, XFCE και ελαφρούς διαχειριστές παραθύρων. Όλα τα γραφικά περιβάλλοντα παρέχουν εύκολη πρόσβαση σε όλες τις εφαρμογές και τις λειτουργίες του συστήματος, με αυτόματη τοποθέτηση αφαιρούμενων συσκευών, συν ειδοποιήσεις των διαθέσιμων ενημερώσεων του εγκατεστημένου λογισμικού, άμεση πρόσβαση στο Διαδίκτυο, σταμάτηση, επανεκκίνηση, και αδρανοποίηση του συστήματος. Κάθε περιβάλλον επιφάνειας εργασίας παρέχει παρόμοια διάταξη των πινάκων και το μενού της εφαρμογής για να παρέχει ένα συνεπές περιβάλλον.

Η επιλεγμένη γλώσσα θα χρησιμοποιηθεί για διεθνοποιημένες εφαρμογές.

Ο πίνακας ελέγχου Slint συγκεντρώνει πρόσβαση σε ρυθμίσεις υλικού και συστήματος, πακέτα, εργαλεία συστήματος, τεκμηρίωση και βοηθητικά προγράμματα.

Slint πλοία με πολλές εφαρμογές έξω από το πλαίσιο για να γράψει και να διαβάσει και να μετατρέψει έγγραφα σε διάφορες μορφές, επικοινωνούν με ηλεκτρονικό ταχυδρομείο, κείμενο και ηχητική συνομιλία, αναπαραγωγή ήχου και βίντεο, αποστολή και λήψη εγγράφων ομότιμος με ομότιμο, επεξεργασία ήχου, βίντεο και γραφικών εγγράφων, ανάπτυξη εφαρμογών. Είναι πλήρως χρησιμοποιήσιμο ως διακομιστής σε μια κονσόλα και χρησιμοποιώντας μία από τις πολλές περιλαμβάνονται desktops.

Πολλές εφαρμογές είναι προσβάσιμες σε χρήστες με προβλήματα όρασης, μια ευρεία επιλογή TTS και οι σχετικές φωνές περιλαμβάνονται, αν εξακολουθείτε να χρειάζεστε άλλους που είναι εύκολα εγκαταστάσιμοι, μπορούν να χρησιμοποιηθούν τόσο σε κειμενικό περιβάλλον (κονσόλα) όσο και στην επιφάνεια εργασίας.

Αρκετά εσωτερικά εργαλεία διευκολύνουν τη διαχείριση και τη διαμόρφωση του συστήματος Slint.

Πολλές περισσότερες εφαρμογές είναι εύκολα κατασκευασμένες ως πακέτα λογισμικού μέσω μιας απλής εντολής ή μερικά κλικ. Χιλιάδες πακέτα λογισμικού είναι στα χέρια σας!

Οι χρήστες του Slint ειδοποιούνται για αναβαθμίσεις εγκατεστημένων πακέτων μόλις είναι διαθέσιμα, εύκολα εγκατεστημένα κατόπιν αιτήματος. Αυτό διατηρεί το σύστημά σας ασφαλές.

Προεπιλεγμένες ρυθμίσεις εφαρμογών παρέχονται και μπορούν εύκολα να προσαρμοστούν.

==== Περιεχόμενο, εκδόσεις και μοντέλο απελευθέρωσης.

Το πρόγραμμα εγκατάστασης Slint παρέχει μόνο μια πλήρη εγκατάσταση. Μόνο η επιφάνεια εργασίας του KDE είναι προαιρετική.

Το Slint βασίζεται στο Slackware, τείνουμε να παρέχουμε μια νέα έκδοση του Slint λίγο μετά την κυκλοφορία μιας έκδοσης Slackware.

Ωστόσο η Slint ακολουθεί μοντέλα απελευθέρωσης "ημι-κύλισης", πράγμα που σημαίνει ότι κατά τη διάρκεια του κύκλου ζωής μιας δεδομένης έκδοσης, εκτός από τις ενημερώσεις ως διορθώσεις ασφαλείας και σημαντικές διορθώσεις σφαλμάτων, μερικά λογισμικό ενημερώνονται επιλεκτικά για να φέρει βελτιώσεις, και προστίθενται για να φέρει νέα χαρακτηριστικά. Αυτή είναι η περίπτωση για το λογισμικό που συμβάλλει στο να κάνει το Slint προσιτό στους τυφλούς, όπως οι αναγνώστες οθόνης.

Συνιστούμε οι χρήστες να μεταβούν σε μια νέα έκδοση το συντομότερο δυνατό μετά την έκδοσή της. Μέχρι στιγμής είμαστε σε θέση να παρέχουν οδηγίες και βοηθητικά σενάρια που επιτρέπουν την αναβάθμιση αντί από το μηδέν μια νέα έκδοση. Θα κάνουμε ό,τι καλύτερο μπορούμε για να παραμείνουμε δυνατοί με μελλοντικές εκδόσεις, ακόμα και αν ένα πλήρες αντίγραφο ασφαλείας των αρχείων των χρηστών, Ακολουθεί μια εγκατάσταση ένα νέο και μια αποκατάσταση των αρχείων των χρηστών μπορεί να είναι ευκολότερη, ειδικά για μια χρήση desktop ή laptop.

=== Σχετικά με αυτό το βιβλίο, άλλες πηγές πληροφοριών

Αυτό το βιβλίο προορίζεται για τον νεοφερμένο Slint τον οποίο καθοδηγεί μέσω της διαδικασίας εγκατάστασης και χρήσης του. Παρουσιάζονται οι έννοιες και οι συμβάσεις που αφορούν ειδικά το Slint και είναι κοινές στις διανομές του Linux και επισυνάπτεται ένα γλωσσάριο.

Προσπαθούμε να φιλοξενήσουμε λαούς που προέρχονται από Windows ή MacOS ως χρήστες μιας άλλης διανομής όπως το Ubuntu.

Τεκμηρίωση για εγκατεστημένο λογισμικό είναι γενικά διαθέσιμη σε ένα σύστημα Slint. Θα αναφέρουμε σε αυτό το βιβλίο πώς να έχει πρόσβαση σε αυτό.

Άλλες πηγές πληροφοριών είναι διαθέσιμες:

* Οι πληροφορίες που παρέχονται συχνά στην ιστοσελίδα τους από τους συγγραφείς του λογισμικού που περιλαμβάνονται στο Slint.
* http://docs.slackware.com/[Το έργο τεκμηρίωσης Slackware] και ιδιαίτερα τα άρθρα http://docs.slackware.com/howtos:start[HOWTO] Πολλά ισχύουν άμεσα για το Slint, μερικές προσαρμογές και ενημερώσεις μπορεί να είναι απαραίτητες.
* Πέρα από τη διανομή της Arch, το ArchWiki παρέχει συχνά χρήσιμο άρθρο για το λογισμικό που αποστέλλεται επίσης στο Slint. Για παράδειγμα η αναζήτηση του "archwiki mate" οδηγεί σε https://wiki.archlinux.org/index.php/MATE[αυτή τη σελίδα για το MATE]. Σεβώδης: οι παρεχόμενες πληροφορίες μπορούν να προσαρμοστούν καθώς οι Slint και Arch διαφέρουν από ορισμένες απόψεις. Για παράδειγμα το Arch χρησιμοποιεί το σύστημα ως init σύστημα και ένα δεδομένο λογισμικό μπορεί να ρυθμιστεί διαφορετικά από προεπιλογή στο Slint και την Arch.
* Και φυσικά μια μηχανή αναζήτησης στο Διαδίκτυο μπορεί συχνά να βοηθήσει στην εξεύρεση απαντήσεων σε ερωτήσεις και λύσεις σε ζητήματα.

=== Υποστήριξη

Μπορείτε να λάβετε βοήθεια μέσω αυτών των καναλιών:

* Η λίστα αλληλογραφίας του Slint είναι το κύριο κανάλι υποστήριξης. Για να εγγραφείτε, στείλτε email στο slint-request@freelists.org με θέμα 'εγγραφή' και μετά απαντήστε στο email επιβεβαίωσης που θα λάβετε. Στη συνέχεια, για να μάθετε περισσότερα email slint-request@freelists.org με θέμα «εντολές» ή «βοήθεια». Μετά την εγγραφή, email slint@freelists.org.
* Τα αρχεία της λίστας είναι διαθέσιμα https://www.freelists.org/archive/slint[εδώ].
* Στις IRC: συνομιλήστε στο κανάλι #slint, server irc.libera.chat, δεν απαιτείται εγγραφή.
* Mumble: server slint.fr (για ραντεβού που λήφθηκε μέσω ενός άλλου καναλιού).
* Το https://forum.salixos.org/viewforum.php?f=44[φόρουμ Slint] φιλοξενείται ευγενικά από τους φίλους μας στο Salix (άλλο παράγωγο Slackware. Απαιτείται εγγραφή.


Για να μάθετε περισσότερα, δείτε τους συνδέσμους στην ενότητα Πληροφορίες στο Slint Dasboard, επισκεφθείτε το https://slint.fr/wiki/doku.php?id=en/start[wiki] ή απλά πληκτρολογήστε: slint-doc σε ένα τερματικό μετά την εγκατάσταση.

=== Μετάφραση και άλλες συνεισφορές στο έργο Slint

Slint χρειάζονται μεταφραστές! Αν θέλετε να συμμετάσχετε στην προσπάθεια μετάφρασης, διαβάστε τις οδηγίες στο https://slint.fr/doc/translate_slint.html[Translate Slint].

Τα αρχεία μετάφρασης φιλοξενούνται στο https://crowdin.com/project/slint[Crowdin].

Αν θέλετε να συνεισφέρετε στο Slint για άλλες εργασίες, απλά δημοσιεύστε τη λίστα αλληλογραφίας ή αφήστε μια γραμμή στο: didieratslintdotfr. Φυσικά οι μεταφραστές είναι ευπρόσδεκτοι και στη λίστα αλληλογραφίας!

===  Ευχαριστίες

Το έργο Slint υπάρχει κυρίως μέσω της σκληρής δουλειάς των μεταφραστών του Slint και άλλων συνεισφερόντων, χάρη σε όλους σας!

Χάρη στον George Vlahavas για τις συμβουλές και τα εργαλεία του, στους συνεισφέροντες στο έργο SlackBuilds.org, οι οποίοι βοηθούν στην κατασκευή τόσων πολλών πρόσθετων λογισμικών.

Το Slint βασίζεται στο Slackware, που έφερε ο Patrick J. Volkerding και οι συντελεστές του. Ευχαριστούμε! Ενθαρρύνω όλους τους χρήστες του Slint να συνεισφέρουν στη χρηματοδότηση του Slackware και επίσης να δωρίσουν στο έργο Salix.

Τα αποθετήρια του Slint φιλοξενούνται δωρεάν από τον Darren 'Tadgy' Austin. Ενθαρρύνω όλους τους χρήστες του Slint να συνεισφέρουν στη χρηματοδότηση του κεντρικού υπολογιστή https://slackware.uk/

Links for financial contributions: +
https://www.patreon.com/slackwarelinux[Become a Slackware patron] or https://paypal.me/volkerdi[Υποστήριξη Slackware] +
Follow the links on top of http://slackware.uk/slint/x86_64/slint-14.2.1/[this page] to support Slackware UK +
https://salixos.org/donations.html[Donations to Salix]

==  Εγκατάσταση Γραμμής

Αυτό το μέρος του HandBook περπατά μέσα από τη διαδικασία λήψης του Slint, επαληθεύοντας την εικόνα ISO με ένα check-sum, γράφοντας το ISO σε ένα μέσο εγκατάστασης, διαμένοντας το σκληρό σας δίσκο, και περιγράφει εν συντομία τη διαδικασία εγκατάστασης.

=== Απαιτήσεις

Η τρέχουσα έκδοση του Slint μπορεί να εγκατασταθεί σε υπολογιστές που πληρούν αυτές τις απαιτήσεις:

* Αρχιτεκτονική: x86_64 (64-bit CPU), γνωστό και ως AMD64
* Ελεύθερος ή ελεύθερος χώρος στο δίσκο (σκληροί δίσκοι, SSD, NVME, eMMC): τουλάχιστον 28G στον αυτόματο τρόπο. Μια πλήρης εγκατάσταση Slint χρειάζεται περίπου 20G, χωρίς αρχεία χρήστη ή πρόσθετα.
* RAM: τουλάχιστον 2G
* μια μονάδα δίσκου DVD ή μια υποδοχή USB διαθέσιμη, με την ικανότητα του firmware να εκκινήσει ένα DVD ή USB stick. Ένα κενό DVD ή ένα 4G ή περισσότερο USB stick μπορεί να χρησιμοποιηθεί ως μέσα εγκατάστασης

NOTE: Η ασφαλής εκκίνηση πρέπει να απενεργοποιηθεί για την εγκατάσταση του Slint.

=== Χαρακτηριστικά του εγκαταστάτη

* Ο εγκαταστάτης είναι ένα "ζωντανό σύστημα", που εκτελείται στη μνήμη: δεν θα τροποποιήσει ένα εγκατεστημένο σύστημα, εκτός αν και μέχρι να το πείτε.
* Για τυφλούς χρήστες, ο εγκαταστάτης είναι πλήρως χρησιμοποιήσιμος με Braille, και ομιλία χρησιμοποιώντας τον αναγνώστη οθόνης speakup.
* Για έμπειρους χρήστες, περιλαμβάνει όλα τα απαραίτητα βοηθητικά προγράμματα για την προετοιμασία του <<drive, δίσκου>> στο οποίο θα εγκατασταθεί το Slint.
* Η αυτόματη λειτουργία εγκατάστασης χρειάζεται μόνο το χρήστη για να απαντήσει σε ερωτήσεις και να παρέχει μια σχετική βοήθεια γι 'αυτούς.
* Ο εγκαταστάτης μπορεί να ελευθερώσει κάποιο χώρο για το Slint σε μια μονάδα δίσκου όπου θέλετε να το εγκαταστήσετε μαζί με ένα άλλο Linux υπό ορισμένες συνθήκες.
* Εάν εγκατασταθεί μόνο σε μια αφαιρούμενη συσκευή συνδεδεμένη μέσω USB, Slint μπορεί να γίνει φορητή, i. . μπορεί να χρησιμοποιηθεί σε οποιονδήποτε υπολογιστή σε θέση να εκκινήσει από μια μονάδα USB.
* Ο εγκαταστάτης μπορεί να κρυπτογραφήσει τη μονάδα δίσκου όπου το Slint είναι εγκατεστημένο μόνο. Αυτό αποτρέπει την κλοπή των δεδομένων που περιέχει σε περίπτωση απώλειας ή κλοπής της μηχανής, ή μιας αφαιρούμενης κίνησης.
* Το Slint μπορεί να εγκατασταθεί στη δική του μονάδα, ή παράλληλα με ένα άλλο σύστημα.

=== Προετοιμασία

<<download_and_verify, Λήψη και επαλήθευση εικόνας ISO Slint>> +
<<write_the_iso, Γράψτε την εικόνα ISO σε μια εγκατάσταση Μεσαίο>> +
<<make_room_for_Slint, Κάνετε χώρο για Slint>> +
<<create_partitions_for_Slint, Δημιουργία διαμερισμάτων για Slint>>

[[download_and_verify]]
====  Κατεβάστε και επαληθεύστε μια εικόνα ISO Slint

Η τελευταία έκδοση της κατανομής Slint είναι η 14.2.1

Η τελευταία εικόνα ISO εγκατάστασης είναι πάντα διαθέσιμη σε https://slackware.uk/slint/x86_64/slint-14.2.1/iso[αυτόν τον κατάλογο]

[TIP]
====
Εφ 'όσον εκτελείτε το Slint έκδοση 14.2. δεν υπάρχει ανάγκη επανεγκατάστασης όταν παρέχεται ένα νέο ISO, καθώς φέρνει μόνο νέα χαρακτηριστικά του εγκαταστάτη και νέα ή και αναβαθμισμένα πακέτα's που μπορείτε επίσης να πάρετε κρατώντας το σύστημά σας ενημερωμένο.
====

Το όνομα αρχείου του ISO που υποδεικνύεται παρακάτω είναι απλά ένα παράδειγμα, που θα προσαρμοστεί στο τρέχον όνομα κατά τη λήψη.

Εάν εκτελείτε Windows, ένα Internet με ως επιχείρημα "ελέγξτε sha256sum windows" θα σας πει τρόπους για να προχωρήσετε.

Εάν εκτελείτε Linux μπορείτε να κατεβάσετε την εικόνα ISO και το άθροισμα ελέγχου sha256 που πληκτρολογεί:
----
wget https://slackware.uk/slint/x86_64/slint-14.2.1/iso/slint64-14.2.1.4.iso
wget https://slackware.uk/slint/x86_64/slint-14.2.1/iso/slint64-14.2.4.iso.sha256
----

Για να ελέγξετε την ακεραιότητα των κατεβασμένων αρχείων πληκτρολογήστε αυτήν την εντολή:
sha256sum -c slint64-14.2.1.4.iso.sha256
το αποτέλεσμα πρέπει να είναι:
OK

----
sha256sum -c slint64-14.2.1.4.iso.sha256
----
Το αποτέλεσμα πρέπει να είναι: Εντάξει +
αλλιώς, επαναλάβετε τις λήψεις.

[[write_the_iso]]
====  Γράψτε την εικόνα ISO σε ένα μέσο εγκατάστασης

Μπορείτε να χρησιμοποιήσετε είτε ένα DVD είτε ένα USB stick ως μέσα εγκατάστασης.

[[make_a_bootable_usb_stick]]
===== Κάντε ένα Bootable USB Stick

On a ++Linux++ system, plug in the USB stick, and check it's name with the following command:

----
lsblk -o μοντέλο, όνομα, μέγεθος, fstype, σημείο τοποθέτησης
----

[WARNING]
====
Ελέγξτε προσεκτικά την έξοδο της εντολής για να βεβαιωθείτε ότι δεν θα πληκτρολογήσετε το όνομα ενός διαμερίσματος σκληρού δίσκου αντί για το όνομα του USB stick.  Όλο το προηγούμενο περιεχόμενο του USB stick ή ενός λανθασμένου διαμερίσματος σκληρού δίσκου θα είναι *LOST* και *IRRECOVERABLE*.
====

Ας's υποθέσουμε ότι το όνομα του USB stick είναι /dev/sdb. Θα μπορούσε να ονομαστεί διαφορετικά, έτσι don't αντιγράψτε τυφλά την ακόλουθη εντολή.  Η σύνταξη εντολών για την εγγραφή του Slint ISO σε ένα USB stick που κατοικεί στο /dev/sdb έχει ως εξής:

----
dd if=slint64-14.2.1.4.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
Η παραπάνω εντολή υποθέτει ότι *αν=* δείχνει τη διαδρομή του Slint ISO και *of=* δείχνει το όνομα του USB stick.  Αυτές οι τιμές μπορεί να διαφέρουν στο σύστημά σας.
====

On ++Windows++ use an application like http://rufus.akeo.ie/[Rufus].  Είναι ελεύθερη και ανοιχτή πηγή.

1. Ανοίξτε το πρόγραμμα Rufus από όπου το κατεβάσατε για να το εκτελέσετε.
2. Επιλέξτε Δημιουργία ενός εκκινήσιμου δίσκου χρησιμοποιώντας και επιλέξτε εικόνα ISO από το αναπτυσσόμενο μενού.
   Κάντε κλικ στο εικονίδιο του δίσκου και περιηγηθείτε στο αρχείο Slint .iso και επιλέξτε το.
3. Για να ασφαλίσετε τη μονάδα flash είναι συμβατή με το UEFI, επιλέξτε FAT32 για <<file_system, σύστημα αρχείων>>.
4. Για να δημιουργήσετε τη μονάδα flash με το "Πατήστε οποιοδήποτε πλήκτρο για να εκκινήσετε από USB" προτροπή, επιλέξτε την επιλογή Δημιουργία εκτεταμένης ετικέτας και εικονιδίων αρχείων.
5. Όταν τελειώσετε επιλέγοντας επιλογές, κάντε κλικ στην επιλογή Έναρξη Όταν σας ζητηθεί, επιβεβαιώστε ότι θέλετε να διαγράψετε το δίσκο flash.
6. Τα αρχεία .iso θα αρχίσουν να αντιγράφουν στη μονάδα flash (η διαδικασία μπορεί να διαρκέσει αρκετά λεπτά). Όταν τελειώσει η Rufus, κλείστε το πρόγραμμα, αφαιρέστε και αφαιρέστε την κίνηση flash.

[[make_a_bootable_DVD_disc]]
=====  Make a Bootable DVD Disc

On a ++Linux++ system insert the DVD and type the following command:

----
growisofs -speed=2 -dvd-compat -Z /dev/sr0=slint64-14.2.1.4.iso
----

Σιγουρευτείτε ότι εισάγετε την πλήρη διαδρομή του ISO Slint στο σύστημα αρχείων σας.

On ++Microsoft Windows 2000/XP/Vista/7++ you can write to a DVD using the application http://infrarecorder.org/[InfraRecorder].  Είναι ελεύθερη και ανοιχτή πηγή.

On ++Microsoft Windows 7/8/10++ you can use the http://windows.microsoft.com/en-US/windows7/Burn-a-CD-or-DVD-from-an-ISO-file[Windows Disk Image Burner] utility that is shipped with Microsoft Windows.

[[make_room_for_Slint]]
====  Φτιάξε χώρο για Slint

Αφιερώστε έναν υπολογιστή ή τουλάχιστον μια μονάδα δίσκου στο Slint, διευκολύνει την εγκατάσταση και συνιστάται. Στη συνέχεια, παραλείψτε αυτό το βήμα και προχωρήστε απευθείας στην εκτέλεση του προγράμματος εγκατάστασης.

Αλλά μπορείτε επίσης να μοιραστείτε μια μονάδα δίσκου με ένα ήδη εγκατεστημένο λειτουργικό σύστημα όπως τα Windows, Mac OS, *BSD, ή άλλη διανομή Linux,

Στη συνέχεια, θα χρειαστείτε έναν ελεύθερο χώρο για το Slint στο τέλος του πίνακα χωρισμάτων αυτού του δίσκου (μετά το τελευταίο διαμέρισμα). Τουλάχιστον 20G είναι απαραίτητη για το ίδιο το σύστημα, αλλά θα χρειαστείτε επίσης κάποιο χώρο για τα αρχεία χρηστών και να εγκαταστήσετε άλλο λογισμικό. Η συρρίκνωση του τελευταίου διαμερίσματος της μονάδας δίσκου μπορεί να γίνει μετά την εκκίνηση του εγκαταστάτη πληκτρολογώντας εντολές linux αν είστε χρήστης ενέργειας Linux. Αυτό μπορεί επίσης να γίνει από τον εγκαταστάτη σε λειτουργία Auto εάν πληρούνται οι ακόλουθες προϋποθέσεις:

* Η κίνηση είναι εξοπλισμένη με έναν πίνακα κατατμήσεων GUID (GPT)
* Η τελευταία κατάτμηση έχει ένα ext <<file_system, σύστημα αρχείων>>.
* Τουλάχιστον 28G μπορεί να απελευθερωθεί σε αυτό.
* Το μηχάνημα έχει εκκινήσει σε λειτουργία EFI (δεν είναι Legacy)

Διαφορετικά, θα χρειαστεί να κάνετε χώρο για το Slint πριν από την εγκατάσταση χρησιμοποιώντας `gparted` ή από Windows (συνιστάται αν τα Windows αν εγκατασταθούν). Ωστόσο, υπό ορισμένες συνθήκες η Slint μπορεί να το κάνει για εσάς όπως υποδεικνύεται στο
<<Automatic_installation, Αυτόματη εγκατάσταση>>

===== Πώς να ελευθερώσετε χώρο σε έναν όγκο Windows

Τα βήματα που αναφέρονται στο
https://docs.microsoft.com/en-us/windows-server/storage/disk-management/shrink-a-basic-volume[αυτό το έγγραφο]
συνοψίζονται παρακάτω.

1. Από τα Windows, ανοίξτε μια γραμμή εντολών και πληκτρολογήστε:
+
`diskpart`

2. Στη γραμμή επιλογής, πληκτρολογήστε:
+
`λίστα έντασης ήχου`
+
Σημειώστε τον αριθμό του απλού τόμου που θέλετε να συρρικνωθεί.

3. Επιλέξτε την ένταση που θέλετε να συρρικνωθεί, η οποία θα πρέπει να έχει ένα σύστημα αρχείων ntfs, πληκτρολογώντας
+
`επιλογή έντασης <number>`

4. για να γνωρίζετε το μέγιστο μέγεθος του οποίου ο όγκος μπορεί να συρρικνωθεί:
+
`συρρίκνωση querymax`

5. Ορίστε το <size> σε megabytes του ελεύθερου χώρου που θέλετε να δημιουργήσετε. Δεν πρέπει να είναι μεγαλύτερο από το μέγιστο μέγεθος που βρέθηκε με την προηγούμενη εντολή. Μπορεί να θέλετε να αφήσετε κάποιο διαθέσιμο χώρο στον όγκο των Windows για να μπορέσετε να αποθηκεύσετε περισσότερα δεδομένα σε αυτό.

6. Πληκτρολογήστε αυτήν την εντολή:
+
`συρρίκνωση επιθυμητό=<size>`
+
το μέγεθος είναι ένας αριθμός στην MB, για παράδειγμα για 30 GB, γνωρίζοντας ότι G=1024M τύπος:
+
`συρρίκνωση επιθυμητό=30720`
+
Διατήρηση αρκετού αχρησιμοποίητου χώρου στην ένταση του συστήματος ώστε να επιτρέπεται η εγκατάσταση ενημέρωσης των Windows.

Εναλλακτικά μπορείτε να χρησιμοποιήσετε το Disk Manager: επιλέξτε τον τόμο που θέλετε να συρρικνωθεί, κάντε δεξί κλικ σε αυτό, επιλέξτε "συρρίκνωση του όγκου", περίμενε μέχρι να εμφανιστεί ο μέγιστος χώρος του οποίου μπορεί να συρρικνωθεί ο τόμος, προσαρμόστε την τιμή για να αφήσετε
λίγο χώρο για να επιτρέψετε την αποθήκευση περισσότερων δεδομένων εκεί όπως βλέπετε σε εφαρμογή, στη συνέχεια, κάντε κλικ στο κουμπί συρρίκνωσης.

===== Πώς να ελευθερώσετε χώρο στο Linux.

Μπορείτε να χρησιμοποιήσετε το http://gparted.org/index.php[gparted]ή ένα γραφικό εργαλείο για τη διαχείριση κατατμήσεων που παρέχεται από τη διανομή σας.

TIP: Εάν 28G μπορεί να απελευθερωθεί στο τελευταίο διαμέρισμα μιας μονάδας δίσκου με GPT εξοπλισμένο με ένα σύστημα αρχείων ext4 ο εγκαταστάτης μπορεί να συρρικνωθεί για σας.

[[create_partitions_for_Slint]]
====  Δημιουργία Τομέων για το Σλιν

Εάν επιλέξετε τη λειτουργία αυτόματης εγκατάστασης και αφιερώσετε μια συσκευή για το Slint, ο εγκαταστάτης θα την κατατμήσει για εσάς. Όταν τελειώσετε, μπορείτε ακόμα να ρυθμίσετε τη διάταξη των κατατμήσεων χρησιμοποιώντας μία από τις προαναφερθείσες εντολές mosted παρακάτω αν yiu whish.

Αν σκοπεύετε να χρησιμοποιήσετε τη λειτουργία Εγκατάστασης Εγχειρίδιο μπορείτε να δημιουργήσετε διαμερίσματα για το Slint είτε πριν είτε κατά τη διάρκεια της εγκατάστασης.

Αν δεν είστε εξοικειωμένοι με το Linux πιθανότατα θα βρείτε ευκολότερο να το κάνετε πριν από την εγκατάσταση. Σας προτείνουμε να χρησιμοποιήσετε http://gparted.org/index.php[gparted] για να το κάνετε αυτό. Το Gparted μπορεί να συρρικνωθεί τις υπάρχουσες κατατμήσεις για να φτιάξει χώρο, καθώς και να δημιουργήσει νέες κατατμήσεις στον ελεύθερο χώρο.  Εάν δεν έχετε σύστημα που υποστηρίζει το Gparted (Microsoft Windows) μπορείτε να χρησιμοποιήσετε το http://gparted.org/livecd.php[Gparted Live].
Οι εντολές cfdisk, fdisk, gdisk, cgfdisk και parted είναι διαθέσιμες από τον εγκαταστάτη. Μπορείτε να χρησιμοποιήσετε το θέμα για να κατατμήσετε ολόκληρη τη συσκευή ή να κάνετε τα χωρίσματα για το Slint στο ελεύθερο χώρο του.

Εγκατάσταση αναγκών Slint:

* Ένα διαμέρισμα τύπου Linux, μέγεθος τουλάχιστον 20G, περισσότερα είναι καλύτερα (τουλάχιστον 30 G συνιστάται).
* Αν θα εκκινήσετε σε λειτουργία EFI, με μέγεθος τύπου "EFI System" (κωδικός ef00) τουλάχιστον 100M. Ακόμα κι αν θα εκκινήσετε σε λειτουργία Legacy κέρδισε't κακό για να έχουν ένα.
* Σε περίπτωση GPT (GUID Partition Table), ένα διαμέρισμα τύπου BIOS Boot (ef02), μεγέθους 4M, για εκκίνηση σε λειτουργία Legacy. Ακόμα κι αν κάνετε εκκίνηση σε λειτουργία EFI, κέρδισε't κακό για να έχουν ένα.
* Προαιρετικά ένα διαμέρισμα τύπου "swap". Αυτό συνιστάται ειδικά αν θέλετε να χειρίζεστε τη μηχανή σας και εάν έχετε λιγότερο από 8G RAM. Ωστόσο, μπορείτε να ρυθμίσετε ένα αρχείο swap μετά την εγκατάσταση.

Μπορείτε επίσης να αφιερώσετε ένα διαμέρισμα για το /home (αλλά αυτό δεν είναι υποχρεωτικό, don't) και άλλα χωρίσματα για συγκεκριμένες περιπτώσεις χρήσης.

[NOTE]
====
Το ίδιο το Slint χρειάζεται περίπου 20 Gigabytes χώρου, αλλά συνιστάται ένα ριζικό διαμέρισμα 50 Gigabytes. Μπορεί να θέλετε να εγκαταστήσετε πρόσθετο λογισμικό ή να χρειαστείτε περισσότερο χώρο για να αποθηκεύσετε τα αρχεία σας.  Όσο περισσότερο χώρο τόσο καλύτερα αν σκοπεύετε να αποθηκεύσετε φωτογραφίες, βίντεο, μουσική, κλπ.
====

=== Εγκατάσταση Slint

<<Start_of_the_installation, Start of the installation>> +
<<Accessibility_of_the_installer, Προσβασιμότητα of the installer>> +
<<Usage_of_the_installer, Usage of the installer>> +
<<Automatic_installation, Automatic installation>> +
<<Manual_installation, Manual installation>> +
<<Slint_in_an_encrypted_drive, Slint in an encrypted drive>> +
<<first_steps_after_installation, First steps after installation>>

[[Start_of_the_installation]]
==== Έναρξη της εγκατάστασης

Εάν χρειάζεται, ρυθμίστε το firmware του μηχανήματος για να εκκινήσετε το DVD ή USB stick που έχετε ετοιμάσει

Τοποθετήστε το μέσο εγκατάστασης (DVD ή USB stick) και επανεκκινήστε το μηχάνημά σας. Οι τυφλοί χρήστες θα ακούσουν ένα 'μπιπ' όταν εμφανιστεί το μενού εκκίνησης.

Ξεκινήστε τον εγκαταστάτη πατώντας το Enter.

Ο εγκαταστάτης θα εξετάσει πρώτα τις κάρτες ήχου.

Αυτό μπορεί να βοηθήσει στη ρύθμιση μιας λειτουργικής ως προεπιλογή, και επίσης χρησιμοποιείται για την ομιλία κατά την εγκατάσταση που χρησιμοποιείται από μερικούς τυφλούς χρήστες.

Αν ο εγκαταστάτης βρει περισσότερες από μία κάρτες ήχου, θα πει για κάθε: +
πατήστε Enter για να επιλέξετε αυτό το ταμπλό ήχου <sound card id> +
Πατήστε Enter μόλις το ακούσετε, να επιβεβαιώσει ότι η προτεινόμενη κάρτα ήχου λειτουργεί. Αυτή η ρύθμιση θα αποθηκευτεί στο νέο σύστημα στο /etc/asound.conf.

Στο επόμενο βήμα, όταν σας ζητηθεί θα επιβεβαιώσετε (πληκτρολογήσεις) ή θα αρνηθείτε (απλά πατώντας Enter) ότι θέλετε ομιλία κατά την εγκατάσταση. Το Braille είναι πάντα διαθέσιμο κατά την εγκατάσταση.

Στη συνέχεια θα επιλέξετε, επιβεβαιώσετε ή αλλάξετε τη γλώσσα που χρησιμοποιήθηκε κατά την εγκατάσταση. Στη συνέχεια, όλες οι οθόνες θα είναι στην επιλεγμένη γλώσσα αν η μετάφραση σε αυτή τη γλώσσα είναι πλήρης.

Αν χρειαστεί να προσαρτήσετε πρόσθετες παραμέτρους πυρήνα στη γραμμή εντολών εκκίνησης, πριν πατήσετε Enter κάντε ό,τι ακολουθεί:
[NOTE]
====
Θα πρέπει να γνωρίζετε ότι ο χάρτης πληκτρολογίου των ΗΠΑ θα χρησιμοποιείται κατά την πληκτρολόγηση. +
Ctrl+x σημαίνει "Πατήστε και κρατήστε πατημένο το πλήκτρο Ctrl ή Control όπως αν ήταν πλήκτρο Shift και στη συνέχεια πατήστε το πλήκτρο X"
====
----
Πατήστε το πλήκτρο e
Πατήστε το κάτω βέλος τρεις φορές
Πατήστε το πλήκτρο λήξης
Πατήστε το πλήκτρο διαστήματος
Πληκτρολογήστε τις παραμέτρους του πυρήνα (παραδείγματα παρακάτω)
Πατήστε Ctrl+X για εκκίνηση (δεν πατήσετε το πλήκτρο Enter!)
Πατήστε Enter για εκκίνηση.
----

Για παράδειγμα για να ρυθμίσετε το πρόγραμμα οδήγησης ομιλίας για το συνθέτη υλικού σας θα μπορούσατε να πληκτρολογήσετε μια παράμετρο πυρήνα όπως:
----
speakup.synth=apollo
----
Μπορείτε επίσης να συμπεριλάβετε στη γραμμή εντολών εκκίνησης τις ρυθμίσεις για τη συσκευή Braille σας, σε αυτή τη μορφή:
-----
brltty=<driver code>,<device>,<text table>
-----
Για παράδειγμα για να εγκαταστήσετε με μια συσκευή Papenmeier συνδεδεμένη μέσω USB με ένα γαλλικό τύπο πίνακα κειμένου:
-----
brltty=pm,usb:,fr_FR
-----
NOTE: μια συσκευή braille συνδέεται μέσω USB θα πρέπει πάντα να αναγνωρίζεται, ίσως μόνο ο πίνακας κειμένου κέρδισε't είναι ο καλός, αν το έκανες't εισάγετε τις ρυθμίσεις πρώτα.

Σε κάθε περίπτωση, καθώς δεν υπάρχει χρονικό όριο, η εκκίνηση θα ξεκινήσει μόνο όταν πατήσετε [Enter].

Ομιλία και Braille θα είναι διαθέσιμα στην αρχή της εγκατάστασης.

[[Usage_of_the_installer]]
==== Χρήση του εγκαταστάτη

Αν είστε εξοικειωμένοι με τη γραμμή εντολών, μπορείτε να παραλείψετε αυτό το θέμα.

Το κύριο μενού εγκατάστασης εμφανίζεται παρακάτω:
....
Καλώς ήλθατε στο πρόγραμμα εγκατάστασης του Slint! (έκδοση 14.2.1)

Διαθέσιμες εντολές (μην πληκτρολογήσετε τα εισαγωγικά):

'doc' για να γνωρίζετε τα χαρακτηριστικά και τη χρήση του εγκαταστάτη.
'αυτόματο' για να ξεκινήσει μια ημι-αυτόματη, καθοδηγούμενη εγκατάσταση.
'εγκατάσταση' για να ξεκινήσει μια χειροκίνητη εγκατάσταση.

Σας συνιστούμε να πληκτρολογήσετε πρώτα το 'doc' για να προετοιμάσετε μια χειροκίνητη εγκατάσταση, ή αν
θέλετε να κρυπτογραφήσετε τη μονάδα δίσκου όπου θα εγκατασταθεί το Slint, or if you need to
reduce the size of a partition to make room for Slint παράλληλα με ένα άλλο σύστημα.
Όταν τελειώσετε την ανάγνωση αυτού του μενού θα εμφανιστεί ξανά.
....

Μόλις εμφανιστεί αυτό το μενού, έχετε το χέρι στη διαδικασία εγκατάστασης.

Μπορείτε να διαβάσετε την οθόνη και πληκτρολογήστε εντολές σε ένα <<virtual_terminal, εικονικό τερματικό>>. Ο εγκαταστάτης
περιλαμβάνει πολλά εικονικά τερματικά που μοιράζονται το ίδιο φυσικό πληκτρολόγιο και την οθόνη
, που μπορούν να χρησιμοποιηθούν παράλληλα.

Ο εγκαταστάτης ξεκινά στο εικονικό τερματικό 1 που ονομάζεται *tty1* αλλά μπορείτε να μεταβείτε
σε άλλο. Για παράδειγμα, μπορείτε να αλλάξετε σε *tty2* πατώντας
*Alt-F2* και έπειτα Enter για να το ενεργοποιήσετε και αργότερα να επιστρέψετε στο *tty1* πατώντας
*Alt-F1*, χωρίς διαγραφή πληροφοριών που εμφανίζονται και στα δύο τερματικά.
*Alt-F1* σημαίνει: πατήστε και κρατήστε πατημένο το πλήκτρο *Alt* και μετά πατήστε το πλήκτρο *F1*.

Αυτό μπορεί να είναι χρήσιμο για να συνεχίσετε να διαβάζετε την τεκμηρίωση κατά τη διάρκεια της εγκατάστασης:
για παράδειγμα μπορείτε να μεταβείτε σε *tty2* για να ξεκινήσετε την εγκατάσταση, άλλαξε σε *tty1* σε
συνεχίστε να διαβάζετε την τεκμηρίωση, στη συνέχεια αλλάξτε σε *tty1* ξανά για να προχωρήσετε στο
το επόμενο βήμα εγκατάστασης.

Αυτό μπορεί επίσης να χρησιμοποιηθεί για να συμβουλευτείτε το γλωσσάριο κατά την ανάγνωση άλλων εγγράφων.

Το τέταρτο εικονικό τερματικό ή το *tty4* εμφανίζει μηνύματα που παρέχουν πληροφορίες
χρήσιμες για τον εντοπισμό σφαλμάτων, αλλιώς δεν χρησιμοποιείται.

Ο εγκαταστάτης έχει διάφορους τρόπους αλληλεπίδρασης με εσάς, τον χρήστη:

. Πληκτρολογείτε εντολές στην προτροπή και διαβάστε την έξοδο.
. Ο εγκαταστάτης κάνει μια ερώτηση, πληκτρολογείτε την απάντηση και την επιβεβαιώνετε πατώντας Enter.
. Το πρόγραμμα εγκατάστασης εμφανίζει ένα μενού επιλογών ή επιλογών: επιλέγετε μία από αυτές χρησιμοποιώντας τα βελάκια πάνω και κάτω, στη συνέχεια, επιβεβαιώστε την επιλογή σας πατώντας Enter, ή ακυρώστε πατώντας Escape.
. Ο εγκαταστάτης εμφανίζει πληροφορίες σε μια σελίδα. Στη συνέχεια, χρησιμοποιήστε τα πλήκτρα βέλους για να διαβάσετε την επόμενη ή προηγούμενη γραμμή, πατήστε το πλήκτρο διαστήματος για να εμφανίσετε την επόμενη σελίδα, Q για να σταματήσετε την ανάγνωση του εγγράφου.

[[Automatic_installation]]
==== Αυτόματη εγκατάσταση

Στην αυτόματη λειτουργία, ο εγκαταστάτης παρέχει προεπιλεγμένες ρυθμίσεις, συμπεριλαμβανομένου του γραφικού περιβάλλοντος (Mate). Αφού ξεκινήσετε
το νέο σας σύστημα, μπορείτε να αναθεωρήσετε και να αλλάξετε όλες τις ρυθμίσεις.

Τα βήματα εγκατάστασης περιγράφονται παρακάτω.

. Η εγκατάσταση του Slint χρειάζεται τουλάχιστον 28G χώρου στο δίσκο. Ο εγκαταστάτης πρώτα ανιχνεύει τις κινήσεις, τα μεγέθη τους και τον ελεύθερο χώρο πάνω τους. Ανάλογα με τα αποτελέσματα, σας επιτρέπει να εγκαταστήσετε σε μια ειδική μονάδα δίσκου ή στον ελεύθερο χώρο σε ένα δίσκο.
.. Εγκατάσταση σε μια ειδική μονάδα δίσκου.
+
Σε αυτή τη λειτουργία εγκατάστασης όλο το προηγούμενο περιεχόμενο της μονάδας δίσκου θα διαγραφεί. Αν περιέχει αρχεία που θέλετε να κρατήσετε, αποθηκεύστε τα σε άλλες περιοχές πρώτα!
+
Εάν η μονάδα είναι αφαιρούμενη και συνδεδεμένη μέσω USB, ο εγκαταστάτης μπορεί να κάνει το Slint φορητό, σας επιτρέπει να το χρησιμοποιήσετε σε οποιονδήποτε υπολογιστή είναι σε θέση να εκκινήσει από μια εξωτερική μονάδα USB.
+
Η μονάδα δίσκου μπορεί προαιρετικά να κρυπτογραφηθεί, για την προστασία των δεδομένων σας από κλοπή αν η μονάδα δίσκου ή ο υπολογιστής χαθεί ή κλαπεί. Δεδομένου ότι υπάρχουν σημαντικές προειδοποιήσεις, διαβάστε προσεκτικά την κρυπτογράφηση εγγράφου πρώτα.

.. Εγκατάσταση σε μονάδα δίσκου που μοιράζεται με άλλο σύστημα. Αυτό καθιστά δυνατή την εγκατάσταση του Slint διατηρώντας το άλλο σύστημα χρησιμοποιώντας μόνο ένα δίσκο.
+
Αυτό επιτρέπεται εάν η μονάδα δίσκου έχει τουλάχιστον 28G χώρου ελεύθερο ή μπορεί να απελευθερωθεί στο τέλος της, έχει έναν πίνακα κατατμήσεων GPT (GUID), και τις μπότες του εγκαταστάτη σε λειτουργία EFI: σε αυτή τη διαμόρφωση και το δύο σύστημα θα εκκινήσει χωρίς να παρεμβαίνει μεταξύ τους.

. Μπορείτε να επιλέξετε το μέγεθος της κύριας κατάτμησης Slint, και προαιρετικά το μέγεθος μιας επιπλέον κατάτμησης, προαιρετικά αφήνοντας κάποιο ελεύθερο χώρο στο αυτοκίνητο για μελλοντική χρήση.
+
Το κύριο διαμέρισμα θα έχει γενικά ένα σύστημα αρχείων ext4. Ωστόσο, εάν εγκατασταθεί σε μια κάρτα SD ή eMMC θα έχει ένα σύστημα αρχείων f2fs.
+
Θα έχετε την ευκαιρία να αναθεωρήσετε και να τροποποιήσετε τις επιλογές σας πριν από την έναρξη της εγκατάστασης.
+
Μετά την επιβεβαίωση εγκαθίστανται τα βασικά πακέτα, η οποία διαρκεί μερικά δευτερόλεπτα.

. Αν επιλέξατε έναν κρυπτογραφημένο δίσκο πληκτρολογείτε τη φράση πρόσβασης που θα χρησιμοποιηθεί για να ξεκλειδώσετε τη μονάδα δίσκου σε κάθε εκκίνηση επάνω.
. Μπορείτε να επιλέξετε έναν κωδικό πρόσβασης για το χρήστη "root". Αυτός είναι ο διαχειριστής του συστήματος, ο οποίος έχει όλα τα προνόμια. Δημιουργείτε επίσης έναν κανονικό λογαριασμό χρήστη, υποδείξτε αν θα χρειαστείτε προσβάσιμη έξοδο Braille, και αν θέλετε να συνδεθείτε στο Slint σε μορφή κειμένου ή γραφικής λειτουργίας.
+
[NOTE]
====
Εάν χρησιμοποιήσατε τη γλώσσα Αγγλικά (ΗΠΑ) κατά τη διάρκεια της εγκατάστασης επιλέγετε τη γλώσσα που θα χρησιμοποιήσετε για το εγκατεστημένο σύστημα, else the installer sets the same as during installation.
====
. Ο εγκαταστάτης προσπαθεί να δημιουργήσει μια σύνδεση στο Διαδίκτυο, επιτρέποντας την πρόταση μιας ζώνης ώρας που αντιστοιχεί στη γεωγραφική σας θέση και αργότερα εγκαταστήστε πακέτα εξ αποστάσεως, ανάλογα με την ανάγκη. Μπορείτε να το ρυθμίσετε ή να επιβεβαιώσετε την προτεινόμενη έκδοση.
. Στη συνέχεια, ο εγκαταστάτης δημιουργεί ένα αρχείο swap στο διαμέρισμα συστήματος, το οποίο μπορείτε εύκολα να αλλάξετε το μέγεθος μετά την εγκατάσταση. Από προεπιλογή, ένα πρόσθετο διάστημα swap 1. φορές το μέγεθος της φυσικής μνήμης RAM θα ρυθμιστεί στο zram κάθε φορά που θα εκκινηθεί το Slint.
. Τα πακέτα είναι εγκατεστημένα στο δίσκο (η σειρά πακέτων του KDE είναι προαιρετική). Ο εγκαταστάτης θα προσπαθήσει να δημιουργήσει μια σύνδεση στο Internet, ώστε να μπορεί να κατεβάσει και να εγκαταστήσει την πιο πρόσφατη έκδοση του κάθε πακέτου, συμπεριλαμβανομένων εκείνων που προβλέπονται από την απελευθέρωση της εικόνας ISO. Έτσι κερδίσατε't πρέπει να κατεβάσετε και να εγκαταστήσετε αυτά τα νέα ή αναβαθμισμένα πακέτα μετά την εγκατάσταση.
+
Η εγκατάσταση όλων των πακέτων διαρκεί περίπου 10 έως 40 λεπτά ανάλογα με το υλικό.

. Στη συνέχεια, το σύστημα έχει ρυθμιστεί και ο διαχειριστής εκκίνησης GRUB εγκαταστάθηκε. Εάν το Slint έχει εγκατασταθεί σε μια ειδική μονάδα, μπορεί να εκκινήσει τόσο σε λειτουργίες Legacy όσο και σε λειτουργίες EFI. Διαφορετικά, θα εκκινήσει μόνο σε λειτουργία EFI. Σε κάθε περίπτωση, το μενού εκκίνησης θα έχει μια πρόσθετη καταχώρηση εκκίνησης "διάσωσης" για να ανιχνεύσει και να εκκινήσει εγκατεστημένο λειτουργικό σύστημα.
. Θα σας ζητηθεί να δημιουργήσετε ένα ραβδί εκκίνησης διάσωσης σε μια μονάδα USB flash. Μπορείτε να χρησιμοποιήσετε αυτό για την εκκίνηση του Slint αν αποτύχει να εκκινήσει από το μενού εκκίνησης.

Τέλος, αφαιρέστε τα μέσα εγκατάστασης και επανεκκινήστε για να ξεκινήσετε το νέο σας σύστημα Slint.
Μπορείτε να εμφανίσετε μια προεπισκόπηση του μενού εκκίνησης πριν από την επανεκκίνηση.

[[Manual_installation]]
==== Χειροκίνητη εγκατάσταση

Μια χειροκίνητη εγκατάσταση αποτελείται από δύο κύρια βήματα.

. Προετοιμάστε το(τα) οδηγό(ές) για εγκατάσταση. Αυτό περιλαμβάνει: σχεδιάστε τη διάταξη κατατμήσεων, δημιουργήστε τα χωρίσματα και προαιρετικά τα διαμορφώστε δηλαδή δημιουργήστε συστήματα αρχείων σε αυτά. Το πρόγραμμα εγκατάστασης μπορεί να διαμορφώσει τις κατατμήσεις Linux αν προτιμάτε.
. Πληκτρολογήστε *ρύθμιση* για να εκτελέσετε περαιτέρω προετοιμασία, εγκατάσταση και διαμόρφωση.

===== Προετοιμάστε το(τα) οδηγό(ές) για εγκατάσταση.

Αν είναι δυνατόν, εγκαταστήστε το Slint στο δικό του δίσκο.

Μπορείτε επίσης να το εγκαταστήσετε σε μια μονάδα δίσκου που μοιράζεται από ένα άλλο σύστημα, αλλά στη συνέχεια κατά προτίμηση
αν εκκινήσετε σε λειτουργία EFI, έτσι ώστε κάθε σύστημα, έχοντας το δικό του OS loader, θα είναι
ανεξάρτητο από τους άλλους και τις ενημερώσεις τους. Στη συνέχεια, θα πρέπει να απελευθερώσει κάποιο χώρο στο
η μονάδα δίσκου για να εγκαταστήσετε Slint. Μπορείτε να χρησιμοποιήσετε την εντολή 'freespace' του εγκαταστάτη Slint
για να το κάνετε αυτό αν το τελευταίο διαμέρισμα της μονάδας δίσκου έχει ext2, ext3 ή
ext4 σύστημα αρχείων, αλλιώς το κάνει από το ήδη εγκατεστημένο σύστημα.

Εάν είναι δυνατόν, αφήστε το μηχάνημα να εκκινήσει σε λειτουργία EFI και ρυθμίστε έναν πίνακα χωρισμάτων GPT (GUID
) για τη μονάδα προορισμού, για μέγιστη ευελιξία.

Ο εγκαταστάτης χρησιμοποιεί το λογισμικό GRUB τόσο για την εκκίνηση του EFI όσο και του Legacy.

Για να εγκαταστήσετε το Slint στο δικό του δίσκο θα χρειαστείτε:

* Για εκκίνηση σε λειτουργία παλαιού τύπου με GPT, ένα διαμέρισμα τύπου BIOS Boot που απαιτείται από
GRUB σε αυτό το πλαίσιο. Ένα μέγεθος 1M για αυτό το διαμέρισμα είναι αρκετό. Είναι
επιφυλάσσεται για GRUB και δεν πρέπει να μορφοποιηθεί.
* Για να εκκινήσετε σε λειτουργία EFI ένα διαμέρισμα τύπου ESP (EFI System Partition) μεγέθους
100M για την αποθήκευση του EFI OS loader. Αυτή η κατάτμηση μπορεί να δημιουργηθεί σε ένα GPT όπως
σε έναν πίνακα κατατμήσεων DOS.
* ένα διαμέρισμα μεγέθους τουλάχιστον 28G για το σύστημα, τύπου Linux.

Σε περίπτωση GPT, σας συνιστούμε να ρυθμίσετε τόσο ένα διαμέρισμα BIOS Boot όσο και ένα ESP για
περισσότερη ευελιξία, επιτρέποντας την εκκίνηση του Slint στο EFI καθώς και σε λειτουργία Legacy.

Η δημιουργία άλλων κατατμήσεων είναι προαιρετική. Αν θέλετε μια κατάτμηση swap θα πρέπει
να έχει τον τύπο swap Linux. Εναλλακτικά ή επιπλέον, μπορείτε να ρυθμίσετε ένα αρχείο swap.
'setup' θα προτείνει τη δημιουργία του αφού δημιουργήσει το σύστημα αρχείων του
ριζικού διαμερίσματος.

Ο εγκαταστάτης περιλαμβάνει αρκετές εφαρμογές διαχωρισμού: cfdisk, fdisk, sfdisk,
cgdisk, gdisk, sgdisk, parted. Οι εφαρμογές με το "g" στο όνομά τους μπορούν
να χειριστούν μόνο το gpt, χωρισμένο μπορεί να χειριστεί πίνακες κατατμήσεων DOS καθώς και GPT. fdisk,
cfdisk και sfdisk μπορούν να χειριστούν πίνακες χωρισμάτων DOS. Επιπλέον, σκουπίδια
(για να διαγράψετε προηγούμενες υπογραφές πίνακα κατατμήσεων και συστήματος αρχείων) και partprobe
(για να ενημερώσετε τον πυρήνα για αλλαγές πίνακα κατατμήσεων) είναι διαθέσιμα.
Η εφαρμογή lsblk εμφανίζει πληροφορίες σχετικά με τις συσκευές μπλοκ και τα χωρίσματα.

Μπορείτε να διαμορφώσετε μόνοι σας τα διαμερίσματα ή να αφήσετε τον εγκαταστάτη να το κάνει για εσάς. Εδώ
'format' σημαίνει: δημιουργήστε ένα σύστημα αρχείων για να διαχειριστείτε τα αρχεία στην κατάτμηση. Να θυμάστε στο
ότι το ESP θα πρέπει να έχει ένα σύστημα αρχείων vfat, ένα διαμέρισμα Bios Boot δεν αρχείο
καθόλου. Για τις κατατμήσεις Linux, ο εγκαταστάτης Slint μπορεί να χειριστεί αυτά τα αρχεία
τύπους συστήματος: btrfs, ext2, ext4, f2fs, jfs, reiserfs, xfs.

Ο εγκαταστάτης μπορεί να ρυθμίσει σημεία προσάρτησης για κοινόχρηστα με ή χρησιμοποιημένα από
Windows διαμερίσματα για να επιτρέψει την πρόσβαση από το Slint. Θα πρέπει να έχουν ένα σύστημα αρχείων τύπου
vfat, msdos ή ntfs, είτε έχουν συσταθεί από τα Windows είτε έχουν δημιουργηθεί πριν από την εκτέλεση των ρυθμίσεων.

===== Ενέργειες που διαχειρίζεται το πρόγραμμα εγκατάστασης.

Το πρόγραμμα εγκατάστασης εμφανίζει ένα μενού με αυτές τις καταχωρήσεις ή βήματα:
....
KEYMAP για να επαναχαρτογραφήσετε το πληκτρολόγιό σας (προαιρετικά)
ADDSWAP για να αναβαθμίσετε τα διαμερίσματα swap (προαιρετικά)
TARGET για να ρυθμίσετε τις κατατμήσεις στόχων σας
ΠΗΓΟΣ για να επιλέξετε πηγαίο μέσο που περιέχει τα πακέτα λογισμικού
ΕΓΚΑΤΑΣΤΑΣΗ για να εγκαταστήσετε τα πακέτα λογισμικού
CONFIGURE για να ρυθμίσετε το σύστημα Slint.
....

Αυτές οι καταχωρήσεις σχολιάζονται παρακάτω. Τα βήματα TARGET, SOURCE, INSTALL και CONFIGURE
είναι υποχρεωτικά και θα πρέπει να εκτελούνται με αυτή τη σειρά.

* Το KEYMAP μπορεί να χρησιμοποιηθεί για την αλλαγή του χάρτη πληκτρολογίου που είχε αρχικά επιλεγεί.
* Το ADDSWAP μπορεί να χρησιμοποιηθεί για τη ρύθμιση διαμερίσματος(ων) swap. Αντίθετα, μπορείτε να ρυθμίσετε ένα αρχείο swap μετά την εγκατάσταση και/ή να ρυθμίσετε ένα χώρο swap στο zram.
* Στο βήμα του TARGET ο εγκαταστάτης ρωτά πρώτα ποια κατάτμηση Linux θα φιλοξενήσει τον κεντρικό κατάλογο (/), τότε ρωτάει αν θέλετε να εγκαταστήσετε ένα σύστημα αρχείων σε αυτό. ΠΡΕΠΕΙ ΝΑ συμφωνείτε αν δεν έχει γίνει ακόμη, η ELSE INSTALLATION ΘΑ ΠΑΙΧΝΙΔΙ στο βήμα INSTALL λόγω έλλειψης χώρου για την εγκατάσταση των πακέτων. Στη συνέχεια, επιλέξτε ένα σύστημα αρχείων μεταξύ των προτεινόμενων.
+
Το πρόγραμμα εγκατάστασης παραθέτει στη συνέχεια άλλες κατατμήσεις Linux, και θέτει για κάθε ένα αν θέλετε
να το χρησιμοποιήσετε στο Slint ένα σημείο προσάρτησης και ένα σύστημα αρχείων.
* Στο βήμα ΠΗΓΟΣ επιλέγετε τα μέσα που περιέχουν τα πακέτα λογισμικού που θα εγκατασταθούν. Αυτό πιθανότατα θα είναι αυτό που περιέχει τον εγκαταστάτη.
* Στο βήμα INSTALL όλα τα πακέτα που περιλαμβάνονται στα μέσα εγκατάστασης είναι εγκατεστημένα, εκτός από τα πακέτα του KDE που έχουν οριστεί αν το don't το θέλουν.
* Στο βήμα CONFIGURE ο εγκαταστάτης ρυθμίζει το νέο σύστημα σύμφωνα με τις προτιμήσεις σας. Αυτό περιλαμβάνει τις ακόλουθες ρυθμίσεις ή επιλογές:
+
** Κάντε μια διάσωση μπάρα εκκίνησης USB.
** Εγκαταστήστε και ρυθμίστε τον διαχειριστή εκκίνησης GRUB και τους σχετικούς λειτουργικούς φορτωτές.
** Επιλέξτε αν θέλετε να χρησιμοποιήσετε το ποντίκι στην κονσόλα.
** Ρύθμιση του δικτύου.
** Αποφασίστε ποια υπηρεσία θα πρέπει να ξεκινήσει κατά την εκκίνηση.
** Επιλέξτε αν το υλικό ρολόι χρησιμοποιεί UTC ή τοπική ώρα, ορίστε τη ζώνη ώρας.
** Επιλέξτε το διαχειριστή σύνδεσης: λειτουργία κονσόλας ή γραφικά.
** Επιλέξτε την προεπιλεγμένη γραφική συνεδρία.
** Ορίστε την προεπιλεγμένη γλώσσα και την περιφερειακή παραλλαγή στο εγκατεστημένο σύστημα. Στη συνέχεια εγκαθίστανται ορισμένα πακέτα ειδικά για την επιλεγμένη γλώσσα.

Όλα γίνονται, αφαιρέστε τα μέσα εγκατάστασης και επανεκκίνηση για να ξεκινήσετε το Slint.

[[Slint_in_an_encrypted_drive]]
==== Slint σε μια κρυπτογραφημένη μονάδα δίσκου.

Σε αυτόματη λειτουργία, ο εγκαταστάτης προτείνει την κρυπτογράφηση της μονάδας δίσκου όπου εγκαθιστά
Slint, αν την αφιερώσετε στο Slint. Αν συμφωνείτε, σε κάθε εκκίνηση ο φορτωτής εκκίνησης GRUB θα σας ζητήσει τη φράση πρόσβασης
που θα έχετε πληκτρολογήσει κατά την εγκατάσταση για να ξεκλειδώσετε το δίσκο, πριν από
εμφάνιση του μενού εκκίνησης. Προσέξτε ότι το ξεκλείδωμα της μονάδας δίσκου θα διαρκέσει μερικά
δευτερόλεπτα (περίπου δέκα δευτερόλεπτα).

Έχοντας μια κρυπτογραφημένη κίνηση αποτρέπει την κλοπή δεδομένων που περιέχει σε περίπτωση
απώλειας ή κλοπής του μηχανήματος, ή μιας αφαιρούμενης κίνησης. Αλλά αυτό κέρδισε't σας προστατεύσει αν ο υπολογιστής παραμείνει σε λειτουργία και χωρίς επιτήρηση, μόνο
αν το μηχάνημα έχει απενεργοποιηθεί εντελώς!

Κατά την εγκατάσταση, η κατάτμηση του συστήματος Slint θα κρυπτογραφηθεί και επίσης η
πρόσθετη κατάτμηση που μπορείτε να ζητήσετε.

Ένα διαμέρισμα συστήματος (ή root) θα ονομαστεί ως εξής: /dev/mapper/cryproot μία φορά το
άνοιξε, αν έχει κρυπτογραφηθεί.

Αυτό φαίνεται από αυτήν την εντολή:

----
lsblk -lpo όνομα,fstype,σημείο ανάρτησης - grep /$
----

Ποια δίνει ένα ouptut όπως:
----
/dev/mapper/cryptroot ext4 /
----

Αυτή η εντολή:

----
lsblk -lpo όνομα,fstype,mountpoint ±grep /dev/sda3
----

δόσεις:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 είναι τώρα ένα "raw" διαμέρισμα που περιλαμβάνει την λεγόμενη "κεφαλίδα LUKS"
που δεν θα χρειαστείτε ποτέ ούτε θα πρέπει ποτέ να έχετε άμεση πρόσβαση.  Φιλοξενεί όλα όσα απαιτούνται
για την κρυπτογράφηση ή αποκρυπτογράφηση του διαμερίσματος /dev/mapper/cryptroot, που
φιλοξενεί πραγματικά τα δεδομένα σας (σε αυτό το παράδειγμα το σύστημα Slint).

[WARNING]
====
Εάν ξεχάσετε τη συνθηματική φράση όλα τα δεδομένα στη μονάδα δίσκου θα χαθούν ανεπανόρθωτα!
Έτσι γράψτε ή καταγράψτε αυτό το συνθηματικό και βάλτε το ρεκόρ σε ασφαλές μέρος όσο
μόλις γίνεται.

Δίσκοι πεθαίνουν. Αν συμβεί αυτό και είναι κρυπτογραφημένο τα δεδομένα σας θα χαθούν.
Έτσι, τακτικά αντίγραφα ασφαλείας σημαντικά δεδομένα σας δεν είναι προαιρετικό.

Επίσης, κάντε ένα αντίγραφο ασφαλείας της κεφαλίδας luks που θα είστε σε θέση να επαναφέρετε
το διαμέρισμα luks να καταστραφεί για οποιοδήποτε λόγο. Η εντολή θα μπορούσε να είναι στο παράδειγμα μας
:
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
όπου <file> είναι το όνομα του αρχείου αντιγράφων ασφαλείας, που θα αποθηκεύσετε σε ασφαλές μέρος.

Τότε θα πρέπει να επαναφέρετε το αντίγραφο ασφαλείας, πληκτρολογήστε:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Don't να αλλάξετε το μέγεθος ενός διαμερίσματος κρυπτογραφημένης μονάδας δίσκου όπως μετά από αυτό θα ήταν
οριστικά κλειδωμένο και όλα τα δεδομένα που περιέχει θα χαθούν! Αν χρειάζεστε πραγματικά περισσότερο χώρο, θα πρέπει να δημιουργήσετε αντίγραφα ασφαλείας όλων των αρχείων που
θέλετε να κρατήσετε, στη συνέχεια εγκαταστήστε εκ νέου και να επαναφέρετε τα αντίγραφα ασφαλείας.

Επιλέξτε μια ισχυρή φράση πρόσβασης, έτσι ώστε θα πάρει πάρα πολύ χρόνο για έναν ληστή να
ανακαλύψετε για να αξίζει τον κόπο.

Ποτέ μην αλλάζετε με το λεγόμενο "LUKS header" που βρίσκεται στην ακατέργαστη κατάτμηση
(το τρίτο, όπως π. χ. . /dev/sda3 για την ακατέργαστη κατάτμηση στην κορυφή του διαμερίσματος συστήματος Slint
).  Πρακτικά: don't δημιουργήστε ένα σύστημα αρχείων σε αυτό το διαμέρισμα,
don't το καθιστούν μέρος ενός πίνακα RAID και γενικά don't γράψτε σε αυτό: όλα τα δεδομένα
θα χαθούν ανεπανόρθωτα!
====

Για να αποφύγετε τις αδύναμες φράσεις πρόσβασης, ο εγκαταστάτης απαιτεί η φράση πρόσβασης να περιλαμβάνει:

. Τουλάχιστον 8 χαρακτήρες.
. Μόνο μη τονισμένα πεζά και κεφαλαία γράμματα, ψηφία από 0 έως 9, κενό και τους ακόλουθους χαρακτήρες στίξης:
+
----
 ' ! " # $ %  & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Αυτό εγγυάται ότι ακόμη και ένα νέο πληκτρολόγιο θα έχει όλους τους χαρακτήρες που απαιτούνται για να
πληκτρολογήστε τη φράση πρόσβασης.

. Τουλάχιστον ένα ψηφίο, ένα πεζό γράμμα, ένα κεφαλαίο γράμμα και ένα χαρακτήρα στίξης.

Το GRUB υποθέτει ότι το πληκτρολόγιο "εμάς" χρησιμοποιείται όταν πληκτρολογείτε τη φράση πρόσβασης.
Για το λόγο αυτό, εάν κατά τη διάρκεια της εγκατάστασης χρησιμοποιείτε άλλο χάρτη πληκτρολογίου, πριν από
ζητώντας τη φράση συνθηματικού ο εγκαταστάτης θα ορίσει το χάρτη πληκτρολογίου σε "εμάς", και
αφού την καταγράψουν, επαναφέρετε το παλαιότερα χρησιμοποιούμενο. Σε αυτή την περίπτωση ο εγκαταστάτης
θα ορθογραφήσει επίσης κάθε πληκτρολογημένο χαρακτήρα της φράσης πρόσβασης, καθώς μπορεί
να διαφέρει από εκείνη που γράφτηκε στο κλειδί.


Η εφαρμογή cryptsetup χρησιμοποιείται για την κρυπτογράφηση του δίσκου. Για να μάθετε περισσότερους τύπους
μετά την εγκατάσταση: +
-----
man cryptsetup
-----
και να μάθουν ακόμα περισσότερα για να διαβάσουν: https://gitlab.com/cryptsetup/cryptsetup/-/wikis/FrequentlyAskedQuestions[αυτό το FAQ].

[[first_steps_after_installation]]
==== Πρώτα βήματα μετά την εγκατάσταση

Εδώ είναι οι πρώτες εργασίες που θα εκτελεστούν μετά την εγκατάσταση

Σε αυτό το έγγραφο, όλο το κείμενο μετά από ένα χαρακτήρα # είναι σχόλια από τις προτεινόμενες
εντολές, για να μην πληκτρολογηθεί.

===== Αρχική ενημέρωση λογισμικού

Μετά την εγκατάσταση, το σύστημα πρέπει να ενημερωθεί για να πάρει την πιο πρόσφατη
παρεχόμενη έκδοση του κάθε λογισμικού, καθώς και νέο λογισμικό που παρέχεται από την έκδοση
του ISO. Αυτό είναι ιδιαίτερα απαραίτητο αν δεν υπήρχε σύνδεση δικτύου
κατά την εγκατάσταση, ως τότε εγκαταστάθηκαν μόνο τα πακέτα που περιλαμβάνονταν στα
μέσα διανομής και θα μπορούσαν να είναι ξεπερασμένα.

Οι περισσότερες εντολές που πληκτρολογήθηκαν κάτω από το δικαίωμα διαχείρισης αίτησης που σχετίζεται με έναν
συγκεκριμένο λογαριασμό που ονομάζεται 'root', για τον οποίο έχετε καταγράψει έναν κωδικό πρόσβασης
κατά την εγκατάσταση.

Για να εκδώσετε μια εντολή ως 'ρίζα', πρώτος τύπος
----
su -
----
στη συνέχεια, εκδίδει τον κωδικό πρόσβασης για το root και πατήστε Enter πριν πληκτρολογήσετε την εντολή.

Αυτό αντικαθιστά το 'sudo' που χρησιμοποιείται σε άλλες διανομές.

Όταν τελειώσετε την έκδοση εντολών ως 'ρίζα', πατήστε Ctrl+d ή πληκτρολογήστε 'έξοδο' για να λάβετε
πίσω την κατάσταση του "κανονικού χρήστη".

Για ενημέρωση, πληκτρολογήστε ως ρίζα σε μια κονσόλα ή ένα γραφικό τερματικό:
----
slapt-get --add-keys # ανακτήστε τα πλήκτρα για τον έλεγχο ταυτότητας των πακέτων
slapt-get -u # να ενημερώσετε τη λίστα των πακέτων στους καθρέπτες
slapt-get --install-set slint # να πάρει τα νέα πακέτα
slapt-get --upgrade # Πάρτε τις νέες εκδόσεις των εγκατεστημένων πακέτων
dotnew # απαριθμεί τις αλλαγές στα αρχεία ρυθμίσεων
----
Όταν εκτελείτε dotnew, αποδεχτείτε να αντικαταστήσετε όλα τα παλιά αρχεία ρύθμισης παραμέτρων με νέα.
Αυτό είναι ασφαλές όπως κάνατε't κάνει οποιαδήποτε προσαρμογή ακόμα.

Εναλλακτικά, μπορείτε να χρησιμοποιήσετε αυτά τα γραφικά μπροστινά άκρα: gslapt αντί
slapt-get, και dotnew-gtk αντί dotnew.

Για να μάθετε περισσότερα για το slapt-get, πληκτρολογήστε:
----
man slapt-get
----
ή ως ρίζα:
----
slapt-get --help
----
και διαβάστε το /usr/doc/slapt-get*/README.slaptgetrc.Slint

===== Διαμόρφωση

Εδώ είναι τα βοηθητικά προγράμματα που μπορείτε να χρησιμοποιήσετε για να (ξανά) ρυθμίσετε το σύστημα Slint μετά την εγκατάσταση.
They are presented in further details in chapter <<Manage_your_system, Διαχείριση του συστήματός σας>>.

Εκτός αν άλλως σημειώνεται αυτά τα βοηθητικά προγράμματα θα πρέπει να χρησιμοποιούνται ως ρίζα. Για να γίνει ρίζα,
π.χ. να πάρει την κατάσταση 'διαχειριστή' και τα προνόμια πληκτρολογήστε "su -" τότε κωδικό πρόσβασης root's.
Για να επιστρέψετε στην κανονική κατάσταση του χρήστη pres Ctrl+d ή πληκτρολογήστε έξοδο.

Τα περισσότερα βοηθητικά προγράμματα έχουν μια γραμμή εντολών και μια γραφική έκδοση. Η έκδοση της γραμμής εντολών
παρατίθεται παρακάτω. Εκτός αν ορίζεται διαφορετικά, όλες οι εντολές θα πρέπει να είναι
τύποι ως root.

*Γενικές ρυθμίσεις*

* Για τη διαχείριση χρηστών: usersetup ή gtkusersetup
* Για να αλλάξετε τη γλώσσα και την περιοχή: localesetup ή gtklocalesetup
* Για να αλλάξετε τη ρύθμιση του πληκτρολογίου και τη μέθοδο εισόδου: keyboardsetup ή gtkkeyboardsetup
* Για να ρυθμίσετε την ημερομηνία, την ώρα ή τη ζώνη ώρας: ρολόι setup και gtkclocksetup.
* Για να επιλέξετε ποιες υπηρεσίες ξεκινούν κατά την εκκίνηση: servicesetup και gtkservicesetup.
* To (re)configure the network: netsetup.
* Για να επιλέξετε να ξεκινήσετε σε λειτουργία κειμένου ή γραφικής παράστασης και στη μεταγενέστερη περίπτωση ο γραφικός διαχειριστής σύνδεσης:
* Για να επιλέξετε μια επιφάνεια εργασίας ή μια γραφική συνεδρία: session-chooser (ως κανονικός χρήστης)
* Εάν το KDE είναι εγκατεστημένο για να εμφανίζει ή να αποκρύπτει τις εφαρμογές του σε άλλα μενού της επιφάνειας εργασίας'σας: εμφάνιση- kde-apps ή αποκρύψετε-kde-apps.

*Ρυθμίσεις προσβασιμότητας*

Για να επιλέξετε και να ενεργοποιήσετε ένα πρόγραμμα ανάγνωσης οθόνης κονσόλας ή να απενεργοποιήσετε όλα αυτά πληκτρολογήστε ως root:
----
μιλάν-μεName
----

Από το Slint έκδοση 14.2. και μετά ο πρώτος κανονικός χρήστης που δημιουργήθηκε κατά τη διάρκεια της εγκατάστασης θα έχει ομιλία και braille ήδη ενεργοποιημένη στο εγκατεστημένο σύστημα, εάν χρησιμοποιήθηκε ομιλία και ζητήθηκε braille κατά τη διάρκεια της εγκατάστασης. Άλλοι χρήστες θα πρέπει να ελέγξουν ή να κάνουν πρόσθετες ρυθμίσεις, όπως υποδεικνύεται παρακάτω.

Για να ενεργοποιήσετε το braille:

. Κάνε το /etc/rc.d/rc.brltty εκτελέσιμη πληκτρολόγηση ως root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Κάνε τον εαυτό σου μέλος της ομάδας braille, πληκτρολογώντας ως ρίζα:
+
----
usermod -G braille -a username
----
+
Στην παραπάνω εντολή, αντικαταστήστε το όνομα χρήστη με το όνομα σύνδεσής σας.
. Στη συνέχεια, επεξεργαστείτε ως root το αρχείο /etc/brltty.conf για να συμπεριλάβετε τις ρυθμίσεις σας.

Για να ενεργοποιήσετε την ομιλία στο επίπεδο του συστήματος ως root:
----
επιλογέας σύνδεσης
----
και επιλέξτε έναν από τους τρόπους σύνδεσης που μιλούν: κείμενο, ελαφρύ ή gdm

Για να ενεργοποιήσετε την ομιλία σε γραφικά περιβάλλοντα ως κανονικό τύπο χρήστη όπως αυτός ο χρήστης:
----
orca-on
----
Στη συνέχεια, ο αναγνώστης οθόνης Orca θα αρχίσει να μιλά την επόμενη φορά που θα ξεκινήσετε ένα γραφικό
περιβάλλον

Για να απενεργοποιήσετε την ομιλία σε γραφικά περιβάλλοντα πληκτρολογήστε αντί:
----
orca-off
----

==  Χρήση επίδεσμου

Αυτό το κεφάλαιο παρουσιάζει τους τρόπους με τους οποίους μπορείτε να αλληλεπιδράσετε με το σύστημα Slint για να έχετε
κάνει αυτό που θέλετε.

=== Τι είναι ένα σύστημα Slint?

Slint είναι ένα σύνολο λογισμικού που κατά προσέγγιση εμπίπτουν σε αυτές τις κατηγορίες:

* Το λειτουργικό σύστημα, από τον πυρήνα <<kernel, Linux>> και <<utilities, βοηθητικά προγράμματα>>. Δρα ως διεπαφή μεταξύ του χρήστη, των εφαρμογών και του υλικού
* Οι <<Applications, εφαρμογές>> που εκτελούν τις εργασίες που οι χρήστες θέλουν να εκπληρώσουν.

Το Slint μπορεί να χρησιμοποιηθεί σε δύο τρόπους που διακρίνονται από την εμφάνιση της οθόνης
και τον τρόπο αλληλεπίδρασης με το σύστημα:

* Στη λειτουργία κειμένου πληκτρολογείτε εντολές που ερμηνεύονται από ένα <<shell, κέλυφος>>. Αυτές οι εντολές μπορούν να ξεκινήσουν ένα βοηθητικό πρόγραμμα ή μια εφαρμογή. Η λειτουργία κειμένου ονομάζεται επίσης λειτουργία <<console, κονσόλας>>. Σε αυτή τη λειτουργία η οθόνη εμφανίζει μόνο τις εντολές και την έξοδο τους σε ένα (συνήθως μαύρο) φόντο.
* Στην γραφική λειτουργία εμφανίζονται στην οθόνη γραφικά στοιχεία, όπως παράθυρα, πάνελ ή εικονίδια, που σχετίζονται γενικά με εφαρμογές ή επιχειρήσεις κοινής ωφέλειας. Ο χρήστης αλληλεπιδρά με αυτά τα στοιχεία χρησιμοποιώντας ένα ποντίκι ή ένα πληκτρολόγιο.

Οι εντολές μπορούν επίσης να πληκτρολογηθούν σε γραφική λειτουργία μέσα σε ένα παράθυρο που σχετίζεται με
ένα <<terminal, τερματικό>> στο οποίο εκτελείται ένα κέλυφος.

=== Πώς ξεκινά το Slint

Κατά την εγκατάσταση, το λογισμικό που αποστέλλεται στο ISO εγκατάστασης ή κατεβασμένο
από απομακρυσμένα αποθετήρια είναι εγκατεστημένο σε μονάδα δίσκου <<drive, >>.

Κατά την εκκίνηση του Slint, το <<firmware, firmware>> πρώτα ελέγχει το υλικό και στη συνέχεια
ψάχνει για ένα πρόγραμμα που ονομάζεται OS loader (συνήθως ονομάζεται φορτωτής εκκίνησης) που ξεκινάει
.

Μπορεί να υπάρχουν αρκετοί φορτωτές OS στο μηχάνημα. Σε αυτή την περίπτωση το
firmware επιτρέπει στο χρήστη να επιλέξει ποιος θα ξεκινήσει σε ένα μενού.

Στο Slint το λογισμικό
που κάνει και να εγκαταστήσετε ένα φορτωτή εκκίνησης είναι GRUB. σχεδόν ο φορτωτής εκκίνησης
που κατασκευάστηκε από το GRUB είναι επίσης ένας διαχειριστής εκκίνησης, καθώς επιτρέπει να επιλέξετε ποιο λειτουργικό σύστημα θα ξεκινήσει αν έχουν εγκατασταθεί
πολλά.

Ο φορτωτής OS που κατασκευάστηκε από την GRUB μπορεί να εγκατασταθεί σε έναν τομέα εκκίνησης
(σε περίπτωση Legacy εκκίνησης) ή σε ένα χώρισμα συστήματος EFI ή ESP (σε
περίπτωση εκκίνησης EFI).

Ο στόχος του φορτωτή Slint είναι να ξεκινήσει το σύστημα Slint. Για να το κάνετε αυτό πρώτα φορτώνει το
RAM ο <<kernel, πυρήνας>>, τότε το <<initrd, initrd>>, το οποίο με τη σειρά του
προετοιμάζει το σύστημα Slint.

Στο τελευταίο βήμα αυτής της αρχικοποίησης ο χρήστης καλείται να "συνδεθεί", in
other words to connect oneself to the system and take the hand on it. Για να κάνετε
ότι ο χρήστης πρώτα πληκτρολογήστε ένα's όνομα χρήστη (ή όνομα σύνδεσης) και στη συνέχεια τον κωδικό πρόσβασης, από τον οποίο
εγκυρότητα ελέγχεται. Το Slint όπως και άλλες διανομές Linux που είναι πολλοί χρήστες αυτό
επιτρέπει σε αυτόν το χρήστη να έχει πρόσβαση σε ένα's αρχεία, αλλά όχι εκείνα των άλλων χρηστών.

Τη στιγμή της εγκατάστασης επιλέξατε να ξεκινήσετε το Slint είτε σε λειτουργία κειμένου είτε σε γραφική λειτουργία.

* Αν επιλέξατε το C για <<console, κονσόλα>> μετά την αρχικοποίηση του συστήματος πληκτρολογείτε το όνομα χρήστη (ή συνδεθείτε) τότε τον κωδικό πρόσβασής σας, κάθε εισαγωγή που επιβεβαιώνεται πατώντας το πλήκτρο Enter τότε μπορείτε να πληκτρολογήσετε εντολές.
* Εάν επιλέξετε G (γραφικά) πληκτρολογείτε τις ίδιες πληροφορίες σε έναν <<display_manager, διαχειριστή εμφάνισης>> ή διαχειριστή σύνδεσης, που στη συνέχεια ξεκινά το <<graphical_environment, γραφικό περιβάλλον>>.

Μετά την εγκατάσταση, αν μπορείτε να αλλάξετε τη λειτουργία πληκτρολόγηση ως root `login-chooser`,
σε κατάσταση λειτουργίας κονσόλας καθώς και σε γραφική λειτουργία (σε ένα <<terminal, τερματικό>>). Αυτή η εντολή
σας επιτρέπει να επιλέξετε `κείμενο` (συνώνυμο λειτουργίας κονσόλας), ή, για
γραφική λειτουργία, μεταξύ πολλών διαχειριστών οθόνης. Η επιλογή σας θα είναι αποτελεσματική
στην επόμενη εκκίνηση του υπολογιστή.

Τώρα θα παρουσιάσουμε τα γραφικά περιβάλλοντα, στη συνέχεια πώς να χρησιμοποιήσετε ένα κέλυφος.

=== Το Γραφικό Περιβάλλον

<<the_windows, Τα παράθυρα>> +
<<the_work_spaces, Τα κενά εργασίας>> +
<<the_desktop, Η επιφάνεια εργασίας>> +
<<the_top_panel, Ο επάνω πίνακας>> +
<<the_bottom_panel, Ο κάτω πίνακας>> +
<<the_slint_control_center, Το Κέντρο Ελέγχου Γραμμών>> +
<<graphical_terminals, Γραφικά τερματικά>> +
<<key_bindings, Συνδέσεις πλήκτρων>>

Ένα πλήρες γραφικό περιβάλλον περιλαμβάνει διάφορα συστατικά, μεταξύ των οποίων ένας διαχειριστής παραθύρων που σχεδιάζει τα παράθυρα στην οθόνη που σχετίζονται με τις εφαρμογές, μετακίνηση, αλλαγή μεγέθους και κλείσιμο αυτών των παραθύρων.

Το Slint επιτρέπει διάφορα γραφικά περιβάλλοντα: BlackBox, Fluxbox, KDE, LXDE και MATE, TWM, XFCE και WindowMaker. Είναι θέμα προτίμησης που εσείς επιλέξετε.

Το KDE, το LXDE MATE και το XFCE είναι πλήρεις επιφάνειες εργασίας, τους άλλους κυρίως
διαχειριστές παραθύρων, αλλά περιλαμβάνουν ένα πάνελ με ένα μενού εφαρμογής. Όλοι σας επιτρέπουν να
έχετε πρόσβαση στα έγγραφα και τις εφαρμογές σας, γενικά ανοιγμένες σε ένα παράθυρο, περιλαμβάνουν έναν πίνακα και ένα μενού.

Το προεπιλεγμένο γραφικό περιβάλλον μπορεί να αλλάξει πληκτρολογώντας ως κανονικός χρήστης `session-chooser`. Σε γραφική λειτουργία μπορείτε επίσης να επιλέξετε κατά τη σύνδεση.

Θα περιγράψουμε τώρα εν συντομία τα στοιχεία της επιφάνειας εργασίας Mate, η οποία είναι η προεπιλογή και είναι επίσης η πιο προσιτή με ομιλία και braille. Άλλες πλήρεις χαρακτήρισε επιτραπέζιους υπολογιστές έχουν παρόμοια χαρακτηριστικά.

Χρησιμοποιώντας το ποντίκι μπορείτε να ανακαλύψετε τα χαρακτηριστικά κάθε στοιχείου που κάνει ή προσομοιώνει ένα δεξί, μεσαίο ή αριστερό κλικ. Μετακινήστε ή διαγράψτε τα περισσότερα από τα συστατικά, τροποποιήστε τα και προσθέστε νέα μπορούν να γίνουν με τον ίδιο τρόπο.

Αυτά τα συστατικά μπορεί να φτάσει τη μετακίνηση του ποντικιού και επίσης μέσω συντομεύσεων πληκτρολογίου. Δηλώνουμε παρακάτω μέσα σε παρένθεση τις συντομεύσεις πληκτρολογίου που επιτρέπουν να επιτευχθεί, με άλλα λόγια να δοθεί έμφαση σε κάθε στοιχείο. Θα συνοψίσουμε επίσης τις <<key_bindings, συντομεύσεις κλειδιού>> για την επιφάνεια εργασίας Mate (χρησιμοποιώντας τον προεπιλεγμένο διαχειριστή παραθύρων Marco) και για τον διαχειριστή παραθύρων Compiz.

[TIP]
====
Μπορείτε να ανακαλύψετε τα περισσότερα από τα χαρακτηριστικά των εφαρμογών και άλλων στοιχείων του Slint με δεξιά, μεσαία ή αριστερό κλικ του ποντικιού.  Για παράδειγμα, κάνοντας κλικ στον πίνακα, τη γραμμή τίτλου, τα πλήκτρα αριστερά και δεξιά του κάθε παραθύρου, ένα εικονίδιο στον πίνακα ή σε κενό χώρο της οθόνης.
====
[[the_windows]]
==== Τα παράθυρα

Ένα παράθυρο είναι μια ορθογώνια περιοχή που σχετίζεται με μια εφαρμογή. Τα Windows μπορούν να μετακινηθούν, να αλλάξουν μέγεθος, να μεγιστοποιηθούν, να αποκατασταθούν, να κλείσουν (τερματισμός της εφαρμογής που χειρίζεται) χρησιμοποιώντας το ποντίκι ή συντομεύσεις πληκτρολογίου.

[[the_work_spaces]]
==== Οι χώροι εργασίας

Για να είναι δυνατή η ομαλή λειτουργία πολλών παραθύρων, το γραφικό περιβάλλον παρέχει αρκετούς χώρους εργασίας και επιτρέπει την εναλλαγή μεταξύ τους. Κάθε χώρος εργασίας θα εμφανίζει την ίδια επιφάνεια εργασίας και πίνακες, αλλά τα παράθυρα μπορούν να τοποθετηθούν σε συγκεκριμένο χώρο εργασίας ή σε όλα αυτά. Αυτή η ρύθμιση είναι διαθέσιμη με δεξί κλικ στην επάνω άκρη του παραθύρου. Εναλλαγή σε άλλο χώρο εργασίας μπορεί να γίνει κάνοντας κλικ στη θέση του στο κάτω μέρος του πίνακα της οθόνης, στον εναλλάκτη χώρου εργασίας, όπως υποδεικνύεται παρακάτω.

[[the_desktop]]
==== Η επιφάνεια εργασίας

Η επιφάνεια εργασίας περιλαμβάνει ολόκληρη την οθόνη, στην οποία μπορούν να τοποθετηθούν άλλα στοιχεία, στην περίπτωση του Mate και όπως αποστέλλεται στο Slint μια κορυφή και ένα κάτω μέρος, και τέσσερα εικονίδια που από πάνω προς τα κάτω επιτρέπουν το άνοιγμα στα παράθυρα:

* ο ριζικός κατάλογος στον διαχειριστή αρχείων
* τον αρχικό σας κατάλογο στον διαχειριστή αρχείων
* το Κέντρο Ελέγχου Slint
* τα σκουπίδια μπορούν, όπου τοποθετούνται αρχεία που σκοπεύετε να διαγράψετε, αλλά didn't ακόμα.

Παράθυρα της εφαρμογής που αρχίζετε, όπως επίσης τοποθετείτε στην επιφάνεια εργασίας.

Mate περιλαμβάνει δύο πάνελ, η οποία παρουσιάζεται ως λεπτή ορθογώνια οριζόντια περιοχές, μία στην κορυφή και μία στο κάτω μέρος της οθόνης.

Πατώντας το Ctrl+Alt+Tab επιτρέπεται ο κύκλος μεταξύ της επιφάνειας εργασίας, της κορυφής και των κάτω πινάκων

Πατώντας το Alt+Tab επιτρέπεται ο κύκλος μεταξύ των παραθύρων στην επιφάνεια εργασίας.

[[the_top_panel]]
==== Ο επάνω πίνακας

Παρουσιάζει, από αριστερά προς τα δεξιά,

* Τρία μενού:
** Ένα μενού εφαρμογών που μπορεί να ανοίξει πατώντας Alt+F1. Από εκεί μπορείτε να ανοίξετε τα άλλα μενού χρησιμοποιώντας το δεξί βέλος. Μπορείτε να χρησιμοποιήσετε τα βελάκια για να φτάσετε στο μενού των άλλων.
** Ένα μενού τοποθεσιών.
** Ένα μενού συστήματος που δίνει πρόσβαση σε ένα υπομενού προτιμήσεων, το Κέντρο Ελέγχου Mate και τα κουμπιά για να λάβετε βοήθεια σχετικά με την επιφάνεια εργασίας, κλειδώστε την οθόνη, κλείστε τη συνεδρία και τερματίστε τον υπολογιστή.
* Εφαρμογές εκτοξευτές για mate-terminal, ο διαχειριστής αρχείων caja, ο πελάτης ηλεκτρονικού ταχυδρομείου thunderbird, το πρόγραμμα περιήγησης web firefox, ο συντάκτης κειμένου Geany.
* Μια ειδοποίηση που μπορεί να συγκεντρώσει μικροεφαρμογές όπως ένας διαχειριστής Bluetooth, ένας μίκτης ήχου, ένας διαχειριστής δικτύου και ένας "διαθέσιμος" κοινοποιών.
* Ένα ρολόι και ημερολόγιο.
* Ένα κλείδωμα οθόνης.
* Ένας στενός διάλογος συνεδρίας.
* Ένας διάλογος τερματισμού.

[TIP]
====
* Για να προσαρμόσετε τον πίνακα με τις προτιμήσεις σας: κάντε δεξί κλικ σε ένα κενό χώρο στον πίνακα.
* Αν θέλετε να μετακινήσετε ένα αντικείμενο στον πίνακα: Μεσαίο κλικ στο στοιχείο, σύρετε το ποντίκι σας και θα ακολουθήσει το ποντίκι μέχρι να απελευθερωθεί το μεσαίο κουμπί.
* Για μια σχετική βοήθεια πατήστε F1
====

[[the_bottom_panel]]
==== Ο κάτω πίνακας

Παρουσιάζει, από αριστερά προς δεξιά:

* Μια λίστα παραθύρων που μπορεί να ρυθμιστεί με ένα δεξί κλικ στη γραμμή των τριών κάθετων κουκκίδων στην αρχή και επιλέγοντας τις προτιμήσεις. Αυτό επιτρέπει επίσης την εκκίνηση της οθόνης συστήματος σε ένα παράθυρο.
* Ένα κουμπί *εμφάνισης επιφάνειας εργασίας*. Ένα αριστερό θα ελαχιστοποιήσει ή θα αποκρύψει όλα τα παράθυρα, κάνοντας κλικ για άλλη μια φορά θα επαναφέρετε τα παράθυρα στην προηγούμενη κατάστασή τους.
* Ένας διακόπτης χώρου εργασίας, ή pager. Επιτρέπει να μεταβείτε από ένα χώρο εργασίας σε ένα άλλο και επίσης να μετακινήσετε τα παράθυρα από ένα χώρο εργασίας σε ένα άλλο με σύρσιμο και πτώση.

Οι διαχειριστές παραθύρων έχουν ρυθμιστεί στο Slint για να μπορούν να χρησιμοποιηθούν χωρίς αλλαγές. Ωστόσο, μπορείτε να τους αναδιαμορφώσετε σύμφωνα με τις προτιμήσεις σας. Ο τρόπος για να γίνει αυτό ποικίλλει από το διαχειριστή παραθύρων σε διαχειριστή παραθύρων. Για περισσότερες πληροφορίες, δείτε: http://docs.slackware.com/en:user_settings[Ρυθμίσεις χρήστη].

[[the_slint_control_center]]
====  Το Κέντρο Ελέγχου Slint

Θα ολοκληρώσουμε αυτή την εισαγωγή στη χρήση Slint's παρουσιάζοντας το Κέντρο Ελέγχου Slint. Μπορείτε να το εμφανίσετε από το μενού της εφαρμογής στον επάνω πίνακα ή κάνοντας κλικ στο εικονίδιό του στην επιφάνεια εργασίας ή πληκτρολογώντας qcontrolcenter σε ένα διάλογο "Εκτέλεση..." υψωμένο με Alt+F2

Ο στόχος του πίνακα ελέγχου είναι να συγκεντρώσει εφαρμογές που είναι χρήσιμες για τη διαχείριση του συστήματος, τεκμηρίωση, και ρυθμίσεις με συνεπή τρόπο σε όλους τους διαχειριστές παραθύρων.  Κάνοντας κλικ σε μια κατηγορία στο αριστερό μενού, μπορείτε να εμφανίσετε τις αντίστοιχες εφαρμογές στο δεξί παράθυρο.  Θα τις παρουσιάσουμε σε μορφή πίνακα.  Αυτό θα μας δώσει την ευκαιρία να παρουσιάσουμε τα εργαλεία διαχείρισης που έχουν επίσης ένα γραφικό περιβάλλον χρήστη.

Τα περισσότερα εργαλεία διαχείρισης πρέπει να χρησιμοποιούνται με δικαιώματα διαχείρισης.  Θα σας ζητηθεί ο κωδικός πρόσβασης του ριζικού λογαριασμού για να ξεκινήσει ένα εργαλείο.

[options="autowidth"]
|====
<|**Κατηγορία** <|**Εργαλείο** <|**Σκοπός και παρατηρήσεις**
<|Εφαρμογές <|Dotnew <|Αυτό το εργαλείο σας επιτρέπει να διαχειριστείτε το νέο (που ονομάζεται _κάτι. ew_ εξ ου και το όνομα του εργαλείου) vs παλιά αρχεία ρυθμίσεων μετά την αναβάθμιση ορισμένων πακέτων.  Είναι's μια καλή συνήθεια να τρέχει αν μετά από μια αναβάθμιση.  Θα σας πει αν υπάρχει κάτι για να φροντίσει και στη συνέχεια να σας παρουσιάσει μια επιλογή των ενεργειών.
<|Εφαρμογές <|Διαχειριστής Πακέτου Gslapt <|Το Gslapt είναι ένα γραφικό front-end στο slapt-get.  Είναι ένα εύχρηστο εργαλείο για να εκτελέσετε <<software_management, διαχείριση λογισμικού στο Slint>>.  Σας επιτρέπει να αναζητήσετε, να εγκαταστήσετε, να αφαιρέσετε, να αναβαθμίσετε και να ρυθμίσετε τα πακέτα λογισμικού.
<|Εφαρμογές <|Διευθυντής Πηγής SlackBuild <|Πηγή είναι ένα γραφικό front-end για slapt-src.  Σας επιτρέπει να αναζητήσετε σενάρια SlackBuilds που μπορεί στη συνέχεια να χρησιμοποιήσει για να αυτοματοποιήσει τη διαδικασία κατασκευής και την εγκατάσταση των πακέτων λογισμικού.  Μπορεί επίσης να αφαιρέσει και να επανεγκαταστήσει πακέτα στο σύστημά σας.
<|Εφαρμογές <|Εύρεση Εφαρμογής <|Βρείτε και ανοίξτε τις εφαρμογές που είναι εγκατεστημένες στο σύστημά σας.  Το πεδίο αναζήτησης είναι πολύ βολικό για να βρείτε εφαρμογές σε σύγκριση με τη μη αυτόματη αναζήτηση στο μενού της εφαρμογής.
<|Υλικό <|Ρύθμιση Εκτυπωτή <|Χρησιμοποιείται για τη ρύθμιση οποιουδήποτε συνδεδεμένου εκτυπωτή.  Πρόκειται για ένα front-end του CUPS print server, ο οποίος εκτελείται από προεπιλογή στο Slint.
<|Υλικό <|Έλεγχος Εκτύπωσης Cups <|Αυτή η εφαρμογή σας επιτρέπει να ρυθμίσετε την υπηρεσία CUPS, να διαχειριστείτε εκτυπωτές και να ελέγχετε εργασίες εκτύπωσης μέσω ενός προγράμματος περιήγησης ιστού.
<|Υλικό <|Keyboard <|Αυτό το εργαλείο σας επιτρέπει να ορίσετε τον τύπο του πληκτρολογίου, το χάρτη πλήκτρων και να ενεργοποιήσετε την υπηρεσία SCIM.  SCIM βοηθά επιτρέποντάς σας να πληκτρολογήσετε χαρακτήρες για τους οποίους δεν υπάρχει κλειδί στο πληκτρολόγιο (όπως σε πολλές ασιατικές γλώσσες).
<|Πληροφορίες <|Ιστοσελίδα SlackDocs <|Τα έγγραφα σε αυτό το wiki προορίζονται κυρίως για έναν χρήστη Slackware, αλλά πολλά από αυτά είναι χρήσιμα για έναν χρήστη Slint.  *Προσοχή:*  Μερικά από τα εργαλεία που αναφέρονται, όπως τα slackpkg, πρέπει να *όχι* να χρησιμοποιούνται στο Slint.
<|Πληροφορίες <|Τεκμηρίωση Slackware <|Αυτή η τεκμηρίωση μπορεί επίσης να είναι χρήσιμη για τους χρήστες του Slint.  Το Slint βασίζεται στο Slackware.
<|Πληροφορίες <|Τεκμηρίωση Slint <|Αυτό δίνει τοπική πρόσβαση σε έγγραφα που είναι επίσης διαθέσιμα στην ιστοσελίδα Slint's.
<|Πληροφορίες <|Φόρουμ Slint <|Άνθρωποι των οποίων η μητρική γλώσσα δεν είναι η αγγλική μπορεί επίσης να δημοσιεύσει στα τοπικά φόρουμ Salix.
<|Πληροφορίες <|Ιστοσελίδα Slint <|Η ιστοσελίδα του Slint παρέχει τεκμηρίωση, συνδέσμους και έναν τρόπο για να βρείτε τα ISOs και τα πακέτα.
<|Πληροφορίες <|Πληροφορίες Συστήματος <|Αυτό το εργαλείο συλλέγει πληροφορίες σχετικά με τον υπολογιστή σας, όπως οι συνδεδεμένες συσκευές του (εσωτερικές και εξωτερικές) και τα εμφανίζει όλα σε ένα μέρος.  Μπορεί επίσης να κάνει σήμανση πάγκων συστημάτων.
<|Ρυθμίσεις <|Ρολόι συστήματος <|Αυτό το εργαλείο σας επιτρέπει να ορίσετε ρολόι συστήματος.
<|Ρυθμίσεις <|Ονόματα Υπολογιστών <|Αυτό το εργαλείο σας επιτρέπει να συσχετίσετε διευθύνσεις IP με ονόματα τομέα και ονόματα κεντρικών υπολογιστών
<|Ρυθμίσεις <|Γλώσσα Συστήματος <|Αυτό το εργαλείο σας επιτρέπει να ρυθμίσετε τις τοπικές ρυθμίσεις του συστήματος (γλώσσα και γεωγραφικές ιδιαιτερότητες), ώστε οι εφαρμογές που χρησιμοποιείτε να εμφανίζουν πληροφορίες σε αυτή τη γλώσσα (αν είναι διαθέσιμες).
<|Σύστημα <|Ρολόι Συστήματος <|Αυτό το εργαλείο σας επιτρέπει να ρυθμίσετε τη ζώνη ώρας, επιλέξτε αν το ρολόι θα πρέπει να συγχρονιστεί με διακομιστές Διαδικτύου (αυτό συνιστάται, αλλά φυσικά χρειάζεται σύνδεση στο διαδίκτυο), και αν όχι, ορίστε την ημερομηνία και την ώρα.
<|Σύστημα <|Ονόματα Υπολογιστών <|Αυτό το εργαλείο σας επιτρέπει να ρυθμίσετε το όνομα κεντρικού υπολογιστή του συστήματος. Είναι χρήσιμο αν χρησιμοποιείτε την εγκατάσταση του Slint ως διακομιστή, σε τοπικό δίκτυο ή στο Διαδίκτυο.  Το όνομα υπολογιστή βοηθά δικτυωμένους υπολογιστές να αναγνωρίσουν ο ένας τον άλλο με ένα κοινό όνομα, αν μια υπηρεσία domain name συστήματος δεν χρησιμοποιείται.
<|Σύστημα <|Αναδόμηση Προσωρινής Μνήμης Εικονιδίων <|Αυτό το βοηθητικό πρόγραμμα αναδομεί την προσωρινή μνήμη εικονιδίων, η οποία είναι ένα αρχείο που εγγράφει όλα τα εικονίδια στο σύστημα, επιτρέποντάς τους ταχύτερη πρόσβαση. Εκτελέστε το όταν είναι εγκατεστημένα νέα εικονίδια στο σύστημά σας.
<|Σύστημα <|Υπηρεσίες Συστήματος <|Αυτό το εργαλείο σας επιτρέπει να επιλέξετε ποιες υπηρεσίες θα είναι ενεργοποιημένες κατά την εκκίνηση.  Για παράδειγμα, Bluetooth, το διακομιστή εκτύπωσης CUPS ή ένα διακομιστή ιστού.  Χρησιμοποιήστε το μόνο για να αλλάξετε τις προεπιλεγμένες ρυθμίσεις αν γνωρίζετε τι κάνετε.
<|Σύστημα <|Χρήστες και ομάδες <|Αυτό το εργαλείο σας επιτρέπει να προσθέσετε, να αφαιρέσετε και να ρυθμίσετε λογαριασμούς χρηστών και ομάδες. Είναι ως επί το πλείστον χρήσιμο σε συστήματα πολλαπλών χρηστών.
<|Σύστημα <|Διαχειριστής Εκκίνησης GUEFI <|Αυτό το εργαλείο είναι ένα γραφικό εμπρόσθιο άκρο στην εντολή efibootmanager .  Επιτρέπει την επεξεργασία του υλικολογισμικού EFI's μενού εκκίνησης.  Ενέργειες όπως προσθήκη, αφαίρεση ή αλλαγή παραγγελίας στοιχείου μενού.
<|Σύστημα <|Οθόνη συστήματος MATE<|Αυτό το εργαλείο εμφανίζει πληροφορίες σχετικά με το σύστημα, όπως τη διαδικασία, τη χρήση πόρων (RAM, CPU, την κυκλοφορία δικτύου) και τη χρήση συστημάτων αρχείων.
|====

[[graphical_terminals]]
==== Τερματικά

Μπορείτε να πληκτρολογήσετε εντολές σε γραφική λειτουργία όπως στη λειτουργία κονσόλας, αν ανοίξετε ένα παράθυρο
με ένα τερματικό σε αυτό. Στο Mate μπορείτε απλά να πατήσετε Ctrl+Alt+t, ή κάντε κλικ στο
στο εικονίδιο mate-terminal στον επάνω πίνακα, ή ανοίξτε ένα διάλογο "Εκτέλεση... " πατώντας
Alt+F2 και στη συνέχεια πληκτρολογώντας `mate-terminal` στο μικρό παράθυρο που ανοίγει.

Οι περισσότερες από τις παρακάτω πληροφορίες σχετικά με τη γραμμή εντολών και το κέλυφος στη λειτουργία Κονσόλας
ισχύουν επίσης για την πληκτρολόγηση εντολών σε ένα τερματικό. Μπορείτε να κλείσετε mate-τερματικό
πατώντας Alt+F4 όπως με οποιοδήποτε άλλο παράθυρο.

[[key_bindings]]
==== Συντομεύσεις πλήκτρων

Παρουσιάζουμε εδώ τις προεπιλεγμένες συνδέσεις πλήκτρων για τον διαχειριστή παραθύρων Compiz και την επιφάνεια εργασίας Mate, και πώς να τις προσαρμόσετε.

[NOTE]
====
Όταν ένα δεσμευτικό κλειδί περιλαμβάνει ένα ή περισσότερα σύμβολα *+* , πατήστε παρατεταμένα από αριστερά προς τα δεξιά τα πλήκτρα πριν το τελευταίο σαν πλήκτρο `Shift` , στη συνέχεια πατήστε το τελευταίο πλήκτρο.
====
===== Συντομεύσεις πλήκτρων για την επιφάνεια εργασίας Mate

Όταν χρησιμοποιείτε το Mate στο Slint, μερικές συντομεύσεις πλήκτρων είναι ίδιες είτε με
τους διαχειριστές παραθύρων Marco ή Compiz. Παρακάτω αναφέρονται:
----
Κύκλος Alt+Tab μεταξύ παραθύρων
Κύκλος Shift+Alt+Tab πίσω μεταξύ παραθύρων
Έλεγχος + Κύκλος Alt+Tab μεταξύ πινάκων και επιφάνειας εργασίας
Shift+Control+Alt+Tab Κύκλος προς τα πίσω μεταξύ πινάκων και επιφάνειας εργασίας
----
Μόλις σε ένα γραφικό περιβάλλον, μπορείτε να εναλλάξετε μεταξύ του και μια
κονσόλα. Let's say you want to use tty2 (tty1 being busy):
Πατήστε `Ctrl+Alt+F2`, και μετά συνδεθείτε. +
Πατήστε `Ctrl+Alt+F7` για να επιστρέψετε στο γραφικό περιβάλλον.

Οι ίδιες γενικές συντομεύσεις πλήκτρων χρησιμοποιούνται σε όλα τα γραφικά περιβάλλοντα,
με λίγες εξαιρέσεις, το Mod1 είναι γενικά το αριστερό πλήκτρο Alt: +
----
Mod1+F1 αυξάνει το μενού εφαρμογής του πίνακα.
Το Mod1+F2 δημιουργεί ένα διάλογο 'run...', αλλά στο Fluxbox (ξεκινά το lxterminal αντίστοιχα).
----
Επίσης στο Fluxbox:
----
Mod1+F3 restarts Fluxbox.
Το Mod1+F4 κλείνει το εστιασμένο παράθυρο.
----
Το μενού εφαρμογών πάνελ's έχει την ίδια διάταξη σε όλα τα προσβάσιμα
γραφικά περιβάλλοντα που αποστέλλονται αλλά MATE. Από πάνω προς τα κάτω:

Εξομοιωτής τερματικού: `mate-terminal` στο MATE, elsewhere `lxterminal` by default +
Διαχειριστής αρχείων: `Caja` in MATE elsewhere `PCManfm` by default +
Πρόγραμμα περιήγησης στο Web: `Firefox` από προεπιλογή +
Πρόγραμμα αλληλογραφίας: Thunderbird by default +
Προτιμήσεις +
Slint Dashboard (non accessible yet as's a Qt4 app) +
Εφαρμογές ταξινομημένες κατά κατηγορία +
Διάλογος Εκτέλεσης +
διαλόγου αποσύνδεσης (επίσης επιτρέπει την απενεργοποίηση και επανεκκίνηση)

Μπορείτε να χρησιμοποιήσετε τα βελάκια για να περιηγηθείτε στο μενού.

Στο MATE, ο επάνω πίνακας περιλαμβάνει στα αριστερά του από αριστερά προς δεξιά:

τα μενού (Applications, then Places, then System) +
εκτοξευτές για mate-terminal, caja (διαχειριστής αρχείων), Firefox, Thunderbird και τον επεξεργαστή κειμένου
geany +
Στα δεξιά του ακόμα από αριστερά προς τα δεξιά:
μια περιοχή ειδοποιήσεων +
ένα κουμπί κλειδώματος οθόνης +
ένα κουμπί αποσύνδεσης +
κουμπιά διακοπής ή επανεκκίνησης.

Ο κάτω πίνακας έχει από αριστερά προς δεξιά:

μια λίστα παραθύρων +
ένα πρόσθετο "show destktop" +
μια εναλλαγή χώρου εργασίας.

Ακόμα στο Mate, οι χρήστες με μειωμένη όραση μπορούν να χρησιμοποιήσουν το παράθυρο compiz αντί αυτού
ή marco που είναι η προεπιλογή.

Ως τακτικός χρήστης, πληκτρολογήστε:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
Για να επιστρέψετε στο μάρκο:
----
gsettings set org.mate.session.required-components windowmanager marco
----
Αυτή η ρύθμιση θα τεθεί σε ισχύ στην επόμενη έναρξη μιας συνεδρίας Mate.

Ή για να κάνετε την αλλαγή μόνο για τον τρέχοντα τύπο συνεδρίας:
----
compiz --replace &
----
and to go back to marcomarco:
----
marco --replace &
----
Η αντικατάσταση θα είναι αποτελεσματική αμέσως

Αυτή η ρύθμιση είναι επίσης διαθέσιμη γραφικά από mate-tweak, στην κατηγορία
Windows.

Μπορείτε να αποκτήσετε πρόσβαση σε συγκεκριμένες ρυθμίσεις Compiz απλά πληκτρολογήστε:
----
ccsm &
----
===== Συντομεύσεις πλήκτρων για τον διαχειριστή παραθύρων Compiz

In the default settings indicated below the key or mouse buttons are
named like this:

Super: Windows key on most keyboards +
Button1: Left Mouse Button (if used with the right hand) +
Button2: Centre Mouse Button, or click with the scroll wheel) +
Button3: Right Mouse Button (if used with the right hand) +
Button4: Scroll Wheel Up +
Button5: Scroll Wheel Down
Button6: (I don't know, I thought that was on mouses for gamers) +

The default settings listed below by category can be changed from the
CCSM. We indicate the short name of the plugin between square brackets.

. Category General
+
[core] General options, tab "key bindings": +
close_window_key = Alt+F4 +
raise_window_button = Control+Button6 +
lower_window_button = Alt+Button6 +
minimize_window_key = Alt+F9 +
maximize_window_key = Alt+F10 +
unmaximize_window_key = Alt+F5 +
window_menu_key = Alt+space +
window_menu_button = Alt+Button3 +
show_desktop_key = Control+Alt+d +
toggle_window_shaded_key = Control+Alt+s +
+
[matecompat] Mate Compatibility +
main_menu_key = Alt+F1 +
run_key = Alt+F2 +

. Category Accessibility
+
[addhelper] Dim inactive (less light on non focused windows) +
toggle_key = Super+p +
+
[colorfilter] (Filter color for accessibility purposes) +
toggle_window_key = Super+Alt+f +
toggle_screen_key = Super+Alt+d +
switch_filter_key = Super+Alt+s +
+
[ezoom] Enhanced Zoom Desktop +
zoom_in_button = Super+Button4 +
zoom_out_button = Super+Button5 +
zoom_box_button = Super+Button2 (zoom out to go back to normal) +
+
[neg] Negative (toggle inverse colors of the window or screen) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Opacity, Brightness and Saturation adjustments +
opacity_increase_button = Alt+Button4 +
opacity_decrease_button = Alt+Button5 +
+
[showmouse] (Increase visibility of the mouse pointer) +
initiate = Super+k +

. Category Window Management
+
[move] Move window +
initiate_button = Alt+Button1 (hold Button1 while moving the mouse) +
initiate_key = Alt+F7 (Esc to stop moving) +
+
[resize] Resize window +
initiate_button = Alt+Button 2 (hold Button2 while moving the mouse) +
initiate_key = Alt+F8 (Esc to stop moving) +
+
[switcher] Application switcher (switch between windows or panels and
                                 the desktop) +
next_window_key = Alt+Tab (cycle between windows) +
prev_window_key = Shift+Alt+Tab +
next_panel_key = Control+Alt+Tab (cycle between panels and desktop) +
prev_panel_key = Shift+Control+Alt+Tab +


===== Πώς να προσθέσετε μια προσαρμοσμένη σύνδεση κλειδιών για το Mate.

Let's take an example: we want that Alt+F3 starts firefox.
πληκτρολογήστε σε ένα τερματικό ή σε εντολή Run (σφυρήλατο πατώντας Alt+F2):
----
ιδιότητες mate-keybinding-
----
Στο νέο παράθυρο μπορείτε να χρησιμοποιήσετε το πάτημα των κάτω και πάνω πλήκτρων βέλους για να
πλοηγηθείτε στη λίστα με τις υπάρχουσες συνδέσεις πλήκτρων.

Για να ορίσετε ένα νέο πλήκτρο σύνδεσης, πατήστε Καρτέλα δύο φορές για να βάλετε το δρομέα στο Add, στη συνέχεια,
πατήστε Enter. Στο μικρό παράθυρο διαλόγου έφερε επάνω πληκτρολογήστε το όνομα του
προσαρμοσμένου κλειδιού σύνδεσης, όπως firefox, πατήστε Tab, πληκτρολογήστε το όνομα στη σχετική εντολή
, σε αυτή την περίπτωση το firefox, στη συνέχεια, πατήστε Καρτέλα δύο φορές στο
βάλτε το δρομέα στο Εφαρμογή και πατήστε Enter.

Για να ενεργοποιήσετε τη νέα σύνδεση πλήκτρων, πλοηγηθείτε μέχρι να τη βρείτε στο
κάτω μέρος της λίστας, κάντε κλικ στο πλήκτρο Alt+F3.

Την επόμενη φορά που θα πατήσετε το Alt+F3 που θα ξεκινήσει το firefox

=== Το κέλυφος

NOTE: Αυτό το κεφάλαιο είναι μια σύντομη εισαγωγή. Περισσότερες σε βάθος πληροφορίες παρέχονται στο έγγραφο https://slint.fr/doc/shell_and_bash_scripts.html[Σενάρια Shell και bash], κυρίως δανεισμένες από SUSE.

Όταν ο υπολογιστής ξεκινά σε λειτουργία κονσόλας, αφού συνδεθεί πληκτρολογώντας το όνομα χρήστη και τον κωδικό πρόσβασης, το <<shell, κέλυφος>> εμφανίζει μια "προτροπή" όπως αυτή που ακολουθεί: +
`didier@darkstar:~$` +
Στο παράδειγμα τους:

* `didier` είναι το όνομα χρήστη
* `σκούρο αστέρι` το όνομα του μηχανήματος
* το tilde `~` αντιπροσωπεύει τον αρχικό κατάλογο του χρήστη, σε αυτό το παράδειγμα `/home/didier`
* το σύμβολο του δολαρίου `$` δείχνει ότι ο χρήστης είναι ένα "κανονικό" όχι ένα "σούπερ χρήστη" (βλ. παρακάτω).

Ο δρομέας τοποθετείται στη συνέχεια μετά την προτροπή.

Ο χρήστης μπορεί τώρα να πληκτρολογήσει μια εντολή στη γραμμή (εξ ου και το όνομα "γραμμή εντολών") και να επιβεβαιώσει το πάτημα Enter. Το κέλυφος then analyzes the command and execute it if valid, else output a message like for instance "command not found". Μπορείτε να επεξεργαστείτε την εντολή πριν πατήσετε το Enter χρησιμοποιώντας τα αριστερά και δεξιά βέλη και τα πλήκτρα Backspace, Home, End and Del.

Κατά την εκτέλεσή της, οι εντολές μπορούν να εμφανίσουν μια έξοδο στην οθόνη ή όχι. Σε όλες τις περιπτώσεις μετά την εκτέλεσή της, η προτροπή θα εμφανιστεί ξανά σε μια νέα γραμμή, που σημαίνει ότι το κέλυφος περιμένει να πληκτρολογηθεί η επόμενη εντολή.

Για να λειτουργήσει αυτό, ο χρήστης πρέπει να γνωρίζει ποιες εντολές είναι διαθέσιμες και η σύνταξή τους. Μερικές εντολές εκτελούνται από το ίδιο το κέλυφος, άλλες ξεκινούν εξωτερικά προγράμματα. Θα δώσει παρακάτω πολλά παραδείγματα εντολών, περισσότερα παρατίθενται σε https://slint.fr/doc/shell_and_bash_scripts.html[Σενάρια Shell και bash]

Υπάρχουν πολλά κελύφη διαθέσιμα για να διαλέξετε. Στο Slint το κέλυφος που χρησιμοποιείται από προεπιλογή ονομάζεται *bash*.

Για να επιτρέψετε την εκτέλεση πολλών προγραμμάτων ταυτόχρονα το Linux παρέχει αρκετές "εικονικές κονσόλες" που μοιράζονται το ίδιο πληκτρολόγιο και οθόνη, αριθμημένες από ένα. Αρχικά το σύστημα ξεκινά στην κονσόλα (ή στο εικονικό τερματικό) νούμερο ένα ονομάζεται επίσης *tty1* (το όνομα tty είναι μια συντομογραφία του "τηλετύπου"). Από εκεί ο χρήστης μπορεί να μεταβεί σε άλλη κονσόλα ή tty; για παράδειγμα μεταβείτε στον αριθμό αριθμό δύο πατώντας Alt+F2, όπου ένα άλλο κέλυφος θα ζητήσει και πάλι το όνομα χρήστη's και τον κωδικό πρόσβασης. Για να επιστρέψετε σε tty1, απλά πατήστε Alt+F1. Από προεπιλογή στο Slint έξι tty είναι διαθέσιμα, αλλά αυτό μπορεί να αλλάξει την επεξεργασία του αρχείου /etc/inittab.

Όταν το κέλυφος χρησιμοποιείται σε ένα γραφικό περιβάλλον (σε ένα γραφικό τερματικό), συμπεριφέρεται με τον ίδιο τρόπο, αλλά η προτροπή είναι ελαφρώς διαφορετική, όπως φαίνεται παρακάτω: +
`dididier[~]$` +

Μπορείτε να μεταβείτε μεταξύ της κονσόλας και ενός γραφικού περιβάλλοντος:

* Από το γραφικό περιβάλλον πατώντας για παράδειγμα Ctrl+Alt+F3 για να μεταβείτε στο tty3. Την πρώτη φορά που θα πάτε σε ένα Όμορφο θα πρέπει να πληκτρολογήσετε το όνομα χρήστη και τον κωδικό πρόσβασής σας.
* Από μια κονσόλα ή Όμορφο πάτημα Alt+F7 αν το γραφικό περιβάλλον εκτελείται ήδη, αλλιώς πληκτρολογώντας `startx` για να ξεκινήσετε.

==== Πληκτρολογώντας εντολές ως root

*ρίζα* είναι το συμβατικό όνομα του "σούπερ χρήστη" που έχει όλα τα δικαιώματα να κάνει διοικητικές εργασίες, συμπεριλαμβανομένων εκείνων που θα μπορούσαν να βλάψουν ή ακόμα και να καταστρέψουν το σύστημα.

Μπορείτε (αλλά αυτό δεν συνιστάται για αρχάριους) συνδεθείτε άμεσα ως root. Για να κάνετε αυτόν τον τύπο *root* ως χρήστης, τότε root's password.
Για να σας ενημερώσουμε (και να σας προειδοποιήσουμε για τους σχετικούς κινδύνους και ευθύνες), η προτροπή θα μοιάζει κάπως έτσι: +
*root@darkstar:s~#* +
ο χαρακτήρας # (σύμβολο αριθμού, επίσης συνήθως ονομάζεται hash) δείχνει ότι οι εντολές θα πληκτρολογηθούν ως root (όχι ως τακτικός χρήστης), με τα σχετικά δικαιώματα, αλλά και κινδύνους και ευθύνες.

Εάν είστε ήδη συνδεδεμένοι ως κανονικός χρήστης, μπορείτε να "γίνετε ριζικός" πληκτρολογήστε: +
*su -* +
και μετά πατώντας Enter. Σε αυτή την εντολή, `su` (η οποία βρίσκεται fr "Υπερδιαχειριστής ") είναι το όνομα της εντολής, and the character *-* (hyphen-minus, επίσης το όνομα μείον) λέει ότι ανοίγετε ένα "login shell": θα σας ζητηθεί πρώτα root's password, then be directed to its home directory /home/root as if you had logged in as root at startup. Αυτό θα αποφύγει την ακούσια εγγραφή αρχείων στον αρχικό σας κατάλογο ως τακτικός χρήστης (/home/didier στο παράδειγμα) που προκαλούν προβλήματα αργότερα.

=== Πώς να επιλύσετε ζητήματα αποκλεισμού

Με το "μπλοκάρισμα ζητήματος" εννοούμε "ένα ζήτημα που αποτρέπει τη χρήση του Slint" όπως:

* Το σύστημα αποτυγχάνει να εκκινήσει.
* Το σύστημα μπότες, αλλά η σειρά εκκίνησης διακόπτεται πριν από την ολοκλήρωση. Αυτό μπορεί να συμβεί για παράδειγμα εάν το διαμέρισμα του ριζικού συστήματος μπορεί't να τοποθετηθεί λόγω σφάλματος στο /etc/fstab, ένα κατεστραμμένο ριζικό σύστημα αρχείων ή ένα πρόσθετο πυρήνα που λείπει για να προσαρτήσετε την κατάτμηση root, or the system bootsμπότες successfully but you don't remember the password for root.

Αν το σύστημα αποτύχει εντελώς να ξεκινήσει, δοκιμάστε κάθε μία από τις παρακάτω λύσεις σε σειρά, μέχρι να δουλέψει.

. Αν αυτό συμβεί μετά την αναβάθμιση του πυρήνα, δοκιμάστε τη δεύτερη καταχώρηση εκκίνησης αντί για την πρώτη.
. Χρησιμοποιήστε την τελευταία καταχώρηση εκκίνησης του μενού GRUB. Θα μπορούσε να βρει το Slint και να επιτρέψει να το ξεκινήσει.
. Προσπαθήστε να εκκινήσετε από το ραβδί εκκίνησης διάσωσης που έχετε ζητήσει στο τέλος της εγκατάστασης.
. Μετάβαση σε Slint για να το επισκευάσει, όπως εξηγείται παρακάτω.
. Ζητήστε βοήθεια μέσω ηλεκτρονικού ταχυδρομείου slint@freelists.org παρέχοντας όλες τις πληροφορίες που θα μπορούσαν να βοηθήσουν στη διερεύνηση του προβλήματος. Εάν δεν έχει γίνει ήδη, εγγραφείτε πρώτα στη λίστα email slint-request@freelists.org με το θέμα 'εγγραφή', και στη συνέχεια απαντήστε στο email που θα λάβετε. Μόνο αν έχετε κάποιο πρόβλημα χρησιμοποιώντας email, ζητήστε βοήθεια στο IRC κανάλι #slint, το διακομιστή irc.libera.chat και μείνετε στο κανάλι μέχρι κάποιος να απαντήσει.

Εάν η ακολουθία εκκίνησης διακοπεί, πηδήξτε στο Slint από τον εγκαταστάτη του για να προσπαθήσετε να λύσετε το πρόβλημα. Εισαγάγετε ή συνδέστε τα μέσα εγκατάστασης (USB stick ή DVD όπου έχετε γράψει την εγκατάσταση ISO), στη συνέχεια, ακολουθήστε τις παρακάτω οδηγίες.

. Ξεκινήστε τον εγκαταστάτη.
. Μόλις συνδεθείτε ως root, για να απαριθμήσετε τους δίσκους και τα διαμερίσματα, πληκτρολογήστε:
+
----
lsblk -lpo name,size,fstype
----
. Βρείτε στην έξοδο το όνομα του ριζικού διαμερίσματος Slint, ελέγχοντας το μέγεθος και τον τύπο του συστήματος αρχείων, με ετικέτα FSTYPE.
. Τοποθετήστε αυτό το διαμέρισμα και ελέγξτε ότι είναι το καλό. Για παράδειγμα, εάν είναι /dev/sda3, τύπος:
+
----
mount /dev/sda3 /mnt
γάτα /mnt/etc/slint-version
----
+
[NOTE]
====
Εάν το σύστημα αρχείων του διαμερίσματος ρίζας Slint φαίνεται κατεστραμμένο, don't mount το αλλά προσπαθήστε να το επισκευάσετε εκτελώντας αυτήν την εντολή:
----
fsck <name of the root partition>
----
Και αν αυτό πετύχει απλά επανεκκίνηση.
====
+
Υποθέτοντας ότι έχετε εγκαταστήσει το Slint64-14.21 η έξοδος πρέπει να είναι:
+
*Γραμμή 14.2.1*
+
Αν η έξοδος είναι "αρχείο δεν βρέθηκε" η κατάτμηση δεν είναι αυτή που αναζητήσατε. Σε αυτή την περίπτωση μόνο, πληκτρολογήστε:
+
----
umount /mnt
----
+
τότε δοκιμάστε ένα άλλο, πηγαίνοντας πίσω στη λίστα δίσκων και κατατμήσεων.
+
Διαφορετικά, δεσμεύστε τα ψευδο-συστήματα αρχείων /dev, /proc και /sys στο σύστημα Slint, πληκτρολογώντας:
+
----
mount -B /dev /mnt/dev
mount -B /proc /mnt/proc
mount -B /dev /mnt/sys
----
+
Ζητήστε την επόμενη εντολή για να "πηδήξετε σε" το Slint:
+
----
chroot /mnt
----
+
chroot σημαίνει "αλλαγή ρίζας (του συστήματος)": δεν είμαστε πλέον στον εγκαταστάτη, αλλά τώρα στο ίδιο το Slint. Από εκεί μπορείτε να τροποποιήσετε το σύστημα για να επιλύσετε το ζήτημα. Ακολουθούν μερικά παραδείγματα:

* Εκτέλεση "update-grub".

* Εκτέλεση "grub-emu".

* Επανεγκαταστήστε το GRUB χρησιμοποιώντας την εντολή "grub-install drivename", drivename είναι η μονάδα δίσκου όπου να εγκαταστήσετε το Slint. Πριν το κάνετε αυτό, αν θα εκκινήσετε σε λειτουργία EFI πληκτρολογήστε πρώτα "mount /boot/efi".

* Πληκτρολογήστε "passwd" για να αλλάξετε τον κωδικό πρόσβασης για root.

* Κατάργηση, εγκατάσταση ή αναβάθμιση πακέτων.

. Όταν τελειώσετε, αφαιρέστε τα μέσα εγκατάστασης και πληκτρολογήστε:
+
----
έξοδος
επανεκκίνηση
----

[[Accessibility]]
== Accessibility

Αν επιλέξατε να κρατήσετε ομιλία όταν ρωτήσετε στην αρχική εγκατάσταση, θα ενεργοποιηθεί
από την εκκίνηση σε μια κονσόλα όπως σε γραφικά περιβάλλοντα.

=== Χρησιμοποιήστε Slint με braille

Slint περιλαμβάνει το λογισμικό brltty για να χειριστεί οθόνες braille.

Οι ρυθμίσεις σας, που έγιναν πριν από την εκκίνηση στη γραμμή εντολών ή αργότερα, καταγράφονται στο εγκατεστημένο σύστημα στο
/etc/brltty.conf.

Ένα ολοκληρωμένο εγχειρίδιο για brltty είναι διαθέσιμο στα αγγλικά, Γαλλικά και
Πορτογαλικά σε διάφορες μορφές, συμπεριλαμβανομένου απλού κειμένου (txt) σε αυτό το URL:
https://mielke.cc/brltty/doc/Manual-BRLTTY/

Εάν το braille δεν ήταν ενεργοποιημένο κατά την εγκατάσταση ή έχει απενεργοποιηθεί, για να το ενεργοποιήσετε αυτό:

. Κάνε το /etc/rc.d/rc.brltty εκτελέσιμη πληκτρολόγηση ως root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Κάνε τον εαυτό σου μέλος της ομάδας braille, πληκτρολογώντας ως ρίζα:
+
----
usermod -G braille -a username
----
+
Στην παραπάνω εντολή, αντικαταστήστε το όνομα χρήστη με το όνομα σύνδεσής σας.

Για να απενεργοποιήσετε τον τύπο braille ως root:
----
chmod 64 /etc/rc.d/rc.brltty
----

=== Ομιλία σε γραφικά περιβάλλοντα

Ως μια ομιλία υπενθύμισης σε γραφικά περιβάλλοντα με χρήση της συσκευής ανάγνωσης οθόνης Orca είναι ενεργοποιημένη η πληκτρολόγηση:
----
orca-on
----

To know how to use Orca, including its specific key bindings, type:
----
άνδρας όρκα
----

Εν ολίγοις, μία φορά σε γραφικό περιβάλλον, σε γραφική λειτουργία:
----
Εισαγωγή+Χώρο: εκκινήστε το διάλογο orca Προτιμήσεις.
Εισαγωγή+S: ενεργοποίηση ή απενεργοποίηση της σύνθεσης φωνητικών.
Εισαγωγή+H: ενεργοποιήστε τη λειτουργία μάθησης. Σε αυτή τη λειτουργία:
   Πατήστε ένα πλήκτρο για να ακούσετε τη λειτουργία του
   F1: για να ακούσετε την τεκμηρίωση του αναγνώστη οθόνης
   F2: δείτε τις συντομεύσεις πληκτρολογίου για το Orca
   F3: δείτε το πληκτρολόγιο για την τρέχουσα εφαρμογή
   Esc: τέλος της λειτουργίας μάθησης
----

=== Φωνές και TTS στο Slint.

Μετά το TTS (συνθέτες σε λόγο) αποστέλλονται στο
Slint64-14.2.1. , το καθένα με ένα σύνολο φωνών, συγκεκριμένα: +
espeak-ng +
flite +
pico +
mbrola +
RHVoice +

Τις περισσότερες φορές αυτές οι TTS και οι σχετικές φωνές και γλώσσες είναι
υπό τη διαχείριση του λόγου μέσω των λεγόμενων "ενοτήτων" (περίπου,
ένα πρόσθετο σχετίζεται με ένα TTS).

Η προσαρμοσμένη λίστα spd-list χρησιμότητας μπορεί να απαντήσει σε αρκετές ερωτήσεις σχετικά με τους
συνθέτες, φωνές και γλώσσες. Πληκτρολόγηση spd-list εμφανίζει αυτό:
----
Αυτό το σενάριο εμφανίζει γλώσσες και συνθέτες διαθέσιμες για εφαρμογές
βασιζόμενοι στον Αποστολέα Ομιλίας, όπως Orca ή ομιλία επάνω. Κάθε εντολή παρακάτω απαντά στην ερώτηση μετά από αυτό.
Μην πληκτρολογήσετε τα εισαγωγικά γύρω από την εντολή.
"/usr/bin/spd-list" χρήση?
"/usr/bin/spd-list -s" διαθέσιμοι συνθέτες?
"/usr/bin/spd-list -l" διαθέσιμοι κωδικοί γλωσσών?
"/usr/bin/spd-list -ls <synthesizer>" γλώσσες διαθέσιμες για αυτόν τον συνθέτη?
"/usr/bin/spd-list -sl <language code>" συνθέτες που παρέχουν φωνές σε αυτή τη γλώσσα?
Ο κωδικός γλώσσας έχει συνήθως δύο χαρακτήρες, όπως 'en' '' ή 'fr'
----
Όλες οι φωνές που αναφέρονται είναι διαθέσιμες σε Orca και ομιλίαd-up, και επίσης fenrir αν έχει ρυθμιστεί για να χρησιμοποιήσει ομιλία-αποστολέα.

Μπορείτε να πάρετε πρόσθετες φωνές για flite και mbrola, που συνδέονται με τις
ενότητες flite-γενικό και espeak-ng-mbrola-generic.

Μπορείτε πάντα να γνωρίζετε ποιες είναι εγκατεστημένες ή όχι πληκτρολογώντας ως root μία από αυτές τις εντολές:
----
slapt-get --search mbrola-voice
slapt-get --search flite-voice
----
τότε εγκαταστήστε ένα από τα όχι ακόμη εγκατεστημένα ένα, όπως π.χ.
----
slapt-get -i mbrola-voice-it2
----
Εκτός από την ελεύθερη (όπως στην ελεύθερη μπύρα) φωνές που αποστέλλονται στο Slint,
μπορείτε να αγοράσετε φωνές για: +
voxin, https://oralux.org/voice.php +
voxygen, στέλνοντας ένα email στο contact@hypra.fr

Περισσότερες φωνές και συνθέτες θα μπορούσαν να διατεθούν αργότερα, αυτό θα ανακοινωθεί στη λίστα αλληλογραφίας
Slint και αυτό http://slackware.uk/slint/x86_64/slint-14.2.1/ChangeLog.txt[ChangeLog]

Οι συντομεύσεις πληκτρολογίου για γραφικά περιβάλλοντα εμφανίζονται σε <<key_bindings, Συντομεύσεις πλήκτρων>>.

=== Χρησιμοποιήστε τους διαχειριστές σύνδεσης με ομιλία

Δύο γραφικοί διαχειριστές σύνδεσης είναι προσβάσιμοι με ομιλία χρησιμοποιώντας Orca: lightdm ή gdm, το τελευταίο συνιστάται ως πλήρως προσβάσιμο.

Σε gdm, η εστίαση είναι αρχικά στο πεδίο χρήστη. Πληκτρολογήστε το χρήστη σας. ή
όνομα χρήστη πληκτρολογήστε Enter και πληκτρολογήστε τον κωδικό πρόσβασής σας.

Μπορείτε να έχετε πρόσβαση σε άλλα χαρακτηριστικά των gdm μέσω συντομεύσεων πληκτρολογίου. Στα
Αγγλικά: +
Alt+A: Ενέργειες (τερματισμός λειτουργίας ή επανεκκίνηση) +
Alt+E: Μενού συνεδρίας +
Alt+L: αλλάξτε τη γλώσσα, for the next session and possibly further
session, possibly also for gdm itself +
Alt+T: Θέμα. +
Μπορείτε να χρησιμοποιήσετε το πλήκτρο Tab για να περιηγηθείτε μεταξύ των πεδίων εισόδου και των πλήκτρων πάνω και
κάτω στα μενού.

Με ελαφρύ φως, πιέζοντας το F4 εναλλαγή του ήχου ενεργοποιημένο ή απενεργοποιημένο. Αρχικά ο δρομέας
είναι στο πεδίο κωδικός. Πατήστε Καρτέλα οδηγεί στο "login push button",
στη συνέχεια στον χρήστη's λίστα ή "combo box". Σε αυτή τη λίστα, πατώντας χώρο
εμφανίζει τον τρέχοντα επιλεγμένο χρήστη. Χρησιμοποιήστε τα βελάκια για να επιλέξετε ένα άλλο
και στη συνέχεια πληκτρολογήστε τον αντίστοιχο κωδικό πρόσβασης. Αντ 'αυτού, η επιλογή "Other..."
προσθέτει ένα πεδίο στο οποίο μπορείτε να πληκτρολογήσετε το όνομα σύνδεσης ενός μη εισηγμένου χρήστη.
Ακόμα στο φως, το F10 φέρνει ένα μενού που επιτρέπει την επανεκκίνηση ή τερματισμό,
και Alt+F4 φέρνει απευθείας ένα UI με κουμπιά τερματισμού ή ακύρωσης.

=== Επιλέξτε έναν αναγνώστη οθόνης κονσόλας

Το Slint παρέχει αυτούς τους αναγνώστες οθόνης κονσόλας: +
espeakup +
speehchd-up +
fenrir

Επιπλέον, αρκετοί συνθέτες ομιλίας υλικού μπορούν να χρησιμοποιηθούν σε
λειτουργία κονσόλας, χρησιμοποιώντας speakup.

Για να επιλέξετε έναν αναγνώστη οθόνης εκτελέστε ως root αυτήν την εντολή:
----
μιλάν-μεName
----
Εδώ είναι η έξοδος του χωρίς παράμετρο:
----
root[~]# speak-with
Usage: /usr/sbin/speak-with <screen reader> or <hard synthesizer> or none
Επιλέξτε έναν αναγνώστη οθόνης κονσόλας to talk with among:
  espeakup (Console screen reader connecting espeak-ng and speakup)
  fenrir (Modular, flexible and fast console screen reader)
  speechd-up (Console screen reader connecting Speech Dispatcher and speakup)
or use one of the supported hard synthesizers:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
or type  "/usr/sbin/speak-with none" to mute all screen readers.
root[~]#
----
Οι συνθέτες ομιλίας υλικού είναι αυτοί που είναι διαθέσιμοι στον
εκτελούμενο πυρήνα ή αποστέλλονται ως ενότητες.

Παράδειγμα εντολών και σχετικής εξόδου:

----
root[~]# ομιλία-με ομιλία-up
Ξεκινώντας ομιλία-up
Θα πρέπει επίσης να ξεκινήσει κατά την επόμενη εκκίνηση? [Y/n]
OK
root[~]# Done.
----
Μόλις πληκτρολογήσετε την εντολή, οι αναγνώστες οθόνης που χρησιμοποιήσατε προηγουμένως θα σταματήσουν
και η ομιλία θα αρχίσει να μιλάει.

Αν απαντήσετε στο Y (η προεπιλογή) στην ερώτηση: +
Θα πρέπει να ξεκινήσει επίσης η ομιλία κατά την επόμενη εκκίνηση? +
spechd-up θα συνεχίσει να χρησιμοποιείται στην επόμενη εκκίνηση. +
Αν αντιθέτως απαντήσετε n ο αναγνώστης οθόνης που χρησιμοποιήθηκε πριν πληκτρολογήσετε ομιλία με
ομιλίας θα χρησιμοποιηθεί μετά την επόμενη εκκίνηση.

Άλλα παραδείγματα:

----
root[~]# μιλώ με apollo
Διακοπή ομιλίας-επάνω...
Θα πρέπει να χρησιμοποιείται επίσης apollo κατά την επόμενη εκκίνηση? [Y/n]
OK
root[~]# Done.

root[~]# μιλώντας-με κανένα
Θέλετε επίσης μια κονσόλα σίγασης στο επόμενο boot? [Y/n]
OK
root[~]#
----

=== Ρυθμίστε ένα πρόγραμμα ανάγνωσης οθόνης κονσόλας.

Το Slint χειρίζεται συνθέτες υλικού ομιλίας χρησιμοποιώντας το speakup και παρέχει τους αναγνώστες οθόνης espeakup
και speechdup.

Μπορείτε να αποθηκεύσετε τις ρυθμίσεις που κάνετε, για παράδειγμα για να αυξήσετε
ή να μειώσετε το ρυθμό της τεχνολογίας ή την ένταση του ήχου. Ακριβώς όπως η ρίζα:
speakup-save. Αυτό αποθηκεύει όλες τις τρέχουσες ρυθμίσεις, συμπεριλαμβανομένων εκείνων που είναι ειδικά για το
συνθέτη υλικού σε χρήση, περίπτωση που εμφανίζεται.

Όλες αυτές οι ρυθμίσεις θα αποκατασταθούν κατά την επόμενη εκκίνηση: τα σενάρια εκκίνησης
rc.espeakup και rc.speechd-up εκτελέσετε την εντολή speakup-επαναφορά για εσάς.

Εάν don't θέλετε να επαναφέρετε τις αποθηκευμένες ρυθμίσεις, πληκτρολογήστε ως root: +
chmod -x /usr/sbin/speakup-restore

Αν τα έχετε αποκαταστήσει ξανά πληκτρολογήστε ως root: +
chmod +x /usr/sbin/speakup-restore

Εδώ είναι μερικές συντομεύσεις πλήκτρων για τις ρυθμίσεις ομιλίας καθώς και ομιλία:
----
spk key_f9 punctuation_level_decrease
spk key_f10 punctuation_level_increase
spk key_f11 reading_punctuation_decrease
spk key_f12 reading_punctuation_increase
spk key_1 volume_decrease (δεν λειτουργεί με speechd-up)
spk key_2 volume_increase (δεν λειτουργεί με speechd-up)
spk key_3 pitch_decrease (δεν λειτουργεί με speechd-up)
spk key_4 pitch_increase (δεν λειτουργεί με speechd-up)
spk key_5 rate_decrease
spk key_6 rate_increase
----
Στον παραπάνω πίνακα το spk είναι το πλήκτρο CapLock, ή Ins/0 σε ένα αριθμητικό
πληκτρολόγιο. Για παράδειγμα για να αυξήσετε το ποσοστό που θα μπορούσατε να πατήσετε και κρατήστε πατημένο το
CapsLock πλήκτρο στη συνέχεια πατήστε το πλήκτρο 6.

Ορισμένες ρυθμίσεις που είναι διαθέσιμες μόνο σε συγκεκριμένους συνθέτες υλικού δεν έχουν
συσχετισμένες συντομεύσεις πλήκτρων. Στη συνέχεια, για να ορίσετε μια νέα τιμή την επαναλαμβάνετε στο
/sys/accessibility/speakup/<synth>/<parameter>

Για παράδειγμα για να αλλάξετε τη φωνή σε χρήση από ένα apollo 2 θα μπορούσατε να γράψετε: +
echo 2 > /sys/accessibility/speakup/apollo/voice

speakup-save θα αποθηκεύσετε επίσης αυτή τη ρύθμιση.

Caveat: Ποτέ δεν χρησιμοποίησα ένα συνθέτη ομιλία υλικού, έτσι ώστε η παρακάτω εξήγηση είναι
μόνο μια υπόθεση που βασίζεται στον οδηγό speakup_apollo, συνεπής με
είναι χειροκίνητη, βρέθηκε στο: +
https://archive.org/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== Speakup πλήκτρα επιφάνειας εργασίας

Σχεδόν όλα τα πλήκτρα που παρατίθενται παρακάτω βρίσκονται στο αριθμητικό πληκτρολόγιο.
Το πλήκτρο Insert ή 0 στο πληκτρολόγιο ενεργεί όπως ένα πλήκτρο shift . Για παράδειγμα,
Ins 2 σημαίνει "κρατήστε πατημένο το πλήκτρο Insert όπως ένα πλήκτρο shift και πατήστε 2".
Κρατήστε το numlock απενεργοποιημένο για να χρησιμοποιήσετε το Speakup.

Πεδίο εφαρμογής: αυτές οι συνδέσεις πλήκτρων μπορούν να χρησιμοποιηθούν με σκληρούς συνθέτες και με
espeakup, αλλά και με ομιλία - up. Ωστόσο, η ρύθμιση του βήματος ή της έντασης ομιλίας
με τη χρήση δεσμεύσεων κλειδιού δεν είναι διαθέσιμη κατά τη χρήση ομιλίας.

Πρώτα κλειδιά για να θυμάστε:
----
Οθόνη εκτύπωσης Ενεργοποίηση/απενεργοποίηση
Ins F1 Speakup Βοήθεια (πατήστε Διάστημα για να βγείτε από τη βοήθεια)
----

Πλήκτρα που χρησιμοποιούνται για την αναθεώρηση της οθόνης:
----
1/2/3 Πείτε προηγουμένως/Τρέχουσα/Επόμενος χαρακτήρας
Shift PageUp Πείτε τον πρώτο χαρακτήρα
Shift PageDown Πείτε τον τελευταίο χαρακτήρα
4/5/6 Πείτε Προηγούμενη/Τρέχουσα/Επόμενη λέξη
5 φορές ορθογραφική τρέχουσα λέξη
Σε 5 Ορθογραφικό τρέχον Word
7/8/9 Πείτε Προηγούμενη/Τρέχουσα/Επόμενη γραμμή
Ins 4 Πείτε από την αριστερή άκρη της γραμμής στην ανάγνωση του δρομέα.
Σε 6 Πείτε από το δρομέα ανάγνωσης στη δεξιά άκρη της γραμμής.
Σε 8 Πείτε από το πάνω μέρος της οθόνης για να διαβάσετε το δρομέα.
Σε συν Πείτε από την ανάγνωση γραμμή δρομέα στο κάτω μέρος της οθόνης.
συν Πείτε ολόκληρη την οθόνη.
Σε r Πείτε όλη την διπλασιασμό
dot Πείτε θέση
Ins dot Say χαρακτηριστικά
Ins minus Πείτε χαρακτήρα hex και δεκαδική τιμή.
μείον Πάρκο δρομέα ανάγνωσης (εναλλαγή)
Σε 9 Μετακίνηση δρομέα ανάγνωσης στο πάνω μέρος της οθόνης (εισάγετε pgup)
Σε 3 Μετακίνηση του δρομέα ανάγνωσης στο κάτω μέρος της οθόνης (εισάγετε pgdn)
Μέσα 7 Μετακίνηση δρομέα ανάγνωσης στο αριστερό άκρο της οθόνης (εισάγετε το σπίτι)
Μέσα 1 Μετακίνηση δρομέα ανάγνωσης στη δεξιά άκρη της οθόνης (εισάγετε το τέλος)
Έλεγχος 1 Κίνηση δρομέα ανάγνωσης στον τελευταίο χαρακτήρα στην τρέχουσα γραμμή.
αστερίσκος Εναλλαγή cursoring
Ins asterisk n<xśy πάει στη γραμμή (y) ή στήλη (x). Όπου το 'n' είναι οποιαδήποτε
               επιτρεπόμενη τιμή για τη γραμμή ή τη στήλη για την τρέχουσα οθόνη σας.
Ins f2 Ρύθμιση παραθύρου
Ins f3 Καθαρισμός παραθύρου
Ins f4 Ενεργοποίηση παραθύρου
----

Άλλα κλειδιά:
----
Ins f5 Edit some
Ins f6 Edit most
Ins f7 Edit delim
Ins f8 Edit repeat
Ins f9 Edit exnum

Enter Shut up (until another key is hit) and sync reading cursor.
Ins Enter Κλείστε (μέχρι να επαναφέρετε επάνω)

κάθετο Mark και περικοπή περιοχή οθόνης.
Ins slash Επικόλληση περιοχή οθόνης σε οποιαδήποτε κονσόλα.
----
==== Speakup πλήκτρα φορητού υπολογιστή

Αυτές οι συντομεύσεις πλήκτρων (για διάταξη πληκτρολογίου ΗΠΑ) don't χρειάζονται ένα αριθμητικό πληκτρολόγιο.
Αν έχετε ένα, χρησιμοποιήστε τα <<desktop_keys, πλήκτρα επιφάνειας εργασίας speakup>> ευκολότερα στη χρήση,
ειδικά αν χρησιμοποιείτε μια άλλη διάταξη πληκτρολογίου από τις ΗΠΑ.

Το πλήκτρο CapsLock ενεργεί σαν ένα πλήκτρο Shift. +
Για παράδειγμα, το CapsLock 2 σημαίνει "κρατήστε πατημένο το πλήκτρο CapsLock σαν πλήκτρο shift και πατήστε 2". +
Κρατήστε το numlock απενεργοποιημένο για να χρησιμοποιήσετε το Speakup.

Πεδίο εφαρμογής: αυτές οι συνδέσεις πλήκτρων μπορούν να χρησιμοποιηθούν με σκληρούς συνθέτες και με
espeakup, αλλά και με ομιλία - up. Ωστόσο, η ρύθμιση του βήματος ή της έντασης ομιλίας
με τη χρήση δεσμεύσεων κλειδιού δεν είναι διαθέσιμη κατά τη χρήση ομιλίας.

Πρώτα κλειδιά για να θυμάστε:
----
Ενεργοποίηση/απενεργοποίηση της οθόνης εκτύπωσης
Βοήθεια Ομιλίας CapsLock F1 (πατήστε το Διάστημα για έξοδο)
----

Κλειδί που χρησιμοποιείται για την αξιολόγηση της οθόνης:
----
CapsLock m/comma/dot Πείτε Προηγούμενο/Τρέχουσα/Τρέχουσα/Επόμενος χαρακτήρας
CapsLock PageUp Πείτε τον πρώτο χαρακτήρα
CpasLock PageDown Πείτε τον τελευταίο χαρακτήρα
CapsLock j/k/l Πείτε Προηγούμενο/Τρέχουσα/Επόμενη λέξη
CpasLock k k δύο φορές Spell τρέχουσα λέξη
CapsLock u/i/o Πείτε Προηγούμενη/τρέχουσα / Επόμενη γραμμή
CapsLock h Πείτε από την αριστερή άκρη της γραμμής για να διαβάσετε το δρομέα.
CapsLock ερωτηματικό Πείτε από την ανάγνωση του δρομέα στη δεξιά άκρη της γραμμής
CapsLock y Say από την κορυφή της οθόνης στην ανάγνωση του δρομέα.
CapsLock p Πείτε από την ανάγνωση γραμμή δρομέα στο κάτω μέρος της οθόνης.
CapsLock apostrophe Πείτε ολόκληρη την οθόνη.
Capslock r Διαβάστε όλα τα έγγραφα.
CapsLock n Πείτε θέση
CapsLock slash Πείτε χαρακτηριστικά
CapsLock μείον πάρκο ανάγνωση δρομέα (toggle)
CapsLock f2 Ορισμός παραθύρου
CapsLock f3 Καθαρισμός παραθύρου
CapsLock f4 Ενεργοποίηση παραθύρου
----
Άλλα κλειδιά:
----
CapsLock f5 Επεξεργαστείτε μερικά
CapsLock f6 Επεξεργασία περισσότερα
CapsLock f7 Επεξεργασία οριοθέτη
CapsLock f8 Επαναλάβετε την επεξεργασία
shift CapsLock f9 Επεξεργασία exnum
----

=== Κάντε τις emacs να μιλούν

Μπορείτε να χρησιμοποιήσετε είτε emacspeak, είτε ομιλίας. Για να ενεργοποιήσετε ή να απενεργοποιήσετε μία από τις
πληκτρολογήστε μια από αυτές τις εντολές:

ενεργοποίηση emacspeak +
ενεργοποίηση ομιλίας-el +
απενεργοποίηση emacspeak +
απενεργοποίηση ομιλίας-el +

Στη συνέχεια, απλά πληκτρολογήστε: +
emacs

Η ενεργοποίηση ενός από αυτά τα λογισμικά απενεργοποιεί το άλλο.

[[Manage_your_system]]
== Manage your system

[[software_management]]
=== Διαχείριση λογισμικού στο Slint.

<<The_basics, Τα βασικά>> +
<<Keep_your_system_up_to_date, Κρατήστε το σύστημά σας ενημερωμένο>> +
<<Kernel_upgrades, αναβαθμίσεις πυρήνα>> +
<<Get_additional_applications, Λήψη πρόσθετων εφαρμογών>> +
<<slapt_src, Χρήση slapt-src>> +
<<sbopkg, Χρήση sbopkg>> +

[[The_basics]]
==== Τα βασικά

Στο λογισμικό Slint παρέχεται με τη μορφή πακέτων. Ένα πακέτο είναι μια δέσμη αρχείων που παρέχονται σε ένα συμπιεσμένο αρχείο αρχείο, που μαζί για να παρέχει όλα όσα είναι απαραίτητα για να τρέξει το λογισμικό. Τα πακέτα περιλαμβάνονται στο ISO εγκατάστασης και αποθηκεύονται σε απομακρυσμένους διακομιστές από τους οποίους μπορούν να μεταφορτωθούν και να εγκατασταθούν. Εγκατάσταση ενός πακέτου σημαίνει εξαγωγή των αρχείων από το αρχείο αρχειοθήκης και αντιγραφή τους σε κάποιο κατάλογο του συστήματος.

Εγκατάσταση και αφαίρεση του λογισμικού καταγράφονται σε μια βάση δεδομένων που αποτελείται από αρχεία κειμένου σε αυτούς τους καταλόγους:
----
/var/log/packages
/var/log/removed_packages
/var/log/scripts
/var/log/removed_scripts
----
Τα αρχεία στον κατάλογο καταγράφουν πληροφορίες σχετικά με τα πακέτα, κυρίως το περιεχόμενό του: τη λίστα των αρχείων που περιλαμβάνει και όπου είναι εγκατεστημένα.

Οι κύριες εντολές διαχείρισης των πακέτων παρατίθενται παρακάτω. Όλοι τους έχουν συσχετίσει σελίδες ατόμων.

Αυτές οι εντολές απαιτούν δικαιώματα διαχείρισης, που σχετίζονται με έναν συγκεκριμένο λογαριασμό που ονομάζεται 'root', για τον οποίο έχετε ορίσει έναν κωδικό πρόσβασης κατά την εγκατάσταση του Slint.

Για να εκδώσετε μια εντολή ως 'ρίζα', πρώτα πληκτρολογήστε
su -
και μετά εισάγετε τον κωδικό πρόσβασης για το root και πληκτρολογήστε την εντολή.

Οι παρακάτω εντολές μπορούν να εκτελεστούν από ένα γραφικό τερματικό ή σε μια κονσόλα, αλλά χάσμα που λειτουργεί μόνο σε ένα γραφικό περιβάλλον.
----
installpkg # για να εγκαταστήσετε ένα πακέτο αποθηκευμένο τοπικά.
αφαίρεσε # για να αφαιρέσεις ένα εγκατεστημένο πακέτο.
upgradepkg # για να αντικαταστήσει ένα εγκατεστημένο πακέτο με ένα άλλο (γενικά με το ίδιο όνομα αλλά σε άλλη έκδοση).
slapt-get # για εγκατάσταση, αφαίρεση, αναβάθμιση πακέτων αποθηκεύονται σε αποθετήρια που αναφέρονται στο /etc/slapt-get/slap-getrc
----
Τα πακέτα που αποστέλλονται στο ISO της εγκατάστασης προέρχονται από τα αποθετήρια που αναφέρονται στο /etc/slapt-get/slapt-getrc

Κάνετε στον εαυτό σας μια ευνοία: διαβάστε τα σχόλια στο /etc/slapt-get/slapt-getrc και /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint στο εγκατεστημένο σύστημα.

Μετά την εγκατάσταση του Slint, θα ειδοποιηθείτε'για ενημερώσεις εγκατεστημένων πακέτων που προέρχονται από αποθετήρια που αναφέρονται στο /etc/slapt-get/slapt-getrc

Μπορείτε να εγκαταστήσετε πρόσθετα πακέτα χρησιμοποιώντας το slapt-get εντολών ή το γραφικό χάσμα εφαρμογής, εάν αποθηκευτεί σε ένα αποθετήριο που αναφέρεται στο /etc/slapt-get/slapt-getrc

slapt-get και gslapt παρέχουν μια λειτουργία αναζήτησης που σας βοηθά να βρείτε τα πακέτα.

WARNING: μπορείτε να χρησιμοποιήσετε slapt-get, gslapt και removepkg για να αφαιρέσετε τα εγκατεστημένα πακέτα αλλά μην αφαιρέσετε τα πακέτα που αποστέλλονται στο Slint ISO, ακόμη κι αν δεν τα χρησιμοποιείτε καθόλου. Η αφαίρεση ενός συμπεριλαμβανόμενου πακέτου θα οδηγήσει σε καμία αύξηση της απόδοσης και θα μπορούσε να αποτρέψει άλλες εφαρμογές να λειτουργήσουν. Επίσης, αν έχετε προσθέσει ένα πακέτο που δεν περιλαμβάνεται στο Slint μπορείτε να το αφαιρέσετε, αλλά να είστε προσεκτικοί ότι το αφαιρεθεί πακέτο δεν είναι μια εξάρτηση από άλλα που επίσης εγκαταστήσατε και σκοπεύετε να συνεχίσετε να χρησιμοποιείτε.

[[Keep_your_system_up_to_date]]
==== Κρατήστε το σύστημά σας ενημερωμένο

Κρατήστε το σύστημά σας ασφαλή εγκατάσταση των ενημερώσεων λογισμικού που παρέχονται από Slint μόλις'εκ νέου διαθέσιμα.

Όλες οι ενημερώσεις παρατίθενται στο ChangeLog: http://slackware.uk/slint/x86_64/slint-14.2.1/ChangeLog.txt

Μετά την εγκατάσταση Slint ή οποιαδήποτε αλλαγή στο αρχείο /etc/slapt-get/slapt-getr εκτελέστε αυτή την εντολή μία φορά:
----
slapt-get --add-keys
----

Για να συγχρονίσετε την τοπική λίστα των διαθέσιμων πακέτων με εκείνη του αποθετηρίου, αυτή η εντολή εκτελείται αυτόματα κάθε δύο ώρες:
----
slapt-get -u
----
Μπορείτε επίσης να το εκτελέσετε χειροκίνητα

Αυτό φυσικά απαιτεί η μηχανή να συνδεθεί στο διαδίκτυο.

Για να κατεβάσετε και να εγκαταστήσετε τα αναβαθμισμένα ή αναδομημένα πακέτα εκτελέστε ως ρίζα
την ακόλουθη εντολή:
----
slapt-get --αναβάθμιση
----
Εναλλακτικά θα μπορούσατε επίσης να χρησιμοποιήσετε gslapt, ένα γραφικό front-end για slapt-get.

Για να λάβετε νέα πακέτα στο Αρχείο καταγραφής αλλαγών ως "Προστέθηκε", πληκτρολογήστε:
----
slapt-get -i <package name>
----
ή για να βεβαιωθείτε ότι έχετε εγκαταστήσει όλα τα πακέτα που αποστέλλονται στο Slint, συμπεριλαμβανομένων εκείνων που προστίθενται στο χώρο αποθήκευσης μετά την εγκατάσταση του Slint, πληκτρολογήστε:
----
slapt-get --install-set slint
----

Στις επιφάνειες εργασίας, ένα μικρό εικονίδιο εμφανίζεται στην περιοχή ειδοποίησης ενός πάνελ (το άνω πάνελ στο MATE) για την κοινοποίηση των διαθέσιμων ενημερώσεων λογισμικού. Απλά κάντε ένα αριστερό κλικ σε αυτό και ακολουθήστε τις οδηγίες που αναφέρονται εκεί.

Θα πρέπει να γνωρίζετε ότι ορισμένα πακέτα είναι στη μαύρη λίστα στο
/etc/slapt-get/slapt-getrc, δηλαδή δεν μπορούν να αναβαθμιστούν αυτόματα ή
να εγκατασταθούν.

[[Πυρήνας_upgrades]]
==== Αναβαθμίσεις πυρήνα

Παρέχονται νέοι πυρήνες όποτε χρειάζεται, είτε για να φέρουν διορθώσεις ασφαλείας είτε για βελτιώσεις.

Συνήθως δεν απαιτείται χειροκίνητη παρέμβαση από τον χρήστη όταν συμβαίνει αυτό, but it can be useful to know how the kernel upgrade is done and what to do if something unexpected occurs.

Διάφορα πακέτα περιλαμβάνουν αρχεία που σχετίζονται με κάθε πυρήνα, δηλαδή: γενικός-πυρήνας-modules, πυρήνας-πηγή, κεφαλίδες πυρήνα. Η πηγή πυρήνα και οι κεφαλίδες πυρήνα περιλαμβάνουν αρχεία που χρησιμοποιούνται για την κατασκευή λογισμικού, απαιτούνται μόνο γενικές πυρήνα και μονάδες πυρήνα για την εκτέλεση ενός συστήματος Slint.

Οι ενότητες πυρήνα πακέτου στέλνουν αρχεία που ονομάζονται ενότητες, τα οποία είναι κομμάτια κώδικα που είναι "συνδεδεμένα" στον πυρήνα για να παρέχει ένα συγκεκριμένο χαρακτηριστικό ή να χειρίζεται ένα συγκεκριμένο υλικό.

Μόλις εγκατασταθούν τόσο ένα πακέτο πυρήνα όσο και το σχετικό πακέτο μονάδων πυρήνα, το script
/sbin/wrapupgradepkg χτίζει ένα <<initrd, initrd>> που σχετίζεται με αυτόν τον πυρήνα (με πρόσθετα που λαμβάνονται από
τα modules kernel-modules) και το εγκαθιστά παράλληλα με τον πυρήνα στον κατάλογο /boot.

Στη συνέχεια, οι προηγούμενοι πυρήνες (όχι σε χρήση κατά τη στιγμή της αναβάθμισης) αφαιρούνται.

Στη συνέχεια, το σενάριο ενημερώνει το αρχείο ρύθμισης παραμέτρων GRUB /boot/grub/grub.cfg, διαβάστε από το OS loader για να δημιουργήσετε την εκκίνηση κατά την εκκίνηση.

Αυτό το μενού εκκίνησης θα περιλαμβάνει στη συνέχεια τουλάχιστον δύο καταχωρήσεις εκκίνησης κάθε ένδειξη, για την ένδειξη ενός πυρήνα και της συσχετιζόμενης initrd του που θα χρησιμοποιηθεί. Από πάνω:

* Μια καταχώρηση εκκίνησης για την εκκίνηση του Slint χρησιμοποιώντας το νέο πυρήνα που μόλις έχει εγκατασταθεί.
* Μια καταχώρηση εκκίνησης για την εκκίνηση του Slint χρησιμοποιώντας τον πυρήνα που χρησιμοποιείται κατά τη στιγμή της αναβάθμισης.

Αυτό παρέχει ένα "δίχτυ ασφαλείας" σε περίπτωση που Slint wouldn't εκκίνησης με το νέο πυρήνα:
σε αυτή την περίπτωση απλά βέλος κάτω μία φορά όταν εμφανίζεται το μενού εκκίνησης για να ξεκινήσει το Slint με τον προηγούμενο πυρήνα

Μπορείτε να κάνετε προεπισκόπηση του νέου μενού εκκίνησης πριν την επανεκκίνηση, πληκτρολογώντας ως root:
----
grub-emu
----
Στη συνέχεια, εμφανίζεται ένα εξομοιωμένο ή "ψεύτικο" μενού εκκίνησης, με την ίδια διάταξη με το πραγματικό που θα εμφανιστεί
κατά την εκκίνηση.

Μπορείτε να περιηγηθείτε σε αυτό με τα κάτω και πάνω βέλη για να επισημάνετε (να βάλετε την εστίαση) μια καταχώρηση εκκίνησης της οποίας μπορείτε να εμφανίσετε τις λεπτομέρειες πατώντας 'e'. Μπορείτε να επιστρέψετε στο μενού πατώντας Escape.

Για να βγείτε από το grub-emu πατήστε c και στη συνέχεια πληκτρολογήστε *Έξοδος* και πατήστε Enter.

[[Get_additional_applications]]
==== Λήψη πρόσθετων εφαρμογών

Εάν η εφαρμογή που θέλετε δεν είναι εγκατεστημένη και επίσης δεν είναι διαθέσιμη σε ένα από τα αποθετήρια ενεργοποιημένα στο /etc/slapt-get/slapt-getrc θα μπορούσατε να κάνετε ένα πακέτο γι 'αυτό, χρήση οικοδομικού υλικού που παρέχεται από εθελοντές @ https://slackbuilds.org. Για να μάθετε πώς-να συνεχίσετε, διαβάστε https://slackbuilds.org/howto/ και https://slackbuilds.org/faq/

Τα πακέτα που κατασκευάζονται με αυτόν τον τρόπο πρέπει να είναι συμβατά με το Slint.

Δύο εφαρμογές σας επιτρέπουν να δημιουργήσετε και να εγκαταστήσετε πακέτα χρησιμοποιώντας το κατασκευαστικό υλικό που παρέχεται στο https://slackbuilds.org: *slapt-src* και *sbopkg*. Εκτός αν είστε εξοικειωμένοι με sbopkg, σας συνιστούμε να χρησιμοποιήσετε slapt-src, πιο γρήγορα να εξοικειωθεί. Ωστόσο, και οι δύο θα πρέπει να λειτουργούν και να παρέχουν τα ίδια αποτελέσματα και θα πρέπει να χρησιμοποιούνται ως ρίζα.

Θα περιγράψουμε το slapt-src με περισσότερες λεπτομέρειες.

[[slapt_src]]
===== Χρήση του slapt-srcrc

Το προεπιλεγμένο σενάριο ρύθμισης παραμέτρων για το slapt-src είναι το /etc/slapt-get/slap-getrc και έχει αυτό το περιεχόμενο:
----
BUILDDIR=/tmp/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/14.2/
----
So:

* Όλο το υλικό κατασκευής και οι συσκευασίες θα πάνε στο /tmp/slapt-src
* Τα ονόματα των πακέτων που κατασκευάζονται τελειώνουν στο .txz
* Το δομικό υλικό λαμβάνεται από το αποθετήριο https://slackbuilds.org/slackbuilds/14.2/

Εδώ είναι η έξοδος της εντολής *slapt-src --help*:
----
Χρήση: slapt-src [επιλογή(-ές)] [action] [slackbuild(s)]
  -u, --update update local cache of remote slackbuilds
  -U, --upgrade-all upgrade all installed slackbuilds
  -l, --list list available slackbuilds
  -e, --clean build directory
  -s, --search search available slackbuilds
  -w, --show show specified slackbuilds
  -i, --εγκατάσταση ανάκτησης, κατασκευάζει και εγκαθιστά τα καθορισμένα slackbuild(s)
  -b, --build μόνο λήψη και κατασκευή των καθορισμένων slackbuild(s)
  -f, --λήψη μόνο των καθορισμένων slackbuild(s)
  -v, --version
  -h, --help
 Επιλογές:
  -y, --yes do not prompt
  -t, --προσομοίωση δείχνουν τι θα γίνει
  -c, --config=FILE χρησιμοποιήστε το καθορισμένο αρχείο ρυθμίσεων
  -n, --no-dep δεν ψάχνει για εξαρτήσεις
  -p, --postprocess=CMD εκτέλεση καθορισμένης εντολής στο δημιουργημένο πακέτο
  -B, --ισχύει μόνο για το --upgrade-all
  -F, --φέρει-μόνο εφαρμόσιμη μόνο στο --upgrade-all
----

Let's σχολιάσει μερικές από αυτές τις επιλογές:

* Χρησιμοποιήστε -u ή --update κάθε φορά για να ενημερώσετε τη λίστα των πακέτων που μπορούν να κατασκευαστούν και να εγκατασταθούν. Αυτή η εντολή γράφει το αρχείο /tmp/slapt-src/slackbuilds_data, αντικαθιστώντας την προηγούμενη περίπτωση που εμφανίζεται.
* Χρησιμοποιήστε το -e για να εξοικονομήσετε χώρο στο δίσκο, αφαιρώντας τα περισσότερα αρχεία στο /usr/src/slapt-src/
* *δεν χρησιμοποιεί* το -U αλλά για να απαριθμήσεις τις πιθανές αναβαθμίσεις ή υποβαθμίσεις, χωρίς επιβεβαίωση: η επιβεβαίωση θα οδηγήσει σε αντικατάσταση όλων των πακέτων Slint από το ένα στην άλλη έκδοση, εάν είναι διαθέσιμα στο απομακρυσμένο αποθετήριο, ενδεχομένως το σπάσιμο λογισμικού δεν είναι συμβατό με αυτή την άλλη έκδοση.
* -i μπορεί επίσης να αναβαθμίσει ένα πακέτο που έχει ήδη εγκατασταθεί από https://slackbuilds.org, αν ένας συντηρητής του σεναρίου SlackBuild το έχει αναβαθμίσει, αλλάζοντας τη μεταβλητή VERSION.
* Χρησιμοποιήστε -f για να κατεβάσετε μόνο τα αρχεία στο https://slackbuilds.org για το λογισμικό προορισμού. Αυτό μπορεί να είναι χρήσιμο αν θέλετε να ελέγξετε το οικοδομικό υλικό ή να προσαρμόσετε την κατασκευή. Για παράδειγμα let's υποθέτουν ότι θέλετε να φέρετε το δομικό υλικό για το λογισμικό *mxml*. Η παρακάτω εντολή δίνει κάποιες πληροφορίες σχετικά με το λογισμικό και τα αρχεία που αποθηκεύονται στο https://slackbuilds.org για αυτό:
+
----
slapt-src --show mxml
SlackBuild Όνομα: mxml
SlackBuild Version: 3.
SlackBuild Κατηγορία: libraries/mxml/
SlackBuild Περιγραφή: mxml (Lightweight xml parsing library)
SlackBuild Files:
 README
 mxml. lackBuild
 mxml.info
 slack-desc
----
+
Τώρα ανακτά τα αρχεία διαστάσεων και επίσης το πηγαίο αρχείο από το ανάντη αποθετήριο με την επόμενη εντολή:
+
----
slapt-get -f mxml
----
+
Γνωρίζοντας από την έξοδο της προηγούμενης εντολής ότι τα αρχεία αποθηκεύονται στις βιβλιοθήκες υποκαταλόγου/mxml, μπορείτε να ελέγξετε ποια αρχεία έχουν ληφθεί με αυτήν την εντολή:
+
----
ls -1 /tmp/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* Χρησιμοποιήστε το -b αν θέλετε να δημιουργήσετε ένα πακέτο αλλά μην το εγκαταστήσετε ακόμα. Στο παραπάνω παράδειγμα θα αποθηκευτεί στο /tmp/slapt-src/libraries/mxml, έτσι θα είστε σε θέση να το εγκαταστήσετε αργότερα απλά πληκτρολογήστε:
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txz
----
+
* Χρησιμοποιήστε -c αν θέλετε να χρησιμοποιήσετε ένα προσαρμοσμένο αρχείο ρυθμίσεων αντί για το προεπιλεγμένο /etc/slapt-get/slap-getrc

[[sbopkg]]
===== Χρήση του sbopkg

WARNING: σε ορισμένες περιπτώσεις, ένα λογισμικό αποστέλλεται στο Slint και είναι επίσης διαθέσιμο στο https://slackbuilds.org αλλά με ένα διαφορετικό όνομα που μπορεί να οδηγήσει σε προβλήματα. Οι διαφορές αυτές επιλύονται κατά τη χρήση slapt-src, αλλά όχι ακόμη κατά τη χρήση sbopkg.

Πριν χρησιμοποιήσετε το sbopkg, διαβάστε το αρχείο βοήθειας και τη σελίδα man πληκτρολογώντας ως ρίζα: *sbopkg --help* και *man sbopkg*

Εν συντομία, αν χρησιμοποιείτε μόνο τη γραμμή εντολών, ως root:

* συγχρονισμός του τοπικού αποθετηρίου με το απομακρυσμένο για ενημέρωση:
+
----
sbopkg - r
----
* γράψτε ένα "αρχείο ουράς" λίστα τις εξαρτήσεις στη σωστή σειρά για να τα χτίσετε και να τα εγκαταστήσετε πριν από το λογισμικό που θέλετε:
+
----
sqg -p <package name>
----
Ένα αρχείο ουράς που ονομάζεται /var/lib/sbopkg/queues/<package name>.sqf θα γραφτεί

Εάν δεν υπάρχει εξάρτηση δεν θα γραφτεί αρχείο ουράς

* να χτίσει και να εγκαταστήσει τις εξαρτήσεις τότες, το επιθυμητό λογισμικό:
+
----
sbopkg -i <package name>
----
Αν υπάρχει ένα αρχείο ουράς για αυτό το πακέτο επιλέξτε να το χρησιμοποιήσετε όταν ρωτήσετε.

Αν ένα πακέτο που αναφέρεται στο αρχείο ουράς είναι ήδη εγκατεστημένο, θα παραλειφθεί.

Κατά συνέπεια, αν θέλετε να αναβαθμίσετε ένα πακέτο που έχει ήδη εγκατασταθεί χρησιμοποιώντας sbopkg, θα πρέπει να το αφαιρέσετε
πριν από την οικοδόμηση και την εγκατάσταση του νέου.

Θα πρέπει να γνωρίζετε ότι η κατασκευή και εγκατάσταση πακέτων με αυτόν τον τρόπο μπορεί περιστασιακά να οδηγήσει σε ζητήματα όπως οι εξαρτήσεις που λείπουν ή οι συγκρούσεις με εγκατεστημένα πακέτα: τα στοιχεία που χρησιμοποιούνται για την κατασκευή των πακέτων παρέχονται από εθελοντές που δεν μπορούν να ελέγξουν τα αποτελέσματα σε κάθε πιθανή ρύθμιση.

WARNING: Εάν δεν μπορείτε να βρείτε ένα πακέτο για ένα λογισμικό που θέλετε ούτε πράγματα για να δημιουργήσετε ένα @ https://slackbuilds.org, θα μπορούσατε να μπείτε στον πειρασμό να δημιουργήσετε και να εγκαταστήσετε αυτό το λογισμικό χειροκίνητα εκδίδοντας τις εντολές". configure && make && make install". Αποφύγετε να το κάνετε αυτό, καθώς το λογισμικό που χτίστηκε και εγκαταστάθηκε με αυτόν τον τρόπο δεν θα είναι διαχειρίσιμο από το σύστημα διαχείρισης πακέτων Slint και τα σχετικά εργαλεία.

Μάλλον, απλά δημοσιεύστε μια ερώτηση ή ένα αίτημα στη λίστα αλληλογραφίας του Slint και θα προσπαθήσουμε να βοηθήσουμε, ενδεχομένως προσθέτοντας αυτό το πακέτο στο αποθετήριο. Όταν γίνει (αυτό θα ανακοινωθεί στη λίστα αλληλογραφίας), για να το εγκαταστήσετε πληκτρολογήστε ως root ένα από αυτά τα comands:
----
slapt-get -i <package name>
slapt-get --install-set Slint
----

=== Διαχείριση χρηστών και ομάδων.

Παρέχονται δύο εντολές για τη διαχείριση χρηστών και ομάδων:

* Η εντολή _usersetup_ (TUI)
* Η εντολή _gtkusersetup_ (GUI), με ένα εικονίδιο στο Κέντρο Ελέγχου Σλιντ, κατηγορία Συστήματος)

Αυτές οι εντολές σας επιτρέπουν να προσθέσετε ή να διαγράψετε χρήστες και ομάδες χρηστών και να προσθέσετε χρήστες σε ομάδες.

Να θυμάστε ότι κάθε λογαριασμός χρήστη συνδέεται από προεπιλογή με το χώρο στο /home directory. Για παράδειγμα αν προσθέσετε ένα χρήστη *leonie*, θα δημιουργηθεί ένας φάκελος /home/leonie, στην οποία μόνο αυτός ο χρήστης (και ρίζα) θα επιτρέπεται να έχει πρόσβαση.

=== Αλλάξτε την προεπιλεγμένη γλώσσα του συστήματος

Παρέχονται δύο εντολές για αυτό:

* Η εντολή _localesetup_ (TUI).
* Η εντολή _gtklocalesetup_ (GUI), με ένα εικονίδιο στο Κέντρο Ελέγχου Σλιντ, κατηγορία Ρυθμίσεων.

Να θυμάστε ότι αυτές οι ρυθμίσεις αλλάζουν τη γλώσσα που χρησιμοποιείται από τις διεπαφές των εφαρμογών αν διεθνοποιηθούν, όχι τον χάρτη πληκτρολογίου (δείτε παρακάτω).

Επίσης, τα μεταφρασμένα πακέτα (αν είναι διαθέσιμα) που ταιριάζουν στην επιλεγμένη γλώσσα έχουν ήδη εγκατασταθεί στο τέλος της εγκατάστασης του Slint. Αν αλλάξετε την προεπιλεγμένη γλώσσα στη συνέχεια, θα πρέπει να εγκαταστήσετε τα αντίστοιχα μεταφρασμένα πακέτα αν θέλετε.

Τοπική σημαίνει "παρέχεται σε μια δεδομένη τοπική", το τοπικό είναι μια γλώσσα συν ιδιαιτερότητες που συνδέονται με μια γεωγραφική περιοχή. Για παράδειγμα, τα πορτογαλικά που ομιλούνται στην Πορτογαλία και τη Βραζιλία διαφέρουν. Στα τοπικοποιημένα ονόματα πακέτων, l10n είναι μια συντομογραφία του "τοπικοποίηση" που σημαίνει "γράμμα l, 10 άλλα γράμματα, γράμμα n".

Τα μεταφρασμένα πακέτα περιλαμβάνονται για πολλές γλώσσες. Το όνομά τους περιλαμβάνει το βασικό όνομα πακέτου, μια παύλα, τότε ο κωδικός γλώσσας. Παραθέτουμε κάτω από τα βασικά ονόματα των τοπικών πακέτων:
[options="autowidth"]
|====
| Όνομα βασικού πακέτου | Περιγραφή
| aspell | λίστες λέξεων για ορθογραφικό έλεγχο
| calligra-l0n | τοπικοποιήθηκε από τη σουίτα γραφείων Calligra
| kde-l10n | μεταφρασμένη επιφάνεια εργασίας του KDE
| libreoffice-l0n | μεταφρασμένη σουίτα γραφείου LibreOffice
| libreoffice-help | εντοπισμένη βοήθεια για το LibreOffice
|====

Για να βρείτε ένα τοπικό πακέτο, πληκτρολογήστε έναν εξομοιωτή τερματικού ως root (παράδειγμα για το kde-l10n): +
`spi libreoffice`

Αυτό θα εμφανίσει τη λίστα όλων των μεταφρασμένων πακέτων LibreOffice. Βρείτε αυτό που θέλετε και εγκαταστήστε το. Για παράδειγμα για τα περσικά ο κωδικός γλώσσας είναι `fa` (σύντομος για τα Farsi), ώστε να το εγκαταστήσετε πληκτρολογήστε: +
`spi -i libreoffice-l0n-fa`

Αν προτιμάτε μπορείτε να χρησιμοποιήσετε `gslapt`. Στη συνέχεια, πληκτρολογήστε το όνομα του πακέτου στο πεδίο αναζήτησης για να εμφανίσετε όλα τα μεταφρασμένα πακέτα libreOffice.

=== Αλλαγή του χάρτη πληκτρολογίου

Μπορείτε να αλλάξετε το προεπιλεγμένο keymap που χρησιμοποιείται σε γραφική λειτουργία χρησιμοποιώντας:

* Η εντολή _keyboardsetup_ (TUI)
* Η εντολή _gtkkeyboardsetup_ (GUI), με ένα εικονίδιο στο Κέντρο Ελέγχου Σλιντ, στην κατηγορία Υλικού.

Αυτές οι εντολές σας επιτρέπουν επίσης να επιλέξετε αν το numlock θα πρέπει να ενεργοποιηθεί κατά την εκκίνηση του συστήματος, και εάν η SCIM (μέθοδος εισόδου) πρέπει να ενεργοποιηθεί κατά την εκκίνηση του συστήματος.

Εάν χρησιμοποιείτε έναν διαχειριστή παραθύρων με έναν πίνακα, μπορείτε επίσης να κάνετε αυτή τη ρύθμιση μέσω ενός δεξιού κλικ στην μικροεφαρμογή πληκτρολογίου (εμφανίζεται από προεπιλογή ως ο κωδικός δύο γραμμάτων γλώσσα του χάρτη πληκτρολογίου σε χρήση). Το KDE και το Xfce έχουν συγκεκριμένα εργαλεία για αυτό.

Στη γραμμή εντολών αλλά για την γραφική λειτουργία χρησιμοποιείται αντ' αυτού το setxbmap

Για παράδειγμα για να ορίσετε τη διάταξη πληκτρολογίου στα Ουκρανικά σε γραφική λειτουργία, απλά πληκτρολογήστε ως κανονικός χρήστης: +
`setxkbmap -layout ua`

Για να μάθετε περισσότερα, διαβάστε τη σελίδα man για setxkbmap.

=== Εγκατάσταση εκτυπωτή

Στο Slint ο εξυπηρετητής εκτυπώσεων CUPS διαχειρίζεται εκτυπωτές και εκτυπωτικές εργασίες. Στην προεπιλεγμένη διαμόρφωση, η οποία καταγράφεται στο αρχείο /etc/cupsd. onf, μόνο οι χρήστες που ανήκουν στην ομάδα `sys` (σύντομη για _σύστημα_) επιτρέπεται να εκτελούν εργασίες διαχείρισης, όπως προσθήκη ή αφαίρεση ενός εκτυπωτή.

Για μια απλή ρύθμιση (εκτυπωτής συνδεδεμένος σε επιτραπέζιο ή φορητό υπολογιστή και δεν μοιράζεται μεταξύ μηχανών), απλά πρέπει να προσθέσετε έναν χρήστη (ο οποίος θα διαχειρίζεται τους εκτυπωτές) στην ομάδα `sys`. Για παράδειγμα η προσθήκη του χρήστη _didier_ στην ομάδα `sys` μπορεί να γίνει δύο τρόπους:

* Σε λειτουργία κονσόλας ή χρησιμοποιώντας έναν εξομοιωτή τερματικού, γίνεται ρίζα με `su` και στη συνέχεια πληκτρολογήστε:
+
`gpasswd --add didier sys`
+
* Στη γραφική λειτουργία από το Κέντρο Ελέγχου Slint κάντε κλικ στους χρήστες και τις ομάδες (κατηγορία του συστήματος), επιλέξτε το χρήστη και κάντε κλικ στις Ιδιότητες και, στη συνέχεια, στην καρτέλα Ομάδες ελέγξτε `sys`. Ή τον αντίστροφο γύρο (επιλέξτε την ομάδα και στη συνέχεια προσθέστε το χρήστη σε αυτό).

Υπάρχουν διάφοροι τρόποι για να προσθέσετε και να ρυθμίσετε έναν εκτυπωτή (αυτό πρέπει να γίνει από ένα μέλος του χρήστη της ομάδας `sys`):

* Από το Κέντρο Ελέγχου Slint, κατηγορία Hardware, κάντε κλικ στο Ρύθμιση εκτυπωτή για να εμφανίσετε ένα γραφικό περιβάλλον που επιτρέπει μια απλή ρύθμιση...
* ... Ή κάντε κλικ στο Cups Print Control η εμφάνιση ενός web interface στον εξυπηρετητή CUPS. Μπορείτε επίσης να εμφανίσετε τη διεπαφή ιστού στον εξυπηρετητή CUPS πληκτρολογώντας `localhost:631` στο πεδίο διεύθυνσης ενός περιηγητή ιστού.
* Αν έχετε μια συσκευή Hewlett Packard, κάντε δεξί κλικ στο λογότυπο *hp* στην περιοχή ειδοποιήσεων του πίνακα.

NOTE: Για να κάνετε οποιαδήποτε ρύθμιση εκτύπωσης θα πρέπει να εκτελείται ο εξυπηρετητής CUPS. Ξεκινά όταν ξεκινάτε το Slint εάν η υπηρεσία `φλιτζάνια` ελέγχεται μεταξύ των Υπηρεσιών Συστήματος (ελέγχεται από προεπιλογή στο Slint).

=== Ρύθμιση ήχου


Σε εφαρμογές Slint είτε στέλνουν την ηχητική τους παραγωγή είτε στην ALSA είτε στο PulseAudio.

Στην τελευταία περίπτωση το PulseAudio με τη σειρά του στέλνει το ρεύμα εξόδου σε ένα μίξερ ALSA που το κατευθύνει στις κάρτες ήχου.

Ως αποτέλεσμα, μια ρύθμιση όπως μια ένταση ήχου εξόδου μπορεί πάντα να γίνει από ένα μίξερ ALSA, και επίσης από ένα μίξερ PulseAudio αλλά μόνο σε περίπτωση που η εφαρμογή στέλνει την έξοδο ήχου του στο PulseAudio.

Θα παρουσιάσουμε τώρα την εφαρμογή που μπορεί να χρησιμοποιηθεί για την τροποποίηση των ρυθμίσεων ήχου

==== pavucontrol (για PulseAudio)

`pavucontrol` σημαίνει PulseAudio Volume Control και είναι μια γραφική εφαρμογή. Μπορείτε να το ξεκινήσετε από ένα μενού τερματικού ή εφαρμογής, ή κάνοντας δεξί κλικ στο εικονίδιο μίξερ ήχου στην κορυφή του πίνακα του Mate. Στην πραγματικότητα επιτρέπει περισσότερες ρυθμίσεις από το μόνο έλεγχο της έντασης, αφιερώστε χρόνο για να εξερευνήσετε όλες τις λειτουργίες της.

Μπορείτε επίσης να χρησιμοποιήσετε την μικροεφαρμογή ελέγχου έντασης στην περιοχή ειδοποιήσεων του πίνακα: ένα αριστερό κλικ επιτρέπει να ρυθμίσετε την ένταση, ένα δεξί κλικ δίνει πρόσβαση σε άλλες ρυθμίσεις και επιτρέπει να ξεκινήσει το μίξερ pavucontrol.

[[Sound_on_the_command_line]]

==== alsamixer  (for ALSA)

alsamixer είναι μια εφαρμογή ncurses, που παρέχει μια ημι-γραφική διεπαφή χρήστη.

Για να χρησιμοποιήσετε τον τύπο: σε μια κονσόλα ή σε ένα γραφικό τερματικό:
----
alsamixer
----
τότε:

* Χρησιμοποιήστε τη σελίδα πάνω από το κλειδί για να αυξήσετε την ένταση κατά 5%
* Χρησιμοποιήστε το πλήκτρο κάτω από τη σελίδα για να μειώσετε την ένταση κατά 5%
* πιέστε το Esc για να αφήσετε την εφαρμογή.

==== amixer (για ALSA)
Η εντολή είναι της μορφής:
----
amixer <arguments>`
----
Για παράδειγμα για να ορίσετε τον κύριο όγκο σε 70% τύπο:
----
amixer sset Master 70%
----
Για να μάθετε περισσότερα, πληκτρολογήστε μία από αυτές τις εντολές:
----
άνθρωπος amixer
amixer -h
----
==== Sam (Ο Μίξερ Άλσα Φιλικός)
sam επιτρέπει την επιλογή της κάρτας ήχου για να εργαστεί όταν υπάρχουν περισσότερα από ένα
τέτοια συσκευή στο μηχάνημα σας. +
Όταν υπάρχει μόνο ένα, παρουσιάζει άμεσα τους διαφορετικούς μίκτες
για διαμόρφωση.

Όλες οι επιλογές, είτε πρόκειται για κάρτες ήχου, οι αναμικτήρες ή ένα συγκεκριμένο χαρακτηριστικό ενός
 συγκεκριμένου αναμείκτη επιλέγονται με κύλιση μέσα από τις διαθέσιμες επιλογές χρησιμοποιώντας τα βέλη πάνω και κάτω, στη συνέχεια, εισάγοντας στο επιθυμητό: +
`q` αφήστε τη λίστα επιλογής και/ή τερματίζει. +
`Shift-q` βγαίνει από το πρόγραμμα από οπουδήποτε. +
`F1` Εμφανίζει τυχόν επιπλέον πληροφορίες εάν είναι διαθέσιμες.

Όταν είναι γνωστό το όνομα της επιθυμητής επιλογής, μπορεί κανείς να πατήσει το
πρώτο γράμμα. Η πλοήγηση με πρώτο γράμμα δεν είναι ευαίσθητη στην περίπτωση.
Αυτό θα σας μεταφέρει στην πρώτη επιλογή ξεκινώντας με το πατημένο
γράμμα.  Πατώντας ξανά το ίδιο γράμμα, θα μετακινηθείτε στην επόμενη επιλογή
ξεκινώντας με αυτό το γράμμα ifmore από μία επιλογή όπως αυτή υπάρχει.
Η επανάληψη του γράμματος θα κάνει κύκλο μεταξύ όλων αυτών των επιλογών που ξεκινούν με αυτό το
γράμμα.

Τα ρυθμιζόμενα χαρακτηριστικά ενός μίξερ μπορούν να καταχωρηθούν πατώντας f1. +
Παρουσιάζονται ως κατάλογος επιλογών, παρουσιάζοντας εν συντομία όλες τις σχετικές πληροφορίες, π. χ. .
η "ένταση αναπαραγωγής κάτω από το 84 τοις εκατό" είναι η επιλογή να μειωθεί η ένταση αναπαραγωγής
η ρύθμιση της έντασης αναπαραγωγής.  Όπως μπορείτε να δείτε, σας λέει επίσης ποια είναι η
τρέχουσα ρύθμιση.

NOTE: sam δεν λειτουργεί σωστά σε ένα γραφικό τερματικό. Χρησιμοποιήστε το σε μια κονσόλα.

==== pamixer και ponymix (για PulseAudio)
Αυτές οι ιδιομορφίες είναι παρόμοια, με τους συντρόφους σε αυτή τη μορφή:
----
pamixer <arguments>
ponymix <arguments>
----
Για παράδειγμα για να ορίσετε τον όγκο στο 70% για την προεπιλεγμένη νεροχύτη πληκτρολογήστε μία από αυτές τις εντολές:
----
pamixer --set-volume 7
ponymix set-volume 8O
----
Για να μάθετε περισσότερα, πληκτρολογήστε:
----
pamixer -h
ponymix --help
----

==== pacmd και pactl (για PulseAudio)

Και οι δύο αυτές εφαρμογές γραμμής εντολών ελέγχουν έναν PulseAdio δαίμονα.

WARNING: pacmd πληκτρολογήθηκε μόνο φέρνει ένα διαδραστικό διάλογο. Πατήστε Ctrl+d για να βγείτε από αυτό, αλλά μην πληκτρολογήσετε έξοδο, καθώς αυτό θα σκοτώσει το PulseAudio!

Για να ξέρετε περισσότερα:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== Αποθήκευση και επαναφορά της στάθμης ήχου

Απλά κάντε το αρχείο /etc/rc.d/rc.alsa εκτελέσιμο. Ως ρίζα:
----
chmod /etc/rc.d/rc.alsa
----
Κατά την εκκίνηση, αυτό το σενάριο θα επαναφέρει τις προηγούμενες ρυθμίσεις ήχου αν
είχαν αποθηκευτεί προηγουμένως, else θα ορίσει προεπιλεγμένους τόμους και θα τους αποθηκεύσει
, έτσι ώστε να αποκατασταθεί κατά την επόμενη επανεκκίνηση.

Αν don't θέλετε αυτό το σενάριο να ορίσει τον προεπιλεγμένο τύπο τόμου ως root:
----
αφή /var/lib/alsa/no.asound.state
----

Μπορείτε να αλλάξετε αυτά τα προεπιλεγμένα επίπεδα ήχου με alsamixer ή amixer
και στη συνέχεια πληκτρολογώντας ως root:
----
κατάστημα alsactl
----
Στη συνέχεια, κατά την επόμενη εκκίνηση το σενάριο θα τους επαναφέρει.

Για να ξέρετε περισσότερα:
----
man alsactl
----
=== Ρύθμιση παραμέτρων δικτύου

Εάν κάνατε't ρυθμίσατε τις ρυθμίσεις δικτύου σας κατά την εγκατάσταση του Slint, πρώτα
γίνει ρίζα πληκτρολογώντας `su -` είτε σε μια κονσόλα είτε σε γραφικό
τερματικό όπως το mate-terminal, στη συνέχεια, πληκτρολογήστε τον κωδικό πρόσβασης root.

Η εγκατάσταση του δικτύου γίνεται με το σενάριο `netsetup`.
Έτσι, απλά πληκτρολογήστε την εντολή `netsetup` σε αυτό το
ίδιο τερματικό, όπου'έχετε μόλις επικαλεσμένα δικαιώματα root.
Θα σας ζητηθεί για πρώτη φορά το όνομα του υπολογιστή σας. μπορείτε να επιλέξετε οποιοδήποτε
όνομα, αλλά το μυαλό ότι πρέπει να είναι μια μόνο λέξη.
Στη συνέχεια, σας ζητείται το όνομα τομέα. Εάν το μηχάνημα δεν είναι διακομιστής
μπορείτε να επιλέξετε κανέναν.
Μετά από αυτό θα ερωτηθείτε πώς το μηχάνημά σας συνδέεται με το δίκτυο. Εκτός αν
έχετε έναν καλό λόγο να μην (και ξέρετε τι κάνετε), κρατήστε
τον προεπιλεγμένο `Διαχειριστή δικτύου` για να ρυθμίσετε αυτόματα το δίκτυο.

Για ενσύρματες συνδέσεις, αυτό θα πρέπει να είναι αρκετό για να συνδεθεί στην επόμενη εκκίνηση
αυτόματα.

Για να ρυθμίσετε μια ασύρματη σύνδεση, διατίθενται δύο εντολές χρησιμοποιώντας
τη γραμμή εντολών.

Και πάλι, μπορείτε να πληκτρολογήσετε τις εντολές απευθείας στην κονσόλα ή σε ένα
γραφικό τερματικό όπως το mate-terminal. Πληκτρολογήστε τους ως τακτικό χρήστη όχι ως
root.
Αν ακολουθήσατε αυτές τις οδηγίες και αρχίσατε ήδη τη ρίζα, απλά
πληκτρολογήστε `έξοδο` για να επιστρέψετε στην κανονική κατάσταση χρήστη.

Οι δύο προαναφερθείσες εντολές είναι `nmtui` (πλαίσια διαλόγου) ή `nmcli` (καθαρή γραμμή εντολών),
και οι δύο είναι προσβάσιμες.

Αν προτιμάτε να εργάζεστε στη γραμμή εντολών, φροντίστε πρώτα να διαβάσετε την τεκμηρίωση nmcli.
Απλά πληκτρολογήστε `nmcli --help` και `man nmcli`
για να μάθετε όλες τις λεπτομέρειες.
Ενώ το `nmcli` προσφέρει περισσότερες δυνατότητες, στις περισσότερες περιπτώσεις χρήσης η λειτουργικότητα
του `nmtui` θα είναι αρκετή για τη δημιουργία του ασύρματου δικτύου σας, έτσι θα το περιγράψουμε
εδώ:

Χρησιμοποιώντας το `nmtui`, μπορείτε να πλοηγηθείτε με τα πλήκτρα Tab και βέλους.
Θα σας προτείνουν τρεις επιλογές: +
`Επεξεργασία σύνδεσης` +
`Ενεργοποίηση σύνδεσης` +
`Ορισμός ονόματος κεντρικού υπολογιστή συστήματος` +

Εάν δεν έχει οριστεί ασύρματη σύνδεση επιλέξτε `Ενεργοποίηση σύνδεσης`.
Ξεκινώντας από πάνω προς τα κάτω, πρώτα θα προτείνονται οι ενσύρματες συνδέσεις (αν υπάρχουν),
μετά από αυτό θα εμφανίζονται όλα τα προσβάσιμα ασύρματα δίκτυα.
Πλοηγηθείτε με τα κάτω και πάνω βέλη για να επιλέξετε το δίκτυο που θέλετε,
τότε απλά πληκτρολογήστε Enter: πιθανότατα θα σας ζητηθεί το κλειδί κωδικού πρόσβασης ή κρυπτογράφησης.
Πληκτρολογήστε το, χρησιμοποιήστε το πλήκτρο Tab για να το επιβεβαιώσετε, στη συνέχεια, βγείτε και τελειώσατε.

Μόνο σε γραφική λειτουργία, αντί για `nmcli` ή `nmtui` μπορείτε να χρησιμοποιήσετε την εφαρμογή
`nm-connection-editor`.

=== Διαμόρφωση υπηρεσιών

Εάν χρησιμοποιήσατε τη χειροκίνητη λειτουργία, ρωτήσατε ποιες υπηρεσίες συστήματος ενεργοποιήθηκαν από προεπιλογή κατά την εκκίνηση. +
Εάν χρησιμοποιήσατε τις προεπιλεγμένες ρυθμίσεις Auto mode εφαρμόστηκαν

Και στις δύο περιπτώσεις μπορείτε να αλλάξετε αυτές τις ρυθμίσεις με διάφορους τρόπους:

* Εκτέλεση ως root της εντολής `servicesetup` (TUI)
* Μόνο σε γραφική λειτουργία, χρησιμοποιώντας το `gtkervicesetup`, προσβάσιμο από το Κέντρο Ελέγχου Σλιντ, κατηγορία Σύστημα ή πληκτρολογώντας Alt+F2 για να αυξήσει ένα "Εκτέλεση..." παράθυρο διαλόγου στη συνέχεια πληκτρολογώντας *gtksetrvicesetup*.
* Ως ρίζα καθιστώντας το σχετικό σενάριο εκτελέσιμο (chmod 755 <path to the script> ή μη εκτελέσιμο (chmod 644 <path to the script>). Για παράδειγμα για να κάνετε εκτελέσιμο το fail2ban θα πληκτρολογήσετε: `chmod 755 /etc/rc.d/rc.fail2ban`

[IMPORTANT]
====
Αλλάξτε τις προεπιλεγμένες ρυθμίσεις μόνο αν γνωρίζετε τι κάνετε.
====

Οι υπηρεσίες διαχειρίζονται σενάρια των οποίων το όνομα αρχίζει με `rc.` στον κατάλογο /etc/rc.d/. Για παράδειγμα, η υπηρεσία acpi διαχειρίζεται από το σενάριο κελύφους /etc/rc.d/rc.acpi. Οι περισσότερες από τις υπηρεσίες είναι ενεργοποιημένες κατά την εκκίνηση αν το αντίστοιχο σενάριο είναι εκτελέσιμο. Στον παρακάτω πίνακα δηλώνουμε αν είναι ενεργοποιημένο κατά την εκκίνηση (`on` στη στήλη A) ή όχι (`off` στη στήλη A). Εάν η στήλη είναι κενή, η ενεργοποίηση των υπηρεσιών εξαρτάται από μια επιλογή που έγινε κατά την εγκατάσταση. Ένα `Α` στη στήλη δείχνει ότι η υπηρεσία είναι ενεργοποιημένη σε λειτουργία αυτόματης εγκατάστασης, αλλιώς ενεργοποιείται αν επιλεγεί από το χρήστη κατά τη διάρκεια της εγκατάστασης. Η στήλη πακέτου υποδεικνύει ποιο πακέτο λογισμικού παρέχει το σενάριο που αντιστοιχεί στην υπηρεσία, περίπτωση που συμβαίνει

[options="autowidth"]
|====
| *Service* | *A* | *Πακέτο* | *Σκοπός και παρατηρήσεις*
| acpi | on | acpid | Το Advanced Configuration and Power Interface, επιτρέπει για παράδειγμα τη διαχείριση της ενέργειας ή την επανεκκίνηση πατώντας ένα κουμπί
| alsa | on | alsa-utils | Παροχή προεπιλεγμένων ρυθμίσεων ήχου ή επαναφορά αυτών που αποθηκεύτηκαν
| alsa-oss | ανενεργό | alsa-utils | Ενότητες πυρήνα ALSA OSS. Δεν είναι χρήσιμο σε περιπτώσεις mot, μη ενεργοποιημένο από προεπιλογή στο Slint.
| αταλκ | ανενεργό | νετατάλκη | Επιτρέπει σε Unix-like λειτουργικά συστήματα να χρησιμεύουν ως διακομιστές αρχείων, εκτύπωσης και χρόνου για υπολογιστές Macintosh.
| autofs | ανενεργό | autofs | Αυτόματη τοποθέτηση με βάση το πυρήνα για Linux
| bind | ανενεργό | bind | Εξυπηρετητής ονόματος. Οι περισσότεροι χρήστες θα βασίζονται σε ένα απομακρυσμένο. Ενεργοποιήστε το αν θέλετε να εκτελέσετε ένα διακομιστή ονόματος σε αυτό το σύστημα.
| bitlbee | on | bitlbee | Το BitlBee είναι ένας δαίμονας του IRC που μπορεί να μιλήσει σε δίκτυα άμεσων μηνυμάτων
       και λειτουργεί ως πύλη. Οι χρήστες μπορούν να συνδεθούν με το διακομιστή με οποιοδήποτε κανονικό
       IRC client και να δουν τη «λίστα φίλων» τους στο &bitlbee.
| bluetooth | on | μπλεζ | Επιτρέπει την επικοινωνία με συσκευές bluetooth
| Όμορφο|  | Όμορφο | Επιτρέπει την επικοινωνία με το τερματικό Braille ή το πρόγραμμα ανάγνωσης οθόνης. Ενεργοποιήθηκε εάν ζητηθεί κατά την εγκατάσταση
| cgconfig | on | libcgroups | Εκτελεί το βοηθητικό πρόγραμμα cgconfigparser που αναλύει το /etc/cgconfig. onf για τη ρύθμιση της ιεραρχίας της ομάδας ελέγχου, συμπεριλαμβανομένης της ρύθμισης των δικαιωμάτων (UID και GID) των ομάδων και ενδεχομένως συντονίσιμες παραμέτρους των ελεγκτών. Αυτό ανακουφίζει το να το κάνουμε εμείς οι ίδιοι σε κάθε εκκίνηση, για παράδειγμα τρέχει ένα ξεχωριστό σενάριο κελύφους. This script is executable by default but anyway wενεργό't do anything until /etc/cgconfig.conf be edited (all lines are commented out as shipped)
| cgmanager | ανενεργό | cgmanager | Starts the cgmanager daemon that provides an alternate way to manage the cενεργόtrol group hierarchy through D-Bus requests possibly through the cgm front-end utility.
| cgproxy | ανενεργό | cgmanager | Starts the cgproxy daemon, that allows programs and users in a cενεργόtainer to make cgroup administration requests using DBus calls, sending the user-ids or group-ids as SCM credentials to the cgmanager.
| cgred | on | libcgroups | Starts the cgroups rules engine daemενεργό that automatically distributes to appropriate control groups the processes that changes their effective UID or GID, applying the rules found in /etc/cgrules.conf. This allows to cενεργόtinue apply resources control resources on such processes that could otherwise escape it. Αυτό το σενάριο εκτελέσιμο από προεπιλογή, αλλά ούτως ή άλλως κέρδισε't κάνει τίποτα μέχρι να επεξεργαστεί το /etc/cgrules.conf (όλες οι γραμμές σχολιάζονται όπως αποστέλλεται)
| consolekit | on | ConsoleKit2 | Αυτός ο δαίμονας χρησιμοποιείται από τον πράκτορα ταυτοποίησης κονσόλας polkit's, για να ελέγξετε τα δικαιώματα του χρήστη που θέλει να επανεκκινήσει ή να τερματίσει το σύστημα, για παράδειγμα.
| cpufreq | on | sysvinit-scripts | Ρυθμίσεις για τη συχνότητα CPU και την κλιμάκωση τάσης στον πυρήνα.
| φλιτζάνια | on | φλιτζάνια | Σενάριο εκκίνησης/τερματισμού για τον εξυπηρετητή εκτυπώσεων CUPS.
| cups-browsed | ανενεργό | κύπελλα-φίλτρα | Κάνει απομακρυσμένους εκτυπωτές διαθέσιμες τοπικά.
| dnsmask | ανενεργό | dnsmask | Start/stop/restart dnsmasq (ένα μικρό διακομιστή DNS/DHCP)
| espeakup | | espeakup | εκκίνηση/σταμάτα/επανεκκίνηση του αναγνώστη οθόνης espeakup. Ενεργοποιήστε αν ο χρήστης ζήτησε ομιλία κατά την εγκατάσταση ή αργότερα πληκτρολογήθηκε ομιλία με espeakup
| fail2ban | ανενεργό | fail2ban | εκκίνηση/σταματά το fail2ban που σαρώνει αρχεία καταγραφής όπως το /var/log/pwdfail και απαγορεύει την IP που κάνει πάρα πολλές αποτυχίες κωδικού πρόσβασης, και επίσης ενημερώνει τα στοιχεία τείχους προστασίας για να απορρίψει τη διεύθυνση IP.
| font | ανενεργό | kbd | Sets the console fενεργόt (used in Console mode, not in Graphical mode)
| θρυαλλίδα | on | θρυαλλίδα | Φόρτωση της ασφάλειας και προσάρτηση του συστήματος αρχείων ελέγχου ασφαλειών. Το FUSE είναι μια απλή διεπαφή για προγράμματα χώρου χρήστη για την εξαγωγή ενός συστήματος εικονικών αρχείων στον πυρήνα του Linux.  Το FUSE στοχεύει επίσης στην παροχή μιας ασφαλούς μεθόδου σε μη προνομιούχους χρήστες για να δημιουργήσουν και να τοποθετήσουν τις δικές τους εφαρμογές συστήματος αρχείων.
| φαινρίρ | ανενεργό | φαινρίρ | εκκίνηση/διακοπή / επανεκκίνηση του αναγνώστη οθόνης fenrir, το οποίο μπορεί να ξεκινήσει μετά την εγκατάσταση πληκτρολογώντας ομιλία με fenrir.
| font | ανενεργό | kbd | ρύθμιση μιας προσαρμοσμένης γραμματοσειράς κονσόλας
| gpm | ενεργό | gpm | Ο διακομιστής Γενικού Σκοπού Ποντικιού επιτρέπει την κοπή και επικόλληση κειμένου από την οθόνη σε μια κονσόλα Linux.
| httpd | ανενεργό | https | Ξεκινά ή σταματά ο εξυπηρετητής ιστού Apache
| inet1 | on | σενάρια δικτύου | Αυτό το σενάριο χρησιμοποιείται για να φέρει επάνω τις διάφορες διεπαφές δικτύου.
| inet2 | ενεργό | σενάρια δικτύου | Αυτό το σενάριο κελύφους εκκινεί ολόκληρο το σύστημα δικτύου.
| inetd | ενεργό | inetd | Δαίμονας BSD "υπερεξυπηρετητής". Ο χρήστης πρέπει να επεξεργαστεί το /etc/inetd.conf για να χρησιμοποιηθούν πραγματικά οι υπηρεσίες.
| ip_forward | ανενεργό | σενάρια δικτύου | Εκκίνηση/διακοπή προώθησης πακέτων IP, που απαιτούνται για τον υπολογιστή σας για να λειτουργήσει ως δρομολογητής.
| χάρτης πλήκτρων | on | installer | Φόρτωση του χάρτη keybord που χρησιμοποιείται στη λειτουργία κονσόλας.
| τοπικός | ανενεργό | sysvinit-scripts | ξεκινά δαίμονες που δεν ξεκίνησαν από το /etc/rc.d/rc.M κατά την εκκίνηση.
| κύκλωμα | on | sysvinit-scripts | Φορτώνει το άρθρωμα πυρήνα συσκευής βρόχου.
| lxc | ανενεργό | lxc | This scripts starts (if cενεργόfigured to be auto-started) and stops lxc containers.
| mcelog | ανενεργό | mcelog | Ξεκινά την καταγραφή σφαλμάτων υλικού mcelog. Αυτό καταγράφει και χειρίζεται τα σφάλματα υλικού CPU στα συστήματα x86
| messagebus | on | dbus | Το σύστημα λεωφορείο μήνυμα D-BUS. Αυτός είναι ένας δαίμονας που μεταδίδει ειδοποιήσεις συμβάντων συστήματος και άλλων μηνυμάτων, παρέχοντας επικοινωνία μεταξύ των διαδικασιών.
| πρόσθετα | on | sysvinit-scripts | Compute the kernel modules dependencies and start other scripts that load modules not automatically loaded by eudev, possibly for specific kernel versiενεργόs
| modules.local | on | sysvinit-scripts | Φόρτωση μονάδων που δεν φορτώθηκαν αυτόματα από τον eudev
| murmur | ανενεργό | murmur | Εκκίνηση/διακοπή του διακομιστή φωνητικής συνομιλίας murmur για mumble
| mysqld | ανενεργό | mariadb | Εκκίνηση/διακοπή του εξυπηρετητή MariaDB. Το MariaDB είναι ένα πιρούνι της MySQL πλήρως συμβατό με αυτό
| διαχειριστής δικτύου|  | Διαχειριστής Δικτύουcomment | This is a daemon for automatically switching network cενεργόnectiενεργόs to the best available cενεργόnection. Activated if NetworkManager is chosen to configure the network, during or after installatiενεργό
| nfsd | ανενεργό | nfs-utils | Εκκίνηση/διακοπή ενός nfs (Network File Server.qq
| ntpd | on | ntp | Ξεκινά να σταματά έναν δαίμονα ntp ( Net'work Time Protocol).
| numlock|  | salixtools | Activate numlock ενεργό the console
| pcmcia | ανενεργό | pcmciautils | Σενάριο για την προετοιμασία του υποσυστήματος PCMCIA.
| php-fpm | ανενεργό | php | Ξεκινά τον δαίμονα διαχείρισης διαδικασιών PHP FastCGI.
| pulseaudio | ανενεργό | pulseaudio | Ξεκινά pulseaudio σύστημα σε πλάτος. Αυτό δεν συνιστάται στο Slint.
| rpc | ανενεργό | rpcbind | Start/stop/restart RPC (remote process communications) daemενεργόs needed to use NFS. Για να εκτελέσετε έναν διακομιστή NFS, η εκκίνηση είναι υποχρεωτική.
| Σάμμπα | ανενεργό | Σάμμπα | Εκκίνηση/διακοπή / επανεκκίνηση του αρχείου Samba SMB CIFS και διακομιστή εκτύπωσης για πελάτες CIFS.  Σας επιτρέπει να κάνετε αρχείο χώρο ή εκτυπωτές σε έναν εξυπηρετητή Samba διαθέσιμο σε πελάτες CIFS (όπως υπολογιστές που τρέχουν Windows).
| saslauthd | ανενεργό | cyrus-sasl | saslauthd is a daemon process that handles plaintext authentication requests ενεργό behalf of the SASL library.  Η βιβλιοθήκη CMU Cyrus SASL χρησιμοποιείται κυρίως για τον έλεγχο ταυτότητας σε διακομιστές αλληλογραφίας.
| sendmail | ανενεργό | sendmail | Εκκίνηση/διακοπή / επανεκκίνηση του Sendmail MTA (πράκτορας μεταφοράς ταχυδρομείου ή σύστημα διανομής ταχυδρομείου).
| σειριακή | ανενεργό | util-linux | Αρχικοποιεί και ορίζει τις σειριακές θύρες στο σύστημά σας
| ορισμός | ενεργό |util-linux |  Παρέχει τη γραμμή εντολών για το βοηθητικό πρόγραμμα setterm για να ρυθμίσετε τα χαρακτηριστικά του τερματικού (κυρίως χρησιμοποιείται για την οθόνη blanking και διαχείριση ισχύος).
| έξυπνο | ανενεργό | smartmontools | Εκκίνηση/διακοπή / επανεκκίνηση του δαίμονα smartd, ο οποίος παρακολουθεί την κατάσταση του S.M.A.R.T. συμβατό σκληρούς δίσκους και αναφέρει τυχόν προβλήματα.
| sshd | on | openssh | Εκκίνηση/διακοπή/επανεκκίνηση του ασφαλούς εξυπηρετητή κελύφους
| snmpd | ανενεργό | net-snmp |Εκκίνηση/διακοπή του δαίμονα net-snmp SNMP (Simple Network Management Protocol)
| syslog | on | sysklogd | Έναρξη/διακοπή/επανεκκίνηση των δαίμων καταγραφής συστήματος, που καταγράφουν τόσο τα μηνύματα του πυρήνα όσο και του συστήματος's.
| sysstat | ενεργό | συστάτη | Επαναφορά των αρχείων καταγραφής δραστηριότητας του συστήματος, που χρησιμοποιείται για τον υπολογισμό των στατιστικών επιδόσεων
| ομιλία |  | ομιλία | εκκίνηση/διακοπή / επανεκκίνηση της ανάγνωσης οθόνης ομιλίας, η οποία μπορεί να ξεκινήσει μετά την εγκατάσταση πληκτρολογώντας ομιλία με ομιλία-επάνω.
| sysvinit | on | sysvinit-scripts | Αυτό το αρχείο παρέχει βασική συμβατότητα με σενάρια εκκίνησης τύπου SystemV που βρίσκονται σε πολλά δυαδικά πακέτα
| swapinzram | on | swapinzram | Ρυθμίστε ένα μπλοκ swap συσκευή στη μνήμη RAM χρησιμοποιώντας το zram
| syslog | on | syslogd | Έναρξη/διακοπή/επανεκκίνηση των δαιμόνων καταγραφής συστήματος.
| sysstat | ανενεργό | sysstat | Επαναφορά των αρχείων καταγραφής δραστηριότητας του συστήματος.
| ατολμία | ανενεργό | TiMidity++ | Start/stop/restart the TiMidity++ ALSA sequencer client. TiMidity++ is a software synthesizer.  Μπορεί να παίξει αρχεία MIDI με τη μετατροπή τους σε στοιχεία κυματομορφής PCM ή άλλες διάφορες μορφές αρχείων ήχου.
| udev | on | eudev | Αυτό το σενάριο αρχικοποιεί το udev, το οποίο συμπληρώνει τον κατάλογο /dev με κόμβους συσκευής, σαρώνει για συσκευές,
φορτώνει τις κατάλληλες ενότητες πυρήνα και ρυθμίζει τις συσκευές.
| ulogd | on | ulogd | ξεκινά το ulogd daemon χώρου χρήστη για το netfilter/iptables που σχετίζονται με την καταγραφή.
| vde2 | ενεργό | vde2 | Έναρξη/διακοπή/επανεκκίνηση του διακόπτη VDE. Το VDE είναι ένα εικονικό δίκτυο ethernet που περιλαμβάνει εργαλεία όπως 'vde_switch' και 'vdeqemu'.
| ασύρματο | on | ασύρματα-εργαλεία|Αυτό το σενάριο ορίζει PCI, USB, και 32-bit Cardbus ασύρματες συσκευές. Κανονικά αυτό το σενάριο καλείται από το rc.inet1 αντί να τρέχει απευθείας
| yp | on | yptools | Start NIS (Network Information Υπηρεσίαs). NIS provides network-wide distributiενεργό of hostname, username, and other information databases.
|====

Μπορείτε να ξεκινήσετε ή να σταματήσετε μια υπηρεσία χρησιμοποιώντας ως root την εντολή `υπηρεσία`. Για να μάθετε περισσότερα τύπου `man service`.

== Glossary

Several definitiενεργόs in this glossary are taken or adapted from  https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiενεργό]]Εφαρμογή:: An applicatiενεργό program (applicatiενεργό for short) is
a computer program designed to carry out a specific task typically requested by
end-users.
+
Applications are not generally cενεργόsidered as part of the operating system, meaning that they can be added to the system after its installation. They
perform non-system-related functiενεργόs, such as word processing, architectural
design, mechanical design, workstation publishing, or financial analysis.


[[boot]]Εκκίνηση::
Boot means switch-ενεργό a computer to start an operating system. Αρκετά λειτουργικά
συστήματα μπορούν να εγκατασταθούν στον ίδιο υπολογιστή. Select which one to load into
RAM and run can be dενεργόe either by the firmware or by a software named boot
manager (GRUB in Slint's case). The firmware of a computer can support ενεργόe of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiενεργόs written in a boot sector.
* Στη λειτουργία EFI το OS loader είναι ένα πρόγραμμα που αποθηκεύεται σε ένα εκτελέσιμο αρχείο, που βρίσκεται σε έναν κατάλογο ενός διαμερίσματος συστήματος EFI (ESP).

[[Επεξεργαστής]]CPU::
Η CPU ή Κεντρική Μονάδα Επεξεργασίας εκτελεί τις οδηγίες των προγραμμάτων.

[[command]]Εντολή:: Η εντολή ορίζεται από τον https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] ως "οδηγία για ένα <<shell, κέλυφος>> για να εκτελέσει μια συγκεκριμένη εργασία".
+
Η εργασία που θα εκτελεστεί μπορεί να είναι μια <<application, εφαρμογή>> ή ένα <<utility, βοηθητικό πρόγραμμα>>.
+
Η βασική δομή των εντολών κελύφους ορίζεται στο κεφάλαιο https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Εντολές κελύφους] της προδιαγραφής POSIX.
+
Παραδείγματα εντολών παρέχονται στο <<bash shell, [κελύφος bash]>>.

[[console]]Κονσόλα:: Η λέξη "κονσόλα" αναφέρεται στην αρχή του υπολογιστή
συστήματα, όταν ο διαχειριστής του συστήματος πληκτρολόγησε εντολές σε μια συσκευή, συμπεριλαμβανομένου ενός πληκτρολογίου
και ενός εκτυπωτή, συνδεδεμένες με τον υπολογιστή, τις εντολές που πληκτρολογήθηκαν και την έξοδο
από τον υπολογιστή που εκτυπώνεται στην κονσόλα, παρέχοντας ένα αρχείο καταγραφής και των δύο.
+
Σε προσωπικούς υπολογιστές, ο χρήστης πληκτρολογεί τις εντολές στο πληκτρολόγιο και η έξοδος τους
εκτυπώνεται σε μια οθόνη, που μπορούν να διαχωριστούν από τον υπολογιστή ή να ενσωματωθούν στον υπολογιστή
όπως σε ένα φορητό υπολογιστή.

[[device]]Συσκευή::

Ένας υπολογιστής περιφερειάρχης ή ένα αντικείμενο που εμφανίζεται στην εφαρμογή ως τέτοιο.[POSIX]

[[directory]]Κατάλογος::
Ένας κατάλογος είναι ένα άλλο όνομα για ένα φάκελο. Τα συστήματα αρχείων χρησιμοποιούν καταλόγους για να
οργανώσουν αρχεία μέσα σε κατατμήσεις.
+
Οι κατάλογοι μπορούν να περιέχουν αρχεία και άλλους καταλόγους. Η προκύπτουσα
δομή μπορεί να αναπαριστάται ως ένα δένδρο ανάποδα. Ο κατάλογος ανωτάτου επιπέδου
μιας μονάδας δίσκου ονομάζεται ριζικός κατάλογος.  Στο Linux ο χαρακτήρας / διαχωρίζει τα
επίπεδα του δέντρου. / και μόνο αντιπροσωπεύει τον κατάλογο ρίζας, /home φιλοξενεί τα αρχεία
που ανήκουν σε χρήστες, /home/didier φιλοξενεί τα αρχεία που ανήκουν στο didier χρήστη.
/root φιλοξενεί τα αρχεία του χρήστη με το όνομα root (το σύστημα's διαχειριστή).
Σημείωση: 'root' μπορεί να ανατρέξει στον κατάλογο ανωτάτου επιπέδου ή στο διαχειριστή του συστήματος's.

[[drive]]Οδηγός::
Μια μονάδα δίσκου είναι μια συσκευή που αποθηκεύει μη πτητικά δεδομένα, πράγμα που σημαίνει ότι τα δεδομένα δεν είναι
σβησμένα όταν η ισχύς είναι απενεργοποιημένη. Παραδείγματα: σκληροί δίσκοι, SSD, USB sticks, SD
κάρτες αναγνώστες, eMMC.
+
Τα μέσα αποθήκευσης των δεδομένων μπορεί να συνδεθεί μόνιμα με τη μονάδα δίσκου ή αφαιρούμενα
όπως κάρτες SD, USB sticks και δίσκους που συνδέονται μέσω USB.
+
Ένα λειτουργικό σύστημα εγκατεστημένο σε αφαιρούμενο μέσο ή μια εξωτερική μονάδα δίσκου λέγεται
φορητό: μπορεί να μετακινηθεί από έναν υπολογιστή σε άλλο.

[[display_manager]]Διαχειριστής οθόνης::
Ένας διαχειριστής εμφάνισης (ή διαχειριστής σύνδεσης) είναι ένα λογισμικό που εμφανίζει ένα παράθυρο στην οθόνη
στο οποίο ζητά το όνομα σύνδεσης και τον κωδικό πρόσβασης του χρήστη, ξεκινά
το γραφικό περιβάλλον που επιλέγεται από τον εν λόγω χρήστη.

[[encryption]]Κρυπτογράφηση::
Η κρυπτογράφηση είναι η διαδικασία μετατροπής δεδομένων σε μια μη αναγνωρίσιμη («κρυπτογραφημένη») μορφή.
Χρησιμοποιείται συνήθως για την προστασία ευαίσθητων πληροφοριών, έτσι ώστε μόνο
εξουσιοδοτημένα πρόσωπα να μπορούν να τις δουν. Ένα ενιαίο αρχείο ή κατάλογος, ένα διαμέρισμα καθώς και
ως ολόκληρη μονάδα δίσκου μπορεί να κρυπτογραφηθεί, which make it accessible only after having
typed a small text called a passphrase, kept secret.

[[file]]Αρχείο::
Ένα αρχείο υπολογιστή είναι ένα σύνολο ψηφιακών δεδομένων που συλλέγονται με το ίδιο όνομα, που καταγράφονται σε ένα μόνιμο μέσο αποθήκευσης, ονομάζεται μαζική αποθήκευση, όπως ένας σκληρός δίσκος, ένα SSD, ένα DVD, μια κάρτα SD ή ένα USN stick και χειρίζεται ως μονάδα.
+
Τα αρχεία μπορούν να περιέχουν δεδομένα όπως κείμενα, εικόνες, ήχους, βίντεο ή προγράμματα υπολογιστών.

[[file_system]]Σύστημα Αρχείων::
Ένα σύστημα αρχείων είναι ένα λογισμικό που διαχειρίζεται τα αρχεία και τους καταλόγους σε μια
κατάτμηση. Απομνημονεύει τη θέση στα φυσικά μέσα των δεδομένων
που περιέχονται στα αρχεία, επιτρέποντας να τα διαβάσει ή να τα γράψει. Παραδείγματα κοινώς
χρησιμοποιούμενων συστημάτων αρχείων είναι vfat, ntfs, ext4, f2fs. Αυτή η εντολή εμφανίζει όλα τα
συστήματα αρχείων που επιτρέπουν την ανάγνωση δεδομένων που περιέχονται σε ένα διαμέρισμα από το Linux:
+
----
cat /proc/filesystems±grep -v nodev
----

[[firmware]]Υλικολογισμικό::
Ένα υλικολογισμικό είναι ένα λογισμικό που αρχικοποιεί και ελέγχει το υλικό, τότε είτε
επιλέγει και φορτώνει σε RAM το λειτουργικό σύστημα, ή ξεκινά ένα λογισμικό που ονομάζεται
διαχειριστής εκκίνησης που θα το κάνει αυτό. Το υλικολογισμικό διατηρείται σε μη-πτητική μνήμη
συσκευές, όπως ROM, EPROM, ή μνήμη flash. Είναι το πρώτο λογισμικό που εκτελείται κατά την
εκκίνηση ενός υπολογιστή. Παρέχει ένα μενού που επιτρέπει να ρυθμίσετε το υλικό και
επιλέξτε σε ποια κατάσταση (Legacy ή EFI) για εκκίνηση, και με την οποία να αναζητήσετε το λειτουργικό σύστημα
ή άλλη εφαρμογή (όπως ο διαχειριστής εκκίνησης GRUB) για να εκτελέσετε.

[[kernel]]Kernel::
Ένας πυρήνας Linux είναι το λογισμικό στον πυρήνα ενός συστήματος Slint που χειρίζεται τις
αλληλεπιδράσεις μεταξύ των εφαρμογών και του υλικού.
+
Παρουσιάζεται ως ένα μόνο αρχείο, εγκατεστημένο στον κατάλογο /boot. Για παράδειγμα το αρχείο /boot/vmlinuz-generic-5.12.11 είναι ένας πυρήνας, που προέρχεται από το γενικό πακέτο πυρήνα.
+
Κατά την εκκίνηση ο πυρήνας αντιγράφεται στη μνήμη RAM.

[[initrd]]Initrd::
Ένα initrd (ακριβέστερα ένα initramfs ή ένα αρχικό σύστημα αρχείων RAM για Slint) είναι
ένα σύστημα Linux που παρέχεται ως συμπιεσμένο αρχείο αρχείου. Κατά την εκκίνηση, μόλις ο
πυρήνας έχει φορτωθεί σε RAM το inird φορτώνεται και στη RAM. Το αρχείο του /init
τρέχει: φορτώνει τις απαιτούμενες ενότητες πυρήνα στη μνήμη RAM, καταχωρήστε τις συσκευές, πιθανώς
ξεκλειδώστε τη ριζική συσκευή, τοποθετήστε τα ψευδο-συστήματα αρχείων και στη συνέχεια μεταβείτε στο ριζικό
σύστημα αρχείων για να ξεκινήσετε πραγματικά το σύστημα.
+
Ένα initrd παρουσιάζεται ως ένα μόνο αρχείο, εγκατεστημένο στην εκκίνηση του καταλόγου.
Για παράδειγμα, το αρχείο initrd-generic-5.12.11 είναι initrd

[[live_system]]Ζωντανό σύστημα::
Ένα ζωντανό σύστημα είναι ένα λειτουργικό σύστημα που, αντί να εγκατασταθεί σε μια συσκευή
όπως ένας σκληρός δίσκος ή SSD, βρίσκεται εξ ολοκλήρου σε <<RAM>>.
+
An initrd is also a live system, and so is a Slint εγκαταστάτης wich is basically an initrd.

[[partition]]Διαμέρισμα::
Ένα διαμέρισμα είναι ένα τμήμα ενός μέσου αποθήκευσης, όπως ένας σκληρός δίσκος ή SSD. Αντιμετωπίζεται
από το λειτουργικό σύστημα ως ξεχωριστό λογικό τόμο, γεγονός που το καθιστά
λειτουργία παρόμοια με ένα ξεχωριστό μέσο.

[[partition_table]]Πίνακας χωρισμάτων::
A partition table is the permanent structure recording how information is laid
out on a media, mainly recording the beginning and end of each partition on
the media.
+
The most common types of partition tables are the DOS partition table, initially
used by the MS-DOS operating system, and the GUID Partition Table or GPT, which
allows to handle more partitions and larger drives.

[[program]]Πρόγραμμα::
A prepared sequence of instructions to the system to accomplish a defined task. The term "program" encompasses applications written in the Shell Command Language, complex utility input languages (for example, awk, lex, sed, and so on), and high-level languages. [POSIX]

[[RAM]]RAM::
RAM σημαίνει μνήμη τυχαίας πρόσβασης. Αυτό το είδος συσκευής αποθηκεύει πτητικά δεδομένα,
που σημαίνει ότι τα δεδομένα διαγράφονται όταν η ισχύς είναι απενεργοποιημένη.

[[shell]]Κέλυφος:: Ένα πρόγραμμα που ερμηνεύει τις ακολουθίες της εισαγωγής κειμένου ως εντολές. Μπορεί να λειτουργεί σε ροή εισόδου ή να μπορεί να προάγει διαδραστικά και να διαβάσει εντολές από τερματικό. The syntax of the commands
that can be interpretd by the shell can vary along the shell in use but are mainly defined in the the chapter
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2.
Shell Command Language] of the POSIX specification.
+
Slint ships several programs acting as shell, listed in the file /etc/shells. The *bash* shell is used by default.

[[swap]]Εναλλαγή::
Ένας χώρος swap χρησιμοποιείται για την προσωρινή αποθήκευση δεδομένων στο παρελθόν σε RAM σε μια συσκευή
όπως ένας σκληρός δίσκος ή SSD, είτε επειδή αλλιώς η μνήμη RAM θα γινόταν πλήρης, ή να
ελεύθερο χώρο στην μνήμη RAM για να αποθηκεύονται εκεί πιο συχνά χρησιμοποιούμενα δεδομένα. Ο χώρος swap μπορεί να
είναι ένα διαμέρισμα σε μια μονάδα δίσκου τύπου 'ανταλλαγή Linux' ή ένα κανονικό αρχείο αποθηκευμένο σε ένα
υπάρχον τμήμα. Υπάρχει επίσης το 'swap in zram': σε αυτή την περίπτωση τα δεδομένα
αποθηκεύονται σε RAM αλλά σε συμπιεσμένη μορφή, στο χρησιμοποιήσιμο μέγεθος της RAM.

[[terminal]]Τερματικό::
Historically a terminal was a physical device composed of a keyboard and a screen
used to type commands and receives responses from a remote computer.
+
Nowadays the commands can be typed in console (or text) mode or in graphical
mode.

[[utility]]Εργαλείο::
Ένα βοηθητικό πρόγραμμα είναι ένα πρόγραμμα που μπορεί να ονομαστεί από ένα κέλυφος (αυτό είναι επίσης η περίπτωση κάποιων <application,applications>>).
+
Utilities are a part of the operating system (but not of the kernel).
They perform system-related functions, such as listing directory contents,
checking file systems, repairing file systems, or
extracting system status information.
+
An utility may be invoked as a separate program that executes in a different
process than the command language interpreter, or it may be implemented as a
part of the command language interpreter.
+
For example, the echo command (the
directive to perform a specific task) may be implemented such that the echo
utility (the logic that performs the task of echoing) is in a separate program;
therefore, it is executed in a process that is different from the command
language interpreter. Practically this means this means that in this case the utility is a program distinct from the shell
+
Conversely, the logic that performs the echo utility
could be built into the command language interpreter; therefore, it could
execute in the same process as the command language interpreter. Such an utility is said "built-in" the shell.

[[virtual_terminal]]Εικονικό τερματικό::
Ένα εικονικό τερματικό είναι ένα λογισμικό που προσομοιώνει ένα φυσικό τερματικό, συσκευή
που αποτελείται από ένα πληκτρολόγιο και μια οθόνη που επιτρέπει την απομακρυσμένη επικοινωνία με έναν υπολογιστή
.
