
=  Slint Handbook (14.2.1)
:toc: left
:toclevels: 2
:toc-title: 内容
:pdf-themesdir: themes
:pdf-theme: default
:sectnums:

==  Slint の紹介

=== Slint について

Slint は https://en.wikipedia.org/wiki/Linux_distribution[Linux ディストリビューション]で、 http://www.slackware.com/[Slackware]に基づいている。 ポリグロット、インストールが簡単で、汎用性があり、初心者に優しく、視覚障害者にもアクセスできます。

Slint システムは、ほとんどのコンピューティング要件に適合するように調整することができます。

==== 特徴

2つのインストールモードが提案されています: Auto (入力する Linux コマンドなし) と Manual (よりカスタマイズしたい人) です。 インストーラにはドキュメントが含まれています。

視覚障害者の視覚障害者は、視覚的な環境でのインストールから、グラフィカルな環境での使用まで、スピーチと点字を使用できます。

すべてのSlint システムには、サーバー、デスクトップ、ラップトップ用の幅広いソフトウェアがインストールされています。 これには、KDE (オプション)、LXDE、MATE、XFCE、軽量のウィンドウマネージャが含まれます。 すべてのグラフィカル環境は、リムーバブルデバイスの自動マウントにより、すべてのアプリケーションおよびシステム操作に簡単にアクセスできます。 加えて、インストールされているソフトウェアの利用可能な更新の通知、インターネットアクセスの即時の停止、再起動、システムの休止。 各デスクトップ環境は、一貫した環境を提供するために、パネルとアプリケーションメニューの同様のレイアウトを提供します。

選択された言語は国際化されたアプリケーションに使用されます。

Slint Dashboardは、ハードウェアおよびシステム設定、パッケージ、システムツール、ドキュメント、およびユーティリティへのアクセスを一元化します。

さまざまな形式でドキュメントを書き、読み取り、変換したり、電子メールで通信するために、箱から多くのアプリケーションを出荷します。 テキストとオーディオチャット、オーディオとビデオを再生し、文書をピアツーピアで送受信し、オーディオ、ビデオ、グラフィカルな文書を編集し、アプリケーションを開発します。 これは、コンソール上のサーバーとして完全に使用可能で、いくつか含まれるデスクトップのいずれかを使用しています。

多くのアプリケーションは視覚障害のあるユーザーにアクセス可能で、TTSや関連する声の幅広い選択肢が含まれています。 それでも他の人が必要な場合は、簡単にインストールでき、テキスト環境(コンソール)でもデスクトップでも使用できます。

いくつかの社内ツールは、Slint システムの管理と構成を容易にします。

多くのアプリケーションは、簡単なコマンドや数回のクリックでソフトウェアパッケージとして簡単にインストールされます。 何千ものソフトウェアパッケージがあなたの指先にあります!

Slint ユーザは、インストールされたパッケージのアップグレードについてできるだけ早く通知され、リクエストに応じて簡単にインストールできます。 これにより、システムを安全に保ちます。

デフォルトの優先アプリケーション設定が用意されており、簡単にカスタマイズできます。

==== コンテンツ、バージョン、リリースモデル。

Slint インストーラは、完全なインストールのみを提供します。 KDE デスクトップのみがオプションです。

SlintはSlackwareをベースにしており、Slackwareバージョンのリリース直後に新しいSlintバージョンを提供する傾向があります。

しかしSlintは、特定のバージョンのライフサイクル中に、「セミローリング」リリースモデルに従っています。 セキュリティ修正や主要なバグ修正としての更新に加えて、一部のソフトウェアは選択的に更新されて機能強化をもたらし、新機能をもたらすように追加されています。 これは、スクリーンリーダーのような、視覚障害者がSlintにアクセスできるようにするためのソフトウェアの場合です。

リリース後、できるだけ早く新しいバージョンに切り替えることをお勧めします。 これまでのところ、私たちは新しいリリースをゼロからではなくアップグレードするための手順やヘルパースクリプトを提供することができました。 私たちは、ユーザーのファイルの完全なバックアップにもかかわらず、将来のバージョンで可能な限り維持するために最善を尽くします 次に、新しいインストールとユーザーのファイルの復元が容易になります, 特にデスクトップやラップトップの使用のための.

=== この本について、他の情報

この本は、インストールプロセスと使用方法をガイドする Slint 新人を対象としています。 LinuxディストリビューションではSlintに特有の概念や規約が紹介され、用語集が併用されています。

私たちは、Ubuntuのような別のディストリビューションのユーザーとして、WindowsまたはMacOSから来ている人々に対応しようとしています。

インストールされたソフトウェアに関するドキュメントは、Slint システムで一般的に入手できます。 私達はこの本の中でそれにアクセスする方法を述べる。

その他の情報源:

* Slint に含まれるソフトウェアの著者によって、ウェブサイトでしばしば提供される情報。
* http://docs.slackware.com/[Slackware documentation project] 、特に http://docs.slackware.com/howtos:start[HOWTO記事] 多くはSlintに直接適用できます。 適応やアップデートが必要になります
* ArchWiki は頻繁にSlint で出荷されるソフトウェアについての便利な記事を提供する。 例えば、 "arch wiki mate" を検索すると、 https://wiki.archlinux.org/index.php/MATE[MATE についてのこのページ] になります。 警告: 提供された情報は、Slint と Arch によってはいくつかの点で異なるため、適応する必要があります。 例えば、Archはinitシステムとしてsystemdを使用し、SlintとArchではデフォルトでソフトウェアを別々に設定することができます。
* そしてもちろんインターネットの調査エンジンは頻繁に問題への質問そして解決への答えを見つけるのを助けることができる。

=== サポート

これらのチャネルでヘルプを得ることができます:

* Slint メーリングリストは、主なサポートチャネルです。 登録するには、件名として slint-request@freelists.org 宛てに電子メールを送信してください: 'subscribe' そして、あなたが受け取る確認メールに答えます。 それから、件名「コマンド」または「ヘルプ」として、より多くの電子メール mailto:slint-request@freelists.org[slint-request@freiists.org] を知るために。 登録後、電子メール mailto:slint@freelists.org[slint@freilists.org].
* メーリングリストのアーカイブはこちら https://www.freelists.org/archive/slint[]からご覧いただけます。
* IRC: #slint チャンネルでチャット、サーバー irc.libera.chat 、登録は必要ありません。
* Mumble: server slint.fr (別のチャンネルを経由した予約時)
* https://forum.salixos.org/viewforum.php?f=44[Slint フォーラム] は、私たちの友人がSalix(別のSlackware 派生物)で親切に主催してくれました。 登録が必要です。


詳細については、Slint Dasboardの「情報」のリンクを参照してください。 https://slint.fr/wiki/doku.php?id=en/start[wiki] にアクセスするか、インストール後に端末に slint-doc と入力してください。

=== Slint プロジェクトへの翻訳やその他の貢献

Slint には翻訳者が必要です！ 翻訳に参加したい場合は、 https://slint.fr/doc/translate_slint.html[Translate Slint] の説明をご覧ください。

翻訳ファイルは https://crowdin.com/project/slint[Crowdin] でホストされています。

他のタスクのためにSlintに貢献したい場合は、メーリングリストに投稿するか、didieratslintdotfr に行をドロップしてください。 もちろん、メーリングリストで翻訳者も歓迎です!

===  謝辞

Slint プロジェクトは主にSlint の翻訳者やその他の貢献者の皆さんのおかげで成り立っています!

非常に多くの追加のソフトウェアを構築するのに役立つSlackBuilds.orgプロジェクトの貢献者に、彼のアドバイスとツールのためのGeorge Vlahavasのおかげで。

Slintは、Patrick J. Volkerdingと貢献者が持ってきたSlackwareをベースにしています。 ありがとう！ Slintユーザーの皆様には、Slackwareの資金調達に貢献していただくとともに、Salixプロジェクトに寄付していただくことをお勧めします。

Slint リポジトリは Darren 'Tadgy' Austin によって親切に無料でホストされています。 私はすべての Slint ユーザーがホスト https://slackware.uk/ の資金調達に貢献することをお勧めします

Links for financial contributions: +
https://www.patreon.com/slackwarelinux[Become a Slackware patron] or https://paypal.me/volkerdi[サポート Slackware] +
Follow the links on top of http://slackware.uk/slint/x86_64/slint-14.2.1/[this page] to support Slackware UK +
https://salixos.org/donations.html[Donations to Salix]

==  Slint のインストール

HandBook のこの部分では、Slint をダウンロードし、チェックサムで ISO イメージを検証するプロセスについて説明します。 ISOをインストールメディアに書き込み、ハードディスクを分割し、インストールプロセスを簡単に説明します。

=== 要件

現在のSlintバージョンは、これらの要件を満たすコンピュータにインストールできます。

* アーキテクチャ: x86_64 (64 ビット CPU), AMD64 とも呼ばれます
* ディスク上の空き領域または空き領域(ハードドライブ、SSD、NVME、eMMC):少なくとも28Gの自動モードです。 完全なSlintインストールは、ユーザーファイルやアドオンなしで、約20Gが必要です。
* RAM: 2G以上
* DVDドライブまたは利用可能なUSBスロット、DVDまたはUSBスティックを起動するファームウェアの能力を備えています。 空白の DVD または 4G 以上の USB スティックをインストールメディアとして使用できます

NOTE: Secure boot should be disabled to install Slint

=== インストーラの特徴

* インストーラは「ライブシステム」で、メモリで動作します: インストールされたシステムを変更しません。
* 視覚障害者の場合、インストーラは点字で完全に使用でき、スピーチはスピーチアップスクリーンリーダで使用できます。
* エキスパートユーザーの場合は、Slintがインストールされる <<drive, ドライブ>> を準備するために必要なすべてのユーティリティが含まれています。
* 自動インストールモードではなく、質問に答えてコンテキストヘルプを提供するだけで済みます。
* インストーラは、何らかの条件の下で別のLinuxと一緒にインストールしたいドライブ上でSlint用のスペースを解放することができます。
* USB経由で接続されたリムーバブルデバイスに単独でインストールした場合、Slintをポータブルにすることができます。 USBドライブを起動できるコンピュータでも使用できます。
* インストーラはSlintだけがインストールされているドライブを暗号化できます。 これにより、マシンの紛失や盗難、またはリムーバブルドライブの場合に含まれるデータの盗難を防ぐことができます。
* Slint は、独自のドライブ、または別のシステムにインストールできます。

=== 準備

<<download_and_verify, Download and verify a Slint ISO image>> +
<<write_the_iso, Write the ISO image on an Installation Medium>> +
<<make_room_for_Slint, Make Room for Slint>> +
<<create_partitions_for_Slint, Create Partitions for Slint>>

[[download_and_verify]]
====  Slint ISO イメージをダウンロードして確認します

Slint の最新版は 14.2.1 です。

最新のインストールISOイメージは常に https://slackware.uk/slint/x86_64/slint-14.2.1/iso[このディレクトリ]で利用可能です

[TIP]
====
Slint バージョン 14.2 を実行している限り。 新しいISOが提供された時に再インストールする必要はありません インストーラの新機能や新しい機能、またはアップグレードされたパッケージ'のみをもたらすため、システムを最新の状態に保つこともできます。
====

以下に示すISOのファイル名は、ダウンロード時に現在の名前に適応するための例です。

Windowsを実行している場合、引数「sha256sum windows」を持つインターネットは、先に進む方法を教えてくれます。

Linuxを使用している場合は、ISOイメージとsha256チェックサムタイプをダウンロードできます。
----
wget https://slackware.uk/slackware.uk/x86_64/slint-14.2.1/iso/slint64-14.2.1.4.iso
wget https://slackware.uk/slint/x86_64/slint-14.2.1/iso/slint64-14.2.1.4.iso.sha256
----

ダウンロードしたファイルの整合性をチェックするには、次のコマンドを入力してください:
sha256sum -c slint64-14.2.1.4.iso.sha256
結果は次のようになります:
OK

----
sha256sum -c slint64-14.2.1.4.iso.sha256
----
結果は : OK +
でなければ、ダウンロードをやり直します。

[[write_the_iso]]
====  インストールミディアムにISOイメージを書く

DVDまたはUSBスティックをインストールメディアとして使用することができます。

[[make_a_bootable_usb_stick]]
===== USBスティックを作成

On a ++Linux++ system, plug in the USB stick, and check it's name with the following command:

----
lsblk -o model,name,size,fstype,mountpoint
----

[WARNING]
====
慎重にコマンドの出力を確認して、USBスティックの名前ではなく、ハードディスクパーティションの名前を入力しないようにしてください。  USBスティックまたは誤ったハードディスクパーティションのすべての以前の内容は、 *LOST* と *IRCOVERABLE* になります。
====

Let's assume that the name of the USB stick be /dev/sdb. それ以外の名前を付けることができますので、Don't は盲目的に次のコマンドをコピーします。  /dev/sdbにあるUSBスティックにSlint ISOを書き込むコマンド構文は次のとおりです。

----
dd if=slint64-14.2.1.4.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
上記のコマンドは、 *if=* がSlint ISO のパスを指しており、 *of=* がUSBスティックの名前を指していると仮定しています。  これらの値はシステムによって異なる場合があります。
====

On ++Windows++ use an application like http://rufus.akeo.ie/[Rufus].  それは自由でオープンソースです。

1. それを実行するためにダウンロードしたルーファスプログラムを開きます。
2. 使用してブータブルディスクを作成を選択し、ドロップダウンメニューからISOイメージを選択します。
   ディスクアイコンをクリックし、Slint .isoファイルを参照して選択します。
3. フラッシュドライブが UEFI と互換性があることを確認するには、 <<file_system, ファイル システム>> の FAT32 を選択します。
4. 「任意のキーを押してUSBから起動する」プロンプトでフラッシュドライブを作成するには、format@@0オプションを選択します。
5. オプションを選択し終わったら、format@@0をクリックします。プロンプトが表示されたら、フラッシュディスクを消去することを確認します。
6. .isoファイルは、フラッシュドライブにコピーを開始します(プロセスは数分かかることがあります)。 ルーファスが完了したら、プログラムを閉じ、フラッシュドライブを取り出し、取り外します。

[[make_a_bootable_DVD_disc]]
=====  Make a Bootable DVD Disc

On a ++Linux++ system insert the DVD and type the following command:

----
growisofs -speed=2 -dvd-compat -Z /dev/sr0=slint64-14.2.1.4.iso
----

必ずファイルシステムの Slint ISO へのフルパスを入力してください。

On ++Microsoft Windows 2000/XP/Vista/7++ you can write to a DVD using the application http://infrarecorder.org/[InfraRecorder].  それは自由でオープンソースです。

On ++Microsoft Windows 7/8/10++ you can use the http://windows.microsoft.com/en-US/windows7/Burn-a-CD-or-DVD-from-an-ISO-file[Windows Disk Image Burner] utility that is shipped with Microsoft Windows.

[[make_room_for_Slint]]
====  Slint の部屋を作る

コンピュータまたは少なくともSlintにドライブを捧げると、インストールが簡単になり、このように推奨されます。 次に、この手順をスキップし、直接インストーラを実行します。

しかし、Windows、Mac OS、*BSD、または他のLinuxディストリビューションのような既にインストールされているオペレーティングシステムとドライブを共有することもできます。

次に、このドライブのパーティションテーブルの末尾(最後のパーティションの後)にSlint用の空き領域が必要になります。 システム自体には少なくとも20Gが必要ですが、ユーザーファイルやその他のソフトウェアをインストールするためのスペースも必要になります。 Linuxパワーユーザーの場合、ドライブの最後のパーティションを縮小することは、Linuxコマンドを入力してインストーラを開始した後に行うことができます。 以下の条件が満たされている場合は、自動モードでインストーラがこれを行うこともできます。

* ドライブにはGUIDパーティションテーブル(GPT)が装備されています
* 最後のパーティションには、ext <<file_system, file system>> がある。
* 少なくとも28Gはそれで解放することができます。
* マシンはEFIモードで起動しました (レガシーではありません)

そうでない場合は、 `gparted` または Windows を使用してインストールする前に Slint 用のスペースを確保する必要があります (インストールされている場合は Windows をお勧めします)。 しかし、いくつかの条件下でSlintは
<<Automatic_installation, 自動インストール>>に示されているようにあなたのためにそれを行うことができます。

===== Windowsのボリュームの空き容量を設定する方法


https://docs.microsoft.com/en-us/windows-server/storage/disk-management/shrink-a-basic-volume[このドキュメント]
に示されている手順を以下にまとめます。

1. Windows では、コマンドプロンプトを開き、次のように入力します。
+
`diskpart`

2. diskpartプロンプトで次のように入力します。
+
`リストの音量`
+
縮小したい単純なボリュームの数に注意してください。

3. ntfs ファイルシステムを持つ必要がある縮小したいボリュームを選択します。
+
`音量 <number> を選択`

4. 音量を縮小できる最大サイズを知るには
+
`shrink querymax`

5. 作成したい空き領域のメガバイト単位で <size> を定義します。 前のコマンドで見つかった最大サイズを超えてはいけません。 より多くのデータを格納できるようにするには、Windowsボリュームに空き領域を残しておきます。

6. このコマンドを入力してください:
+
`shrink desired=<size>`
+
サイズは、例えば30 GBの場合、G=1024M の型を知っている数字です。
+
`shrink desired=30720`
+
Windowsのアップデートをインストールできるように、システムボリュームに十分な空き容量を保持します。

または、ディスクマネージャを使用することができます: 縮小したいボリュームを選択し、右クリックして「ボリュームを縮小」を選択します。 ボリュームを縮小できる最大空間が表示されるまで待ってください 値を
のままにするように調整し、適合しているようにさらに多くのデータを格納できるようにし、縮小ボタンをクリックします。

===== Linuxでスペースを解放する方法。

http://gparted.org/index.php[gparted]、または配布物によって提供されるパーティション管理のためのグラフィカルツールを使用することができます。

TIP: 28Gがext4ファイルシステムを備えたGPTを備えたドライブの最後のパーティションで解放される場合、インストーラはそれを縮小することができます。

[[create_partitions_for_Slint]]
====  Slint 用のパーティションを作成

自動インストールモードを選択してSlint用のデバイスを専用すると、インストーラがそのデバイスを分割します。 完了した場合でも、以下のほとんどのコマンドのいずれかを使用して、パーティションのレイアウトを調整することができます' yiuwhish.

format@@0モードを使用する場合は、インストール前またはインストール中にSlint用のパーティションを作成できます。

Linuxに慣れていない場合は、インストール前に簡単に実行できます。 http://gparted.org/index.php[gparted] を使うことをお勧めします。 Gpartedは、既存のパーティションを縮小し、空き領域に新しいパーティションを作成するだけでなく、ルームを作ることができます。  Gpartted (Microsoft Windows) をサポートするシステムがない場合は、 http://gparted.org/livecd.php[Gparted Live] を使用できます。
cfdisk、fdisk、gdisk、cgfdisk、partedコマンドはインストーラから利用できます。 Theme を使用して、デバイス全体を分割したり、空き領域で Slint 用のパーティションを作成したりできます。

Slint のインストールのニーズ:

* Linuxの種類のパーティションは、少なくとも20Gのサイズは、より良いです(少なくとも30Gを推奨)。
* EFI モードで起動する場合は、"EFI System" (code ef00) と入力します。 あなたがレガシーモードで起動したとしても、それは勝った'tは1を持って傷つけます。
* GPT(GUIDパーティションテーブル)の場合、BIOSブート(ef02)、サイズ4Mのパーティションがレガシーモードで起動します。 EFIモードで起動しても、それは勝った'tはそれを持って傷つける。
* 必要に応じて型「swap」のパーティション。 これは、特にマシンを冬眠させたい場合や、8G以下のRAMがある場合に推奨されます。 ただし、インストール後にスワップファイルを設定することもできます。

You can also dedicate a partition for /home (but this is not mandatory, I don't) and other partitions for specific use cases.

[NOTE]
====
Slint 自体は約 20 ギガバイトのスペースが必要ですが、50 ギガバイトのルートパーティションが推奨されます。 追加のソフトウェアをインストールするか、ファイルを保存するためのスペースが必要な場合があります。  あなたが写真、ビデオ、音楽などを保存する予定の場合、より多くのスペースが良い。
====

=== Slint インストール

<<Start_of_the_installation, Start of the installation>> +
<<Accessibility_of_the_installer, アクセシビリティ of the installer>> +
<<Usage_of_the_installer, Usage of the installer>> +
<<Automatic_installation, Automatic installation>> +
<<Manual_installation, Manual installation>> +
<<Slint_in_an_encrypted_drive, Slint in an encrypted drive>> +
<<first_steps_after_installation, First steps after installation>>

[[Start_of_the_installation]]
==== インストールの開始

必要に応じて、準備したDVDまたはUSBスティックを起動するためにマシンのファームウェアをセットアップしてください

インストールメディア(DVDまたはUSBスティック)を挿入し、コンピュータを再起動します。 ブラインドユーザーは、ブートメニューが表示されると「ビープ音」を聞くことができます。

Enterキーを押してインストーラを起動します。

インストーラは最初にあなたがカードをサウンドをプローブします。

これは、動作するものをデフォルトとして設定するのに役立ちます。また、一部の視覚障害者がインストール中に使用する音声にも使用されます。

インストーラが2つ以上のサウンドカードを見つけた場合、それぞれに表示されます: +
Enterキーを押してこのサウンドボードを選択します <sound card id> +
それを聞いたらすぐにEnterキーを押します 提案されたサウンドカードが動作していることを確認します。 この設定は /etc/asound.conf の新しいシステムに保存されます。

次のステップでは、あなたがインストール中にスピーチをしたいことを確認(s)または拒否(単にEnterキーを押します)を求められます。 点字は設置中はいつでも利用できます。

インストール時に使用する言語を選択、確認、または変更します。 この言語への翻訳が完了すると、すべての画面が選択された言語になります。

ブートコマンドラインに追加のカーネルパラメータを追加する必要がある場合、Enterキーを押す前に以下の操作を行います:
[NOTE]
====
入力時には、米国のキーボードマップが使用されることに注意してください。 +
Ctrl+x は、「Shift キーである場合と同様に、Ctrl キーまたはコントロール キーを押し続け、X キーを押します」
====
----
e キーを押す
下向き矢印を3回押す
終了キーを押す
スペースバーを押す
カーネルパラメータを入力 (下の例)
Ctrl+X を押して起動 (Enterを押さない)
Enterキーを押して起動します。
----

たとえば、ハードウェアシンセサイザーのスピーカアップドライバを設定するには、次のようなカーネルパラメータを入力します。
----
speakup.synth=apollo
----
ブートコマンドラインで、点字デバイスの設定をこの形式で記入することもできます。
-----
brltty=<driver code>,<device>,<text table>
-----
たとえば、フランス語のテキストテーブルタイプでUSBを介して接続されたPapenmeierデバイスをインストールする場合:
-----
brltty=pm,usb:,fr_FR
-----
NOTE: 点字デバイスは常に認識されるべきUSB経由で接続されています たぶん、あなたが最初に設定を入力しなかった場合、'テキストテーブルが勝った'tは良いものです。

いずれにしてもタイムアウトがないので、 [Enter] を押すと起動が始まります。

設置の最初にスピーチと点字が利用可能になります。

[[Usage_of_the_installer]]
==== インストーラの使い方

コマンドラインに精通している場合は、このトピックをスキップしてください。

以下に、メインインストールメニューを表示します。
....
Slint インストーラーへようこそ！ (version 14.2.1)

利用可能なコマンド (引用符を入力しないでください):

'doc' はインストーラの機能と使い方を知ることができます。
半自動インストールを開始するには「auto」を導入します。
手動でインストールを開始するには 'setup' を設定します。

We recommend that you type 'doc' first to prepare a manual installation, or if
you want to encrypt the drive where Slint will be installed, or if you need to
reduce the size of a partition to make room for Slint alongside another system.
このメニューを読み終えると再び表示されます。
....

このメニューが表示されるとすぐに、あなたはインストールプロセスに手を持っています。

画面を読み、 <<virtual_terminal, 仮想端末>>にコマンドを入力します。 インストーラ
には、同じ物理キーボードと
スクリーンを共有する複数の仮想端末が含まれており、並列で使用することができます。

インストーラは、 *tty1* という名前の仮想ターミナル 1 で起動しますが、
を別のターミナルに切り替えることができます。 たとえば、 *tty2* に切り替えるには、
*Alt-F2* を押してEnterを押し、後で *tty1* に戻ります。
*Alt-F1*を押します。 両方の端末に表示される情報を消去することなく。
*Alt-F1* を意味する: *Alt* キーを押したまま *F1* キーを押します。

This can be useful to continue reading the documentation during installation:
for instance you can switch to *tty2* to begin installation, switch to *tty1* to
continue reading the documentation, then switch to *tty1* again to proceed to
the next installation step.

これは、他の文書を読む際に用語集を参照するためにも使用できます。

4 番目の仮想端末または *tty4* はデバッグに役立つ情報
を提供するメッセージを表示します。それ以外の場合は使用しません。

インストーラにはユーザーとの相互作用のいくつかのモードがあります。

. プロンプトでコマンドを入力し、出力を読み取ります。
. インストーラは質問をし、答えを入力し、Enterキーを押して確認します。
. インストーラには、選択肢またはオプションのメニューが表示されます。上下矢印キーを使用していずれかを選択します。 次に、Enterキーを押して選択を確認するか、Escapeキーを押してキャンセルします。
. インストーラはページャーに情報を表示します。 次に、次または前の行を読み取るために矢印キーを使用し、次のページ、Qを表示するにはスペースを押してドキュメントの読み取りを停止します。

[[Automatic_installation]]
==== 自動インストール

自動モードでは、インストーラはグラフィカル環境 (format@@0) を含むデフォルトの設定を提供します。 新しいシステムを
起動したら、すべての設定を確認して変更できます。

インストール手順は以下の通りです。

. Slintをインストールするには、ドライブに少なくとも28Gのスペースが必要です。 インストーラは最初にドライブ、サイズとそれらの自由なスペースを調査します。 結果に応じて、専用ドライブまたはドライブ内の空き領域にインストールすることができます。
.. 専用ドライブにインストール.
+
このインストールモードでは、ドライブの以前のコンテンツはすべて消去されます。 保存したいファイルが含まれている場合は、まず他の場所で保存してください!
+
ドライブが取り外し可能でUSB経由で接続されている場合、インストーラはSlint をポータブルにすることができます。 外付けUSBドライブを起動できるコンピュータでも使用できます。
+
ドライブは、必要に応じて暗号化することができます, ドライブやコンピュータが紛失または盗まれた場合、盗難からデータを保護するために. 重要な関連付けられた警告があるため、最初に文書の暗号化を注意深く読んでください。

.. 別のシステムで共有されているドライブにインストールします。 これにより、1つのドライブだけを使用して他のシステムを維持しながらSlintをインストールすることが可能になります。
+
ドライブに少なくとも28Gの空き容量がある場合、またはそれが最後に解放される場合、これは許可されます GPT (GUIDパーティションテーブル) EFI モードでインストーラーが起動します: この構成では、両方のシステムが相互に干渉することなく起動します。

. メインのSlint パーティションのサイズを選択し、必要に応じて追加のパーティションのサイズを選択します。 必要に応じて将来の使用のためにドライブに空きスペースを残します。
+
メインパーティションには、一般的にext4ファイルシステムがあります。 ただし、SDカードまたはeMMCドライブにインストールされている場合、f2fsファイルシステムがあります。
+
インストールが開始される前に、選択を確認し、変更する機会があります。
+
確認後、基本パッケージがインストールされ、数秒かかります。

. 暗号化されたディスクを選択した場合は、起動時にドライブのロックを解除するために使用されるパスフレーズを入力します。
. ユーザー"root"のパスワードを選択します。 これはシステム管理者で、すべての権限を持っています。 また、通常のユーザーアカウントを作成し、アクセス可能な点字出力が必要かどうかを示します。 そしてSlint にテキストモードでログインするかグラフィカルモードでログインするかどうか。
+
[NOTE]
====
インストール中に英語(アメリカ)を使用した場合は、インストールされたシステムに使用する言語を選択します そうでなければ、インストーラはインストール時と同じように設定します。
====
. インストーラはインターネット接続を確立しようとしています タイムゾーンを提案し必要に応じて後でパッケージを設置する 設定または提案されたものを確認します。
. インストーラはシステムパーティションにスワップファイルを作成し、インストール後に簡単にサイズを変更できます。 デフォルトでは、追加のスワップスペース 1 があります。 Slintが起動されるたびに、物理RAMのサイズがzramで設定されます。
. パッケージはドライブにインストールされます(KDE シリーズのパッケージはオプションです)。 各パッケージの最新バージョンをダウンロードしてインストールできるように、インストーラはインターネット接続を確立しようとします。 これには、ISO イメージのリリース以降に提供されたものも含まれます。 したがって、あなたは勝った't インストール後、これらの新しいまたはアップグレードされたパッケージをダウンロードしてインストールする必要があります。
+
すべてのパッケージのインストールは、ハードウェアに応じて約10〜40分かかります。

. 次に、システムが設定され、GRUBブートマネージャがインストールされます。 Slintが専用ドライブにインストールされている場合、LegacyモードとEFIモードの両方で起動できます。 そうでなければ、EFIモードでのみ起動します。 どちらの場合でも、ブートメニューには、インストールされたOSを検出して起動するための追加の「rescue」ブートエントリがあります。
. USBフラッシュドライブにレスキューブートスティックを作成するように求められます。 これを使用すると、そのブートメニューから起動できない場合は Slint を起動できます。

最後に、インストールメディアを削除し、新しいSlintシステムを起動するために再起動します。
再起動前にブートメニューのプレビューを表示できます。

[[Manual_installation]]
==== 手動でインストール

手動のインストールは、2つの主要な手順で構成されています。

. インストール用にドライブを準備します。 これには以下が含まれます: パーティションレイアウトを設計し、パーティションを作成し、必要に応じてそれらをフォーマットします。 必要に応じて、インストーラはLinuxパーティションをフォーマットできます。
. *setup* を入力して、さらなる準備、インストール、設定を行います。

===== インストール用にドライブを準備します。

可能な場合は、独自のドライブにSlintをインストールします。

You may also install it in a drive shared by another system, but then preferably
if booting in EFI mode, so that each system, having its own OS loader, will be
independent from others and their updates. その後、Slintをインストールするには、ドライブの
にスペースを解放する必要があります。 You can use the 'freespace' command of the Slint
installer to do that if the last partition of the drive is has an ext2, ext3 or
ext4 file system, else do it from the already installed system.

可能であれば、マシンを EFI モードで起動させ、ターゲットドライブの GPT (GUID
パーティションテーブル) を設定します。 柔軟性を最大限に高めることができます

インストーラはEFIとレガシーの両方の起動にGRUBソフトウェアを使用します。

Slint を独自のドライブにインストールするには、以下が必要です。

* GPTでレガシーモードで起動するには、このコンテキストで
GRUBが必要とするBIOSブートタイプのパーティション。 このパーティションのサイズは1Mで十分です。 これはGRUBのために予約されている
であり、フォーマットするべきではありません。
* EFI モードで起動するには、EFI OS ローダーを格納するためのサイズ
100M の型 ESP (EFI System Partition) のパーティションを使用します。 このパーティションは、
DOSパーティションテーブルのようにGPTで作成できます。
* Linuxタイプのシステムのサイズが少なくとも28Gのパーティション。

GPTの場合は、BIOSブートパーティションとESPの両方を
より柔軟に設定することをお勧めします。 EFIとレガシーモードでSlintを起動することができます。

他のパーティションの作成は任意です。 swap パーティションが必要な場合は、
は Linux swap 型でなければなりません。 あるいは加えて、スワップ
ファイルを設定することもできます。 'setup' は root パーティションの
ファイルシステムを作成した後にセットアップを提案します。

インストーラには、いくつかの分割アプリケーションが含まれています: cfdisk, fdisk, sfdisk,
cgdisk, gdisk, sgdisk, parted. 名前の「g」を持つアプリケーションは、
gptのみを扱うことができ、parttedはDOSパーティションテーブルとGPTを扱うことができます。 fdisk
の cfdisk と sfdisk は DOS パーティションテーブルを扱うことができます。 加えて、 wipefs
(以前のパーティションテーブルとファイルシステム署名を消去するため) と partprobe
(パーティションテーブルの変更をカーネルに通知するため) が利用可能です。
lsblkアプリケーションには、ブロックデバイスとパーティションに関する情報が表示されます。

パーティションを自分でフォーマットすることも、インストーラに任せることもできます。 ここで
'フォーマット' を意味します: パーティション内のファイルを管理するファイルシステムを作成します。 Bear in
mind that the ESP should have a vfat file system, a Bios Boot partition no file
system at all. Linuxパーティションの場合、Slintインストーラはこれらのファイル
システムタイプを扱うことができます: btrfs、ext2、ext4、f2fs、jfs、reiserfs、xfs。

インストーラは、Slint からのアクセスを許可するために、
Windows と共有または使用されているパーティションのマウントポイントを設定できます。 これらは、
vfat、msdos、ntfsのいずれかの種類のファイルシステムを持つ必要があります。Windowsによって設定されるか、設定を実行する前に作成されます。

===== セットアッププログラムによって管理されるアクション。

セットアッププログラムには、次の項目またはステップが含まれるメニューが表示されます。
....
キーボードを再マッピングするためのKEYMAP(オプション)
ADDSWAPからスワップパーティション(複数可) (オプション)
ターゲットパーティションをセットアップするためのターゲット
ソフトウェアパッケージを含むソースメディアを選択するための SOURCE
ソフトウェアパッケージをインストールするための
Slint システムを構成するための構成。
....

これらのエントリは以下にコメントされています。 TARGET、SOURCE、INSTALLおよびCONFIGURE
ステップは必須であり、この順序で行う必要があります。

* KEYMAPは最初に選択したキーボードマップを変更するために使用することができます。
* ADDSWAP を使用してスワップパーティションを設定できます。 代わりに、インストール後にスワップファイルを設定したり、zramでスワップ領域を設定したりすることができます。
* TARGET ステップでは、インストーラは最初に root (/) ディレクトリをホストする Linux パーティションを尋ねます。 ファイルシステムをインストールするかどうかを尋ねます まだ完了していない場合は、パッケージをインストールするスペースがないため、インストール手順で ELSE インストールが失敗することに同意する必要があります(SHOULD)。 次に、提案されたファイルシステムを選択します。
+
インストーラは、他のLinuxパーティションを一覧表示します。 そして、
でマウントポイントとファイルシステムを Slint で使用したい場合、それぞれに設定します。
* SOURCE ステップでは、インストールするソフトウェア パッケージを含むメディアを選択します。 これはおそらくインストーラを含むものになります。
* INSTALL ステップでは、インストールメディアに含まれるすべてのパッケージがインストールされています。ただし、don't で設定されている場合は、KDE パッケージがインストールされています。
* CONFIGURE ステップで、インストーラは新しいシステムを好みに合わせて構成する。 これには以下の設定またはオプションが含まれます:
+
** レスキューUSBブートスティックを作成します。
** GRUBブートマネージャと関連するOSローダーをインストールして設定します。
** コンソールでマウスを使用するか、wetherを選択します。
** ネットワークの設定
** 起動時に開始するサービスを決定します。
** ハードウェアクロックがUTCを使用するか、ローカルタイムを使用するか、タイムゾーンを設定するかを選択します。
** ログインマネージャー:コンソールモードまたはグラフィカルを選択します。
** デフォルトのグラフィカル セッションを選択します。
** インストールされているシステムでデフォルトの言語と地域のバリエーションを設定します。 選択した言語に固有のパッケージがインストールされます。

完了しました。インストールメディアを削除し、Slintを起動するために再起動します。

[[Slint_in_an_encrypted_drive]]
==== 暗号化されたドライブに突っ込みます。

Auto モードでは、インストーラはSlint に捧げる場合、
Scint をインストールするドライブを暗号化することを提案します。 If you agree, at each boot the GRUB boot loader will ask you the passphrase
that you will have typed during installation to unlock the drive, before
displaying the boot menu. Be aware that unlocking the drive will take a few
seconds (about ten seconds).

暗号化されたドライブを持つことは、マシンの
損失または盗難の場合に含まれるデータの盗難を防ぎます。 リムーバブルドライブのようなものです しかし、これは'コンピュータが動作し続け、無人の場合、
マシンが完全にオフになっている場合にのみ、あなたを保護します！

インストール中にSlintシステムパーティションが暗号化され、
追加パーティションが必要になります。

Slint システム(または root)パーティションは、暗号化されている場合、/dev/mapper/cryproot という名前になります。


これは次のコマンドで表示されます。

----
lsblk -lpo name,fstype,mountpoint | grep /$
----

これは以下のようなアウトプットを与えます:
----
/dev/mapper/cryptroot ext4 /
----

代わりにこのコマンド:

----
lsblk -lpo name,fstype,mountpoint | grep /dev/sda3
----

gives:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 は、いわゆる「LUKS ヘッダー」を含む "raw" パーティションになりました。
直接アクセスする必要もありません。  It hosts all that is
needed to encrypt or decrypt the partition /dev/mapper/cryptroot, which
actually hosts your data (in this example the Slint system).

[WARNING]
====
パスフレーズを忘れた場合、ドライブ内のすべてのデータは回復不能に失われます!
だから、このパスフレーズを書き留めるか、記録し、完了したらすぐに
安全な場所に記録してください。

ドライブは死にます。 それが起こり、それが暗号化された場合、データは失われます。
したがって、重要なデータを定期的にバックアップすることは任意ではありません。

また、復元できるルークヘッダをバックアップすると、何らかの理由でルークパーティションが
破損します。 コマンドは
の例にあります:
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
ここで <file> はバックアップファイルの名前で、安全な場所に保存します。

次に、バックアップを復元する必要があります。
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Don't 暗号化されたドライブのパーティションのサイズを変更します。その後は
確実にロックされ、含まれるすべてのデータが失われます！ 本当に多くのスペースが必要な場合は、
保存したいすべてのファイルをバックアップする必要があります。 再インストールしてバックアップされたファイルを復元します。

強力なパスフレーズを選択してください。強盗が
価値があることを発見するには時間がかかりすぎるでしょう。

Never ever fiddle with the so-called "LUKS header" located on the raw partition
(the third one, like e.g. /dev/sda3 for the raw partition on top of the Slint
system partition).  Practically: don't create a file system in this partition,
don't make it part of a RAID array and generally don't write to it: all data
would be irrecoverably lost!
====

弱いパスフレーズを避けるために、インストーラはパスフレーズを次のようにする必要があります:

. 少なくとも 8 文字以上。
. 大文字と大文字、0 から 9 までの数字、空白、句読点以降の文字のみ:
+
----
 ' ! " # $ %  & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
これは、新しいキーボードでさえ
パスフレーズを入力するのに必要なすべての文字を持つことを保証します。

. 少なくとも1つの数字、1つの小文字、1つの大文字、および1つの句読点文字です。

GRUBは、パスフレーズを入力するときに「私たち」キーボードが使用されていると仮定しています。
For this reason, if during installation you use an other keyboard map, before
asking the passphrase the installer will set the keyboard map to "us", and
after having recorded it restore the previously used one. In this case the
installer will also spell each typed character of the passphrase, as it may
differ from the one written on the key.


アプリケーションcryptsetupはドライブを暗号化するために使用されます。 インストール後に
より多くのタイプを知るには: +
-----
man cryptsetup
-----
さらに詳しく知るには: https://gitlab.com/cryptsetup/cryptsetup/-/wikis/FrequentlyAskedQuestions[この FAQ].

[[first_steps_after_installation]]
==== インストール後の最初のステップ

インストール後に最初に実行するタスクは次のとおりです

このドキュメントでは、# 文字以降のすべてのテキストは、提案された
コマンドのコメントであり、入力してはいけません。

===== 初期ソフトウェアの更新

インストール後、各ソフトウェアの最新バージョン
を取得するためにシステムを更新する必要があります。
ISOの
リリース以降に提供される新しいソフトウェアと同様に。 This is especially necessary if no network connection was
available during installation, as then only the packages included in the
distribution media were installed, and they could be outdated.

Most commands typed below request administrative right associated to a
specific account named 'root', for which you have recorded a a password
during installation.

コマンドを「root」として発行するには、最初に入力してください
----
su -
----
そして、root用のパスワードを発行し、コマンドを入力する前にEnterを押します。

これは他のディストリビューションで使われる「須藤」に置き換えられます。

「root」としてコマンドを発行したら、Ctrl+dまたは「exit」と入力し、
「通常のユーザー」ステータスを取り戻します。

更新するには、コンソールまたはグラフィカル端子にrootとして入力します。
----
slapt-get --add-keys # パッケージを認証するためのキーを取得する
slapt-get -u # ミラー内のパッケージのリストを更新する
slapt-get --install-set slint # 新しいパッケージを取得する
slapt-get --upgrade # インストールされたパッケージの新しいバージョンを取得する
dotnew # 設定ファイルの変更をリストする
----
dotnewを実行する場合は、すべての古い設定ファイルを新しいファイルに置き換えることを受け入れます。
これはまだカスタマイズを行っていないので安全です。'

あるいは、これらのグラフィカルなフロントエンドを使用することもできます。gslapt-get の代わりに
、dotnew-gtk です。

slapt-get の詳細については、次のように入力します。
----
man slapt-get
----
またはルートとして:
----
slapt-get --help
----
そして /usr/doc/slapt-get*/README.slaptgetrc.Slint

===== 設定

以下は、
インストール後にSlintシステムを(再)設定するために使用できるユーティリティです。 They are presented in further details in chapter <<Manage_your_system, システムの管理>>.

特に指摘しない限り、これらのユーティリティは root として使用する必要があります。 ルートになるには、
すなわち、「admin」ステータスと権限を取得し、「su-」と入力し、root's password。
通常のユーザーの状態を取得するには、Ctrl+dまたはexitと入力します。

ほとんどのユーティリティにはコマンドラインとグラフィカルなバージョンがあります。 コマンドライン
のバージョンは下記の最初にリストされています。 別段の記載がない限り、すべてのコマンドは
型を root とする必要があります。

*一般設定*

* ユーザーを管理するには: usersetup または gtkuserset
* 言語とリージョンを変更するには: localesetup または gtklocalesetup
* キーボードのセットアップと入力方法を変更するには: keyboardsetup or gtkkeyboardsetup
* 日付、時刻、またはタイムゾーンを設定するには: clocksetup と gtkclocksetup を実行します。
* 起動時に開始するサービスを選択するには: servicesetup と gtkservicesetup
* (再)ネットワークを設定します。
* テキストモードまたはグラフィカルモードで開始するかを選択するには、後の場合はグラフィカルなログインマネージャー:login-chooser
* デスクトップまたはグラフィカル セッションを選択するには: セッションセレクター（通常のユーザーとして）
* 他のデスクトップ's メニューでそのアプリケーションを表示または非表示にするために KDE がインストールされている場合: show-kde-apps または hide-kde-apps

*ユーザー補助の設定*

コンソールスクリーンリーダーを選択して有効にするか、すべての root として入力を無効にするには:
----
speak-with
----

Slint バージョン 14.2 から。 インストール中に最初に作成された正規ユーザーはスピーチと点字がすでにインストールされたシステムで有効になります スピーチを使って点字を要求されたら 他のユーザーは、以下に示すように、設定を確認または追加する必要があります。

点字を有効にするには:

. /etc/rc.d/rc.brltty 実行形式の型を root として指定します。
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. 点字グループのメンバーになり、rootと入力します。
+
----
usermod -G 点字のユーザー名
----
+
上記のコマンドで、ユーザー名をログイン名に置き換えます。
. 次に、root ファイルとして /etc/brltty.conf を編集し、設定を含めます。

システムレベルで root として音声を有効にするには、次のようにします。
----
ログイン選択
----
ログインモードのいずれかを選択します。テキスト、lighdm、gdmのいずれかです。

通常のユーザタイプとしてグラフィカル環境で音声を有効にするには、次のようにします。
----
Orca-on
----
その後、次回グラフィカルな
環境を起動したときにOrcaスクリーンリーダーが話し始めます。

代わりにグラフィカル環境で音声を無効にするには:
----
Orca-off
----

==  Slint の使用状況

この章では、Slint システムとやり取りする方法を紹介します。
あなたが望むことを行います。

=== Slint システムとは何ですか?

Slint は、大体これらのカテゴリに分類される一連のソフトウェアです。

* Linux <<kernel, カーネル>> と <<utilities, ユーティリティ>> で作られたオペレーティングシステム。 これは、ユーザー、アプリケーション、およびハードウェア間のインターフェイスとして機能します
* ユーザーが達成したいタスクを実行する <<Applications, アプリケーション>>。

画面の外観とシステムとの対話方法によって区別される2つのモードで使用できます


* テキストモードでは、 <<shell, シェル>>によって解釈されるコマンドを入力します。 これらのコマンドは、ユーティリティまたはアプリケーションを起動できます。 テキストモードは <<console, コンソール>> モードとも呼ばれます。 このモードでは、画面はコマンドと出力を背景にのみ表示します。
* グラフィカルモードでは、ウィンドウなどのグラフィカル要素は、パネルやアイコンが画面に表示され、一般にアプリケーションやユーティリティに関連付けられています。 ユーザーは、マウスまたはキーボードを使用してこれらの要素と相互作用します。

コマンドは、シェルを実行する
 <<terminal, ターミナル>> に関連付けられたウィンドウ内でグラフィカルモードで入力することもできます。

=== Slint の開始方法

インストール時に、インストールISOに出荷されるか、リモートリポジトリから
ダウンロードしたソフトウェアは、 <<drive, ドライブ>>にインストールされます。

Slint を起動する時 <<firmware, ファームウェア>> は、最初にハードウェアをチェックし、
が起動するOSローダー(一般的にブートローダーと呼ばれる)というプログラムを探します。
。

マシンにはいくつかのOSローダーがあります。 この場合、
ファームウェアは、ユーザーがメニューで開始するものを選択することができます。

In Slint the
software that makes and install a boot loader is GRUB.Actually the boot loader
built by GRUB is also a boot manager, as it allows to choose which OS to start if
several are installed.

The OS loader built by GRUB can be installed in a boot
sector (in case of Legacy booting) or in an EFI System Partition or ESP (in
case of EFI booting).

Slint ローダーの目的はSlint システムを始動することである。 To do that it first loads in
RAM the <<kernel, kernel>>, then the <<initrd, initrd>>, which in turn
initializes the Slint system.

この初期化の最後のステップでは、ユーザーが "ログイン" に招待されています
つまり、システムに自分自身を接続し、それに手を取ることです。 To do
that user first type one's user (or login) name then password, which
validity. Slint as other Linux distributions being multi-users this
allows this user to access one's files but not those of other users.

インストール時に、テキストモードまたはグラフィカルモードでSlintを開始することを選択しました。

* システムの初期化後、 <<console, コンソール>> で C を選択した場合は、ユーザー名(またはログイン)を入力し、パスワードを入力します。 Enterキーを押すことを確認されている各入力は、コマンドを入力することができます。
* If you chose G (graphical) you type the same information in a <<display_manager, display manager>> or login manager, which then starts the <<graphical_environment, graphical environment>>.

After installation, you can change the mode typing as root `login-chooser`,
in console mode as well as in graphical mode (in a <<terminal, terminal>>). この
コマンドを使用すると、 `テキスト` (コンソールモードの同義語)、または
グラフィカルモードの場合は、複数の表示マネージャーの中から選択できます。 あなたの選択は、コンピュータの次の起動時に
有効になります。

ここでは、グラフィカルな環境、そしてシェルの使用方法を紹介します。

=== グラフィカル環境

<<the_windows, The windows>> +
<<the_work_spaces, The work spaces>> +
<<the_desktop, The desktop>> +
<<the_top_panel, The top panel>> +
<<the_bottom_panel, The bottom panel>> +
<<the_slint_control_center, The Slint Control Center>> +
<<graphical_terminals, Graphical terminals>> +
<<key_bindings, Key bindings>>

フル機能のグラフィカル環境にはいくつかのコンポーネントが含まれています。 その中でウィンドウマネージャーは画面上にウィンドウを描画します アプリケーションに関連付けられたウィンドウを移動し、サイズを変更し、ウィンドウを閉じます

Slintは、BlackBox、Fluxbox、KDE、LXDE、MATE、TWM、XFCE、WindowMakerといったいくつかのグラフィカル環境を含めることができます。 どちらを選ぶかは好みの問題です。

KDE、LXDE MATE、XFCEはフル機能のデスクトップです。 他のウィンドウマネージャは主に
ウィンドウマネージャですが、それらはアプリケーションメニューのあるパネルを含みます。 全ては、一般的にウィンドウで開かれているドキュメントとアプリケーションに
アクセスすることができます。パネルとメニューが含まれます。

デフォルトのグラフィカル環境は、通常のユーザ `session-chooser` として入力を変更できます。 グラフィカルモードではログイン時に選択することもできます。

ここでは、デフォルトであるMateデスクトップの構成要素を簡単に説明し、音声と点字で最もアクセスしやすいものにします。 他のフル機能のデスクトップにも同様の機能があります。

マウスを使用して、右、中、または左クリックをシミュレートする各コンポーネントの特徴を発見することができます。 コンポーネントのほとんどを移動または削除し、それらを変更し、新しいものを追加することは同じ方法で行うことができます。

これらのコンポーネントは、マウスの移動やキーボードショートカットを介しても達成できます。 括弧内では、キーボードショートカットを指定します。つまり、各要素にフォーカスを置きます。 また、Mateデスクトップ用の <<key_bindings, キーバインド>> とCompizウィンドウマネージャ用のキーバインド(デフォルトのマルコウィンドウマネージャを使用)についても要約します。

[TIP]
====
マウスの右クリック、中クリック、または左クリックでSlintのアプリケーションやその他のコンポーネントの機能のほとんどを見ることができます。  たとえば、パネル、タイトルバー、任意のウィンドウの左と右のボタンをクリックすることによって例えば、 パネルのアイコンや、画面の空きスペースにアイコンが表示されます。
====
[[the_windows]]
==== 窓

ウィンドウは、アプリケーションに関連付けられた矩形領域です。 Windowsは、マウスまたはキーボードショートカットを使用して移動、サイズ変更、最大化、復元された縮小、閉じる(処理するアプリケーションを終了する)ことができます。

[[the_work_spaces]]
==== 作業スペース

多くの窓を整然と開けるようにするために、グラフィカル環境は複数の作業スペースを提供し、それらを切り替えることができます。 各作業スペースには同じデスクトップとパネルが表示されますが、ウィンドウは特定の作業スペースまたはそれらすべてに配置できます。 この設定は、ウィンドウの上端に右クリックで使用できます。 別のワークスペースに切り替えることは、画面の下部パネル上のその位置をクリックすることができます。 以下に示すように、作業スペースチェンジャーに表示されます。

[[the_desktop]]
==== デスクトップ

デスクトップは画面全体を含み、その上に他のコンポーネントを置くことができます。 Mateの場合とSlintで出荷されるように、トップとボトムパネル。 上から下までの4つのアイコンがウィンドウで開くことができます

* ファイルマネージャーのルートディレクトリ
* ファイルマネージャーのホームディレクトリ
* その Slint Control Center
* ゴミ箱は、削除しようとしているが、まだ削除しなかった場所'tのファイルを置くことができます。

アプリケーションのWindowsは、デスクトップにも置くように起動します。

Mateには2つのパネルが含まれています, これは、スリムな長方形の水平領域として自分自身を提示します, 上部に1つ、画面の下部に1.

Ctrl+Alt+Tabキーを押すと、デスクトップ、上部、下部のパネルを切り替えることができます。

Alt+Tabキーを押すと、デスクトップ上のウィンドウを切り替えることができます。

[[the_top_panel]]
==== トップパネル

左から右へと提示されます

* 3つのメニュー:
** Alt+F1 キーを押して開くことができるアプリケーション メニュー。 そこから、右矢印キーを使用して他のメニューを開くことができます。 矢印キーを使用して、他のメニューに移動できます。
** Placesメニュー。
** システムメニューは、プリファレンスサブメニュー、Mateコントロールセンター、およびデスクトップに関するヘルプを取得するためのボタンへのアクセスを提供します。 画面をロックしてセッションを閉じて、コンピュータをシャットダウンします。
* mate-terminal、ファイルマネージャcaja、電子メールクライアントthunderbird、Webブラウザのfirefox、テキストエディタGeanyのためのアプリケーションの起動。
* Bluetoothマネージャー、サウンドミキサー、ネットワークマネージャ、および「更新可能な」通知などのアプレットを収集することができる通知。
* 時計とカレンダー。
* スクリーンロッカー。
* セッション終了ダイアログ
* シャットダウンダイアログ

[TIP]
====
* 好みに合わせてパネルをカスタマイズするには: パネルの空き領域を右クリックします。
* パネル上のアイテムを移動したい場合: 要素を中クリックします。 マウスをドラッグすると中央ボタンが離されるまでマウスに従います
* 文脈依存のヘルプを表示するには F1 を押します。
====

[[the_bottom_panel]]
==== 下部パネル

左から右に表示されます。

* 最初に垂直方向の3つの点の線を右クリックして設定し、好みを選択することができるウィンドウリスト。 これにより、システムモニタをウィンドウで起動することもできます。
* *デスクトップ* ボタンを表示します。 左側にあるすべてのウィンドウを最小化または非表示にします。もう一度クリックすると以前の状態のウィンドウが復元されます。
* ワークスペーススイッチャー、またはページャー。 作業領域から別の領域に切り替えたり、作業領域から別の領域にドラッグ&ドロップでウィンドウを移動したりすることができます。

ウィンドウマネージャはSlint で変更なしで使用できるように設定されています。 しかし、好みに合わせて再設定することができます。 そうする方法はウィンドウマネージャによって異なります。 詳細については、次を参照してください: http://docs.slackware.com/en:user_settings[ユーザー設定].

[[the_slint_control_center]]
====  Slint Control Center

Slint's の使用法については、Slint Control Center をご紹介します。 トップパネルのアプリケーションメニューから表示するか、デスクトップのアイコンをクリックするか、Alt+F2 で起動される "Run..." ダイアログで qcontrolcenter と入力できます。

制御パネルの目的は、システム管理に有用なアプリケーションを集めることです。 すべてのウィンドウマネージャで一貫した方法でドキュメントや設定を行うことができます  左メニューのカテゴリをクリックすると、右ペインに該当するアプリケーションを表示できます。  それらを表形式で提示します。  これにより、グラフィカルユーザーインターフェイスを持つ管理ツールを紹介する機会が得られます。

ほとんどの管理ツールは、管理者権限で使用する必要があります。  ツールを起動するには、rootアカウントのパスワードを尋ねられます。

[options="autowidth"]
|====
<|**カテゴリ** <|**ツール** <|**目的とコメント**
<|アプリケーション <|Dotnew <|This tool allows you to manage the new (named __something.new__ hence the name of the tool) vs old configuration files after having upgraded some packages.  それは'アップグレード後に実行する良い習慣です。  それはあなたの世話をし、あなたに行動の選択肢を提示する何かがあるかどうかを教えてくれます。
<|アプリケーション <|Gslaptパッケージマネージャー <|Gslaptは、スラップゲットへのグラフィカルなフロントエンドです。  Slint <<software_management, で>> ソフトウェア管理を行うのに便利なツールです。  ソフトウェアパッケージを検索、インストール、削除、アップグレード、および構成することができます。
<|アプリケーション <|Sourcery SlackBuild Manager <|Sourceryは、slapt-srcへのグラフィカルなフロントエンドです。  これにより、ビルドプロセスとソフトウェアパッケージのインストールを自動化するために使用できる SlackBuilds スクリプトを検索できます。  また、システムにパッケージを削除して再インストールすることもできます。
<|アプリケーション <|アプリケーションファインダー <|システムにインストールされているアプリケーションを見つけて起動します。  検索フィールドは、アプリケーションメニューを手動で検索するのと比較して、アプリケーションを見つけるのに非常に便利です。
<|ハードウェア <|プリンタのセットアップ <|接続されたプリンタを設定するために使用します。  これは、Scint でデフォルトで実行されている CUPS 印刷サーバーのフロントエンドです。
<|ハードウェア <|カップの印刷コントロール <|このアプリケーションを使用すると、CUPSサービスの設定、プリンタの管理、およびWebブラウザを通じて印刷ジョブの制御を行うことができます。
<|ハードウェア <|Keyboard <|このツールを使用すると、キーボードの種類を設定したり、キーマップを設定したり、SCIM サービスを有効にしたりできます。  SCIM は、キーボードにキーがない文字を入力できるようにするのに役立ちます (多くのアジア言語のように)。
<|情報 <|SlackDocs ウェブサイト <|このwiki内のドキュメントは主にSlackwareユーザ向けですが、その多くはSlintユーザにとって有用です。  *注意:*  slackpkg のようなリストされているツールのいくつかは、Slint で ** 使用しないでください。
<|情報 <|Slackware ドキュメント <|このドキュメントはSlint ユーザにとっても役に立ちます。  SlintはSlackwareをベースにしています。
<|情報 <|Slint ドキュメント <|これにより、Slint's ウェブサイトでも利用可能なドキュメントへのローカルアクセスが可能になります。
<|情報 <|Slint Forum <|母国語が英語でない人は、ローカライズされた唾液フォーラムに投稿することもできます。
<|情報 <|Slint Web サイト <|Slint Web サイトでは、ドキュメント、リンク、および ISO やパッケージを見つける方法を提供しています。
<|情報 <|システム情報 <|このツールは、接続されたデバイス(内部および外部)などのコンピュータに関する情報を収集し、すべてを1箇所に表示します。  システムベンチマーキングもできます。
<|設定 <|システム時計 <|このツールを使用すると、システムクロックを設定できます。
<|設定 <|ホスト名 <|このツールを使用すると、IPアドレスをドメイン名とホスト名に関連付けることができます。
<|設定 <|システム言語 <|このツールを使用すると、システムロケール(言語と地理的特性)を設定できます。 使用するアプリケーションは、このロケール(利用可能な場合)に情報を表示するようにします。
<|システム <|システム時計 <|このツールでタイムゾーンを設定できます。 時計をインターネットサーバーと同期させるかどうかを選択します（これは推奨されますが、もちろんインターネット接続が必要です） 日付と時刻を設定します。
<|システム <|ホスト名 <|このツールを使用すると、システムホスト名を設定できます。 Slint をサーバーとして使用する場合、ローカルエリアネットワークまたはインターネット上で使用する場合に便利です。  ホスト名は、ドメイン名システムサービスが使用されていない場合、ネットワーク化されたコンピュータが共通の名前で互いを識別するのに役立ちます。
<|システム <|アイコンキャッシュを再構築 <|このユーティリティは、システム内のすべてのアイコンを登録しているファイルであるアイコンキャッシュを再構築し、高速アクセスを可能にします。 新しいアイコンがシステムにインストールされたときに実行します。
<|システム <|システムサービス <|このツールを使用すると、起動時にどのサービスを有効にするかを選択できます。  例えば、Bluetooth、CUPS印刷サーバー、またはWebサーバー。  何をしているか分かっている場合にのみ、デフォルトの設定を変更するために使用してください。
<|システム <|ユーザーとグループ <|このツールを使用すると、ユーザーアカウントとグループを追加、削除、設定できます。 これは、主にマルチユーザーシステムで便利です。
<|システム <|GUEFI Boot Manager <|このツールはefibootmanagerコマンドのグラフィカルなフロントエンドです。  EFI ファームウェアの's ブートメニューを編集できます。  メニュー項目の順序の追加、削除、変更などのアクション。
<|システム <|MATEシステムモニター<|このツールは、プロセス、リソース使用量(RAM、CPU、ネットワークトラフィック)やファイルシステム使用量などのシステムに関する情報を表示します。
|====

[[graphical_terminals]]
==== ターミナル


ウィンドウを開くと、コンソールモードと同様にグラフィカルモードでコマンドを入力できます。 Mateでは、Ctrl+Alt+tキーを押すか、上部パネルのメイトターミナルアイコンで
をクリックします。 または "Run char@@0... " ダイアログを開き、
Alt+F2 を押し、開いた小さなウィンドウで `mate-terminal` と入力します。

コマンドラインとコンソール
モードのシェルに関する以下の情報のほとんどは、ターミナルでコマンドを入力する際にも適用されます。 他のウィンドウと同様に、mate-terminal
を閉じることができます。

[[key_bindings]]
==== キー割り当て

ここでは、Compiz ウインドウマネージャとMateデスクトップ用のデフォルトのキーバインディングと、それらをカスタマイズする方法を紹介します。

[NOTE]
====
When a key binding includes one or more **+** sign, press then hold from left to right the keys before the last one like a `Shift` key, then press the last key.
====
===== Mateデスクトップのキーバインド

SlintでMateを使用する場合、いくつかのキーバインディングは、
マルコまたはCompizウィンドウマネージャのいずれかを使用して同じです。 以下に示す。
----
Alt+Tab ウィンドウ間のサイクル
Shift+Alt+Tab ウィンドウ間の逆方向
Control+Alt+Tab パネルとデスクトップ間のサイクル
Shift+Control+Alt+Tab パネルとデスクトップ間のサイクル
----
グラフィカルな環境では、コンソールと
コンソールを切り替えることができます。 Let's say you want to use tty2 (tty1 being busy):
Press `Ctrl+Alt+F2`, then login. +
Press `Ctrl+Alt+F7` to go back to the graphical environment.

同じ一般的なキーバインディングはすべてのグラフィカルな環境で使用されます。
いくつかの例外がありますが、Mod1は一般的に左のAltキーです。 +
----
Mod1+F1 がパネルのアプリケーションメニューを上げます。
Mod1+F2 は「run...」ダイアログを発生させますが、Fluxbox (代わりに lxterminal を起動します)。
----
Fluxboxでも：
----
Mod1+F3 restarts Fluxbox.
Mod1+F4はフォーカスされたウィンドウを閉じます。
----
パネル's アプリケーション メニューは、出荷されているすべてのアクセス可能な
グラフィカル環境で同じレイアウトを持っていますが、MATE。 上から下へ:

Terminal emulator: `mate-terminal` in MATE, elsewhere `lxterminal` by default +
File manager: `Caja` in MATE elsewhere `PCManfm` by default +
Web browser: `Firefox` by default +
Mail client: `Thunderbird` by default +
Preferences +
Slint Dashboard (non accessible yet as it's a Qt4 app) +
Applications sorted by category +
Run dialog +
Logout dialog (also allows shut down and reboot)

矢印キーを使用して、メニュー内を移動できます。

MATEでは、上部パネルは左から右に含まれています。

the menus (Applications, then Places, then System) +
launchers for mate-terminal, Caja (file manager), Firefox, Thunderbird and the Geany
text editor. +
On its right still from left to right:
a notification area +
a screen locker button +
a logout button +
a halt or reboot buttons.

下部のパネルは左から右へ:

windows list +
a "show destktop" plugin +
a workspace switcher.

まだMateでは、部分的に晴眼者のユーザーはデフォルトである
またはmarcoの代わりにcompizウィンドウを使用することができます。

通常のユーザとして、次のようにタイプします:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
マルコに戻るには:
----
gsettings set org.mate.session.required-components windowmanager marco
----
この設定は、Mateセッションの次の開始時に有効になります。

または、現在のセッションタイプの変更を行います。
----
compiz --replace &
----
マルコに戻りましょう
----
marco --replace &
----
交換はすぐに有効になります

この設定は、
Windowsカテゴリのmate-tweakからもグラフィカルに使用できます。

入力するだけで特定のCompiz設定にアクセスできます：
----
ccsm &
----
===== Compiz ウィンドウマネージャのキー割り当て

In the default settings indicated below the key or mouse buttons are
named like this:

Super: Windows key on most keyboards +
Button1: Left Mouse Button (if used with the right hand) +
Button2: Centre Mouse Button, or click with the scroll wheel) +
Button3: Right Mouse Button (if used with the right hand) +
Button4: Scroll Wheel Up +
Button5: Scroll Wheel Down
Button6: (I don't know, I thought that was on mouses for gamers) +

The default settings listed below by category can be changed from the
CCSM. We indicate the short name of the plugin between square brackets.

. Category General
+
[core] General options, tab "key bindings": +
close_window_key = Alt+F4 +
raise_window_button = Control+Button6 +
lower_window_button = Alt+Button6 +
minimize_window_key = Alt+F9 +
maximize_window_key = Alt+F10 +
unmaximize_window_key = Alt+F5 +
window_menu_key = Alt+space +
window_menu_button = Alt+Button3 +
show_desktop_key = Control+Alt+d +
toggle_window_shaded_key = Control+Alt+s +
+
[matecompat] Mate Compatibility +
main_menu_key = Alt+F1 +
run_key = Alt+F2 +

. Category Accessibility
+
[addhelper] Dim inactive (less light on non focused windows) +
toggle_key = Super+p +
+
[colorfilter] (Filter color for accessibility purposes) +
toggle_window_key = Super+Alt+f +
toggle_screen_key = Super+Alt+d +
switch_filter_key = Super+Alt+s +
+
[ezoom] Enhanced Zoom Desktop +
zoom_in_button = Super+Button4 +
zoom_out_button = Super+Button5 +
zoom_box_button = Super+Button2 (zoom out to go back to normal) +
+
[neg] Negative (toggle inverse colors of the window or screen) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Opacity, Brightness and Saturation adjustments +
opacity_increase_button = Alt+Button4 +
opacity_decrease_button = Alt+Button5 +
+
[showmouse] (Increase visibility of the mouse pointer) +
initiate = Super+k +

. Category Window Management
+
[move] Move window +
initiate_button = Alt+Button1 (hold Button1 while moving the mouse) +
initiate_key = Alt+F7 (Esc to stop moving) +
+
[resize] Resize window +
initiate_button = Alt+Button 2 (hold Button2 while moving the mouse) +
initiate_key = Alt+F8 (Esc to stop moving) +
+
[switcher] Application switcher (switch between windows or panels and
                                 the desktop) +
next_window_key = Alt+Tab (cycle between windows) +
prev_window_key = Shift+Alt+Tab +
next_panel_key = Control+Alt+Tab (cycle between panels and desktop) +
prev_panel_key = Shift+Control+Alt+Tab +


===== メイト用のカスタムキーバインディングを追加する方法

Let's take an example: we want that Alt+F3 starts firefox.
ターミナルまたは実行コマンドで入力します(Alt+F2キーを押します):
----
mate-keybinding-properties
----
新しいウィンドウでは、下矢印キーと上矢印キーを押して
既存のキーバインディングのリストをナビゲートすることができます。

新しいキーバインドを設定するには、
キーを2回押してカーソルを追加し、format@@1キーを押します。 In the small dialog box brought up  type the name of the
custom key binding, like firefox, press Tab, type the name to the
associated command, in this case firefox, then press Tab twice to
put the cursor on Apply and press Enter.

新しいキーバインディングを有効にするには、リストの
下部にあるキーを見つけるまで移動します。Alt+F3キーを押します。

次回はAlt+F3でFirefoxを起動します。

=== シェル

NOTE: この章は簡単な紹介です。 詳細情報については、ドキュメント https://slint.fr/doc/shell_and_bash_scripts.html[シェルスクリプトと bash スクリプト]で提供されています。

コンピュータがコンソールモードで起動すると、ユーザー名とパスワードを入力してログインした後。 <<shell, シェル>> は、以下のような "プロンプト" を表示します: +
`didier@darkstar:~$` +
 例:

* `didier` はユーザー名です
* `ダークスター` のマシン名
* チルダ `~` はユーザのホームディレクトリを表します。この例では `/home/didier`
* ドル記号 `$` はユーザが「スーパーユーザ」ではなく「通常のユーザ」であることを示します(下記参照)。

カーソルがプロンプトの後に配置されます。

ユーザーは行にコマンドを入力することができます (したがって、名前は「コマンドライン」)、それをEnterキーを押して確認します。 シェル then analyzes the command and execute it if valid, else output a message like for instance "command not found". コマンドは、左右の矢印と Backspace、Home、End、Delキーを使用して、Enterキーを押す前に編集できます。

実行中に、コマンドは画面に出力を表示するかどうかを表示できます。 すべての場合、その実行後、プロンプトは再び新しい行に表示されます。 つまりシェルは次のコマンドが入力されるのを待っています

これが機能するためには、利用可能なコマンドと構文をユーザが知る必要があります。 いくつかのコマンドは、シェル自身によって実行されます。他のコマンドは、外部プログラムを起動します。 コマンドのいくつかの例を以下に示します。 https://slint.fr/doc/shell_and_bash_scripts.html[Shell と bash スクリプト]

Linuxで選択できるシェルはいくつかあります。Slint では、デフォルトで使用されるシェルの名前は *bash* です。

同時に複数のプログラムを実行できるようにするために、Linuxは、同じキーボードとスクリーンを共有し、1つから番号を付けるいくつかの「仮想コンソール」を提供します。 最初は、システムはコンソール(または仮想端末)の1番目で始まります。 *tty1* (tty は「telype」の略語です)。 そこから、ユーザーは別のコンソールまたは tty に切り替えることができます。 例えば、Alt+F2 キーを押して tty 番号に切り替えます。ここで、別のシェルはユーザー's のユーザー名とパスワードを再度尋ねます。 tty1 に切り替えるには、Alt+F1 を押します。 デフォルトでは Sclint 6 の tty が利用可能ですが、/etc/inittab というファイルを編集して変更することができます。

シェルがグラフィカルな環境(グラフィカル端子内)で使用されている場合、シェルは同じように動作しますが、プロンプトは若干異なります。 以下の図のように: +
`didier[~]$` +

コンソールとグラフィカル環境を切り替えることができます。

* 例えば、グラフィカル環境から tty3 に移動するには、Ctrl+Alt+F1 キーを押します。 最初に tty に行くときは、ログインとパスワードを入力する必要があります。
* グラフィック環境がすでに実行されている場合は、コンソールからAlt+F7キーを押すか、それ以外の場合は `startx` と入力して起動します。

==== コマンドをルートとして入力

*root* は、管理タスクを行うすべての権利を持つ「スーパーユーザ」の従来の名前です。 システムを傷つけたり破壊したりするものも含めてね

ルートとして直接ログインすることができます(初心者には推奨されません)。 このタイプ *root* をユーザーとして実行するには、root's password。
お客様に通知する(および関連するリスクと責任について警告する) プロンプトは次のようになります: +
*root@darkstar:s~#* +
文字 # (数の記号, (一般的に名前が付けられたハッシュも) root としてコマンドが入力されることを示しています (通常のユーザーとしてではなく) リスクや責任もあります

あなたがすでに通常のユーザーとしてログインしている場合は、"root" と入力することができます: +
*su -* +
そしてEnterを押します。 In this command, `su` (which stands for "Super User") is the name of the command, and the character *-* (hyphen-minus, also named minus) tells that you are opening a "login shell": you will first be asked root's password, then be directed to its home directory /home/root as if you had logged in as root at startup. これは、後で問題を引き起こす通常のユーザー (/home/didier) として、不注意にホームディレクトリにファイルを書き込むことを避けます。

=== ブロックする問題を解決する方法

「問題をブロックする」とは、以下のような「Slintを使用しない問題」を意味します。

* システムが起動できません。
* システムは起動しますが、起動シーケンスは完了前に中断されます。 This can happen for instance if the root system partition can't be mounted because of an error in /etc/fstab, a corrupted root file system or a missing kernel module to mount the root partition, or the system boots successfully but you don't remember the password for root.

システムが完全に起動できない場合は、以下の各ソリューションを順番に試してみてください。

. カーネルのアップグレード後にこれが発生した場合は、最初のものではなく、2番目のブートエントリを試してください。
. GRUBメニューの最後のブートエントリを使用します。 それはSlintを見つけて、それを開始することができます。
. あなたがインストールの終わりに要求したレスキューブートスティックを起動してみてください。
. 以下で説明したように、それを修理するためにSlintに飛び込んでください。
. 問題の調査に役立つすべての情報を提供する slint@freelists.org にメールでお問い合わせください。 まだ完了していない場合は、最初に件名「subscribe」で slint-request@freelists.org のメールを購読し、受け取るメールに答えてください。 電子メールを使用して問題がある場合にのみ、IRCチャンネル #slint、サーバー irc.libera.chat でヘルプを要求し、誰かが答えるまでチャネルに滞在します。

起動シーケンスが中断された場合は、インストーラから Slint にジャンプして問題を解決しようとします。 インストールメディア(インストールISOを書いたUSBスティックまたはDVD)を挿入またはプラグインし、以下の手順に従ってください。

. インストーラーを起動します。
. root としてログインするとすぐに、ドライブとパーティションを一覧表示するには、次のように入力します。
+
----
lsblk -lpo name,size,fstype
----
. 出力でSlint root パーティションの名前を検索し、サイズとファイルシステムタイプをチェックし、FSTYPE というラベルを付けます。
. このパーティションをマウントし、それが良いものであることを確認してください。 例えば、/dev/sda3 の場合は次のように入力します。
+
----
mount /dev/sda3 /mnt
cat /mnt/etc/slint-version
----
+
[NOTE]
====
Slint rootパーティションのファイルシステムが破損しているように見える場合は、don't はまだマウントしていますが、このコマンドを実行して修復してみてください:
----
fsck <name of the root partition>
----
これが成功した場合は再起動します。
====
+
Slint64-14.21 をインストールしたと仮定すると、出力は次のようになります。
+
*Slint 14.2.1*
+
出力が "ファイルが見つからない" 場合、パーティションはあなたが探していたものではありません。 この場合のみ、次のように入力します:
+
----
umount /mnt
----
+
ドライブとパーティションのリストに戻って別のものを試してください
+
そうでない場合は、Spint システムに /dev, /proc と /sys をマウントします。
+
----
mount -B /dev /mnt/dev
mount -B /proc /mnt/proc
mount -B /dev /mnt/sys
----
+
Slint を「ジャンプ」する次のコマンドを発行します。
+
----
chroot /mnt
----
+
chroot は「(システムの)ルートを変更」を意味します。インストーラにはもう存在しませんが、今は Slint 自体にあります。 そこからシステムを変更して問題を解決することができます。 以下にいくつかの例を示します。

* "update-grub" を実行します。

* "grub-emu" を実行します。

* GRUBを「grub-install drivename」コマンドを使用して再インストールします。drivenameはSlintをインストールするドライブです。 その前に、EFIモードで起動する場合は、最初に「mount /boot/efi」と入力します。

* root のパスワードを変更するには、「passwd」と入力します。

* パッケージを削除、インストールまたはアップグレードします。

. インストールが完了したら、インストールメディアを削除し、次に入力します:
+
----

を終了する
----

[[Accessibility]]
== Accessibility

最初のインストール時に音声を保持することを選択した場合 グラフィカルな環境の場合と同様にコンソールで起動すると
が有効になります。

=== 点字でSlint を使う

Slint には点字ディスプレイを扱うソフトウェアが含まれています。

コマンドライン以降で起動する前に行われた設定は、
/etc/brltty.conf のインストール済みシステムに記録されます。

A comprehensive manual for brltty is available in English, French and
Portuguese in several formats including plain text (txt) at this URL:
https://mielke.cc/brltty/doc/Manual-BRLTTY/

インストール中に点字が有効になっていないか、無効になっている場合は、以下の操作を行ってください。

. /etc/rc.d/rc.brltty 実行形式の型を root として指定します。
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. 点字グループのメンバーになり、rootと入力します。
+
----
usermod -G 点字のユーザー名
----
+
上記のコマンドで、ユーザー名をログイン名に置き換えます。

ルートとして点字タイプを無効にするには:
----
chmod 64 /etc/rc.d/rc.brltty
----

=== グラフィカルな環境でのスピーチを行う

Orca スクリーンリーダーを使用してグラフィカルな環境でのリマインダースピーチが有効になっています。
----
Orca-on
----

特定のキーバインディングを含む、Orcaの使い方を知るには、次のように入力します。
----
♪ManOrca ♪
----

一言で言えば、グラフィカルモードでは、以下のようになります。
----
Insert+Space:orca Preferencesダイアログを起動します。
Insert+S: ボーカルシンセサイザーを有効化または無効化します。
Insert+H: 学習モードを有効にします。 このモードでは:
   キーを押してその関数を聞きます
   F1: スクリーンリーダーのドキュメントを聞きます
   F2: Orcaのキーボードショートカットを一覧表示します
   F3: 現在のアプリケーションのキーボードを一覧表示します
   Esc: 学習モードの終了
----

=== 声とスリントのTTS。

次のTTS(テキストから音声シンセサイザー)は
Slint64-14.2.1で出荷されています。 をクリックします。それぞれに声のセットがあります。 すなわち:
 +
espeak-ng +
flite +
pico +
mbrola +
RHVoice +

Most of the time these TTS and the associated voices and languages are
managed by speech-dispatcher through its so-called "modules" (roughly,
a module is associated to a TTS).

カスタムユーティリティの spd-list は、
シンセサイザー、声、言語に関するいくつかの質問に答えることができます。 spd-list に入力すると次のようになります:
----
このスクリプトは、Orcaやスピーチアップなど、Speech Dispatcherに依存するアプリケーションで利用可能な言語とシンセサイザー
をリストします。 以下の各コマンドは、それに続く質問に答えます。
コマンドを囲む引用符を入力しないでください。
"/usr/bin/spd-list" の使用方法は?
"/usr/bin/spd-list -s" 利用可能なシンセサイザーですか?
"/usr/bin/spd-list -l" 利用可能な言語コードですか?
"/usr/bin/spd-list -ls <synthesizer>" このシンセサイザーで利用できる言語?
"/usr/bin/spd-list -sl <language code>" この言語のボイスを提供するシンセサイザーですか?
言語コードのほとんどの場合、'en' または 'fr' のような 2 文字があります。
----
リストされたすべての声は、Orcaとスピーチアップで利用可能であり、スピーチディスパッチャを使用するように設定されている場合はfenrirも使用できます。

You can get additional voices for flite and mbrola, associated with the
modules flite-generic and espeak-ng-mbrola-generic.

どちらがインストールされているか、ルートコマンドとして入力されていないかは、いつでも知ることができます。
----
slapt-get --search mbrola-voice
slapt-get -search flite-voice
----
次に、まだインストールされていないものをインストールします。例えば、
----
slapt-get -i mbrola-voice-it2
----
In addition to the free (as in free beer) voices shipped in Slint,
you can buy voices for: +
voxin, https://oralux.org/voice.php +
voxygen, sending an email to contact@hypra.fr

さらに多くの声とシンセサイザーを後で利用可能にすることができます。これは、
Slint メーリングリストとこの http://slackware.uk/slint/x86_64/slint-14.2.1/ChangeLog.txt[ChangeLog] で発表されます。

グラフィカル環境のキーボードショートカットは、 <<key_bindings, キー割り当て>> にリストされています。

=== 音声付きのログインマネージャーを使用

2つのグラフィカルなログインマネージャは、OrCAを使用してスピーチでアクセスできます: lighdmまたはgdm、後者は完全にアクセス可能として推奨されます。

gdmでは、最初はUserフィールドにフォーカスがあります。 ユーザーを入力します。 または
ログイン名を入力し、パスワードを入力します。

キーボードショートカットを使用すると、gdmの他の機能にアクセスできます。 In
English: +
Alt+A: Actions (shutdown or reboot) +
Alt+E: Session menu +
Alt+L: change the language, for the next session and possibly further
session, possibly also for gdm itself. +
Alt+T: Theme. +
You can use the Tab key to navigate among input fields, and the up and
down keys to menus.

Lightdmでは、F4を押すとサウンドのオン/オフが切り替わります。 カーソル
は最初にパスワードフィールドにあります。 Tab キーを押すと「ログインプッシュボタン」が表示され、
ユーザー's リストまたは「コンボ ボックス」が表示されます。 このリストにスペース
を押すと、現在選択されているユーザーが表示されます。 矢印キーを使用して別の
を選択し、対応するパスワードを入力します。 代わりに、 "その他..."
を選択すると、非リストのユーザーのログイン名を入力できるフィールドが追加されます。
それでも、F10は再起動やシャットダウンを可能にするメニューを表示します。
とAlt+F4はシャットダウンまたはキャンセルボタンを備えたUIを直接起動します。

=== コンソールスクリーンリーダーを選択

Slint はコンソールスクリーンリーダーを提供します: +
espeakup +
speehchd-up +
fenrir

さらに、いくつかのハードウェア音声シンセサイザーは、
コンソールモードでスピーチアップを使用できます。

スクリーンリーダーを選択するには、このコマンドをルートとして実行します。
----
speak-with
----
引数のない出力は次のとおりです。
----
root[~]# speak-with
Usage: /usr/sbin/speak-with <screen reader> or <hard synthesizer> or none
コンソールスクリーンリーダーを選択 to talk with among:
  espeakup (Console screen reader connecting espeak-ng and speakup)
  fenrir (Modular, flexible and fast console screen reader)
  speechd-up (Console screen reader connecting Speech Dispatcher and speakup)
or use one of the supported hard synthesizers:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
or type  "/usr/sbin/speak-with none" to mute all screen readers.
root[~]#
----
記載されているハードウェア音声シンセサイザーは、
実行中のカーネルまたはモジュールとして出荷されているものです。

コマンドと関連する出力の例:

----
root[~]# speak-with speechdup
スタートスピーチアップ
次の起動時にもスピーチアップを開始する必要がありますか? [Y/n]
OK
root[~]# 完了。
----
コマンドを入力するとすぐに、以前に使用されていたスクリーンリーダーが
停止され、スピーチアップが話し始めます。

If you answer Y (the default) to the question: +
Should speechd-up be also started at next boot? +
spechd-up will be continue to be used at next boot. +
If instead you answer n the screen reader used before typing speak-with
speechd-up will be used after next boot.

その他の例:

----
root[~]# speak-with apollo
スピーチを停止...
アポロは次のブート時にも使うべきか? [Y/n]
OK
root[~]# 完了。

root[~]# speak-with none
次の起動時にミュートコンソールも必要ですか? [Y/n]
OK
root[~]#
----

=== コンソールスクリーンリーダーを設定します。

Slint はスピーチハードウェアシンセサイザーをスピーチアップで処理し、espeakup
やスピーチアップスクリーンリーダーを提供します。

設定を保存すると、たとえば、
を増やしたり、seechやサウンドボリュームの速度を下げたりできます。 rootとして入力してください:
speakup-save. これにより、使用中の
ハードウェアシンセサイザー固有の場合を含む現在のすべての設定が保存されます。

これらの設定はすべて次の起動時に復元されます: 起動スクリプト
rc.espeakup と rc.speechd-up コマンドを実行します。

If you don't to want to restore the saved settings, type as root: +
chmod -x /usr/sbin/speakup-restore

もし root として復元されたならば: +
chmod +x /usr/sbin/speakup-restore

ここでは、スピーチアップと同様に設定用のいくつかの重要なバインディングを紹介します。
----
spk key_f9   punctuation_level_decrease
spk key_f10  punctuation_level_increase
spk key_f11  reading_punctuation_decrease
spk key_f12  reading_punctuation_increase
spk key_1    volume_decrease (doesn't work with speechd-up)
spk key_2    volume_increase (doesn't work with speechd-up)
spk key_3    pitch_decrease (doesn't work with speechd-up)
spk key_4    pitch_increase (doesn't work with speechd-up)
spk key_5    rate_decrease
spk key_6    rate_increase
----
上の表では、spkはスピーカキーCapLock、または数字の
キーパッドのIns/0です。 例えば、
CapsLockキーを押したまま6キーを押します。

特定のハードウェアシンセサイザーでのみ利用可能ないくつかの設定には、
関連するキーバインディングがありません。 新しい値を設定するには、
/sys/accessibility/speakup/<synth>/<parameter> でエコーします。

例えば、次のように書くことができます: +
echo 2 > /sys/accessibility/speakup/apollo/voice

speakup-save もこの設定を保存します。

Caveat: I never used a hardware speech synthesizer, so the explanation below is
only an assumption based in the speakup_apollo driver, consistent with
is manual, found in: +
https://archive.org/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== デスクトップキーの実行

以下にリストされているほとんどすべてのキーはテンキーにあります。
キーパッドのformat@@0またはformat@@1キーはシフトキーのように機能します。 例えば、
Ins 2は「Shiftキーのように挿入キーを押したまま2を押します」という意味です。
Speakup を使用するには、numlock をオフにしてください。

Scope: これらのキーバインディングは、ハードシンセサイザーや
のespeakupやスピーチアップでも使用できます。 ただし、スピーチアップを使用する場合は、キーバインディングを使用してピッチや
音声音量を設定することはできません。

覚えておくべき最初のキー:
----
PrintScreen スピーカーのオン/オフを切り替えます。
インズF1スピーカーヘルプ（ヘルプを終了するにはスペースを押します）
----

スクリーンレビューに使用されるキー:
----
1/2/3          Say Previous/Current/Next character
Shift PageUp   Say first character
Shift PageDown Say last character
4/5/6          Say Previous/Current/Next word
5 twice        Spell current word
Ins 5          Spell Current Word phonetically
7/8/9          Say Previous/Current/Next line
Ins 4          Say from left edge of line to reading cursor.
Ins 6 カーソルの読み取りから行の右端まで言います。
Ins 8 画面の上からカーソルを読み取るように言います。
Ins plus カーソル行の読み取りから画面の下部に移動します。
+ 画面全体を言う。
Ins r say all doutment
dot Say position
Ins dot Say attributes
Ins mins say character hex and decimal value.
マイナス読み取りカーソル(トグル)
Ins 9 読み取りカーソルを画面の上部に移動 (pgupを挿入)
Ins 3 読み取りカーソルを画面の下部に移動 (pgdnを挿入)
Ins 7 読み取りカーソルを画面の左端に移動 (ホームを挿入)
Ins 1 読み取りカーソルを画面の右端に移動 (終端を挿入)
Control 1 読み取りカーソルを現在の行の最後の文字に移動します。
アスタリスク カーソルの切り替え
Ins アスタリスク n<x|y は行 (y) または 列 (x) に移動します。 'n' が現在の画面の行または列に
               許可されている値の場合。
Ins f2 Set window
Ins f3 Clear window
Ins f4 Enable window
----

その他のキー:
----
Ins f5 いくつかの
Ins f6 ほとんどの編集
Ins f7 Delim を編集
Ins f8 繰り返しを編集
Ins f9 Exnum を編集

Shut up (別のキーがヒットするまで) に入り、読み取りカーソルを同期します。
Ins Enter Shut up (戻るまで)

スラッシュマークとカット画面領域。
Ins スラッシュ画面領域を任意のコンソールに貼り付けます。
----
==== ノートパソコンのキーを高速化する

これらのキー割り当て（米国のキーボードレイアウト用）ドン'tはテンキーを必要とします。
もしあれば、 <<desktop_keys, speakup デスクトップキー>> を使いやすく、
特に米国以外のキーボードレイアウトを使用する場合は使用します。

The CapsLock key acts like a Shift key. +
For instance, CapsLock 2 means "hold down the CapsLock key like a shift key and press 2". +
Keep numlock off to use Speakup.

Scope: これらのキーバインディングは、ハードシンセサイザーや
のespeakupやスピーチアップでも使用できます。 ただし、スピーチアップを使用する場合は、キーバインディングを使用してピッチや
音声音量を設定することはできません。

覚えておくべき最初のキー:
----
PrintScreenの話のオン/オフを切り替える
CapsLock F1 Speakup Help (終了するにはスペースを押してください)
----

スクリーンレビューに使用するキー:
----
CapsLock m/カンマ/dot Say Previous/Current/Next characters
CapsLock PageUp Say First character
CpasLock PageDown Say Last character
CapsLock j/k/l Say Previous/Current/Next word
CpasLock 2 Spell current word
CapsLock u/i/o Say Previous/Current/Next line
CapsLock h 左端から読むカーソルまで言う。
CapsLock semicolon カーソルを読むことから行の右端まで言う
CapsLock y カーソルを読むことにスクリーンの上から言う。
CapsLock p カーソル行を画面の下に読み込むことから言う。
CapsLockアポストロフィ 画面全体を表示します。
Capslock r すべてのドキュメントを読みます。
CapsLock n Say position
CapsLock slash Say attributes
CapsLock minus park reading cursor (toggle)
CapsLock f2 Set window
CapsLock f3 Clear window
CapsLock f4 Enable window
----
その他のキー:
----
CapsLock f5 いくつかの編集
CapsLock f6 ほとんどの編集
CapsLock f7 区切り文字の編集
CapsLock f8 Repeat edit
shift CapsLock f9 Edit exnum
----

=== Emacsに発言させる

emacspeakまたはspeech-elのいずれかを使用できます。
のいずれかを有効または無効にするには、次のいずれかのコマンドを通常のいずれかと入力します。

switch-on emacspeak +
switch-on speechd-el +
switch-off emacspeak +
switch-offspeak +

それから単にタイプしてください: +
emacs

これらのソフトウェアのいずれかを有効にすると、もう一方のソフトウェアが無効になります。

[[Manage_your_system]]
== Manage your system

[[software_management]]
=== Slint のソフトウェア管理.

<<The_basics, The basics>> +
<<Keep_your_system_up_to_date, Keep your system up to date>> +
<<Kernel_upgrades, Kernel upgrades>> +
<<Get_additional_applications, Get additional applications>> +
 <<slapt_src, Usage of slapt-src>> +
 <<sbopkg, Usage of sbopkg>> +

[[The_basics]]
==== 基本

Slint ソフトウェアではパッケージの形で提供されています。 パッケージは、圧縮されたアーカイブファイルで提供されるファイルの束であり、ソフトウェアを実行するために必要なすべてを提供するためにまとめられます。 パッケージはインストールISOに含まれており、そこからダウンロードしてインストールできるリモートサーバーに保存されます。 パッケージをインストールすることは、アーカイブファイルからファイルを抽出し、システムのディレクトリにコピーすることを意味します。

ソフトウェアのインストールと削除は、これらのディレクトリ内のテキストファイルで作られたデータベースに記録されます:
----
/var/log/packages
/var/log/removed_packages
/var/log/scripts
/var/log/removed_scripts
----
ディレクトリ内のファイルは、パッケージに関するレコード情報、主にその内容:含まれるファイルのリストとそれらがインストールされる場所。

パッケージを管理する主なコマンドは以下のとおりです。 それらのすべてはmanページに関連付けられている。

これらのコマンドには、Slint インストール時にパスワードを指定した特定のアカウント「root」に関連付けられた管理者権限が必要です。

'root' としてコマンドを発行するには、最初に
su -
と入力し、root 用のパスワードを入力し、コマンドを入力します。

以下のコマンドは、グラフィカル端子またはコンソールから実行することができますが、グラフィカルな環境でのみ動作するgslapt。
----
installpkg # ローカルに保存されたパッケージをインストールします。
インストールされたパッケージを削除するには、removepkg #
upgradepkg # インストールされたパッケージを別のパッケージに置き換えます (一般的には同じ名前ですが、別のバージョンで)。
/etc/slapt-get/slap-get-getrc にリストされているリポジトリに格納されているパッケージをインストール、削除、アップグレードする #
----
インストール ISO に出荷されているパッケージは、/etc/slapt-get/slapt-get-get-rc にリストされているリポジトリから取得されます。

/etc/slapt-get/slapt-get-getrc および /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint にあるコメントを読んでください。

Slint をインストールした後、あなた'/etc/slapt-get/slapt-get-get-rc にリストされているリポジトリからインストールされたパッケージの更新を通知します

/etc/slapt-get/slapt-get-get-get-rc にリストされているリポジトリに格納されている場合は、コマンドの slapt-get またはグラフィカルなアプリケーションの gslap を使用して追加のパッケージをインストールできます。

slapt-get と gslaptは、パッケージを見つけるのに役立つ検索機能を提供します。

WARNING: インストールされているパッケージを削除するには、slapt-get, gslapt, removepkg を使用しますが、Slint ISO で出荷されているパッケージは削除しません。 全然使わなくてもね 付属のパッケージを削除すると、パフォーマンスが向上せず、他のアプリケーションを実行できなくなる可能性があります。 また、Slint に含まれていないパッケージを追加した場合は、削除することができますが、削除されたパッケージがインストールされた他のパッケージの依存関係ではなく、引き続き使用することに注意してください。

[[Keep_your_system_up_to_date]]
==== システムを最新の状態に維持する

Slint が提供するソフトウェアアップデートをインストールするには、システムを安全にインストールしてください'再利用可能になります。

すべての更新は ChangeLog に記載されています: http://slackware.uk/slint/x86_64/slint-14.2.1/ChangeLog.txt

Slint がインストールされた後、または /etc/slapt-get/slapt-get-get-getr というファイルが変更された後、このコマンドは 1 回実行されます。
----
slapt-get --add-keys
----

使用可能なパッケージのローカルリストをリポジトリのリストと同期させるには、このコマンドは2時間ごとに自動的に実行されます。
----
slapt-get -u
----
手動で実行することもできます

これはもちろん、マシンがインターネットに接続される必要があります。

アップグレードまたは再構築されたパッケージをダウンロードしてインストールするには、次のコマンドをルート
として実行します。
----
slapt-get --upgrade
----
あるいは、slapt-get のグラフィカルなフロントエンドである gslaptを使用することもできます。

ChangeLog に「追加済み」としてリストされた新しいパッケージを取得するには、次のように入力します。
----
slapt-get -i <package name>
----
または、Slint をインストールした後にリポジトリに追加されたパッケージも含め、Slint に出荷されるすべてのパッケージがインストールされていることを確認するには、次のように入力します。
----
slapt-get --install-set slint
----

デスクトップ上で 使用可能なソフトウェアの更新を通知するために、パネル(MATEのトップパネル)の通知領域に小さなアイコンが表示されます。 それを左クリックして、そこに記載されている指示に従ってください。


/etc/slapt-get/slapt-get-getrc にブラックリストに登録されているパッケージがあります。つまり、自動的にアップグレードできないか、
インストールされていることに注意してください。

[[カーネル_upgrades]]
==== カーネルのアップグレード

新しいカーネルは、セキュリティ修正または機能強化のいずれかを必要に応じて提供されます。

通常、これが起こるとき、ユーザーからの手動介入は必要ありません。 しかしカーネルのアップグレードの仕方や予期しないことが起きた場合の対処方法を知ることが有用です

いくつかのパッケージには、各カーネルに関連付けられたファイル、すなわち: kernel-generic, kernel-modules, kernel-source, kernel-headers が含まれています。 kernel-source と kernel-headers には、ソフトウェアのビルドに使用されるファイルが含まれており、Slint システムを実行するには kernel-generic と kernel-modules のみが必要です。

kernel-modules はモジュールと呼ばれるファイルを提供しています 特定の機能を提供したり、特定のハードウェアを扱うためにカーネルを「接続」されたコードの断片です。

カーネルパッケージと関連する kernel-modules パッケージの両方がインストールされるとすぐに。 スクリプト
/sbin/wrapupgradepkg は、このカーネルに関連付けられた <<initrd, initrd>> をビルドし(モジュールは
パッケージカーネルモジュールから取得)、/boot ディレクトリのカーネルとともにインストールします。

そうすると、以前のカーネル(アップグレード時には使用されていません)が削除されます。

次に、スクリプトはGRUB設定ファイル/boot/grub/grub.cfgを更新し、OSローダーで読み込んで起動時に起動をビルドします。

このブートメニューには、それぞれが使用するカーネルとそれに関連する initrd を示す少なくとも2つのブートエントリが含まれます。 上から:

* インストールされたばかりの新しいカーネルを使用して Slint を開始するためのブートエントリ。
* アップグレード時にカーネルを使用してSlintを起動するためのブートエントリ。

これはSlint が'新しいカーネルで t ブートを行う場合に一種の "セーフティネット" を提供します:
この場合、前のカーネルで Slint を開始するためにブートメニューが表示されると一度矢印を押すだけです。

再起動する前に新しいブートメニューをプレビューし、root と入力することができます:
----
grub-emu
----
Then an emulated or "fake" boot menu is displayed, with the same layout as the real one which will
displayed at boot.

下矢印キーと上矢印キーで移動して、詳細を表示できるブートエントリをハイライト(フォーカスを置く)することができます。 メニューに戻るには、Escapeキーを押します。

grub-emuを終了するには、cを押して *exit* と入力し、Enterを押します。

[[Get_additional_applications]]
==== 追加のアプリケーションを取得

If the application you want is not installed and also not available in one of the repositories enabled in /etc/slapt-get/slapt-getrc you could make a package for it, using build material provided by volunteers @ https://slackbuilds.org. how-to proceedについては、 https://slackbuilds.org/howto/ および https://slackbuilds.org/faq/ を参照してください。

この方法で構築されたパッケージは Slint と互換性があるはずです。

Two applications allow you build and install packages using the build material provided at https://slackbuilds.org: *slapt-src* and *sbopkg*. sbopkg に慣れていない限り、slapt-src を使用することをお勧めします。 しかし、両方とも動作し、同じ結果を提供する必要があり、root として使用する必要があります。

slapt-src について詳しく説明します。

[[slapt_src]]
===== slapt-srcrc の使用

slapt-src のデフォルトの設定スクリプトは /etc/slapt-get/slap-getrc であり、以下の内容を持っています。
----
BUILDDIR=/tmp/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/14.2/
----
そう:

* すべてのビルドマテリアルとパッケージは /tmp/slapt-src に移動します
* .txzでビルドされたパッケージの名前
* ビルドマテリアルはリポジトリから取得されています https://slackbuilds.org/slackbuilds/14.2/

以下は、コマンド *slapt-src --help* の出力です。
----
Usage: slapt-src [option(s)] [action] [slackbuild(s)]
  -u, --update           update local cache of remote slackbuilds
  -U, --upgrade-all      upgrade all installed slackbuilds
  -l, --list             list available slackbuilds
  -e, --clean            clean build directory
  -s, --search           search available slackbuilds
  -w, --show             show specified slackbuilds
  -i, --install          fetch, build, and install the specified slackbuild(s)
  -b, --build            only fetch and build the specified slackbuild(s)
  -f, --fetch            only fetch the specified slackbuild(s)
  -v, --version
  -h, --help
 Options:
  -y, --yes              do not prompt
  -t, --simulate         show what will be done
  -c, --config=FILE      use the specified configuration file
  -n, --no-dep           do not look for dependencies
  -p, --postprocess=CMD  run specified command on generated package
  -B, --build-only       applicable only to --upgrade-all
  -F, --fetch-only       applicable only to --upgrade-all
----

Let's comment some of these options:

* ビルドおよびインストール可能なパッケージのリストを更新するには、毎回-uまたは--updateを使用してください。 このコマンドは、/tmp/slapt-src/slackbuilds_data というファイルを書き込み、前の 1 つのケースを置き換えます。
* /usr/src/slapt-src/ にあるほとんどのファイルを削除するには、ディスク上のスペースを節約するために -e を使用してください。
* ** は -U を使用せず、アップグレードまたはダウングレードの可能性をリストするために使用します。 確認なし: remote repositoryで利用可能な場合、すべてのSlintパッケージを別のバージョンで置き換えることになります。 おそらくこの他のバージョンと互換性のないソフトウェアを壊している
* -i can also upgrade a package already installed from https://slackbuilds.org, if a the maintainer of the SlackBuild script has upgraded it, changing the VERSION variable.
* -f を使用すると、対象ソフトウェアの https://slackbuilds.org 内のファイルのみをダウンロードできます。 これは、ビルド材料を確認したり、ビルドをカスタマイズしたりする場合に便利です。 例えば let's はソフトウェア *mxml* のビルドマテリアルを取得すると仮定します。 以下のコマンドは、ソフトウェアと https://slackbuilds.org に保存されているファイルに関する情報を提供します。
+
----
slapt-src --show mxml
SlackBuild Name: mxml
SlackBuild Version: 3.1
SlackBuild Category: libraries/mxml/
SlackBuild Description: mxml (Lightweight xml parsing library)
SlackBuild Files:
 README
 mxml.SlackBuild
 mxml.info
 slack-desc
----
+
次に、ファイルと上流リポジトリからのソースアーカイブを次のコマンドで取得します。
+
----
slapt-get -f mxml
----
+
前のコマンドの出力から、ファイルがサブディレクトリlibraries/mxmlに保存されていることがわかります。 このコマンドでどのファイルをダウンロードしたかを確認できます。
+
----
ls -1 /tmp/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* パッケージをビルドしたいがまだインストールしていない場合は -b を使用してください。 上の例では、/tmp/slapt-src/libraries/mxml に保存されているので、入力するだけでインストールできます。
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txt
----
+
* デフォルトの /etc/slapt-get/slap-get-getrc の代わりにカスタム設定ファイルを使用する場合は -c を使用します。

[[sbopkg]]
===== Usage of sbopkg

WARNING: in some cases a software is shipped in Slint and is also available in https://slackbuilds.org but with a different name which can lead to problems. これらの矛盾は、slapt-src を使用している場合に解決されますが、sbopkg を使用している場合はまだ解決されません。

sbopkg を使用する前に、ヘルプファイルと man ページで root と入力してください: *sbopkg --help* と *man sbopkg*

簡単に言えば、コマンドラインのみをrootとして使用する場合:

* ローカルリポジトリとリモートリポジトリを同期して更新します。
+
----
sbopkg -r
----
* 必要なソフトウェアの前にビルドしてインストールするために右の順序で依存関係を一覧表示する「キューファイル」を作成します。
+
----
sqg -p <package name>
----
/var/lib/sbopkg/queues/<package name>.sqf という名前のキューファイルが書き込まれます

依存関係がない場合、キューファイルは書き込まれません

* 依存関係をビルドしてインストールします。それから、望んでいたソフトウェア:
+
----
sbopkg -i <package name>
----
このパッケージのキューファイルが存在する場合、要求されたときに使用することを選択します。

キューファイルに記載されているパッケージがすでにインストールされている場合はスキップされます。

結果として、sbopkg を使用してすでにインストールされているパッケージをアップグレードしたい場合。 新しいものを構築してインストールする前に
を削除する必要があります。

この方法でパッケージをビルドしてインストールすると、依存関係がなくなったり、インストールされているパッケージとの競合などの問題が生じることがあります。パッケージをビルドするために使用されるコンポーネントは、あらゆる設定で結果をチェックできないボランティアによって提供されます。

WARNING: If you neither can find a package for a software you want nor stuff to build one @ https://slackbuilds.org, you could be tempted to build and install this software manually by issuing the commands "./configure && make && make install". これを行うことは避けてください, この方法を構築し、インストールされたソフトウェアは、Slint パッケージ管理システムと関連するツールによって管理することはできません.

むしろ、Slint メーリングリストに質問やリクエストを投稿するだけで、このパッケージをリポジトリに追加する可能性があります。 実行されたとき (メーリングリストにて発表されます) は、これらのコマの root としてインストールします。
----
slapt-get -i <package name>
slapt-get --install-set Slint
----

=== ユーザーとグループを管理します。

ユーザーとグループを管理するための2つのコマンドが提供されています:

* _usersetup_ コマンド (TUI)
* _gtkusersetup_ コマンド (GUI) で、Slint Control Center, System category)

これらのコマンドを使用すると、ユーザーとユーザーのグループを追加または削除したり、グループにユーザーを追加したりできます。

各ユーザーアカウントはデフォルトで /home ディレクトリ内の on スペースに関連付けられていることに注意してください。 例えば、ユーザ *leonie*を追加すると、 /home/leonie フォルダが作成されます。 このユーザー(およびroot)のみアクセスが許可されます。

=== システムのデフォルト言語を変更する

2つのコマンドが用意されています:

* _localesetup_ コマンド (TUI).
* _gtklocalesetup_ コマンド (GUI) で、Slint Control Center, Settings カテゴリにアイコンが表示されます。

この設定は、キーボードマップではなく、国際化されたアプリケーションのインターフェイスで使用される言語を変更することに注意してください(以下を参照)。

また、選択した言語に一致するローカライズされたパッケージは、Slint インストールの最後にすでにインストールされています。 後でデフォルトの言語を変更する場合は、対応するローカライズされたパッケージをインストールする必要があります。

ローカライズされた手段は、「特定のロケールで提供される」という意味で、ロケールは言語と地理的領域に関連付けられたプラス特殊性である。 例えばポルトガルとブラジルで話さポルトガル語は異なります。 ローカライズされたパッケージ名では、l10n は "localization" の略語で、"letter l, 10, other letters, letter n" を意味します。

多くの言語にローカライズされたパッケージが含まれています。 名前には基本パッケージ名、ハイフン、次に言語コードが含まれます。 ローカライズされたパッケージの基本名の下にリストされています:
[options="autowidth"]
|====
| ベースパッケージ名 | 説明
| aspell | 単語リストでスペルチェック
| calligra-l0n | Calligra officeスイートのローカライズされた
| kde-l10n | ローカライズされた KDE デスクトップ
| libreoffice-l0n | ローカライズされたLibreOfficeオフィススイート
| libreoffice-help | LibreOfficeのローカライズされたヘルプ
|====

ローカライズされたパッケージを見つけるには、端末エミュレータをroot として入力してください(例: kde-l10n): +
`spi libreoffice`

これは、すべてのローカライズされたLibreOfficeパッケージのリストを表示します。 必要なものを見つけてインストールします。 例えばペルシャ語の言語コードは `fa` (Farsiの略) です。 だから、それをインストールするには: ` ` +
`spi -i libreoffice-l0n-fa`

ご希望の場合は、 `gslapt` を使用できます。 次に、検索フィールドにパッケージ名を入力し、すべてのローカライズされたlibreofficeパッケージを表示します。

=== キーボードマップを変更する

グラフィカル モードで使用される既定のキーマップを変更できます。

* _キーボードセットアップ_ コマンド (TUI)
* _gtkkeyboardsetup_ コマンド (GUI) は、Slint Control Center, Hardware カテゴリにアイコンがあります。

これらのコマンドを使用すると、システムの起動時にnumlockを有効にするかどうかを選択することができます。 そして、システム起動時にSCIM(入力方法)を有効にする必要がある場合。

ウィンドウマネージャをパネルで使用する場合 キーボードアプレットの右クリックでこの設定を行うこともできます(デフォルトではキーボードマップの2文字の言語コードとして表示されます)。 KDE と Xfce には、そのための特定のツールがあります。

コマンドラインではなくグラフィカルモードでは代わりにsetxbmapを使用します

たとえば、グラフィックモードでキーボードのレイアウトをウクライナ語に設定するには、通常のユーザーとして入力してください: +
`setxkbmap -layout ua`

詳細については、setxkbmap の man ページを参照してください。

=== プリンタをインストールする

Sclintでは、CUPS印刷サーバーがプリンタと印刷タスクを管理します。 デフォルト設定では、/etc/cups/cupsd ファイルに記録されています。 onf では、 `システム` ( _システム_の略) グループに属するユーザーのみが管理タスクを実行することができます。 プリンタの追加や削除などです

簡単なセットアップ(デスクトップまたはラップトップに取り付けられており、マシン間で共有されていないプリンタ) `システム` グループにプリンタを管理するユーザーを1人追加するだけです。 例えば、ユーザー _didier_ をグループ `sys` に追加する方法は、2つあります。

* コンソールモードまたは端末エミュレータを使用して、 `su` で root になり、次に入力します:
+
`gpasswd --add didier sys`
+
* グラフィカル・モードでは、Slint Control Centerからユーザーとグループ(システムカテゴリ)をクリックします。 ユーザーを選択し、 `をクリックし、`タブでformat@@2システムformat@@3をチェックします。 または、別の方法でラウンドします (グループを選択し、ユーザーを追加します)。

プリンタを追加および設定するにはいくつかの方法があります(これはグループ `sys` のユーザーメンバによって行われる必要があります):

* Slint Control Centerからカテゴリハードウェアを選択し、プリンタの設定をクリックしてシンプルな設定を行えるGUIを表示します...
* ... もしくは、CUPSサーバーへのWebインターフェイスを表示するカップをクリックしてください。 また、ウェブブラウザのアドレスフィールドに `localhost:631` と入力する CUPS サーバへの Web インターフェイスを表示することもできます。
* Hewlett Packardデバイスをお持ちの場合は、パネルの通知領域にある *馬力* のロゴを右クリックしてください。

NOTE: 印刷設定を行うには、CUPSサーバーが実行されている必要があります。 システムサービス間でチェックされているサービス `カップ` がある場合、Slint を起動したときに開始されます (Slint でデフォルトでチェックされています)。

=== サウンドの設定


Slint アプリケーションでは、サウンド出力を ALSA または PulseAudio に送信します。

後者の場合、PulseAudioは出力ストリームをALSAミキサーに送信し、サウンドカードにダイレクトします。

その結果、出力音量のような設定は、ALSAミキサーでいつでも行うことができます。 また、PulseAudio ミキサーでも使用できますが、アプリケーションがサウンド出力を PulseAudio に送信する場合に限ります。

サウンドの設定を変更するために使用できるアプリケーションを紹介します

==== 舗装制御 (PulseAudio用)

`pubucontrol` はPulseAudio Volume Control の略で、グラフィカルなアプリケーションです。 ターミナルまたはアプリケーションメニューから起動できます。 または、Mateの上部パネルのサウンドミキサーアイコンを右クリックしてください。 実際には、ボリュームコントロールだけでなく、すべての機能を調べるのに時間がかかります。

パネルの通知領域で音量コントロールアプレットを使用することもできます: 左クリックで音量を調整できます。 右クリックすると他の設定にアクセスでき、パブコントロールミキサーを起動できます。

[[Sound_on_the_command_line]]

==== alsamixer  (for ALSA)

alsamixerはncursesアプリケーションで、半グラフィカルなユーザーインターフェイスを提供します。

使用方法: コンソールまたはグラフィカル端末で:
----
alsamixer
----
それから:

* ページアップキーを使用して音量を5%増やします
* ページの下キーを使用して音量を5%減らします
* アプリケーションを終了するには、Escを押します。

==== amixer（ALSA用）
コマンドは以下の形式です:
----
amixer <arguments>`
----
たとえば、メインボリュームを70%タイプに設定します。
----
amixer sset Master 70%
----
詳細については、以下のコマンドのいずれかを入力してください。
----
man amixer
amixer -h
----
==== sam(Speech Friendly Alsa Mixer)
Samは、あなたのマシンに複数の
そのようなデバイスがあるときにサウンドカードの選択を可能にします。
 +
1つだけの場合、異なるミキサー
を直接表示して構成します。

All selections, be it sound cards, mixers or a given feature of a
 specific mixer are selected by scrolling through the available options using the up and down arrows, then entering on the desired one: +
`q` leave the selection list and/or quits. +
`Shift-q` exits the program from anywhere. +
`F1` Displays any extra information if available.

希望するオプションの名前がわかっている場合、代わりにその
文字を押すことができます。 最初の文字ナビゲーションは大文字小文字を区別しません。
それから、押された
文字から始まる最初の選択に移動します。  同じ文字をもう一度押すと、そのようなオプションが存在する場合、その文字で始まる次のオプション
に移動します。
文字を繰り返すと、その
文字で始まるすべてのオプションが繰り返されます。

The settable features of a mixer can be  listed by pressing f1. +
They are presented as a selection list, showing briefly all relevant information, e.g.
"playback volume down from 84 percent" is the option to lower the playback volume
setting of the playback volume.  ご覧のとおり、
現在の設定が何であるかを示しています。

NOTE: サムはグラフィカルな端末では正しく動作しない コンソールで使用します。

==== pamixerとponymix（PulseAudio用）
これらのイタレーションは、この形のコマに似ています。
----
pamixer <arguments>
ponymix <arguments>
----
たとえば、デフォルトのシンクタイプのボリュームを 70% に設定するには、以下のコマンドのいずれかを実行します。
----
pamixer --set-volume 7
ponymix set-volume 8O
----
詳細については、以下のように入力してください。
----
pamixer -h
ponymix --help
----

==== pacmd と pactl (for PulseAudio)

これらのコマンドラインアプリケーションは、PulseAdioデーモンを制御します。

WARNING: pacmd タイプだけで対話型のダイアログが表示されます。 Ctrl+dキーを押して終了しますが、終了と入力しないでください。PulseAudioを停止します!

詳細を知るには:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== サウンドレベルを保存して復元

/etc/rc.d/rc.alsaファイルを実行可能にします。 ルート名:
----
chmod /etc/rc.d/rc.alsa
----
At startup, this script will restore the previous sound settings if
they were previously stored, else will set default volumes and store
them, so that they will be restored at next reboot.

If you don't want that this script to set the default volume type as root:
----
touch /var/lib/alsa/no.asound.state
----

Alsamixerまたはamixer
でこれらのデフォルトのサウンドレベルを変更し、rootとして入力できます。
----
アルザクトル・ストア
----
次の起動時にスクリプトがそれらを復元します。

詳細を知るには:
----
man alsactl
----
=== ネットワーク設定

Slint インストール中に't がネットワーク設定を行っていない場合。 最初の format@@0 を
と入力して `su -` のいずれかをコンソールまたは mate-terminal のような
グラフィカルな端末にする 次にrootパスワードを入力します。

ネットワークのセットアップは `netsetup` スクリプトにより行われます。
そのため、同じ端末で `` コマンド
netsetup format@@3 を入力するだけで、この'は root 権限を取得しました。
最初にマシンのホスト名を尋ねられます。 あなたは任意の
名前を選択することができますが、それは単一の単語でなければならないことに注意してください。
次に、ドメイン名を求められます。 マシンがサーバー
でない場合は、誰でも選択できます。
その後、マシンがネットワークに接続する方法を尋ねられます。 Unless
you have a good reason not to (and you know what you are doing), keep
the default `NetworkManager` to automatically configure the network.

有線接続の場合は、次の起動時に自動的に接続するのに十分です
。

無線接続を設定するには、コマンドライン
を使用して2つのコマンドを使用できます。

ここでも、コンソールまたはmate-terminalのような
グラフィカル端子にコマンドを直接入力できます。
rootとしてではなく、正規ユーザーとしてそれらを入力します。
If you followed these instructions and became root already, you would just
type `exit` to get back the regular user status.

2つのコマンドは、 `nmtui` (ダイアログボックス) または `nmcli` (純粋なコマンドライン)
両方ともアクセス可能です。

コマンドラインで作業したい場合は、まずnmcli
のドキュメントを読んでください。 `nmcli --help` と `man nmcli`
と入力するだけで詳細を確認できます。
While `nmcli` offers more possibilities, in most use-cases the functionality
of `nmtui` will be sufficient for setting up your wireless network, so we will
describe it here:

`nmtui`を使用すると、Tab キーと矢印キーで移動できます。
You will be proposed three options: +
`Edit a connection` +
`Activate a connection` +
`Set system hostname` +

まだ無線接続が設定されていない場合は、 `接続を有効にする` を選択します。
Starting from top to bottom, first the wired connections (if any) will
be proposed, after that all accessible wireless networks will be listed.
下矢印キーと上矢印キーで移動して、必要なネットワークを選択します。
次に、Enter と入力します。おそらくパスワードまたは暗号化
キーを求められるでしょう。 それを入力し、format@@0キーを使用して確認し、終了します。

グラフィカル モードでのみ、 `nmcli` または `nmtui` の代わりに、アプリケーション
`nm-connection-editor` を使用できます。

=== サービスの構成

<br>モードを使用している場合は、起動時にデフォルトでどのシステムサービスが有効になっているかを尋ねられました。  +
オートモードのデフォルト設定が適用された場合

両方の場合、これらの設定をいくつかの方法で変更できます:

* root として `servicesetup` コマンド (TUI) を実行します
* In graphical mode only, using `gtkervicesetup`, accessible from the Slint Control Center, category System or typing Alt+F2 to raise a "Run..." dialog then typing *gtksetrvicesetup*.
* 関連するスクリプトを実行可能にする root として (chmod 755 <path to the script> または非実行可能) (chmod 644 <path to the script>). 例えばfail2ban 実行可能にするには、次のように入力します: `chmod 755 /etc/rc.d/rc.fai2ban`

[IMPORTANT]
====
何をしているか分かっている場合にのみ、デフォルトの設定を変更してください。
====

サービスは、/etc/rc.d/ ディレクトリ内の `rc.` で始まる名前のスクリプトによって管理されます。 例えば、サービス acpi はシェルスクリプト /etc/rc.d/rc.acpiによって管理されます。 対応するスクリプトが実行可能である場合、ほとんどのサービスは起動時に有効になります。 以下の表では、起動時に有効になっているかどうかを示します(列Aの`、列Aの` 、列Aの`オフ`)。 列が空白の場合、サービスの有効化はインストール時の選択に依存します。 列の `A` は、自動インストールモードでサービスが有効になっていることを示します。 else は、インストール中にユーザーが選択した場合に有効になります。 「パッケージ」列は、サービスに対応するスクリプトを提供するソフトウェアパッケージの場合を示します。

[options="autowidth"]
|====
| *Service* | *A* | *パッケージ* | *目的とコメント*
| acpi | on | acpid | 高度な設定と電源インターフェースにより、例えば電源を管理したり、ボタンを押して再起動することができます。
| alsa | on | alsa-utils | デフォルトのサウンド設定を提供するか、保存したサウンドを復元します
| alsa-oss | オフ | alsa-utils | ALSA OSS カーネルモジュール。 MOTケースでは役に立ちません。Slintではデフォルトで有効になっていません。
| atalk | オフ | netatalk | Unix ライクなオペレーティングシステムが、Macintoshコンピュータ用のファイル、プリント、タイムサーバーとして機能することを可能にします。
| autofs | オフ | autofs | Linux用のカーネルベースの自動マウント
| bind | オフ | bind | 名前サーバー ほとんどのユーザーは、リモートのものに依存します。 このシステムでネームサーバーを実行したい場合は有効にしてください。
| bitlbee | on | bitlbee | BitlBeeはインスタントメッセージングネットワーク
       と通信し、ゲートウェイとして機能するIRCデーモンです。 ユーザーは通常の
       IRC クライアントでサーバーに接続し、'buddy list' を &bitlbeeで確認できます。
| Bluetooth | on | ブルーズ | Bluetooth デバイスとの通信を許可する
| brltty|  | brltty | 点字端末やスクリーンリーダーとの通信を可能にします。 インストール中に要求された場合に有効になりました
| cgconfig | on | libcgroups | /etc/cgconfig を解析する cgconfigparser ユーティリティを実行します。 グループのアクセス許可(UIDとGID)やコントローラの調整可能なパラメータを設定するなど、コントロールグループ階層を設定します。 これは、たとえば別のシェルスクリプトを実行するために、すべての起動時に自分でそれを行うことを軽減します。 This script is executable by default but anyway wオン't do anything until /etc/cgconfig.conf be edited (all lines are commented out as shipped)
| cgmanager | オフ | cgmanager | Starts the cgmanager daemon that provides an alternate way to manage the cオンtrol group hierarchy through D-Bus requests possibly through the cgm front-end utility.
| cgproxy | オフ | cgmanager | Starts the cgproxy daemon, that allows programs and users in a cオンtainer to make cgroup administration requests using DBus calls, sending the user-ids or group-ids as SCM credentials to the cgmanager.
| cgred | on | libcgroups | Starts the cgroups rules engine daemオン that automatically distributes to appropriate control groups the processes that changes their effective UID or GID, applying the rules found in /etc/cgrules.conf. This allows to cオンtinue apply resources control resources on such processes that could otherwise escape it. このスクリプトはデフォルトで実行可能ですが、とにかく勝ちました't /etc/cgruls.conf を編集するまで何でも実行します (すべての行は出荷時にコメントアウトされます)
| consolekit | on | ConsoleKit2 | このデーモンは polkit's コンソールエージェントで使用され、たとえばシステムを再起動またはシャットダウンしたいユーザーの権限を確認します。
| cpufreq | on | sysvinit-scripts | カーネルのCPU周波数と電圧スケーリングの設定。
| カップ | on | カップ | CUPSプリントサーバーの起動/シャットダウンスクリプト。
| cups-browsed | オフ | cups-filters | リモートプリンタをローカルで利用できるようにします。
| dnsmask | オフ | dnsmask | dnsmasq (小さなDNS/DHCPサーバ) の起動/停止/再起動
| espeakup | | espeakup | espeakupコンソールスクリーンリーダーを起動/停止/再起動します。 インストール中または後でタイプされたspeak-with espeakup
| fail2ban | オフ | fail2ban | /var/log/pwdfailのようなログファイルをスキャンするfail2banを起動/停止し、パスワードの失敗が多すぎるIPを禁止します。 また、ファイアウォールのルールを更新してIPアドレスを拒否します。
| font | オフ | kbd | Sets the console fオンt (used in Console mode, not in Graphical mode)
| ヒューズ | on | ヒューズ | fuseモジュールをロードし、fuse制御ファイルシステムをマウントします。 FUSE は Linux カーネルに仮想ファイルシステムをエクスポートするための、ユーザー空間プログラムのためのシンプルなインターフェイスです。  FUSE もまた、非特権ユーザーが独自のファイルシステムの実装を作成しマウントするための安全なメソッドを提供することを目指しています。
| fenrir | オフ | fenrir | fenrirスクリーンリーダーをstarts/stop/restart にします。これはインストール後にfenrirと入力することができます。
| font | オフ | kbd | カスタムコンソールフォントの設定
| gpm | オン | gpm | 一般目的マウスサーバーは、Linuxコンソール上で画面からテキストをカット&ペーストすることができます。
| httpd | オフ | https | Apache ウェブサーバを起動または停止します
| inet1 | on | network-script | このスクリプトは、さまざまなネットワークインターフェイスを呼び出すために使用されます。
| inet2 | オン | network-script | このシェルスクリプトはネットワークシステム全体を起動します。
| inetd | オン | inetd | BSD "super-server" デーモン。 実際に使われるサービスを /etc/inetd.conf に編集する必要があります。
| ip_forward | オフ | network-script | コンピュータがルータとして動作するために必要なIPパケット転送の開始/停止。
| キーマップ | on | installer | コンソールモードで使用されるキーボードマップを読み込みます。
| ローカル | オフ | sysvinit-scripts | 起動時に /etc/rc.d/rc.M が起動しないデーモンを開始します。
| ループ | on | sysvinit-scripts | ループデバイスカーネルモジュールをロードします。
| lxc | オフ | lxc | This scripts starts (if cオンfigured to be auto-started) and stops lxc containers.
| mcelog | オフ | mcelog | mcelogハードウェアエラーログを開始します。 このログはx86システムのCPUハードウェアエラーを処理します
| メッセージ バス | on | dbus | D-BUSシステム全体のメッセージバス。 これは、システムイベントやその他のメッセージの通知をブロードキャストするデーモンで、プロセス間の通信を提供します。
| モジュール | on | sysvinit-scripts | Compute the kernel modules dependencies and start other scripts that load modules not automatically loaded by eudev, possibly for specific kernel versiオンs
| modules.local | on | sysvinit-scripts | eudev で自動的に読み込まれないモジュールの読み込み
| murmur | オフ | murmur | つぶやきのための雑音のボイスチャットサーバーを開始/停止します
| mysqld | オフ | mariadb | MariaDBサーバーを起動/停止します。 MariaDBはMySQLと完全に互換性のあるフォークです
| ネットワークマネージャー|  | NetworkManager | This is a daemon for automatically switching network cオンnectiオンs to the best available cオンnection. Activated if NetworkManager is chosen to configure the network, during or after installatiオン
| nfsd | オフ | nfs-utils | nfs を開始/停止 (Network File Server.qq
| ntpd | on | ntp | ntp (Net'work Time Protocol) デーモンを停止します。
| numlock|  | salixtools | Activate numlock オン the console
| pcmcia | オフ | pcmciautils | PCMCIAサブシステムを初期化するスクリプト。
| php-fpm | オフ | php | PHP FastCGI プロセス管理者デーモンを起動します。
| pulseaudio | オフ | pulseaudio | パルスオーディオシステム全体を起動します。 これはSlintでは推奨されません。
| rpc | オフ | rpcbind | Start/stop/restart RPC (remote process communications) daemオンs needed to use NFS. NFS サーバを実行するには、これらを開始する必要があります。
| サンバ | オフ | サンバ | Samba SMB CIFSファイルを開始/停止/再起動し、CIFSクライアント用のサーバーを印刷します。  これにより、Sambaホスト上のファイルスペースまたはプリンタをCIFSクライアント(Windowsを実行しているPCなど)で利用できるようにすることができます。
| Saslauthd | オフ | cyrus-sasl | saslauthd is a daemon process that handles plaintext authentication requests オン behalf of the SASL library.  CMU の Cyrus SASL ライブラリは、メールサーバでの認証に主に使用されます。
| sendmail | オフ | sendmail | Sendmail MTA (メール転送エージェントまたはメール配信システム) の起動/停止/再起動 Sendmail MTA 。
| シリアル番号 | オフ | util-linux | システムのシリアルポートを初期化して設定します
| setterm | オン |util-linux |  ターミナル属性を設定するためのsettermユーティリティのコマンドラインを提供します(主に画面のブランキングと電源管理に使用されます)。
| smartd | オフ | smartmontools | S.M.A.R.T の状態を監視する smartd デーモンを起動/停止/再起動します。 互換性のあるハードドライブと問題を報告します
| sshd | on | openssh | セキュアシェルサーバーの開始/停止/再起動
| snmpd | オフ | net-snmp |net-snmp SNMP (シンプルネットワーク管理プロトコル) デーモンを開始/停止
| syslog | on | sysklogd | システムロギングデーモンを開始/停止/再起動します。カーネルとシステムの両方'メッセージをログに記録します。
| sysstat | オン | systat | パフォーマンス統計の計算に使用されるシステムアクティビティログをリセットします
| スピーチアップ |  | スピーチアップ | starts/stop/restart スピーチアップスクリーンリーダーは、インストール後にスピーチアップを入力して開始することができます。
| sysvinit | on | sysvinit-scripts | このファイルは、多くのバイナリパッケージにあるSystemVスタイルの起動スクリプトとの基本的な互換性を提供します。
| swapinzram | on | swapinzram | zramを使用してRAM内のスワップブロックデバイスを設定します
| syslog | on | syslogd | システムロギングデーモンを開始/停止/再起動します。
| sysstat | オフ | sysstat | システムアクティビティログをリセットします。
| 臆病度 | オフ | TiMidity++ | Start/stop/restart the TiMidity++ ALSA sequencer client. TiMidity++ is a software synthesizer.  MIDIファイルは、PCM波形データやその他のさまざまなオーディオファイル形式に変換することで再生できます。
| udev | on | eudev | このスクリプトは、/dev ディレクトリにデバイス ノードを追加し、デバイスをスキャンする udev を初期化し、
は適切なカーネルモジュールをロードし、デバイスを設定します。
| ulogd | on | ulogd | netfilter/iptables 関連のログのための userspace ulogd デーモンを開始します。
| vde2 | オン | vde2 | VDE スイッチを開始/停止/再起動します。 VDE はイーサネット準拠の仮想ネットワークで、 'vde_switch' や 'vdeqemu' などのツールが含まれています。
| ワイヤレス | on | wiress-tools|このスクリプトは、PCI、USB、および32ビットカードバスのワイヤレスデバイスを設定します。 通常、このスクリプトは直接実行するのではなく rc.inet1 から呼び出されます。
| yp | on | yptools | Start NIS (Network Information サービスs). NIS provides network-wide distributiオン of hostname, username, and other information databases.
|====

コマンド `サービス` をルートとして使用してサービスを開始または停止できます。 もっと知るには `man service`.

== Glossary

Several definitiオンs in this glossary are taken or adapted from  https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiオン]]アプリケーション:: An applicatiオン program (applicatiオン for short) is
a computer program designed to carry out a specific task typically requested by
end-users.
+
Applications are not generally cオンsidered as part of the operating system, meaning that they can be added to the system after its installation. They
perform non-system-related functiオンs, such as word processing, architectural
design, mechanical design, workstation publishing, or financial analysis.


[[boot]]Boot::
Boot means switch-オン a computer to start an operating system. 複数のオペレーティング
システムを同じコンピュータにインストールできます。 Select which one to load into
RAM and run can be dオンe either by the firmware or by a software named boot
manager (GRUB in Slint's case). The firmware of a computer can support オンe of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiオンs written in a boot sector.
* EFIモードでは、OSローダーはEFIシステムパーティション(ESP)のディレクトリにある実行可能ファイルに格納されたプログラムです。

[[CPU]]CPU::
CPUまたは中央処理ユニットはプログラムの命令を実行します。

[[command]](Command):: コマンドは https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] によって「特定のタスクを実行するための <<shell, シェル>> へのディレクティブ」として定義されます。
+
実行するタスクは、 <<application, アプリケーション>> または <<utility, ユーティリティ>> であることができます。
+
シェルコマンドの基本的な構造は、POSIX 仕様の第 https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 シェルコマンド] 章で定義されています。
+
コマンドの例は <<bash shell>> にあります。

[[console]]コンソール:: The word "console" refers to the beginning of computer
systems, when the system administrator typed commands on a device including a
keyboard and a printer, linked to the computer, the commands typed and the
output from the computer being printed on the console, providing a log of both.
+
In personal computers the user type the commands on keyboard and their output
is printed on a screen, that can be separated from or integrated to the
computer as in a laptop.

[[device]]デバイス::

コンピュータの周辺装置またはアプリケーションにそのように表示されるオブジェクト。[POSIX]

[[directory]]ディレクトリ::
ディレクトリはフォルダの別の名前です。 ファイルシステムは、
パーティション内のファイルを整理するためにディレクトリを使用します。
+
ディレクトリにはファイルや他のディレクトリも含めることができます。 得られた
構造は逆さまのツリーとして表すことができます。 ドライブの最上位ディレクトリ
はルートディレクトリに名前が付けられます。  Linux では、文字 / ツリーの
レベルを分離します。 / は単独でルートディレクトリを表します。/home はユーザに属するファイル
をホストします。/home/didier はユーザのディレクトリに属するファイルをホストします。
/root は root という名前のユーザーのファイルをホストします (システム'の管理者)。
注意: 'root' はトップレベルディレクトリまたはシステム's 管理者を参照できます。

[[drive]]ドライブ::
ドライブは不揮発性データを保存するデバイスであり、電源をオフにするとデータが
消去されることはありません。 例:ハードディスク、SSD、USBスティック、SD
カードリーダー、eMMC。
+
データを保存するメディアは、SDカード、USBスティック、USB経由で接続されたドライブのように、ドライブまたは取り外し可能な
に恒久的に接続できます。
+
リムーバブルメディアまたは外付けドライブにインストールされているオペレーティングシステムは、
ポータブル:それはコンピュータから別のものに移動することができます。

[[display_manager]]ディスプレイマネージャー::
A display manager (or login manager) is a software that displays a window on the
screen in which it asks the login name and password of the user, then starts
the graphical environment chosen by said user.

[[encryption]]暗号化::
暗号化とは、データを認識できない(「暗号化された」)
フォームに変換するプロセスです。 一般的に、
人のみが閲覧できるように、機密情報を保護するために使用されています。 A single file or directory, a partition as well
as a whole drive can be encrypted, which make it accessible only after having
typed a small text called a passphrase, kept secret.

[[file]]ファイル::
コンピュータファイルは、永続的な記憶媒体に記録された同じ名前で収集された一連のデジタルデータです。 大容量ストレージと呼ばれるハードディスク、SSD、DVD、SDカード、USNスティックと呼ばれ、ユニットとして扱われます。
+
ファイルには、テキスト、画像、サウンド、ビデオやコンピュータのプログラムなどのデータを含むことができます。

[[file_system]]ファイル システム::
ファイルシステムは、
パーティション内のファイルとディレクトリを管理するソフトウェアです。 ファイルに含まれるデータ
の物理メディア内の場所を記憶し、それらを読み書きすることができます。 一般的に使用される
ファイルシステムの例としては、vfat、ntfs、ext4、f2fsがあります。 このコマンドは、Linux からパーティションに含まれるデータを読み取ることができるすべてのファイル
システムを一覧表示します。
+
----
grep -v nodev
----

[[firmware]]ファームウェア::
ファームウェアは、ハードウェアを初期化してチェックし、
オペレーティングシステムのRAMに
を選択してロードするソフトウェアです。 または、
ブートマネージャーと呼ばれるソフトウェアを起動します。 ファームウェアは、ROM、EPROM、またはフラッシュメモリなどの不揮発性メモリ
デバイスに保持されます。
がコンピュータを起動したときに最初に実行されるソフトウェアです。 It provides a menu allowing to configure the hardware and
select in which mode (Legacy or EFI) to boot, and in which order look for the
operating system or other application (like the GRUB boot manager) to run.

[[kernel]]Kernel::
Linuxカーネルは、アプリケーションとハードウェアの間の
相互作用を処理するSlintシステムの中核にあるソフトウェアです。
+
/bootディレクトリにインストールされた単一のファイルとして表示されます。 例えば、/boot/vmlinuz-generic-5.12.11 というファイルはカーネルで、kernel-generic パッケージからのものです。
+
起動時にカーネルがRAMにコピーされます。

[[initrd]]Initrd::
initrd (より正確には initramfs または Slint の初期の RAM ファイルシステム) は
圧縮アーカイブファイルとして提供される Linux システムです。 ブート時には、
カーネルがRAMにロードされた直後に、インバードもRAMにロードされます。 Its file /init
runs: it loads needed kernel modules in RAM, register the devices, possibly
unlock the root device, mount the pseudo file systems then switch to the root
file system to actually start the system.
+
initrdは、ディレクトリブートにインストールされた単一のファイルとしてそれ自身を表示します。
例えば、initrd-generic-5.12.11 ファイルは initrd です。

[[live_system]]ライブシステム::
ライブシステムは、ハードディスクやSSDのようなデバイス
にインストールされる代わりに、オペレーティングシステムです。 完全に
 <<RAM>> に横たわっています。
+
An initrd is also a live system, and so is a Slint インストーラ wich is basically an initrd.

[[partition]]パーティション::
パーティションは、ハードディスクやSSDなどのストレージメディアのセクションです。 オペレーティングシステムによって別の論理ボリュームとして扱われる
であるため、
は別のメディアと同様に機能します。

[[partition_table]]パーティションテーブル::
A partition table is the permanent structure recording how information is laid
out on a media, mainly recording the beginning and end of each partition on
the media.
+
The most common types of partition tables are the DOS partition table, initially
used by the MS-DOS operating system, and the GUID Partition Table or GPT, which
allows to handle more partitions and larger drives.

[[program]]プログラム::
A prepared sequence of instructions to the system to accomplish a defined task. The term "program" encompasses applications written in the Shell Command Language, complex utility input languages (for example, awk, lex, sed, and so on), and high-level languages. [POSIX]

[[RAM]]RAM::
RAMはRandom Access Memoryの略称です。 このようなデバイスには揮発性データ
が保存されており、電源をオフにするとデータが消去されます。

[[shell]]シェル:: テキスト入力のシーケンスをコマンドとして解釈するプログラム。 入力ストリーム上で動作したり、端末からコマンドを読み込んだりすることがあります。 The syntax of the commands
that can be interpretd by the shell can vary along the shell in use but are mainly defined in the the chapter
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2.
Shell Command Language] of the POSIX specification.
+
Slint ships several programs acting as shell, listed in the file /etc/shells. The *bash* shell is used by default.

[[swap]]入れ替え::
A swap space is used to tentatively store data previously in RAM on a device
like a hard disk or SSD, either because else the RAM would become full, or to
free space in RAM to store there most frequently used data. The swap space can
be a partition on a drive of type 'Linux swap' or a regular file stored in an
an existing partition. 「zramでのスワップ」もあります:この場合、データ
はRAMに保存されますが、圧縮形式で保存されます。 使用可能なRAMのサイズに変更します。

[[terminal]]ターミナル::
Historically a terminal was a physical device composed of a keyboard and a screen
used to type commands and receives responses from a remote computer.
+
Nowadays the commands can be typed in console (or text) mode or in graphical
mode.

[[utility]]ユーティリティ::
ユーティリティは、シェルから名前で呼び出すことができるプログラムです(これはいくつかの場合でもあります <application,applications>>)。
+
Utilities are a part of the operating system (but not of the kernel).
They perform system-related functions, such as listing directory contents,
checking file systems, repairing file systems, or
extracting system status information.
+
An utility may be invoked as a separate program that executes in a different
process than the command language interpreter, or it may be implemented as a
part of the command language interpreter.
+
For example, the echo command (the
directive to perform a specific task) may be implemented such that the echo
utility (the logic that performs the task of echoing) is in a separate program;
therefore, it is executed in a process that is different from the command
language interpreter. Practically this means this means that in this case the utility is a program distinct from the shell
+
Conversely, the logic that performs the echo utility
could be built into the command language interpreter; therefore, it could
execute in the same process as the command language interpreter. Such an utility is said "built-in" the shell.

[[virtual_terminal]]仮想ターミナル::
仮想端末は、物理端末をシミュレートするソフトウェアです。 デバイス
は、キーボードとスクリーンで構成されており、
コンピュータとリモートで通信することができます。
