
=  Slint Handbook (14.2.1)
:toc: left
:toclevels: 2
:toc-title: Содержание
:pdf-themesdir: themes
:pdf-theme: default
:sectnums:

==  Знакомство со Slint

=== О Slint

Slint — это https://en.wikipedia.org/wiki/Linux_distribution[дистрибутив Linux], основанный на http://www.slackware.com/[Slackware], полиглот, простой в установке, универсальный, удобный для начинающих и доступный для людей с ограниченным зрением.

Система Slint функционирует из коробки и может быть адаптирована под большинство требований к вычислениям.

==== Возможности

Предложены два режима установки: автоматический (без ввода команд Linux) и ручной для тонкой настройки. Программа установки включает в себя документацию.

Slint доступен для пользователей с недостатками зрения с речью и braille, от установки до использования в консоли, как в графическом окружении.

Широкий ассортимент программного обеспечения для серверов, настольных компьютеров и ноутбуков установлен во всех системах Slint, , которые включают в себя несколько графических окружений рабочего стола: KDE (необязательно), LXDE, MATE, XFCE и легкие оконные менеджеры. Все графические окружения обеспечивают легкий доступ ко всем приложениям и системным операциям, с автомонтированием съемных устройств, а также уведомления о доступных обновлениях установленного программного обеспечения, немедленного доступа к Интернету, остановки, перезагрузки и отключения системы. Каждое окружение рабочего стола имеет схожее расположение панелей и прикладное меню для обеспечения совместимой среды.

Выбранный язык будет использоваться для интернационализированных приложений.

Slint Dashboard осуществляет централизованный доступ к аппаратным и системным настройкам, пакетам, системным инструментам, документации и утилитам.

Сверните корабли со многими приложениями из коробки для записи и чтения и преобразования документов в различных форматах, общаться по электронной почте, Текстовый и аудио чат, воспроизведение аудио и видео, отправка и получение документов по пиру, редактирование аудио, видео и графических документов, разработка приложений. Он полностью может использоваться как сервер на консоли и использовать один из нескольких подключенных рабочих столов.

Многие приложения доступны для пользователей с недостатками зрения, включен широкий выбор TTS и связанных с ними голосов, если вам все еще нужны другие, они легко устанавливаются и могут быть использованы как в текстовой среде (консоль), так и на рабочем столе.

Некоторые встроенные инструменты облегчают администрирование и настройку вашей системы Slint.

Многие другие приложения легко собраны в виде пакетов программного обеспечения с помощью простой команды или нескольких кликов. Тысячи пакетов программного обеспечения находятся у вас в руках!

Пользователи Slint уведомляются об обновлениях установленных пакетов, как только они будут доступны, легко устанавливаются по запросу. Это защищает вашу систему.

Предпочитаемые по умолчанию настройки приложений представлены и могут быть легко настроены.

==== Содержание, версии и релиз модели.

Программа установки Slint предоставляет только полную установку. Только рабочий стол KDE является необязательным.

Slint, основанный на Slackware, мы предоставляем новую версию Slint вскоре после выхода версии Slackware.

Однако Слинт следует за выпуском "полупрокатки", что означает, что в течение жизненного цикла данной версии, в дополнение к обновлениям в качестве исправлений безопасности и основных исправлений ошибок, некоторые программы избирательно обновляются для внесения улучшений и добавляются для использования новых возможностей. Это относится к программному обеспечению, способствующему тому, чтобы Slint стал доступен для слепот, как и для чтения с экрана.

Мы рекомендуем пользователям переключиться на новую версию как можно скорее после ее выпуска. До сих пор мы смогли предоставить инструкции и вспомогательные скрипты, позволяющие обновиться, а не с нуля новый релиз. Мы сделаем все возможное, чтобы быть в состоянии с будущими версиями, даже если полная резервная копия пользовательских файлов, после установки может быть проще восстановить пользовательские файлы, особенно для настольного компьютера или ноутбука.

=== Об этой книге, другие источники информации

Эта книга предназначена для новичков, которым она руководит в процессе установки и использования. Концепции и конвенции, относящиеся к Slint и общим в дистрибутивах Linux, представлены и глоссарий прилагается.

Мы стараемся учесть людей, исходящих от Windows или MacOS в качестве пользователей другого дистрибутива, например Ubuntu.

Документация о установленном программном обеспечении обычно доступна в системе Slint. Мы расскажем в этой книге, как получить к ней доступ.

Имеются и другие источники информации:

* Информация, которую часто предоставляют на своем сайте авторы программного обеспечения, включенные в Slint.
* http://docs.slackware.com/[Проект документации по Slackware] и особенно http://docs.slackware.com/howtos:start[статей HOWTO] Многие применимы непосредственно к Slint, некоторые адаптации и обновления могут потребоваться.
* Помимо дистрибутива Arch, ArchWiki часто предоставляет полезную статью о программном обеспечении, поставляемом в Slint. Например поиск "арка вики-товарища" приводит к https://wiki.archlinux.org/index.php/MATE[этой странице о MATE]. Предупреждение: представленная информация может потребоваться адаптировать в качестве слепого и арки в зависимости от конкретного аспекта. Например, Arch использует систему как init систему, и данное программное обеспечение может быть настроено по-умолчанию в Slint и Arch.
* И, конечно, поисковик в Интернете часто помогает найти ответы на вопросы и решения проблем.

=== Поддержка

Вы можете получить помощь через эти каналы:

* Список рассылки Slint является основным каналом поддержки. Чтобы зарегистрироваться, напишите slint-request@freelists.org в качестве темы: 'subscribe', затем ответьте на письмо с подтверждением, которое вы получите. Затем, чтобы узнать больше по электронной почте slint-request@freelists.org с заголовком 'commands' или 'help'. После регистрации напишите slint@freelists.org.
* Архивы списка рассылки доступны https://www.freelists.org/archive/slint[здесь].
* На IRC: чат на канале #slint, сервер irc.libera.chat, регистрация не требуется.
* Mumble: сервер slint.fr (по назначению по другому каналу).
* Форум https://forum.salixos.org/viewforum.php?f=44[Slint] организован нашими друзьями на Salix (еще одним производным Slackware). Необходима регистрация.


Чтобы узнать больше, смотрите ссылки в разделе Информация в Slint Dasboard, посетите нашу https://slint.fr/wiki/doku.php?id=en/start[wiki] или просто тип: slint-doc в терминале после установки.

=== Перевод и другие вклады в проект Slint

Кремень нужен переводчикам! Если вы хотите принять участие в работе над переводом, прочитайте инструкции в https://slint.fr/doc/translate_slint.html[Translate Slint].

Файлы перевода хранятся на https://crowdin.com/project/slint[Crowdin].

Если вы хотите внести свой вклад в Slint для других задач, просто отправьте сообщение в список рассылки или оставьте строку на адрес didieratslintdotfr. Разумеется, переводчики также приглашаются в список рассылки!

===  Благодарности

Проект Slint существует в основном за счет напряженной работы переводчиков Slint и других участников, благодаря всем вам!

Благодарим Джорджа Влахавы за его советы и инструменты для участников проекта SlackBuilds.org, которые помогают создать так много дополнительных программ.

Slint базируется на Slackware, созданном Patrick J. Volkerding and contributors. Спасибо! Я призываю всех пользователей Slint внести вклад в финансирование Slackware, а также пожертвовать проекту Salix.

Хранилища Slint размещены бесплатно Darren 'Tadgy' Austin. Я призываю всех пользователей Slint внести свой вклад в финансирование хоста https://slackware.uk/

Links for financial contributions: +
https://www.patreon.com/slackwarelinux[Become a Slackware patron] or https://paypal.me/volkerdi[Поддержка Slackware] +
Follow the links on top of http://slackware.uk/slint/x86_64/slint-14.2.1/[this page] to support Slackware UK +
https://salixos.org/donations.html[Donations to Salix]

==  Install Slint

Эта часть Справочника проходит через процесс загрузки Slint, проверяя ISO-образ с помощью чек-суммы, запись ISO на носитель установки, разметка жесткого диска и краткое описание процесса установки.

=== Требования

Текущая версия Slint может быть установлена на компьютерах, отвечающих этим требованиям:

* Архитектура: x86_64 (64-битный процессор), также известный как AMD64
* Бесплатное или свободное место на диске (жесткие диски, SSD, NVME, eMMC): по крайней мере 28G в авторежиме. Полная установка Slint требует около 20G, без пользовательских файлов или дополнений.
* ОЗУ: по крайней мере 2G
* Имеется DVD диск или слот USB с возможностью загрузки микропрограммы на DVD или USB-накопитель. Пустой DVD или 4G или более USB стик может быть использован в качестве установочного носителя

NOTE: Безопасная загрузка должна быть отключена для установки Slint.

=== Особенности программы установки

* Программа установки является "живой системой", работающей в памяти: она не будет изменять установленную систему до тех пор, пока вы не сообщите об этом.
* Для незрячих пользователей программа установки полностью применима к Брайлю и чтению с помощью программы чтения с экрана громкоговорителя.
* Для опытных пользователей он включает все необходимые утилиты для подготовки <<drive, диска>> , на котором будет установлен Slint.
* Вместо этого пользователю требуется лишь ответить на вопросы и предоставить контекстную справку о них.
* Программа установки может освободить место для Slint на диске, где вы хотите установить его вместе с другим Linux при определенных условиях.
* Если установлена самостоятельно на съемном устройстве, подключенном через USB, Slint может быть сделан портативным, i. . Используется на любом компьютере, который может загрузиться с USB-накопителя.
* Программа установки может зашифровать диск, на котором установлен Slint. Это предотвращает кражу данных в случае потери или кражи машины или съемного диска.
* Slint может быть установлен в собственном накопителе или параллельно с другой системой.

=== Подготовка

<<download_and_verify, Скачать и проверить ISO-образ>> +
<<write_the_iso, Напишите ISO-образ на носителе установки>> +
<<make_room_for_Slint, Создать комнату для слепого>> +
<<create_partitions_for_Slint, Создать разделы для слепой>>

[[download_and_verify]]
====  Скачать и проверить ISO-образ Slint

Последняя версия дистрибутива Slint - 14.2.1

Последний ISO-образ установки всегда доступен в https://slackware.uk/slint/x86_64/slint-14.2.1/iso[этом каталоге]

[TIP]
====
До тех пор, пока вы используете Slint версию 14.2. нет необходимости переустанавливать при создании нового ISO, так как он предоставляет только новые возможности программы установки и новые или обновленные пакеты'с которыми вы также можете обновлять свою систему.
====

Имя файла ISO, указанное ниже, является лишь примером, который вы адаптируете к текущему имени при загрузке.

Если вы запускаете Windows, Интернет с аргументом "check sha256sum windows" скажет вам способы продолжить.

Если вы используете Linux, вы можете загрузить ISO-образ и контрольную сумму sha256:
----
wget https://slackware.uk/slint/x86_64/slint-14.2.1/iso/slint64-14.2.1.4.iso
wget https://slackware.uk/slint/x86_64/slint-14.2.1/iso/slint64-14.2.1.4.iso.sha256
----

Для проверки целостности загруженных файлов введите следующую команду:
sha256sum -c slint64-14.2.1.4.iso.sha256
в результате:
OK

----
sha256sum -c slint64-14.2.1.4.iso.sha256
----
Результатом должно быть : OK +
Иначе, повторить загрузки.

[[write_the_iso]]
====  Напишите ISO-образ на носителе установки

Вы можете использовать DVD или USB-носитель как установочный носитель.

[[make_a_bootable_usb_stick]]
===== Сделать загрузочный USB-палки

On a ++Linux++ system, plug in the USB stick, and check it's name with the following command:

----
lsblk -o модель,имя,размер,fstype,точка подключения
----

[WARNING]
====
Внимательно просмотрите вывод команды чтобы убедиться, что вместо имени USB-карты имя раздела не будет напечатано на жестком диске.  Все предыдущие содержимое USB-карты или поврежденного жесткого диска будут *ПОТЕРЯМИ* и *IRRECOVERABLE*.
====

Пусть'ы предполагают, что имя USB-карты будет /dev/sdb. Это может быть названо иначе, поэтому don't скопировать слепое следующую команду.  Синтаксис команды для записи Slint ISO на USB-накопитель, который находится в /dev/sdb, выглядит следующим образом:

----
dd if=slint64-14.2.1.4.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
Команда выше предполагает, что *если=* указывает на путь Slint ISO и *=* указывает на имя USB-накопителя.  Эти значения могут отличаться в вашей системе.
====

On ++Windows++ use an application like http://rufus.akeo.ie/[Rufus].  Он является свободным и открытым исходным кодом.

1. Откройте программу Rufus, с которой вы скачали ее, чтобы запустить ее.
2. Выберите Создать загрузочный диск и выберите ISO Image из выпадающего меню.
   Нажмите на значок диска и перейдите в файл Slint .iso и выберите его.
3. Чтобы удостовериться, что флеш диск совместим с UEFI, выберите FAT32 для <<file_system, файловой системы>>.
4. Чтобы создать прошивку с помощью «Нажмите любую клавишу для загрузки из USB», выберите опцию Create extended label and icon files (Создать расширенную метку и файлы значков).
5. Когда вы закончите выбор параметров, нажмите Начать при появлении запроса, подтвердите, что вы хотите стереть флэш-диск.
6. Файлы .iso начнут копировать на флэш-диск (процесс может занять несколько минут). Когда Rufus завершен, закройте программу, извлеките и удалите флеш диск.

[[make_a_bootable_DVD_disc]]
=====  Make a Bootable DVD Disc

On a ++Linux++ system insert the DVD and type the following command:

----
growisofs -speed=2 -dvd-compat -Z /dev/sr0=slint64-14.2.1.4.iso
----

Обязательно введите полный путь к Slint ISO в файловой системе.

On ++Microsoft Windows 2000/XP/Vista/7++ you can write to a DVD using the application http://infrarecorder.org/[InfraRecorder].  Он является свободным и открытым исходным кодом.

On ++Microsoft Windows 7/8/10++ you can use the http://windows.microsoft.com/en-US/windows7/Burn-a-CD-or-DVD-from-an-ISO-file[Windows Disk Image Burner] utility that is shipped with Microsoft Windows.

[[make_room_for_Slint]]
====  Сделать комнату для крепости

Выделить компьютер или, по крайней мере, привод к Slint, упрощает установку и поэтому рекомендуется. Затем пропустите этот шаг и запустите программу установки.

Но вы также можете поделиться накопителем с уже установленной операционной системой, такой как Windows, Mac OS, *BSD или другой дистрибутив Linux,

Затем вам понадобится свободное место для Slint в конце таблицы разделов этого диска (после последнего раздела). По крайней мере 20G необходима для самой системы, но вам также понадобится некоторое место для пользовательских файлов и установить другое программное обеспечение. Сглаживание последнего раздела диска может быть сделано после того, как вы запустили программу установки, набрав команды linux, если вы являетесь пользователем питания Linux. Это также может быть сделано программой установки в автоматическом режиме при соблюдении следующих условий:

* Привод оборудован таблицей перегородки GUID (GPT)
* Последний раздел содержит внешнюю файловую систему <<file_system, >>.
* Не менее 28G можно освободить в нем.
* Машина загрузилась в режиме EFI (не Legacy)

Иначе, перед установкой вам потребуется место для Slint `gparted` или из Windows (рекомендуется при установке Windows). Однако, при некоторых условиях, Слинт может сделать это для вас, как указано в
<<Automatic_installation, Автоматическая установка>>

===== Как освободить место в объёме Windows

Ниже кратко описаны шаги, указанные в
https://docs.microsoft.com/en-us/windows-server/storage/disk-management/shrink-a-basic-volume[этом документе]
.

1. Откройте командную строку и введите её из Windows:
+
`diskpart`

2. В строке Diskpart введите:
+
`громкость списка`
+
Обратите внимание на количество простоты громкости, которую вы хотите уменьшить.

3. Выберите том который вы хотите уменьшать, в котором должна быть файловая система ntfs, набрав
+
`выбрать том <number>`

4. , чтобы узнать максимальный размер которого объем может быть уменьшен:
+
`сужать запрос макс`

5. Определите <size> в мегабайтах свободного пространства, которое вы хотите создать. Оно не должно быть больше, чем максимальный размер с помощью предыдущей команды. Возможно, вы захотите оставить некоторое пространство доступным в томе Windows, чтобы иметь возможность хранить в нем больше данных.

6. Введите эту команду:
+
`сокращение желаний=<size>`
+
размер - это число в МБ, например за 30 ГБ, зная, что тип G=1024М:
+
`сокращение желаний=30720`
+
Держите достаточно неиспользуемого места в томе системы, чтобы позволить установить обновление Windows.

Или вы можете использовать Диск-менеджер: выберите том который вы хотите уменьшить, щелкните правой кнопкой мыши на нем, выберите "Уменьшить громкость", подождите, пока не появится максимальное пространство для которого может быть уменьшена громкость, адаптируйте значение, чтобы оставить
немного пространства, чтобы позволить хранить больше данных там, где вы видите подходящую, а затем нажмите кнопку термоусадок.

===== Как освободить место на Linux.

Вы можете использовать http://gparted.org/index.php[gparted], или графический инструмент для управления разделами, предоставляемый вашим дистрибутивом.

TIP: Если 28G может быть освобожден в последнем разделе диска с помощью GPT с файловой системой ext4, то программа установки может сократить его для вас.

[[create_partitions_for_Slint]]
====  Создать разделы для Slint

Если вы выберете режим автоматической установки и выделите устройство для Slint, то программа установки будет размещать его для вас. После этого вы можете настроить расположение разделов с помощью одной из перечисленных ниже команд, если yiu откуда угодно.

Если вы собираетесь использовать режим установки вручную, вы можете создать разделы для Slint как до, так и во время установки.

Если вы не привыкли к Linux, то перед установкой это, скорее всего, будет проще. Для этого мы рекомендуем использовать http://gparted.org/index.php[gparted]. Gparted может уменьшить существующие разделы для создания комнаты, а также создать новые разделы в свободном пространстве.  Если у вас нет системы, поддерживающей Gparted (Microsoft Windows), вы можете использовать http://gparted.org/livecd.php[Gparted Live].
Команды cfdisk, fdisk, gdisk, cgfdisk и parted доступны у программы установки. Вы можете использовать тему для разделения всего устройства или создания разделов для Slint в свободном пространстве.

Требуется Slint:

* Раздел типа Linux, размер не менее 20G, больше лучше (по крайней мере 30 G).
* Если вы загрузитесь в режиме EFI, то тип "система EFI" (код ef00) должен быть не менее 100M. Даже если вы загрузитесь в режиме Legacy он выиграл't больно иметь одну.
* В случае GPT (GUID Partition Table), раздел типа BIOS Boot (ef02), размер 4M, для загрузки в режиме Legacy режим. Даже если вы загружаетесь в режиме EFI, он выиграл't больно иметь.
* При необходимости раздел типа "подкачка". Это рекомендуется, особенно если вы хотите сжать машину и если у вас меньше 8G оперативной памяти. Однако вместо этого вы можете настроить файл подкачки после установки.

Вы также можете выделить раздел для /home (но это не обязательно, я don't) и других разделов для конкретных случаев использования.

[NOTE]
====
Slint сам нуждается в около 20 гигабайт пространства, но рекомендуется корневой раздел 50 гигабайт. Вам может потребоваться установить дополнительное программное обеспечение или больше места для хранения ваших файлов.  Чем больше пространства, тем лучше, если вы планируете хранить фотографии, видео, музыку и т.д.
====

=== Установка Slint

<<Start_of_the_installation, Start of the installation>> +
<<Accessibility_of_the_installer, Доступность of the installer>> +
<<Usage_of_the_installer, Usage of the installer>> +
<<Automatic_installation, Automatic installation>> +
<<Manual_installation, Manual installation>> +
<<Slint_in_an_encrypted_drive, Slint in an encrypted drive>> +
<<first_steps_after_installation, First steps after installation>>

[[Start_of_the_installation]]
==== Начало установки

Если необходимо, настройте прошивку машины для загрузки с DVD или карты памяти USB, которые вы подготовили

Вставьте установочный носитель (DVD или USB-накопитель) и перезагрузите машину. Слепые пользователи услышит 'beep' при отображении загрузочного меню.

Запустите программу установки, просто нажав Enter.

Программа установки сначала будет проверять звуковые карты.

Это может помочь установить рабочий по умолчанию, а также использовать для речи во время установки, используемой некоторыми слепыми пользователями.

Если программа установки обнаруживает более одной звуковой карты, она произведет для каждого: +
нажмите Enter для выбора этой звуковой платы <sound card id> +
Нажмите Enter как только это услышат, , чтобы подтвердить, что предлагаемая звуковая карта работает. Этот параметр будет сохранен в новой системе в /etc/asound.conf.

На следующем шаге, когда вас просят подтвердить (набрать) или запретить (просто нажмите Enter), что вы хотите произнести во время установки. Брайль всегда доступен во время установки.

Затем вы выберете, подтвердите или измените язык, используемый в процессе установки. Затем все экраны будут на выбранном языке, если перевод на этот язык будет завершен.

Если вам нужно добавить дополнительные параметры ядра в командную строку перед нажатием клавиши Enter выполните следующие действия:
[NOTE]
====
Имейте в виду, что карта клавиатуры США будет использоваться при наборе. +
Ctrl+x означает "Нажмите и удерживайте клавиши Ctrl или Control как если бы это была клавиша Shift, то нажмите клавишу X"
====
----
Нажмите клавишу e
Нажмите стрелку вниз три раза
Нажмите кнопку End
Нажмите пробел
Введите параметры ядра (примеры ниже)
Нажмите Ctrl+X для загрузки (не нажимайте Enter!)
Нажмите Enter для загрузки.
----

Например, для настройки драйвера произношения для вашего аппаратного синтезатора можно набрать такой параметр ядра, как:
----
speakup.synth=apollo
----
Вы также можете включить в командную строку настройки для вашего устройства Брайля в этой форме:
-----
brltty=<driver code>,<device>,<text table>
-----
Например, для установки с устройством Papenmeier, подключенным к USB с типом текстовой таблицы на французском языке:
-----
brltty=pm,usb:,fr_FR
-----
NOTE: устройство Брайля подключено через USB, оно всегда должно быть распознано, может быть, только текстовая таблица выиграла't быть хорошей если вы сначала набрали'т в настройках.

В любом случае, так как таймаут не будет, загрузка начнется только при нажатии [Enter].

Речь и Брайль будут доступны в начале установки.

[[Usage_of_the_installer]]
==== Использование программы установки

Если вы знакомы с командной строкой, вы можете пропустить эту тему.

Главное меню установки показано ниже:
....
Добро пожаловать в установщик Slint! (версия 14.2.1)

Доступные команды (не вводите кавычки):

'doc', чтобы узнать о возможностях и использовании программы установки.
'auto' для запуска полуавтоматической, управляемой установки.
'настройки' для запуска ручной установки.

Мы рекомендуем сначала набрать 'doc' для подготовки ручной установки, или если
вы хотите зашифровать диск, на котором будет установлен Slint, или если вам нужно
уменьшить размер раздела, чтобы освободить место для Slint вместе с другой системой.
Когда вы закончите чтение, это меню будет отображено снова.
....

Как только появится это меню, у вас есть рука об установочном процессе.

Вы читаете экран и печатаете команды на <<virtual_terminal, виртуальном терминале>>. Программа установки
включает в себя несколько виртуальных терминалов с одной и той же физической клавиатурой и экраном
, которые можно использовать параллельно.

Программа установки запускается в виртуальном терминале 1 под названием *tty1* , но вы можете переключить
на другой. Например, вы можете переключиться на *tty2* нажав
*Alt-F2* , затем Enter, чтобы активировать его, а затем вернуться к *tty1* нажав
*Alt-F1*, без стирания информации, отображаемой на обоих терминалах.
*Alt-F1* означает: нажмите и удерживайте клавишу *Alt* , затем нажмите клавишу *F1*.

Это может быть полезно для продолжения чтения документации во время установки:
например, вы можете переключиться на *tty2* для начала установки, переключиться на *tty1* на
продолжить чтение документации, затем переключитесь на *tty1* , чтобы перейти к
следующему шагу установки.

Это также может быть использовано для ознакомления с глоссарием при чтении других документов.

Четвертый виртуальный терминал или *tty4* отображает сообщения, которые предоставляют информацию
полезную для отладки, в противном случае он не используется.

Программа установки имеет несколько режимов взаимодействия с вами, пользователь:

. Вы набираете команды в запросе и читаете их вывод.
. Программа установки задает вопрос, введите ответ и подтвердите его, нажав Enter.
. Программа установки отображает меню выбора или опций: вы выбираете один из них, используя клавиши со стрелками вверх и вниз, затем подтвердите свой выбор, нажав Enter, или отмените, нажав Escape.
. Программа установки отображает информацию в папке. Затем используйте клавиши со стрелками для чтения следующей или предыдущей строки, нажмите пробел для отображения следующей страницы, Q для остановки чтения документа.

[[Automatic_installation]]
==== Автоматическая установка

В автоматическом режиме программа установки предоставляет настройки по умолчанию, включая графическое окружение (Mate). После запуска
вашей новой системы, вы можете просмотреть и изменить все настройки.

Ниже подробно описаны шаги по установке.

. Установка Slint требует не менее 28G места на диске. Программа установки сначала предоставляет дисков, их размеры и свободное место на них. В зависимости от результатов, он позволяет установить на выделенный диск или на свободное место в диске.
.. Установка на выделенном диске.
+
В этом режиме все предыдущее содержимое диска будет удалено. Если он содержит файлы, которые вы хотите сохранить, сохраните их сначала!
+
Если привод удаляется и подключен через USB, программа установки может сделать Slint переносимым, позволяет использовать его на любом компьютере, способном загружать с внешнего USB-накопителя.
+
При желании можно зашифровать накопитель для защиты от кражи данных в случае потери или кражи накопителя или компьютера. Так как есть важные предостережения, сначала внимательно прочитайте шифрование документа.

.. Установка в накопитель, общий для другой системы. Это позволяет устанавливать Slint при сохранении другой системы, использующей только один диск.
+
Это допускается, если накопитель имеет по крайней мере 28G свободного места или может быть освобожден в конце имеет GPT (GUID таблицу), и программа установки загружается в режиме EFI: в этой конфигурации обе системы будут загружаться без ущерба друг другу.

. Вы выбираете размер основного раздела Slint, а также размер дополнительного раздела, опционально оставляя немного свободного места на диске для будущего использования.
+
Основной раздел обычно содержит файловую систему ext4. Однако, если она установлена на SD-карте или на диске eMMC, она будет иметь файловую систему f2fs.
+
Перед началом установки у вас будет возможность просмотреть и изменить свой выбор.
+
После подтверждения устанавливаются базовые пакеты, которые займут несколько секунд.

. Если вы выбрали зашифрованный диск, введите ключевую фразу, которая будет использоваться для разблокировки диска при каждой загрузке.
. Вы выбираете пароль для пользователя "root." Это системный администратор, который имеет все привилегии. Вы также создаете обычный пользовательский аккаунт, укажите, нужен ли вам доступный выход Брайля, и вы хотите ли вы войти в Slint в текстовом или графическом режиме.
+
[NOTE]
====
Если вы использовали английский язык (США) во время установки, вы выбираете, какой язык использовать для установленной системы, иначе программа установки устанавливает то же самое, что и во время установки.
====
. Программа установки пытается установить подключение к Интернету позволяет предлагать часовой пояс, соответствующий вашему географическому положению, а затем устанавливать пакеты удаленно по мере необходимости. Вы устанавливаете или подтверждаете предложенное.
. Затем программа установки создает файл подкачки в системном разделе, который после установки можно легко изменить. По умолчанию, дополнительный раздел подкачки 1. когда размер физической памяти устанавливается в zram каждый раз при загрузке Slint.
. Пакеты устанавливаются на диск (серии KDE необязательны). Программа установки попытается установить подключение к Интернету, чтобы он мог загрузить и установить последнюю версию каждого пакета, в том числе те, которые предусмотрены после выхода ISO-изображения. Таким образом, вы выиграли't должны скачать и установить эти новые или обновленные пакеты после установки.
+
Установка всех пакетов занимает от 10 до 40 минут в зависимости от оборудования.

. Далее система настроена и установлен менеджер загрузки GRUB. Если Slint был установлен на выделенном диске, он может загружаться как в режиме Legacy так и EFI. В противном случае, он загрузится только в режиме EFI. В обоих случаях у загрузочного меню будет дополнительная "спасательная" загрузочная запись для обнаружения и загрузки установленной ОС.
. Вам будет предложено создать карту восстановления на флешке USB. Вы можете использовать это для загрузки Slint, если не удается загрузиться из загрузочного меню.

Наконец, удалите установочный носитель и перезагрузите, чтобы запустить новую систему Slint.
Вы можете отобразить предварительный просмотр загрузочного меню перед перезагрузкой.

[[Manual_installation]]
==== Ручная установка

Ручная установка состоит из двух основных этапов.

. Подготовить диск(ы) для установки. Сюда входят: проектирование макета разделов, создание разделов и их форматирование, т. е. создание файловых систем в них. При желании программа установки может отформатировать разделы Linux.
. Введите *конфигурацию* для дальнейшей подготовки, установки и конфигурации.

===== Подготовить диск(ы) для установки.

Если возможно установить Slint на свой диск.

Вы также можете установить его в накопитель, который используется другой системой, но желательно
если загрузится в режиме EFI, для того, чтобы каждая система, имеющая свой собственный загрузчик, была
независимой от других и их обновлений. Затем вам нужно освободить место на
диске для установки Slint. Вы можете использовать команду 'freespace' программы установки Slint
для этого, если последний раздел диска имеет ext2, ext3 или
ext4 файловая система, иначе сделайте это из уже установленной системы.

По возможности, разрешите машине загрузиться в режиме EFI и настройте GPT (GUID
таблицу разделов) для целевого диска, для максимальной гибкости.

Программа установки использует GRUB для загрузки как EFI, так и Legacy.

Чтобы установить Slint на свой диск, вам понадобится:

* Чтобы загрузиться в режиме Legacy с GPT, тип BIOS Boot, необходимый
GRUB в этом контексте. Размер 1M для этого раздела достаточно. Он
зарезервирован для GRUB и не должен быть форматирован.
* Для загрузки в режиме EFI раздел типа ESP (EFI System Partition) размером
100M для хранения загрузчика EFI OS. Этот раздел может быть создан в GPT как в
таблице разделов DOS.
* раздел размером не менее 28G для системы, типа Linux.

В случае GPT мы рекомендуем установить BIOS Boot раздел и ESP для
большей гибкости, позволяет загружать Slint как в EFI, так и в режиме Legacy.

Создание других разделов необязательно. Если вы хотите раздел подкачки, он должен
иметь тип подкачки Linux. Кроме того, вы можете настроить файл подкачки.
'setup' предложит установить его после создания файловой системы
корневого раздела.

Программа установки включает в себя несколько приложений для разметки: cfdisk, fdisk, sfdisk,
cgdisk, gdisk, sgdisk, parted. Приложения с "g" в их имени могут
обрабатывать только gpt, parted может обрабатывать таблицы разделов DOS и GPT. fdisk,
cfdisk и sfdisk могут работать с таблицами разделов DOS. Кроме того, wipefs
(для удаления предыдущей таблицы разделов и подписей файловой системы) и partprobe
(для информирования ядра об изменениях в таблице разделов).
Приложение lsblk отображает информацию о блокировке устройств и разделов.

Вы можете отформатировать разделы самостоятельно, или позволить программе установки сделать это за вас. Здесь
«формат» означает: создание файловой системы для управления файлами в разделе. В
имейте в виду, что ESP должен иметь файловую систему vfat, раздел Bios не содержит файловой системы
вообще. For Linux partitions the Slint installer can handle these file
system types: btrfs, ext2, ext4, f2fs, jfs, reiserfs, xfs.

Программа установки может установить точки монтирования разделов, разделенных или используемых
Windows, для разрешения доступа к ним из Slint. Они должны иметь файловую систему типа
vfat, msdos или ntfs, либо настроенные Windows, либо созданные перед запуском установки.

===== Действия, управляемые программой установки.

Программа установки отображает меню с этими элементами или шагами:
....
KEYMAP для изменения названия клавиатуры (необязательно)
ADDSWAP в дополнение к разделам подкачки (необязательно)
TARGET для настройки целевых разделов
ВЫКЛЮЧИТЬ для выбора исходных файлов, содержащих пакеты программного обеспечения
УСТАНОВИТЬ для установки программных пакетов
CONFIGURE для настройки вашей системы Slint.
....

Эти записи прокомментированы ниже. TARGET, SOURCE, INSTALL и CONFIGURE
шаги являются обязательными и должны выполняться в этом порядке.

* KEYMAP может быть использован для изменения выбранной раскладки клавиатуры.
* ADDSWAP может быть использован для настройки раздела(ов) подкачки. Вместо этого вы можете настроить swap-файл после установки и/или установить swap-пробел в zram.
* В шаге TARGET программа установки сначала спрашивает, какой раздел Linux будет размещать корневой каталог (/), , то спрашивает, хотите ли вы установить в нем файловую систему. Вы соглашаетесь, если это еще не сделано, ELSE INSTALLATION WILL на шаге INSTALL из-за нехватки места для установки пакетов. Затем выберите файловую систему из предложенных.
+
Затем в программе установки перечислены другие разделы Linux, и устанавливает для каждого если вы хотите
использовать его в Slint точке монтирования и файловой системе.
* На шаге SOURCE вы выбираете носители, содержащие пакеты программного обеспечения для установки. Скорее всего, это будет тот, который содержит программу установки.
* В шаге INSTALL установлены все пакеты, включенные в установочный носитель, за исключением пакетов KDE, установленных если вы don't хотите этого.
* В разделе КОНФИГУРАЦИЯ программа установки настраивает новую систему на ваш вкус. Это включает следующие настройки или опции:
+
** Сделайте спасательный накопитель USB.
** Установка и настройка менеджера загрузки GRUB и связанных с ним операционных загрузчиков.
** Выберите мышь на консоли или не используйте ее.
** Настроить сеть.
** Определить, какая служба должна быть запущена при запуске.
** Выберите, если аппаратные часы используют UTC или локальное время, установите часовой пояс.
** Выберите диспетчер входа в систему: консольный режим или графический.
** Выберите графическую сессию по умолчанию.
** Установите язык по умолчанию и региональный вариант в установленной системе. Затем устанавливаются некоторые пакеты, специфичные для выбранного языка.

Все готово, удалите установочный носитель и перезагрузитесь для запуска Slint.

[[Slint_in_an_encrypted_drive]]
==== Встаньте в зашифрованный диск.

В автоматическом режиме программа установки предлагает зашифровать диск, где он устанавливает
Slint, если вы посвятили его Slint. Если вы согласны, во время каждой загрузки системный загрузчик GRUB попросит вас ввести ключевую фразу
для разблокировки диска, перед
отображением загрузочного меню. Имейте в виду, что разблокировка накопителя займёт
секунд (около 10 секунд).

Having an encrypted drive prevents the steal of data it contains in case of
loss or theft of the machine, or of a removable drive. Но это выиграло't защищает вас, если компьютер остается запущенным и непривязанным, только
, если машина была полностью выключена!

Во время установки системный раздел Slint будет зашифрован, а также
дополнительный раздел, который вы можете запросить.

Раздел Slint (или root) будет именовано: /dev/mapper/cryproot после открытия
, если он зашифрован.

Это отображается этой командой:

----
lsblk -lpo имя,fstype,mountpoint | grep /$
----

Который дает ouptut так:
----
/dev/mapper/cryptroot ext4 /
----

Эта команда вместо этого:

----
lsblk -lpo имя,fstype,mountpoint | grep /dev/sda3
----

отдача:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 теперь является "raw" разделом, включающим так называемый "LUKS header"
который вам никогда не понадобится и не будет иметь прямого доступа.  Он содержит все, что необходимо
для шифрования или расшифровки раздела /dev/mapper/cryptroot, ,
на самом деле ведет ваши данные (в данном примере Slint системы).

[WARNING]
====
Если вы забыли парольную фразу все данные в диске будут безвозвратно потеряны!
So write down or record this passphrase and put the record on a safe place as
soon as done.

Диски погибают. Если это произойдет и зашифровано, ваши данные будут потеряны.
Поэтому регулярное резервное копирование важных данных не является обязательным.

Также сделайте резервную копию заголовка luks, который вы сможете восстановить
раздел luks будет поврежден по любой причине. Эта команда может быть в нашем
примере:
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
где <file> — это имя файла резервной копии, который вы будете хранить в надежном месте.

Затем вам нужно восстановить резервную копию, натип:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Дон'изменение размера раздела зашифрованного диска, как и после этого, он окончательно заблокирован
и все данные, которые он содержит будут потеряны! Если вам действительно нужно больше места, вам нужно будет сделать резервную копию всех файлов, которые вы
хотите сохранить, , установите заново и восстановите файлы резервной копии.

Выберите сильную парольную фразу, чтобы разбойник мог
найти подходящее время.

Никогда никогда не смещается с так называемым "LUKS заголовком", расположенным на первичном разделе
(третьего, как e. /dev/sda3 для исходного раздела поверх системного раздела Slint
).  Практически: don't создать файловую систему в этом разделе,
don't делают его частью RAID массива и обычно don't записывать его: все данные
будут безвозвратно потеряны!
====

Чтобы избежать слабых паролей, программа установки требует, чтобы парольная фраза включала в себя:

. Минимум 8 символов.
. Только неакцентированные строчные буквы, цифры от 0 до 9, пробелы и следующие знаки препинания:
+
----
 ' ! " # $ %  & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Это гарантирует, что даже новая клавиатура будет иметь все символы, необходимые
для ввода ключевой фразы.

. По крайней мере одна цифра, одна строчная буква, одна заглавная буква и один знак пунктуации.

GRUB предполагает, что клавиатура «нас» используется при вводе ключевой фразы.
По этой причине, если во время установки вы используете другую клавиатуру, прежде чем
просить парольную фразу, программа установки установит схему клавиатуры на "нас", и
после записи восстановить ранее использованный. В этом случае программа установки также произведет заклинания каждого символа ключевой фразы типа
, так как он может отличаться от
записанного на ключе.


Программа cryptsetup используется для шифрования диска. Чтобы узнать больше типа
после установки: +
-----
man cryptsetup
-----
и узнать еще следующее: https://gitlab.com/cryptsetup/cryptsetup/-/wikis/FrequentlyAskedQuestions[этот FAQ].

[[first_steps_after_installation]]
==== Первые шаги после установки

Вот первые задачи, которые необходимо выполнить после установки

В этом документе весь текст после # символа являются комментариями предлагаемых
команд, не набрать.

===== Начальное обновление программного обеспечения

После установки, система должна быть обновлена для того, чтобы получить самую последнюю
предоставленную версию каждого программного обеспечения, а также новое программное обеспечение, предоставленное после
релиза ISO. Это особенно необходимо, если нет сетевого подключения
во время установки, , то были установлены только пакеты, включенные в дистрибутив
, и они могут быть устаревшими.

Большинство команд, введенных ниже, имеют административное право, связанное с
конкретной учетной записью под названием 'root', для которого вы записали пароль
во время установки.

Чтобы выдать команду как «root», сначала введите
----
Сус -
----
затем выдайте пароль для root и нажмите Enter перед тем, как ввести команду.

Это заменяет 'sudo' в других дистрибутивах.

Когда вы закончите выполнение команд как 'root', нажмите Ctrl+d или введите 'exit', чтобы вернуть
статус "обычного пользователя".

Для обновления введите root в консоли или графический терминал:
----
slapt-get --add-keys # retrieve the keys to authenticate the packages
slapt-get -u # update the list of packages in the mirrors
slapt-get --install-set slint # get the new packages
slapt-get --upgrade # Get the new version of installed packages
dotnew # lists the changes in configuration files
----
При запуске dotnew, согласитесь заменить все старые файлы конфигурации новыми.
Это безопасно, как вы не делали'сделайте любую настройку.

В качестве альтернативы вы можете использовать эти графические интерфейсы: gslapt вместо
slapt-get, и dotnew-gtk вместо dotnew.

Чтобы узнать больше о slapt-get, наберите:
----
man slapt-get
----
или как корень:
----
slapt-get --help
----
и прочитайте /usr/doc/slapt-get*/README.slaptgetrc.Slint

===== Конфигурация

Вот утилиты, которые вы можете использовать для (пере)настройки системы Slint после установки.
They are presented in further details in chapter <<Manage_your_system, Управление системой>>.

Если не указано иное, эти утилиты должны использоваться в качестве корневого каталога. Чтобы стать root,
, то есть получите статус 'admin' и привилегии типа 'su -', а затем root's пароль.
Чтобы вернуть статус обычного пользователя pres Ctrl+d или введите выход.

Большинство утилит имеют командную строку и графическую версию. Первая версия командной строки
перечислена ниже. Если не указано иное, все команды должны быть
типами как root.

*Общие настройки*

* Для управления пользователями: настройка пользователя или gtkusersetup
* Изменить язык и регион: localesetup или gtklocalesetup
* Для изменения настроек клавиатуры и метода ввода: настройка клавиатуры или настройка gtkkeyboard
* Для настройки даты, времени или часового пояса: настройка часов и установка gtkclocp.
* Для того чтобы выбрать, какие сервисы запускаются при загрузке: сервисы и gtkservicesetup.
* Для (пере)настройки сети: сетевая установка.
* Чтобы выбрать запуск в текстовом или графическом режиме и в более позднем случае графический менеджер логинов: выбор логина
* Выберите рабочий стол или графический сеанс: session-chooser (как обычный пользователь)
* Если KDE установлен, чтобы показать или скрыть свои приложения на другом рабочем столе'сети: показать приложения или скрыть приложения.

*Настройки специальных возможностей*

Чтобы выбрать и включить консольный считыватель экранов или отключить все из них введите как root:
----
говорить с
----

Из Slint версии 14.2. вслед за первым регулярным пользователем, созданным во время установки, в установленной системе будет включена речь и braille, если речь была использована и требуется Брайль во время установки. Другие пользователи должны проверить или сделать дополнительные настройки, как указано ниже.

Чтобы включить тормоз:

. Сделайте /etc/rc.d/rc.brltty исполняемым типом как root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Сделайте себя членом группы Брайля, набрав в качестве root:
+
----
usermod -G braille -a имя пользователя
----
+
В команде выше замените имя пользователя с логином.
. Затем отредактируйте в качестве корня файл /etc/brltty.conf для включения настроек.

Чтобы включить речь на уровне системы, введите как корень:
----
Выбор логина
----
и выберите один из режимов входа, которые говорят: текст, lightdm или gdm

Чтобы включить речь в графических средах как обычный пользователь вводит в качестве пользователя:
----
орка
----
Затем программа чтения экрана Orca начнет произносить при следующем запуске графической среды


Чтобы отключить чтение в графическом окружении, введите следующее:
----
орка выкл
----

==  Использование Slint

В этой главе рассказывается о том, как вы можете взаимодействовать с системой Slint, чтобы
сделать то, что вы хотите.

=== Что такое система Slint?

Slint — это набор программ, которые примерно подпадают под эти категории:

* Операционная система создана из Linux <<kernel, ядра>> и <<utilities, утилит>>. Он действует как интерфейс между пользователем, приложениями и аппаратным обеспечением
* <<Applications, приложений,>> выполняющих задачи, которые хотят выполнить пользователи.

Слайт может быть использован в двух режимах, отличающихся внешностью экрана
и способом взаимодействия с системой:

* В текстовом режиме вы вводите команды, интерпретируемые <<shell, оболочкой>>. Эти команды могут запускать утилиту или приложение. Текстовый режим также называется режимом <<console, консоль>>. В этом режиме экран отображает только команды и их вывод в (обычно черном) фоне.
* В графическом режиме графические элементы, такие как окна, панели или иконки, отображаются на экране, обычно связанные с приложениями или утилитами. Пользователь взаимодействует с этими элементами с помощью мыши или клавиатуры.

Команды также могут быть введены в графическом режиме внутри окна, связанного с
a <<terminal, терминалом>> , в котором запускается оболочка.

=== Как старт Slint

После установки программное обеспечение, поставляемое в установочном ISO или скачанное
из удаленных репозиториев, устанавливается в <<drive, диске>>.

Когда вы загружаете слепота, <<firmware, прошивка>> сначала проверяет аппаратное обеспечение, а затем
ищет программу, называемую операционным загрузчиком (обычно именуемым системным загрузчиком), который
запускается.

В машине может быть несколько системных загрузчиков. В этом случае прошивка
позволяет пользователю выбрать, какой из них запускается в меню.

В Slint программа
, которая делает и устанавливает системный загрузчик, это GRUB. на самом деле системный загрузчик
, собранный GRUB также является менеджером загрузки, так как позволяет выбрать, какая ОС запускается, если
установлены несколько.

The OS loader built by GRUB can be installed in a boot
sector (in case of Legacy booting) or in an EFI System Partition or ESP (in
case of EFI booting).

Целью загрузчика Slint является запуск системы Slint. Чтобы сделать это, первый загружается в
ОЗУ <<kernel, ядро>>, затем <<initrd, initrd>>, который в свою очередь
инициализирует систему Slint.

На последнем этапе инициализации пользователю предлагается "войти", в
других словах, чтобы соединиться с системой и взять руку на нее. Чтобы сделать
, сначала введите одно'с пользователем (или войти) имя, а затем пароль,
действие которого проверяется. Slint as other Linux distributions being multi-users this
allows this user to access one's files but not those of other users.

Во время установки вы решили запустить Slint в текстовом или графическом режиме.

* Если вы выбрали C для <<console, консоли>> после инициализации системы, вы введете имя пользователя (или войти), то ваш пароль, каждый входной файл будет подтверждён нажатием клавиши Enter, затем вы можете ввести команды.
* Если вы выбрали G (графический), вы введете такую же информацию в <<display_manager, менеджере отображения>> или менеджере входа в систему, , который затем запускает графическое окружение <<graphical_environment, >>.

After installation, you can change the mode typing as root `login-chooser`,
in console mode as well as in graphical mode (in a <<terminal, terminal>>). Эта команда
позволяет выбрать `текст` (синоним консольного режима), или, для
графического режима, среди нескольких менеджеров. Ваш выбор будет эффективным
при следующей загрузке компьютера.

Теперь мы представим графическую среду, а затем как использовать оболочку.

=== Графические окружения

<<the_windows, Окна>> +
<<the_work_spaces, Рабочая область>> +
<<the_desktop, На рабочем столе>> +
<<the_top_panel, Верхняя панель>> +
<<the_bottom_panel, Нижняя панель>> +
<<the_slint_control_center, Центр управления Слепой>> +
<<graphical_terminals, Графические терминалы>> +
<<key_bindings, <a data-type="xref" href="#key_bindings"> Привязки клавиш>>

Полная графическая среда включает в себя несколько компонентов, Среди которых оконный менеджер, рисующий окна на экране, ассоциированные с приложениями, перемещает, изменяет размер и закрывает эти окна.

Slint позволяет включать в себя несколько графических средств: BlackBox, Fluxbox, KDE, LXDE и MATE, TWM, XFCE и WindowMaker. Это вопрос предпочтения, который вы выбираете.

KDE, LXDE MATE и XFCE являются полнофункциональными рабочими столами, остальные, в основном,
оконных менеджеров, но содержат панель с меню приложения. Все это позволяет
получить доступ к документам и приложениям, которые обычно открыты в окне, включать панель и меню.

Графическая среда по умолчанию может быть изменена как обычный пользователь `session-chooser`. В графическом режиме при входе в систему вы также можете выбрать нужное место.

Теперь мы кратко опишем компоненты рабочего стола Mate, который является дефолтным и является наиболее доступным с помощью речи и мозга. Другие полнофункциональные рабочие столы имеют схожие возможности.

С помощью мыши вы можете обнаружить возможности каждого компонента, делая или имитируя правый щелчок по центру или влево. Переместить или удалить большинство компонентов, изменить их и добавить новые могут быть выполнены таким же образом.

Эти компоненты могут достигать перемещения мыши, а также нажатия клавиш. Ниже мы указываем в скобках сочетания клавиш, позволяющие достичь, другими словами, сосредоточить внимание на каждом элементе. Мы также кратко опишем <<key_bindings, привязки кнопок>> для рабочего стола Mate (используя менеджер по умолчанию Marco Windows) и для менеджера окон Compiz.

[TIP]
====
Вы можете открыть для себя большинство функций приложений и других компонентов Slint с правом, средним или левым щелчком мыши.  Например, нажав на панель, заголовк, левую и правую кнопки любого окна, значок в панели или на пустом месте экрана.
====
[[the_windows]]
==== Окна

Окно - это прямоугольная область, связанная с приложением. Окна могут быть перемещены, изменены, размер, восстановлены, закрыты (заканчивая приложением, которое оно управляет) с помощью клавиш мыши или клавиатурных клавиш.

[[the_work_spaces]]
==== Рабочие места

Для того, чтобы можно было открыть много окон упорядоченно, графическая среда обеспечивает несколько рабочих мест и позволяет переключаться между ними. Каждое рабочее место отобразит один и тот же рабочий стол и панели, но окна могут быть помещены в определенное рабочее место или во всем. Эта настройка доступна правой кнопкой мыши по верхнему краю окна. Щелкнув на его позицию на нижней панели экрана, вы сможете переключиться на другую рабочую область, в области изменения рабочего пространства, как указано ниже.

[[the_desktop]]
==== Рабочий стол

Рабочий стол охватывает весь экран, на котором могут быть установлены другие компоненты, в случае Мат и как поставляются в стебель верхней и нижней панелях, и четыре значка, которые сверху внизу позволяют открывать в окнах:

* корневой каталог в файловом менеджере
* ваш домашний каталог в файловом менеджере
* центр управления слепотой
* корзина может быть там, где размещены файлы, которые вы собираетесь удалить, но не'т.

Окна приложения, которые вы запускаете, как и положить на рабочий стол.

Мат состоит из двух панелей, которые представляются как тонкие прямоугольные горизонтальные области, одна сверху и одна внизу экрана.

Нажатие клавиши Ctrl+Alt+Tab позволяет переключаться между рабочим столом, верхним и нижним панелями

Нажатие Alt+Tab позволяет перемещаться между окнами на рабочем столе.

[[the_top_panel]]
==== Верхняя панель

Он представляет, слева направо,

* Три меню:
** Меню приложений, которое можно открыть нажатием Alt+F1. Оттуда вы можете открыть другие меню с помощью клавиши со стрелками. Вы можете использовать клавиши со стрелками для доступа к другому меню.
** Меню Метки.
** Системное меню, которое дает доступ к подменю настроек, центру управления Mate и кнопкам, чтобы получить справку о рабочем столе, Заблокируйте экран, закройте сессию и выключите компьютер.
* Программа запускает для mate-terminal, файловый менеджер caja, почтовый клиент thunderbird, веб-браузер firefox, текстовый редактор Geany.
* Уведомление, которое может собирать апплеты, такие как менеджер Bluetooth, звуковой микшер, менеджер сети и «доступное обновление» оповещение.
* Часы и календарь.
* Блокировщик экрана.
* Диалог о закрытии сессии.
* Выключение диалога.

[TIP]
====
* Чтобы настроить панель по своему вкусу: щелкните правой кнопкой мыши на пустом месте на панели.
* Если вы хотите переместить элемент на панели: щелкните по элементу средней кнопки, перетащите мышь, и она будет следовать за мышкой, пока не будет отпущена центральная кнопка.
* Для контекстной справки нажмите F1
====

[[the_bottom_panel]]
==== Нижняя панель

Оно представляет, слева направо:

* Список окон, который можно настроить правой кнопкой мыши по строке из трех вертикальных точек в начале и при выборе предпочтений. Это также позволяет запускать системный монитор в окне.
* *Показать рабочий стол*. Слева от него будет сворачиваться или скрывать все окна, нажимая снова, вы восстановите окна в их предыдущем состоянии.
* Переключатель рабочего пространства или пейджер. Он позволяет переключаться с рабочего пространства на другое и перемещать окна с рабочего пространства на другое путем перетаскивания и перетаскивания.

Окна менеджеров настроены в Slint для использования без изменений. Однако вы можете переконфигурировать их по своему вкусу. Путь к этому варьируется от оконного менеджера к оконному менеджеру. Для получения дополнительной информации, смотрите http://docs.slackware.com/en:user_settings[Настройки пользователя].

[[the_slint_control_center]]
====  Центр управления слепотой

Мы закончим введение в Slint's, представив Центр управления Slint. Вы можете отобразить его из меню приложения на верхней панели или щелкнуть на его иконке на рабочем столе или напечатать qcontrolcenter в диалоге "Выполнить..." с Alt+F2

Цель панели управления - собрать приложения, полезные для системного администрирования, и настройки последовательно во всех оконных менеджерах.  Нажав на категорию в левом меню, вы можете отобразить соответствующие приложения в правой панели.  Мы представим их в табличном формате.  Это даст нам возможность представить инструменты администрирования, которые также имеют графический интерфейс.

Большинство административных инструментов следует использовать с административными привилегиями.  Для запуска инструмента вам будет предложено ввести пароль учетной записи root.

[options="autowidth"]
|====
<|**Категория** <|**Инструмент** <|**Цель и комментарии**
<|Заявления <|Dotnew <|Этот инструмент позволяет вам управлять новым (называемый _что-то. ew_ отсюда имя инструмента) против старых конфигурационных файлов после обновления некоторых пакетов.  'с хорошей привычкой для запуска, если после обновления.  Он расскажет вам, есть ли что-то, чтобы позаботиться, а затем подарит вам выбор действий.
<|Заявления <|Менеджер пакетов Gslapt <|Gslapt - это графический интерфейс для slapt-get.  Это удобный инструмент для выполнения <<software_management, управления программным обеспечением в Slint>>.  Он позволяет вам искать, устанавливать, удалять, обновлять и настраивать пакеты программного обеспечения.
<|Заявления <|Менеджер Сборки Источников <|Sourcery это графический интерфейс slapt-src.  Он позволяет искать SlackBuilds скрипты, которые он может использовать для автоматизации процесса сборки и установки пакетов программного обеспечения.  Он также может удалять и переустанавливать пакеты в вашей системе.
<|Заявления <|Поиск приложений <|Найдите и запустите приложения, установленные в системе.  В поле поиска очень удобно найти приложения, по сравнению с ручным поиском меню приложения.
<|Аппаратное <|Настройка принтера <|Используется для настройки любого подключенного принтера.  Это интерфейс сервера печати CUPS, который по умолчанию работает в Slint.
<|Аппаратное <|Cups Print Control <|Это приложение позволяет вам настраивать службу CUPS, управлять принтерами и управлять заданиями по печати через веб-браузер.
<|Аппаратное <|Keyboard <|Эта утилита позволяет задать тип клавиатуры, сопоставить клавиши и включить службу SCIM.  SCIM помогает вам вводить символы, для которых нет клавиш на клавиатуре (как на многих азиатских языках).
<|Информация <|Веб-сайт SlackDocs <|Документы в этой вики в основном предназначены для пользователя Slackware, но многие из них полезны для пользователя Slint.  *Внимание:*  Некоторые из перечисленных инструментов, такие как slackpkg, должны *не* использоваться в Slint.
<|Информация <|Документация по Slackware <|Эта документация может быть полезна и для пользователей Slint.  Slint основан на Slackware.
<|Информация <|Документация по слепому <|Это дает локальный доступ к документам также доступен на сайте Slint's.
<|Информация <|Скрепость форума <|Люди, родной язык которых не является английским, также могут публиковать на локализованных форумах Salix.
<|Информация <|Сайт Slint <|Веб-сайт Slint содержит документацию, ссылки и способ найти ИСО, а также пакеты.
<|Информация <|Информация о системе <|Этот инструмент собирает информацию о вашем компьютере, например, его подключенные устройства (внутренние и внешние) и отображает все его в одном месте.  Он также может выполнять системную стендовую маркировку.
<|Настройки <|Часы системы <|Эта утилита позволяет установить системные часы.
<|Настройки <|Имена хостов <|Этот инструмент позволяет связать IP-адреса с доменными именами и именами хостов
<|Настройки <|Язык системы <|Эта утилита позволяет установить системный язык (языковые и географические особенности), так, что приложения, которые вы используете, будут отображать информацию в этой локали (если она доступна).
<|Система <|Системные часы <|Этот инструмент позволяет задать часовой пояс, выберите, следует ли синхронизировать часы с Интернет-серверами (это рекомендуется, но конечно же требуется подключение к Интернету), и если нет, установите дату и время.
<|Система <|Имена хостов <|Эта утилита позволяет настроить имя хоста системы. Это полезно, если вы используете Slint как сервер, в локальной сети, или в Интернете.  Имя хоста помогает сетевым компьютерам идентифицировать друг друга по общему имени, если служба системы доменных имен не используется.
<|Система <|Перестроить кэш значков <|Эта утилита перестраивает кэш значков, который является файлом, регистрирующим все иконки в системе, позволяя им быстрее доступ. Запустите его при установке новых иконок в системе.
<|Система <|Системные сервисы <|Этот инструмент позволяет выбрать, какие службы будут включены при запуске.  Например, Bluetooth, сервер печати CUPS или веб-сервер.  Используйте его только для изменения настроек по умолчанию, если знаете, что вы делаете.
<|Система <|Пользователи и группы <|Эта утилита позволяет добавлять, удалять и настраивать учетные записи и группы пользователей. Он в основном полезен для многопользовательских систем.
<|Система <|Менеджер загрузки GUEFI <|Этот инструмент является графическим интерфейсом для команды efibootmanager.  Это позволяет редактировать системную прошивку EFI's загрузочное меню.  Такие действия, как добавление, удаление или изменение порядка пункта меню.
<|Система <|Монитор системы MATE<|Эта утилита отображает информацию о системе, например о процессе, использовании ресурсов (RAM, CPU, сетевой трафик) и использовании файловых систем.
|====

[[graphical_terminals]]
==== Терминалы

Команды можно вводить в графическом режиме как в консольном режиме, если вы открываете окно
с терминалом в нем. В Mate можно просто нажать Ctrl+Alt+t или
на значке mate-terminal на верхней панели, или откройте диалог "Выполнить... ", нажав
Alt+F2, а затем набрав `mate-terminal` в открывшемся небольшом окне.

Большая часть информации ниже о командной строке и оболочке в режиме Консоль
также применима к набору команд в терминале. Вы можете закрыть mate-terminal
нажав Alt+F4 как и в любом другом окне.

[[key_bindings]]
==== Привязки клавиш

Здесь представлены сочетания клавиш по умолчанию для оконного менеджера Compiz и рабочего стола Mate и как их настраивать.

[NOTE]
====
Когда привязка ключей включает в себя один или более знаков *+* , затем удерживайте клавиши слева направо до последней клавиши, например клавишу `Shift` , затем нажмите последнюю клавишу.
====
===== Привязки клавиш для рабочего стола Mate

При использовании Mate в Slint, некоторые сочетания клавиш совпадают с использованием либо
оконных менеджеров Marco или Compiz. Они перечислены ниже:
----
Alt+Tab Цикл между окнами
Shift+Alt+Tab Цикл назад между окнами
Control+Alt+Tab Цикл между панелями и рабочим столом
Shift+Control+Alt+Tab Цикл назад между панелями и рабочим столом
----
Однажды в графическом окружении вы можете переключаться между ним и консолью.
Пусть'вы хотите использовать tty2 (tty1 занят):
Нажмите `Ctrl+Alt+F2`, а затем войдите в систему. +
Нажмите `Ctrl+Alt+F7` , чтобы вернуться в графическую среду.

Такие же общие сочетания клавиш используются во всех графических средах,
за несколькими исключениями, Модуль1 обычно является левым клавишей Alt: +
----
Mod1+F1 отображает меню приложений панели.
Mod1+F2 вызывает диалог 'run..., но во Fluxbox (запускает lxterminal вместо него).
----
Также в Fluxbox:
----
Mod1+F3 restarts Fluxbox.
Mod1+F4 закрывает выделенное окно.
----
Меню панели'с приложением одинаково макет во всех доступных
графических средах отправлено, но MATE. От верхней к нижней части:

Терминал эмулятор: `mate-terminal` в MATE, Где угодно `lxterminal` по умолчанию +
Файловый менеджер: `Caja` в MATE в другом месте `PCManfm` по умолчанию +
Веб-браузер: `Firefox` по умолчанию +
Mail client: Thunderbird по умолчанию +
Настройки +
Slint Dashboard (пока не доступна, как это'с приложением Qt4) +
Приложения, отсортированные по категории +
Запустить диалоговое окно +
Выход из системы (также позволяет закрыть и перезагрузить)

Вы можете использовать клавиши со стрелками для навигации в меню.

В MATE верхняя панель включает слева направо:

меню (Приложения, затем «Размещения», затем «Система») +
запускает для mate-terminal, caja (файловый менеджер), Firefox, Thunderbird и
текстовый редактор geany . +
Справа по-прежнему слева направо:
Область уведомлений +
кнопка блокировки экрана +
кнопка выхода +
кнопка остановки или перезагрузки.

Нижняя панель слева направо:

в списке окон +
плагин "показать десктоп" +
переключатель рабочей области.

Еще в Mate, частично зрящие пользователи могут использовать окно compiz вместо
или marco, которое является стандартным.

Как обычный пользователь, тип:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
Чтобы вернуться к марко:
----
gsettings set org.mate.session.required-components windowmanager marco
----
Эта настройка вступит в силу при следующем запуске сеанса.

Или внести изменения только для текущего типа сессии:
----
compiz --replace &
----
и вернуться к марко:
----
marco --заменить &
----
Замена будет произведена немедленно

Этот параметр также доступен графически из mate-tweak, в категории Windows
.

Вы можете получить доступ к определенным настройкам Compiz просто набрав:
----
ccsm &
----
===== Привязки клавиш для оконного менеджера Compiz

In the default settings indicated below the key or mouse buttons are
named like this:

Super: Windows key on most keyboards +
Button1: Left Mouse Button (if used with the right hand) +
Button2: Centre Mouse Button, or click with the scroll wheel) +
Button3: Right Mouse Button (if used with the right hand) +
Button4: Scroll Wheel Up +
Button5: Scroll Wheel Down
Button6: (I don't know, I thought that was on mouses for gamers) +

The default settings listed below by category can be changed from the
CCSM. We indicate the short name of the plugin between square brackets.

. Category General
+
[core] General options, tab "key bindings": +
close_window_key = Alt+F4 +
raise_window_button = Control+Button6 +
lower_window_button = Alt+Button6 +
minimize_window_key = Alt+F9 +
maximize_window_key = Alt+F10 +
unmaximize_window_key = Alt+F5 +
window_menu_key = Alt+space +
window_menu_button = Alt+Button3 +
show_desktop_key = Control+Alt+d +
toggle_window_shaded_key = Control+Alt+s +
+
[matecompat] Mate Compatibility +
main_menu_key = Alt+F1 +
run_key = Alt+F2 +

. Category Accessibility
+
[addhelper] Dim inactive (less light on non focused windows) +
toggle_key = Super+p +
+
[colorfilter] (Filter color for accessibility purposes) +
toggle_window_key = Super+Alt+f +
toggle_screen_key = Super+Alt+d +
switch_filter_key = Super+Alt+s +
+
[ezoom] Enhanced Zoom Desktop +
zoom_in_button = Super+Button4 +
zoom_out_button = Super+Button5 +
zoom_box_button = Super+Button2 (zoom out to go back to normal) +
+
[neg] Negative (toggle inverse colors of the window or screen) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Opacity, Brightness and Saturation adjustments +
opacity_increase_button = Alt+Button4 +
opacity_decrease_button = Alt+Button5 +
+
[showmouse] (Increase visibility of the mouse pointer) +
initiate = Super+k +

. Category Window Management
+
[move] Move window +
initiate_button = Alt+Button1 (hold Button1 while moving the mouse) +
initiate_key = Alt+F7 (Esc to stop moving) +
+
[resize] Resize window +
initiate_button = Alt+Button 2 (hold Button2 while moving the mouse) +
initiate_key = Alt+F8 (Esc to stop moving) +
+
[switcher] Application switcher (switch between windows or panels and
                                 the desktop) +
next_window_key = Alt+Tab (cycle between windows) +
prev_window_key = Shift+Alt+Tab +
next_panel_key = Control+Alt+Tab (cycle between panels and desktop) +
prev_panel_key = Shift+Control+Alt+Tab +


===== Как добавить пользовательскую комбинацию ключей для Mate.

Let's take an example: we want that Alt+F3 starts firefox.
введите терминал или команду Run (нажмите Alt+F2):
----
mate-keybinding-свойства
----
В новом окне вы можете использовать клавиши со стрелками вниз и вверх для
навигации в списке существующих привязок.

Чтобы установить новую привязку, дважды нажмите Tab для добавления курсора, затем
нажмите Enter. В небольшом диалоговом окне введите имя пользовательской привязки клавиш
, как firefox, нажмите Tab, введите имя для ассоциированной команды
, в этом случае firefox, затем дважды нажмите Tab для
поместите курсор на Apply и нажмите Enter.

Чтобы активировать привязку новой клавиши, перейдите до тех пор, пока вы не найдете ее в
нижней части списка, предварительно введите нажатие Alt+F3.

В следующий раз вы pres Alt+F3, которые должны запускать firefox

=== Оболочка

NOTE: Настоящая глава представляет собой краткое введение. Более подробная информация представлена в документе https://slint.fr/doc/shell_and_bash_scripts.html[Shell и bash скриптах], в основном заимствованном из SUSE.

Когда компьютер запускается в консольном режиме, после входа в систему введите имя пользователя и пароль, <<shell, shell>> отображает "подсказку", как показано ниже: +
`didier@darkstar:~$` +
В следующем примере:

* `dididier` это имя пользователя
* `темная звезда` имя машины
* tilde `~` представляет домашнюю директорию пользователя, в данном примере `/home/didier`
* знак доллара `$` указывает, что пользователь является "обычным", а не "супер пользователем" (см. ниже).

Затем курсор позиционируется после подсказки.

Теперь пользователь может ввести в строке команду (отсюда и название "командной строки") и подтвердить ее нажатием клавиши Enter. Оболочка then analyzes the command and execute it if valid, else output a message like for instance "command not found". Вы можете отредактировать команду перед нажатием клавиши Enter с помощью стрелок влево и вправо и клавиш Backspace, Home, End и Del.

Во время выполнения команды могут отображать вывод на экране или нет. Во всех случаях после выполнения запроса будет отображено снова в новой строке , что shell ждет ввода следующей команды.

Для этого пользователю необходимо знать, какие команды доступны и их синтаксис. Некоторые команды выполняются самой оболочкой, другие запускают внешние программы. Ниже приведено несколько примеров команд, больше перечислены в https://slint.fr/doc/shell_and_bash_scripts.html[Shell и bash скриптах]

Для Linux доступно несколько оболочек; в Slint оболочке, используемой по умолчанию, называется *bash*.

Чтобы позволить запускать несколько программ одновременно, Linux предоставляет несколько "виртуальных консолей", а затем одну и ту же клавиатуру и экран, нумерованные с одного. Первоначально система запускается в консоли (или виртуальном терминале) номер 1 также называется *tty1* (название tty является аббревиатура "teletype"). Оттуда пользователь может переключиться на другую консоль или tty; например переключиться на Tty number 2, нажав Alt+F2, где другая оболочка снова попросит пользователя'с именем пользователя и паролем. Чтобы вернуться в tty1, просто нажмите Alt+F1. По умолчанию в Slint доступны шесть тонов, но это может быть изменено при редактировании файла /etc/inittab.

Когда оболочка используется в графическом окружении (в графическом терминале), она ведет себя так же, как и подсказка, несколько иначе, как показано ниже: +
`dididier[~]$` +

Вы можете переключаться между консолью и графическим окружением:

* Из графического окружения нажмите кнопку Ctrl+Alt+F3, чтобы перейти в tty3. В первый раз вам придется ввести свой логин и пароль.
* С консоли или tty нажатием Alt+F7, если графическая среда уже запущена, иначе введите `startx` , чтобы запустить ее.

==== Набрав команды как root

*root* является обычным именем "супер пользователя", который имеет все права на выполнение административных задач, включая те, которые могут повредить или даже уничтожить систему.

Вы можете (но это не рекомендуется для новичков) войти непосредственно в систему как root. Чтобы сделать этот тип *root* в качестве пользователя, а затем root'S пароль.
To inform you (and warn you about the associated risks and responsibilities), the prompt will look like this: +
*root@darkstar:s~#* +
the character # (number sign, also commonly named hash) indicates that the commands will be typed as root (not as regular user), with the associated rights, but also risks and responsibilities.

Если вы уже вошли в систему как обычный пользователь, вы можете "стать root" набрать: +
*su -* +
затем нажмите Enter. В этой команде `su` (которая стоит fr "Супер пользователь") является именем команды, и символ *-* (дефис-минус, также с именем minus) говорит, что вы открываете "оболочку": сначала вас спросят пароль суперпользователя'с паролем, затем будут направлены в домашний каталог /home/root, как если бы вы вошли в систему при запуске с правами суперпользователя. Это позволит избежать случайной записи файлов в домашний каталог в качестве обычного пользователя (например, /home/didier), которые вызывают проблемы позже.

=== Как решить блокирующие задачи

Под "блокированием вопросов" мы понимаем "проблему, которая не позволяет использовать Slint", как то:

* Не удалось загрузить систему.
* Система загружается, но последовательность запуска прерывается перед завершением. Это может произойти, например, если корневой раздел может't смонтирован из-за ошибки в /etc/fstab, поврежденная корневая файловая система или отсутствующий модуль ядра для монтирования корневого раздела, или система успешно загружается, но вы don't помните пароль для root.

Если система полностью не сможет загрузиться, попробуйте каждое из нижеперечисленных решений последовательно до тех пор, пока не будет работать.

. Если это происходит после обновления ядра, попробуйте вторую загрузку вместо первой.
. Используйте последнюю загрузочную запись в меню GRUB. Он мог найти Slint и позволить его начать.
. Попробуйте загрузиться с спасательной загрузочной карты, которую вы запросили в конце установки.
. Перейдите к крестоносцу для его ремонта, как описано ниже.
. Спросите помощь по электронной почте slint@freelists.org предоставив всю информацию, которая может помочь исследовать проблему. Если еще не сделано, сначала подпишитесь на рассылку slint-request@freelists.org с темой 'subscribe', затем ответьте на письмо, которое вы получите. Только если у вас есть проблема с использованием электронной почты, запросите помощь в IRC канале #slint, server irc.libera.chat и оставайтесь в канале до тех пор, пока кто-то не ответит.

Если последовательность запуска прервана, перейдите в Slint из программы установки, чтобы попытаться решить проблему. Вставьте или подключите носитель установки (USB-стик или DVD, на котором вы записали установочный ISO), затем следуйте инструкциям ниже.

. Запустить установщик.
. Как только вы вошли в систему как root, для списка дисков и разделов, наберите следующее:
+
----
lsblk -lpo name,size,fstype
----
. Найдите в выходе имя корневого раздела Slint, проверьте его размер и тип файловой системы, помеченные FSTYPE.
. Монтируйте этот раздел и проверьте, что он хороший. Например, если это /dev/sda3, тип:
+
----
mount /dev/sda3 /mnt
cat /mnt/etc/slint-version
----
+
[NOTE]
====
Если файловая система корневого раздела Slint кажется повреждена, don't смонтировать его, но попробуйте восстановить его с помощью этой команды:
----
fsck <name of the root partition>
----
И если это удается, просто перезагрузится.
====
+
Если предположить, что вы установили Slint64-14.21, вывод должен быть:
+
*Слепь 14.2.1*
+
Если вывод "file not найден", то раздел не является тем разделом, который вы искали. Только в этом случае набери:
+
----
umount /mnt
----
+
а затем попробуйте еще один, перейдя обратно к списку дисков и разделов.
+
Иначе связать псевдофайловые системы /dev, /proc и /sys в системе Slint, набрав следующее:
+
----
монтировать -B /dev /mnt/dev
монтировать -B /proc /mnt/proc
монтировать -B /dev /mnt/sys
----
+
Выдать следующую команду для «прыгнуть в» вашей подстроки:
+
----
chroot /mnt
----
+
chroot означает "изменить root (из системы)": мы больше не в программе установки, но теперь в Slint сам по себе. Отсюда вы можете внести изменения в систему для решения проблемы. Вот несколько примеров:

* Выполнить "update-grub".

* Запустить "grub-emu".

* Переустановите GRUB, используя команду "grub-install drivename", привод которого является диском, где устанавливается Slint. Перед тем как это сделать, если вы загрузитесь в режиме EFI введите сначала "mount /boot/efi".

* Введите "passwd", чтобы изменить пароль для root.

* Удалять, установить или обновить пакеты.

. После завершения удалите установочный носитель, затем тип:
+
----
выйти из
перезагрузки
----

[[Accessibility]]
== Accessibility

Если вы решили сохранить речь при первой установке, он будет включен
с запуска в консоли, как в графических средах.

=== Использование Slint с терминалом Брайля

Slint включает в себя программное обеспечение brltty для работы с дисплеями Брайля.

Ваши настройки, сделанные перед загрузкой в командной строке или позже, записываются в установленную систему в
/etc/brltty.conf.

Полное руководство по бритве доступно на английском языке, Французский и
португальский в нескольких форматах, включая простой текст (txt) по этому URL:
https://mielke.cc/brltty/doc/Manual-BRLTTY/

Если Брайль не был включен во время установки или был отключен, для его включения:

. Сделайте /etc/rc.d/rc.brltty исполняемым типом как root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Сделайте себя членом группы Брайля, набрав в качестве root:
+
----
usermod -G braille -a имя пользователя
----
+
В команде выше замените имя пользователя с логином.

Чтобы отключить тип Брайля как root:
----
chmod 64 /etc/rc.d/rc.brltty
----

=== Речь в графических средах

Для напоминания в графических средах с помощью экранного чтения Orca включена печатание:
----
орка
----

Чтобы узнать, как использовать Orca, включая специфические ключевые ссылки, наберите:
----
мужчина орка
----

Короче говоря, однажды в графическом окружении, в графическом режиме:
----
Вставка+Пробел: запустите диалог настроек орки.
Вставить +S: активировать или деактивировать вокальный синтез.
Вставка+Н: активируйте режим обучения. В этом режиме:
   Нажмите клавишу, чтобы услышать её функцию
   F1: чтобы услышать документацию по экрану
   F2: перечислите клавиши быстрого доступа к Orca
   F3: перечислите клавиатуру для текущего приложения
   Esc: конец учебного режима
----

=== Voices and TTS in Slint.

Следующие синтезаторы речи (Текстовые синтезаторы) поставляются в
Slint64-14.2.1. , каждый из которых имеет набор голосов, именно: +
espeak-ng +
flite +
pico +
mbrola +
RHVoice +

Чаще всего эти TTS и связанные с ними голоса и языки
управляются голосовым диспетчером через его так называемые "модули" (резко, резко,
модуль связан с TTS).

Пользовательская утилита spd-list может ответить на несколько вопросов о
синтезаторах, голосах и языках. Ввод spd-list отображает следующее:
----
В этом скрипте перечислены языки и синтезаторы, доступные для приложений
на основе диспетчера речи, например, Orca или речи. Каждая команда ниже отвечает на следующий за ней вопрос.
Не вводите кавычки вокруг команды.
Использование "/usr/bin/spd-list"?
"/usr/bin/spd-list -s" доступны синтезаторы?
"/usr/bin/spd-list -l" доступны языковые коды?
"/usr/bin/spd-list -ls <synthesizer>" доступны для этого синтезатора?
"/usr/bin/spd-list -sl <language code>" синтезаторы, предоставляющие голоса на этом языке?
Код языка чаще всего содержит два символа, такие как 'ru' или 'fr'
----
Все перечисленные голоса доступны в Orca и речи, а также fenrir если настроен на использование рече-диспетчера.

Вы можете получить дополнительные голоса за flite и mbrola, связанные с
модулями flite-generic и espeak-ng-mbrola-generic.

Вы всегда можете знать, какие из этих команд установлены или не набраны как root-файлы:
----
slapt-get --search mbrola-voice
slapt-get --search flite-voice
----
затем установите один из неустановленных например один из них, как напр.
----
slapt-get -i mbrola-voice-it2
----
В дополнение к свободному (как в свободном пиве) голоса, поставляемые в Slint,
вы можете купить голоса для: +
voxin, https://oralux.org/voice.php +
voxygen, отправив письмо на contact@hypra.fr

Позже можно будет сделать больше голосов и синтезаторов, это будет объявлено в
списке рассылки Slint и этом http://slackware.uk/slint/x86_64/slint-14.2.1/ChangeLog.txt[Журнале изменений]

Горячие клавиши для графических окружений перечислены в <<key_bindings, сочетаниях клавиш>>.

=== Использовать менеджеры входа с речью

С помощью Orca: lightdm или gdm, которые рекомендуются как полностью доступные.

В gdm фокус находится в поле "Пользователи". Введите пользователя. или
логин, затем введите введенный пароль и введите его.

Вы можете получить доступ к другим функциям gdm через сочетания клавиш. На
Английском: +
Alt+A: Действия (выключение или перезагрузка) +
Alt+E: меню сессии +
Alt+L: изменить язык, для следующей сессии и, возможно, дальнейшей
сессии, возможно, также для Gdm. +
Alt+T: Тема. +
Вы можете использовать клавишу Tab для навигации между полями ввода, а также клавиши вверх и вниз
для меню.

В lightdm нажатие F4 переключает звук вкл. или выкл. Изначально курсор
находится в поле пароля. Нажмите Tab приводит к "login push кнопку",
а затем пользователю'S список или "combo box". В этом списке нажатие на пробел
показывает текущего выбранного пользователя. Используйте клавиши со стрелками для выбора другого
и введите соответствующий пароль. Вместо этого, выбрав "Другое..."
добавляет поле, где вы можете ввести имя входа пользователя без списка.
Еще в lightdm, F10 вызовет меню, позволяющее перезагрузить или выключить,
и Alt+F4 вызывает пользовательский интерфейс с кнопками выключения или отмены.

=== Выберите консольный считыватель экрана

Slint предоставляет эти программы для считывания экранов: +
espeakup +
speehchdup +
fenrir

Кроме того, в
консольном режиме можно использовать несколько аппаратных синтезаторов речи.

Для выбора программы чтения с экрана выполните эту команду:
----
говорить с
----
Вот его вывод без аргументов:
----
root[~]# speak-with
Usage: /usr/sbin/speak-with <screen reader> or <hard synthesizer> or none
Выберите консольный считыватель экрана to talk with among:
  espeakup (Console screen reader connecting espeak-ng and speakup)
  fenrir (Modular, flexible and fast console screen reader)
  speechd-up (Console screen reader connecting Speech Dispatcher and speakup)
or use one of the supported hard synthesizers:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
or type  "/usr/sbin/speak-with none" to mute all screen readers.
root[~]#
----
Список аппаратных синтезаторов речи доступен в
запущенном ядре или поставляемом в виде модулей.

Пример команд и связанных с ними выводов:

----
root[~]# громкоговоритель
Стартовое выступление
Должно быть также запущено при следующей загрузке? [Y/n]
ОК
корень[~]# Готово.
----
Как только вы введете команду, ранее использовавшиеся читатели экрана будут
остановлены, и чтение речи начнет говорить.

Если вы ответите Y (по умолчанию) на вопрос: +
Должен ли быть также запущен режим речи при следующей загрузке? +
spechd-up будет использоваться при следующей загрузке. +
Если вместо этого вы ответите n экран, используемый перед вводом динамика с
голосом, будет использоваться после следующей загрузки.

Другие примеры:

----
root[~]# громко с аполисом
Остановка речи...
Следует ли использовать apollo при следующей загрузке? [Y/n]
ОК
корень[~]# Готово.

root[~]# не говорит ни с кем
Хотите заглушить консоль при следующей загрузке? [Y/n]
OK
root[~]#
----

=== Настроить консольный считыватель экранов.

Аппаратные синтезаторы речи, использующие озвучивание и воспроизведение
, а также чтение речи на экране воспроизведения.

Вы можете сохранить параметры, например, увеличить частоту пика или громкость звука
или уменьшить частоту звука. Просто введите как root:
громкости-сохранить. Это сохраняет все текущие настройки, в том числе настройки
, используемого аппаратного синтезатора.

Все эти настройки будут восстановлены при следующей загрузке: скрипты запуска
rc.espeakup и rc.speechd-up запустить команду Speup-restore для вас.

Если вы don't хотите восстановить сохраненные настройки, введите как root: +
chmod -x /usr/sbin/speakup-restore

Если вы их восстановили снова тип как root: +
chmod +x /usr/sbin/speakup-restore

Вот некоторые сочетания клавиш для настройки произношения, а также речь:
----
spk key_f9 punctuation_level_decrease
spk key_f10 punctuation_level_increase
spk key_f11 reading_punctuation_decrease
spk key_f12 reading_punctuation_increase
spk key_1 volume_decrease (не работает с речью)
spk key_2 volume_increase (не работает с речью)
spk key_3 pitch_decrease (не работает с речью)
spk key_4 pitch_increase (Не работает с речью)
spk key_5 rate_decrease
spk key_6 rate_increase
----
В таблице выше spk это клавиша CapLock, или Ins/0 на числовой клавише. Например, чтобы увеличить скорость, вы можете нажать и удерживать клавишу
CapsLock, а затем нажмите клавишу 6.

Некоторые настройки доступны только на конкретных аппаратных синтезаторах не
имеют привязки к ним. Затем установите новое значение в
/sys/accessibility/speakup/<synth>/<parameter>

Например, чтобы изменить голос, используемый apollo 2, вы можете написать: +
echo 2 > /sys/accessibility/speakup/apollo/voice

Speup-save также сохранит эту настройку.

Предупреждение: Я никогда не использовал аппаратный синтезатор речи, поэтому объяснение ниже -
только предположение, основанное в драйвере speakup_apollo, совместимый с
является вручную, найдено в +
https://archive.org/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== Выражение клавиш рабочего стола

Почти все перечисленные ниже ключи находятся на числовой клавиатуре.
Клавиша Вставить или 0 на клавиатуре действует как клавиша Shift (Shift клавиши). Например,
Ins 2 означает, что "удерживайте клавишу Вставки, как клавиша Shift и нажмите 2".
Оставьте numlock выключенным, чтобы использовать Speakup.

Объем: эти сочетания клавиш можно использовать с жестким синтезатором и эскалацией
, а также с речью. Однако установка высоты или громкости речи
с помощью сочетаний клавиш недоступна при использовании речи.

Первые ключи для запоминания:
----
Вкл/выкл кнопки "Вкл/выкл" экрана печати
Ins F1 Help (нажмите "Пробел", чтобы выйти из справки)
----

Ключи, используемые для просмотра экрана:
----
1/2/3 Скажи предыдущий/Current/Следующий символ
Shift PageUp Скажи первый символ
Shift PageDown последний символ
4/5/6 Скажи предыдущий/предыдущее слово
5 раз Заклинание текущее слово
Ins 5 Spell Current Word phonetically
7/8/9 Скажи Предыдущую/следующую строку
Ins 4 Скажи левый край строки для чтения курсора.
Ins 6 Say от чтения курсора до правого края линии.
Ins 8 Say from top of screen to reading the cursor.
Ins plus Say from reading the cursor line to bottom of screen.
плюс Скажи весь экран.
Ins r Say all doument
dot Say position
Ins dot Say attributes
Ins minus Say character hex and decimal value.
minus Park чтение курсора (переключение)
Ins 9 Move reading cursor to top of screen (insert pgup)
Ins 3 Move reading cursor to bottom of screen (insert pgdn)
Ins 7 Move reading cursor to left edge of screen (insert home)
Ins 1 Move reading cursor to the right edge of screen (insert end)
Control 1 Move reading cursor to last character on current line.
asterisk Переключить курсор
Ins asterisk n<x|y перейти на строку (y) или столбец (x). Где 'n' является любое допустимое значение
               для строки или столбца для вашего текущего экрана.
Окно Ins f2 Set
Ins f3 Clear window
Ins f4 Enable window
----

Другие ключи:
----
Ins f5 Edit some
Ins f6 Edit most
Ins f7 Edit delim
Ins f8 Edit repeat
Ins f9 Edit exnum

Enter Shut up (until another key is hit) and sync reading cursor.
Ins Enter Shut Up (до переключения назад)

slash Mark and Cut screen region.
Регион экрана для слэш-вставки в любую консоль.
----
==== Вызов кнопок ноутбука

Эти сочетания клавиш (для американской клавиатуры) don't требуют числового типа.
Если у вас есть, используйте клавиши <<desktop_keys, для рабочего стола>> легче в использовании,
особенно если вы используете другую раскладку клавиатуры, чем США.

Клавиша CapsLock действует как клавиша Shift. +
Например, CapsLock 2 означает, что "удерживайте клавишу CapsLock как Shift и нажмите 2". +
Держите блокировку numlock, чтобы использовать Speakup.

Объем: эти сочетания клавиш можно использовать с жестким синтезатором и эскалацией
, а также с речью. Однако установка высоты или громкости речи
с помощью сочетаний клавиш недоступна при использовании речи.

Первые ключи для запоминания:
----
Переключение экрана при вкл/выкл
CapsLock F1 Help (нажмите пробел для выхода)
----

Ключ, используемый для просмотра экрана:
----
CapsLock т/запятая/точка Скажи Предыдущий/Current/Следующий символ
CapsLock PageUp Скажи первый символ
CpasLock PageDown Скажи последний символ
CapsLock j/k/l Скажи Предыдущее/urrent/Следующее слово
CpasLock к двойному заклинанию
CapsLock u/i/o Скажи Предыдущее/urrent/Следующую строку
CapsLock h Скажет левый край строки для чтения курсора.
CapsLock точку с запятой Скажем от курсора чтения к правому краю строки
CapsLock y Say от верхней части экрана до чтения курсора.
CapsLock p Say от чтения строки курсора к нижней части экрана.
CapsLock апостроф Скажи весь экран.
Capslock r Прочитать все документы.
CapsLock n Say позиция
CapsLock косой косой черты атрибута
CapsLock минус парком чтения курсора (переключатель)
CapsLock f2 Установить окно
CapsLock f3 Очистить окно
CapsLock f4 Включить окно
----
Другие ключи:
----
CapsLock f5 Редактировать некоторые
CapsLock f6 Изменить максимум
CapsLock f7 Редактировать разделитель
CapsLock f8 Repeat редактировать
смещение CapsLock f9 Edit exnum
----

=== Позволить эмакам

Вы можете использовать произношение или речь. Чтобы включить или выключить один из
ввести одну из этих команд:

switch-on emacspeak +
switch-on speech-el +
switch-off emacspeak +
switch-off speech-el +

Затем просто наберите +
эмаков

Включение одного из этих программ отключает другой.

[[Manage_your_system]]
== Manage your system

[[software_management]]
=== Управление программным обеспечением в Slint.

<<The_basics, Основы>> +
<<Keep_your_system_up_to_date, Сохраняйте вашу систему в актуальном состоянии>> +
<<Kernel_upgrades, Обновление ядра>> +
<<Get_additional_applications, Получить дополнительные приложения>> +
<<slapt_src, Использование slapt-src>> +
<<sbopkg, Использование sbopkg>> +

[[The_basics]]
==== Основы

В Slint программное обеспечение предоставляется в виде пакетов. Пакет - это набор файлов из сжатого архива, собранных вместе, чтобы обеспечить все, что необходимо для запуска программы. Пакеты включены в установочный ISO и хранятся в удаленных серверах, с которых они могут быть загружены и установлены. Установка пакета означает извлечь файлы из архива и скопировать их в директорию системы.

Установка и удаление программного обеспечения записываются в базу данных, состоящую из текстовых файлов в этих каталогах:
----
/var/log/packages
/var/log/removed_packages
/var/log/scripts
/var/log/removed_scripts
----
Файлы в каталоге записывают информацию о пакетах, в основном, его содержимое: список файлов, которые он включает и где они установлены.

Ниже перечислены основные команды для управления пакетами. Все они имеют связанные страницы справки.

Эти команды требуют административных прав, связанных с конкретной учетной записью под названием 'root', для которой вы указали пароль при установке Slint.

Чтобы выдать команду как 'root', сначала введите пароль
su -
и введите команду.

Ниже приведенные команды могут быть запущены с графического терминала или в консоли, но gslapt работает только в графической среде.
----
installpkg # для установки пакета, хранимого локально.
removepkg # для удаления установленного пакета.
upgradepkg # для замены установленного пакета другим (обычно с тем же именем, но с другой версией).
slapt-get # для установки, удаления, обновления пакетов, хранящихся в репозиториях, перечисленных в /etc/slapt-get/slap-getrc
----
Отправленные в установке пакеты из репозиториев, перечисленных в /etc/slapt-get/slapt-getrc

Прочитайте комментарии в /etc/slapt-get/slapt-getrc и /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint в установленной системе.

После установки Slint, вы'будете уведомлены об обновлениях установленных пакетов из репозиториев, перечисленных в /etc/slapt-get/slapt-getrc

Вы можете установить дополнительные пакеты, используя команду slapt-get или gslapt, если они хранятся в репозитории в /etc/slapt-get/slapt-getrc

slapt-get и gslapt предоставляют функцию поиска, которая помогает вам найти пакеты.

WARNING: вы можете использовать slapt-get, gslapt и removepkg для удаления установленных пакетов, но не удалять пакеты, отправленные в Slint ISO, даже если вы не используете их вообще. Удаление включенного пакета не приведет к увеличению производительности и может предотвратить запуск других приложений. Также, если вы добавили пакет, не входящий в состав Slint, вы можете удалить его, но будьте осторожны, что удаленный пакет не является зависимым от других установленных вами пакетов и будет продолжать использовать.

[[Keep_your_system_up_to_date]]
==== Держите вашу систему в актуальном состоянии

Держите вашу систему в безопасности устанавливать обновления программного обеспечения, предоставляемые Slint, как только они'будут доступны.

Все обновления перечислены в ChangeLog: http://slackware.uk/slint/x86_64/slint-14.2.1/ChangeLog.txt

После установки Slint или любых изменений в файле /etc/slapt-get/slapt-getr запустите эту команду один раз:
----
slapt-get --add-keys
----

Чтобы синхронизировать локальный список доступных пакетов с репозиторием, эта команда автоматически запускается каждые два часа:
----
slapt-get -u
----
Вы также можете запустить его вручную

Это, конечно, требует подключения машины к Интернету.

Чтобы загрузить и установить обновленные или пересобранные пакеты запустите с правами root
следующую команду:
----
шлак-получить --upgrade
----
Кроме того, вы можете использовать gslapt, графический интерфейс для slapt-get.

Чтобы получить новые пакеты, перечисленные в Журнале изменений как "Добавленные", наберите:
----
slapt-get -i <package name>
----
или убедиться, что вы установили все пакеты, отправленные в Slint, включая те, которые добавлены в репозиторий после установки Slint, наберите:
----
slapt-get --install-set slint
----

На настольных компьютерах небольшая иконка отображается в области уведомлений панели (верхней панели в MATE) для уведомления о доступных обновлениях программного обеспечения. Просто щелкните левой кнопкой мыши и следуйте инструкциям, указанным там.

Имейте в виду, что некоторые пакеты перечислены в черном списке
/etc/slapt-get/slapt-getrc, то есть не могут быть автоматически обновлены или
установлены.

[[Ядро_upgrades]]
==== Обновление ядра

При необходимости предоставляются новые ядра либо для исправления требований безопасности, либо для улучшений.

Как правило, при возникновении такой ситуации ручное вмешательство пользователя не требуется, но может быть полезно знать, как осуществляется обновление ядра и что делать, если произойдет что-то неожиданное.

Несколько пакетов включают файлы, связанные с каждым ядром, а именно: kernel-generic, kernel-modules, kernel-source, kernel-headers. kernel-source и kernel-headers включают файлы, используемые при сборке программ, для запуска системы Slint необходимы только kernel-generic и kernel-headers.

Файлы kernel-модулей поставляются с помощью модулей, , которые являются частями кода, которые "подключены" ядро, чтобы предоставить определенную функцию или справиться с определенным оборудованием.

Как только установлен пакет с ядром и соответствующий пакет с модулями ядра, скрипт
/sbin/wrapupgradepkg собирает <<initrd, initrd>> связанный с этим ядром (с модулями, взятыми из
пакета kernel-modules) и устанавливает его вместе с ядром в каталог /boot.

Затем удаляются предыдущие ядра (не используемые при обновлении).

Затем скрипт обновляет конфигурационный файл GRUB /boot/grub/grub.cfg, считываемый загрузчиком ОС для создания загрузки при загрузке.

Это загрузочное меню включает как минимум два элемента загрузки, указывающие ядро и связанный с ним initrd. Сверху:

* Запуск Slint с использованием только что установленного ядра загрузочного элемента.
* Запуск Slint с использованием ядра, используемого во время обновления.

Это обеспечивает тип "безопасной сети" на случай, если Slint не должен't загрузки с новым ядром:
в этом случае просто стрелка вниз после того, как отображается меню загрузки для запуска Slint с предыдущим ядром

Вы можете просмотреть новое загрузочное меню перед перезагрузкой, набрав его как root:
----
grub-emu
----
Затем отображается загрузочное меню эмулятора или "fake", с тем же расположением, что и реальное меню, которое будет отображаться
при загрузке.

Вы можете перемещаться в ней с помощью клавиш со стрелками вниз и вверх, чтобы выделить (поставить фокус) загрузочную запись, в которой вы можете отобразить подробности нажатия 'e'. Вы можете вернуться в меню, нажав Escape.

Чтобы выйти из grub-emu нажмите c, затем *exit* и нажмите Enter.

[[Get_additional_applications]]
==== Получить дополнительные приложения

Если приложение, которое вы хотите, не установлено и не доступно в одном из репозиториев, включенных в /etc/slapt-get/slapt-getrc, вы можете сделать для него пакет, использование материалов от волонтеров @ https://slackbuilds.org. Чтобы узнать, как продолжить, прочитайте https://slackbuilds.org/howto/ и https://slackbuilds.org/faq/

Пакеты, собранные таким образом, должны быть совместимы с Slint.

Два приложения позволяют собрать и установить пакеты, используя строительный материал, предоставленный на https://slackbuilds.org: *slapt-src* и *sbopkg*. Если вы не привыкли к sbopkg, мы рекомендуем использовать slapt-src, чтобы быть знакомым. Однако оба должны работать и давать одни и те же результаты и должны использоваться в качестве корня.

Подробнее мы опишем slapt-src .

[[slapt_src]]
===== Использование slapt-srcrc

Скриптом конфигурации slapt-src по умолчанию является /etc/slapt-get/slap-getrc и имеет это содержимое:
----
BUILDDIR=/tmp/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/14.2/
----
Итак:

* Все строительные материалы и пакеты будут помещены в /tmp/slapt-src
* Названия пакетов заканчиваются .txz
* Материал сборки загружен из репозитория https://slackbuilds.org/slackbuilds/14.2/

Вот вывод команды *slapt-src --help*:
----
Используйте: slapt-src [option(s)] [action] [slackbuild(s)]
  -u, --update обновить локальный кэш удаленных сборок слайдов
  -U, --upgrade-все обновить все установленные сборочные сборки
  -l, --list доступные сборки со слайдами
  -e, --clean очистить каталог сборки
  -с, --search в доступных slackbuild'ах
  -w, --show specified slackbuild
  -i, --установить выборку, построить и установить указанную сборку(и) slackbuild(s)
  -b, --build только получить и построить указанную сборку(и) со шлаком
  -f, --fetch только получить указанную сборку(и) слаксбол(ов)
  -v, --version
  -h, --help
 Опции:
  -y, --Да не запрашивать
  -т, --simulate показывать что будет сделано
  -c, --config=ФАЙЛ использовать указанный файл конфигурации
  -n, --no-dep не искать зависимости
  -p, --postprocess=CMD запускает указанную команду в сгенерированном пакете
  -B, --build-only применимо только к --upgrade-all
  -F, --fetch-only применимо только к --upgrade-all
----

Позвольте'комментировать некоторые из этих опций:

* Используйте -u или --update каждый раз, чтобы обновить список пакетов, которые можно собрать и установить. Эта команда записывает файл /tmp/slapt-src/slackbuilds_data, заменяя предыдущий регистр.
* Используйте -e для сохранения места на диске, удаляя большинство файлов в /usr/src/slapt-src/
* *не* используйте -U, но чтобы перечислить возможные обновления или понижения, без подтверждения: подтверждение приведет к замене всех Slint пакетов на другую версию, если они доступны в удалённом репозитории, возможно ломать программное обеспечение, несовместимое с этой другой версией.
* -i также может обновить пакет, уже установленный с https://slackbuilds.org, если сопровождающий сценария SlackBuild обновил его, изменив переменную VERSION.
* Используйте -f для загрузки файлов только в https://slackbuilds.org для целевой программы. Это может быть полезно, если вы хотите проверить материал для сборки или настроить сборку. Например, пусть'с предполагают, что вы хотите получить строительный материал для программного обеспечения *mxml*. Команда ниже дает некоторую информацию о программном обеспечении и какие файлы хранятся в https://slackbuilds.org для него:
+
----
slapt-src --show mxml
Название SlackBuild : mxml
SlackBuild Version: 3.
SlackBuild Категория: библиотеки/mxml/
SlackBuild Описание: mxml (библиотека парсинга)
SlackBuild файлы:
 README
 mxml. lackBuild
 mxml.info
 slack-desc
----
+
Загрузите эти файлы, а также архив исходных текстов из исходного репозитория со следующей командой:
+
----
slapt-get -f mxml
----
+
зная из вывода предыдущей команды о том, что файлы хранятся в подкаталогах/mxml, вы можете проверить, какие файлы были загружены с помощью этой команды:
+
----
ls -1 /tmp/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* Используйте -b, если вы хотите построить пакет, но не установите его. В приведенном выше примере он будет сохранен в /tmp/slapt-src/libraries/mxml, так что вы сможете установить его после нажатия:
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txz
----
+
* Используйте -c, если вы хотите использовать пользовательский файл конфигурации вместо стандартного файла /etc/slapt-get/slap-getrc

[[sbopkg]]
===== Использование sbopkg

WARNING: в некоторых случаях программное обеспечение поставляется в Slint и также доступно в https://slackbuilds.org , но с другим именем, которое может привести к проблемам. Эти несоответствия решаются при использовании slapt-src, но еще не при использовании sbopkg.

Перед использованием sbopkg, прочитайте его файл справки и его страницу man typing как root: *sbopkg --help* и *man sbopkg*

Короче, если использовать только командную строку, как root:

* синхронизировать локальный репозиторий с удаленным хранилищем для его обновления:
+
----
сбопкг -р
----
* написать «Очередной файл» с указанием зависимостей в правильном порядке сборки и установки их перед тем, как вы хотите:
+
----
sqg -p <package name>
----
Будет записан файл очереди с именем /var/lib/sbopkg/queues/<package name>.sqf

Если нет зависимостей, файл очереди не будет записан

* сборка и установка зависимостей тогда,нужное программное обеспечение:
+
----
sbopkg -i <package name>
----
Если файл очереди существует для этого пакета, выберите использовать его при запросе.

Если пакет, упомянутый в очереди файл, уже установлен, он будет пропущен.

Следовательно, если вы хотите обновить пакет, уже установленный с помощью sbopkg, вам придется удалить его
перед сборкой и установкой нового.

Имейте в виду, что сборка и установка пакетов может иногда приводить к возникновению проблем, таких как недостающие зависимости или конфликты с установленными пакетами: компоненты, используемые для сборки пакетов, предоставляются добровольцами, которые не могут проверить результаты в каждой возможной конфигурации.

WARNING: Если вы не можете найти пакет для программного обеспечения, которое вы хотите, или вещи построить один @ https://slackbuilds.org, вы можете попробовать собрать и установить эту программу вручную, выпустив команды ". настроить && make && make install". Не стоит этого делать, так как программное обеспечение, собранное и установленное таким образом, не будет управляться системой управления пакетами Slint и связанными с ними инструментами.

Напротив, просто оставьте вопрос или запрос в списке рассылки Slint и мы постараемся помочь, возможно добавление этого пакета в репозиторий. По завершении (это будет объявлено в списке рассылки), чтобы установить его в качестве root одного из этих команд:
----
slapt-get -i <package name>
slapt-get --install-set Slint
----

=== Управление пользователями и группами.

Для управления пользователями и группами предоставляются две команды:

* Команда _usersetup_ (TUI)
* Команда _gtkusersetup_ (GUI), с иконкой в Системной категории Slint)

Эти команды позволяют добавлять или удалять пользователей и группы пользователей и добавлять пользователей в группы.

Имейте в виду, что каждая учетная запись по умолчанию связана с ее областью в каталоге /home . Например, если вы добавите пользователя *leonie*, будет создана папка /home/leonie, к которым только этот пользователь (и root) будет иметь доступ.

=== Изменить язык системы по умолчанию

Две команды предусматривают следующее:

* Команда _localesetup_ (TUI).
* Команда _gtklocalesetup_ (GUI), с иконкой в группе Slint Control Center.

Имейте в виду, что эти параметры изменяют язык, используемый интерфейсами приложений, если они интернационализированы, а не раскладку клавиатуры (см. ниже).

Также, локализованные пакеты (если имеются), соответствующие выбранному языку, уже установлены в конце установки Slint. Если позже вы измените язык по умолчанию, то вам нужно будет установить соответствующие локализованные пакеты, если хотите.

Локализованные означает «предоставляемые в данном месте», локаль является языком плюс особенности, связанные с географическим районом. Например, на португальском языке в Португалии и Бразилии разные. В локализованных именах пакетов l10n это аббревиатура "локализация", означающая "буква l, 10 других букв, буква n".

Локализованные пакеты включены для многих языков. Их имя включает в себя имя базового пакета, дефис, затем код языка. Ниже перечислены базовые имена локализованных пакетов:
[options="autowidth"]
|====
| Имя базового пакета | Описание
| асфальт | списки слов для проверки орфографии
| calligra-l0n | локализован в офисе Calligra
| kde-l10n | локализованный рабочий стол KDE
| libreoffice-l0n | локальный пакет LibreOffice
| libreoffice-помощь | локальная справка для LibreOffice
|====

Чтобы найти локализованный пакет, введите в эмуляторе терминала в качестве root (пример для kde-l10n): +
`spi libreoffice`

Отображается список всех локализованных пакетов LibreOffice. Найдите то, что вы хотите и установите его. Например, для Персидского языка код `fa` (короче для Farsi), чтобы установить его тип: +
`spi -i libreoffice-l0n-fa`

Если вы предпочитаете, вы можете использовать `gslapt`. Затем введите имя пакета в поле поиска для отображения всех локализованных пакетов libreOffice.

=== Изменить клавиатуру

Вы можете изменить раскладку по умолчанию, используемую в графическом режиме с помощью:

* Команда _настройки клавиатуры_ (TUI)
* Команда _gtkkeyboardsetup_ (GUI), с иконкой в Центре управления Slint Center, категории фурнитура.

Эти команды также позволяют выбирать, следует ли включать numlock при запуске системы, и если SCIM (метод ввода) должен быть включен при загрузке системы.

Если вы используете оконный менеджер с панелью, также можно сделать этот параметр щелчком правой кнопкой мыши по апплету клавиатуры (отображается по умолчанию в виде двух букв кода языка карты клавиатуры). KDE и Xfce имеют для этого специфические инструменты.

В командной строке, но все еще для графического режима используйте вместо setxbmap

Например, для установки раскладки на украинскую в графическом режиме просто введите как обычный пользователь: +
`setxkbmap -layout ua`

Чтобы узнать больше, прочтите страницу man для setxkbmap.

=== Установить принтер

В Slint CUPS сервер печати управляет задачами печати и принтеров. В конфигурации по умолчанию, записанная в файле /etc/cups/cupsd. если только пользователям, принадлежащим к `sys` (короткий для _системы_) группе разрешено выполнять административные задачи, как добавление или удаление принтера.

Для простой установки (принтер, подключенный к настольному компьютеру или ноутбуку и не разделяемый между машинами), вам просто нужно добавить одного пользователя (который будет управлять принтерами) в группу `sys`. Для примера, добавление пользователя _dididier_ к группе `sys` может быть сделано двумя способами:

* В консольном режиме или с помощью эмулятора терминала станьте пользователем с `su` , а затем напечатайте :
+
`gpasswd --add didier sys`
+
* В графическом режиме из центра управления слепой щелкните на Пользователи и Группы (категория Система), выберите пользователя и нажмите Свойства, затем на вкладке Группы отметьте `sys`. Или другой раунд линии (выберите группу, затем добавьте пользователя в нее).

Есть несколько способов добавления и настройки принтера (это должно быть сделано пользователем из группы `sys`):

* Нажмите кнопку Настроить принтер из центра управления слепом, чтобы отобразить графический интерфейс, позволяющий простую установку...
* ... Или нажмите на Cups Print Control the display web interface to the CUPS server. Вы также можете отобразить веб-интерфейс на сервере CUPS набрав `localhost:631` в поле адреса веб-браузера.
* Если у вас устройство Hewlett Packard, щелкните правой кнопкой мыши на логотипе *hp* в области уведомлений панели.

NOTE: Чтобы выполнить любой параметр печати, сервер CUPS должен быть запущен. Запускается при запуске Slint, если сервис `чашки` проверены системными службами (проверено по умолчанию в Slint).

=== Настройка звука


В Slint приложения либо посылают звуковой сигнал ALSA или PulseAudio.

В последнем случае PulseAudio в свою очередь посылает выходной поток на микшер ALSA, который направляет его на звуковые карты.

Как следствие, установка как громкости выходного звука всегда может выполняться микшером ALSA, , а также микшером PulseAudio , но только в том случае, если приложение посылает звуковой сигнал в PulseAudio.

Теперь мы представим приложение, которое может быть использовано для изменения настроек звука

==== pavucontrol (для PulseAudio)

`pavucontrol` означает управление громкостью PulseAudio и графическое приложение. Вы можете запустить его из меню терминала или приложения, или щелкните правой кнопкой мыши значок звукового микшера на верхней панели Mate. На самом деле он позволяет больше параметров, чем просто управление громкостью, потратьте время на изучение всех его функций.

Вы также можете использовать апплет управления громкостью в области уведомлений панели: щелчок левой кнопкой мыши позволяет настроить громкость, Щелчок правой кнопкой мыши дает доступ к другим настройкам и позволяет запускать микшер павильона.

[[Sound_on_the_command_line]]

==== alsamixer  (for ALSA)

alsamixer — приложение для ncurses, обеспечивающее полуграфический пользовательский интерфейс.

Для использования введите в консоли или в графическом терминале:
----
alsamixer
----
затем:

* Используйте клавишу вверх для увеличения громкости на 5%
* Используйте клавишу вниз, чтобы уменьшить громкость на 5%
* нажмите Esc для выхода из приложения.

==== amixer (для ALSA)
Эта команда имеет форму:
----
amixer <arguments>`
----
Например, для установки главного громкости на 70% тип:
----
amixer sset Master 70%
----
Чтобы узнать больше, введите одну из следующих команд:
----
amixer man
amixer -h
----
==== Сэм (смеситель с дружественным отношением к речи)
sam позволяет выбрать звуковую карту при наличии более чем одного
такого устройства в вашей машине. +
Когда есть только один, он непосредственно представляет различные микшеры
для конфигурации.

Все выделения, будь то звуковые карты, Микширы или данная особенность
 конкретного микшера выбираются прокруткой доступных параметров с помощью стрелок вверх и вниз, затем введите желаемый один: +
`q` оставить список выбора и/или quits. +
`Shift-q` выходит из программы отовсюду. +
`F1` Отображает любую дополнительную информацию, если таковая имеется.

Когда имя желаемого параметра известно, вместо этого можно нажать его первую букву.
Первая буквенная навигация не чувствительна к регистру.
Это приведет вас к первому выбору, начиная с нажатой
буквы.  Нажав на ту же букву снова, вы перейдете к следующему варианту
, начиная с этой буквы, если такой вариант существует.
Повторение буквы будет повторяться среди всех вариантов, начинающихся с этой буквы.

Свойства установки микшера можно перечислить, нажав f1. +
Они представлены в виде списка отбора, кратко показывающей всю актуальную информацию. .
"Громкость воспроизведения вниз от 84%" является параметром для уменьшения громкости воспроизведения
в настройках громкости воспроизведения.  Как вы можете видеть, он также говорит вам, что такое
текущие настройки.

NOTE: sam не работает корректно в графическом терминале. Используйте его в консоли.

==== pamixer и ponymix (для PulseAudio)
Эти свойства аналогичны, с коммандами в этой форме:
----
pamixer <arguments>
ponymix <arguments>
----
Например, для раскрашивания типа, используемого по умолчанию, необходимо установить громкость в 70%:
----
pamixer --set-volume 7
set-volume ponymix 8O
----
Чтобы узнать больше, наберите:
----
pamixer -h
ponymix --help
----

==== pacmd и pactl (для PulseAudio)

Оба этих приложения управляют запущенным сервисом PulseAdio .

WАRNING: Однажды pacmd набрал интерактивный диалог. Нажмите Ctrl+d, чтобы выйти из него, но не вводите выход, так как это может убить PulseAudio!

Чтобы узнать больше:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== Сохранить и восстановить уровень звука

Просто сделайте файл /etc/rc.d/rc.alsa исполняемым. Как корень:
----
chmod /etc/rc.d/rc.alsa
----
При запуске этот скрипт восстановит предыдущие настройки звука, если
они были ранее сохранены, устанавливает тома по умолчанию и хранит
их, так что они будут восстановлены при следующей перезагрузке.

Если вы don't хотите, чтобы этот скрипт установил тип тома по умолчанию как root:
----
касание /var/lib/alsa/no.asound.state
----

Вы можете изменить уровни звука по умолчанию с помощью alsamixer или amixer
, а затем ввести как root:
----
alsactl магазин
----
Затем при следующем запуске скрипт восстановит их.

Чтобы узнать больше:
----
man alsactl
----
=== Конфигурация сети

Если вы не установили't настройки сети во время установки Slint, первый
станет root'ом, набрав `su -` либо в консоли, либо в графическом
терминале, например mate-terminal, затем введите пароль администратора.

Настройка сети осуществляется скриптом `netsetup`.
Таким образом, вы просто наберите команду `netsetup` на этом
том же терминале, где вы've просто требует root-привилегий.
Сначала вам будет предложено имя хоста вашей машины. вы можете выбрать любое имя
, но имейте в виду, что оно должно быть одним словом.
Тогда вас попросят доменное имя. Если машина не является сервером
, вы можете выбрать любого.
После этого вам будет задан вопрос о том, как ваша машина подключается к сети. Если у вас
, у вас есть некая причина (и вы знаете, что делаете), храните
по умолчанию `NetworkManager` для автоматической настройки сети.

Для проводных соединений, которые должны быть достаточно для подключения при следующей загрузке
автоматически.

Для настройки беспроводного соединения доступны две команды с помощью
командной строки.

Опять же, вы можете напечатать команды прямо на консоли или в графическом терминале
типа mate-terminal. Напечатайте их как обычных пользователей не как
root.
Если вы следовали этим инструкциям и уже стали суперпользователями, вы просто
напечатаете `выход` , чтобы вернуть статус обычного пользователя.

Две упомянутые команды - `nmtui` (диалоговое окно) или `nmcli` (чистая командная строка),
доступны для обоих.

Если вы предпочитаете работать с командной строкой, сначала прочтите документацию nmcli. Просто введите `nmcli --help` и `man nmcli`
, чтобы узнать все детали.
Хотя `nmcli` предлагает больше возможностей, в большинстве случаев, функциональность
из `nmtui` будет достаточной для настройки беспроводной сети, так что мы
опишем это здесь:

Используя `nmtui`, вы можете перемещаться с помощью клавиш Tab и стрелки.
Вам будут предложены три варианта: +
`Редактировать соединение` +
`Активировать соединение` +
`Задать имя системного хоста` +

Если беспроводное соединение еще не установлено, выберите `Активировать соединение`.
Начиная с сверху вниз, сначала проводные соединения (если таковые имеются)
будут предложены, после чего все доступные беспроводные сети будут перечислены.
Перейдите с помощью клавиш со стрелками вниз и вверх, чтобы выбрать нужную вам сеть,
затем просто введите Enter: вы, вероятно, попросят ввести пароль или ключ шифрования.
Введите его, используйте клавишу Tab для подтверждения, а затем выйдите и вы закончите.

Только в графическом режиме вместо `nmcli` или `nmtui` вы можете использовать приложение
`nm-connection-editor`.

=== Конфигурация сервисов

Если вы использовали Ручной режим, то при запуске были заданы вопросы о том, какие системные службы по умолчанию активировались. +
Если вы использовали настройки по умолчанию

В обоих случаях эти настройки можно изменить несколькими способами:

* Запуск как root команды `servicesetup` (TUI)
* Только в графическом режиме, используя `gtkervicesetup`, доступен из центра управления слепом, категории Система или набрав Alt+F2, чтобы вызвать диалог "Выполнить...", затем набрав *gtksetrvicesetup*.
* В качестве корневого создания соответствующего скрипта (chmod 755 <path to the script> или не исполняемый файл (chmod 644 <path to the script>). Например, чтобы сделать fail2ban исполняемым файлом вы введете: `chmod 755 /etc/rc.d/rc.fail2ban`

[IMPORTANT]
====
Изменять настройки по умолчанию, только если вы знаете, что вы делаете.
====

Сервисы управляются скриптами, имя которых начинается с `rc.` в каталоге /etc/rc.d/. Например, сервис acpi управляется скриптом оболочки /etc/rc.d/rc.acpi. Большинство сервисов включаются при запуске, если соответствующий скрипт исполняется. В нижеследующей таблице мы указываем, активируется ли она при запуске (`на` в колонке А) или нет (`выкл` в колонке А). Если столбец пуст, то активация сервисов зависит от выбора, сделанного во время установки. `A` в столбце означает, что служба активирована в режиме автоустановки, активируется если пользователь выбран во время установки. Столбец Пакета указывает, какой программный пакет предоставляет сценарий, соответствующий службе, случается

[options="autowidth"]
|====
| *Service* | *A* | *Пакет* | *Цель и комментарии*
| acpi | on | кислота | Расширенная конфигурация и интерфейс питания, позволяет, например, управлять питанием или перезагрузкой
| alsa | on | alsa-utils | Установить настройки звука по умолчанию или восстановить сохраненные
| alsa-oss | выкл | alsa-utils | Модули ядра ALSA OSS. Не полезно в случаях модов, которые не включены по умолчанию в Slint.
| эльк | выкл | нетталк | Позволяет Unix-подобным операционным системам служить файлом, печатью и временем серверами для компьютеров Macintosh.
| автофс | выкл | автофс | Автомонтирование на основе ядра для Linux
| bind | выкл | bind | Сервер имени. Большинство пользователей будут полагаться на пульт дистанционного управления. Включите его, если вы хотите запустить сервер имён в этой системе.
| bitlbee | on | bitlbee | BitlBee — это IRC демон, который может общаться с сетями обмена мгновенными сообщениями
       и выступать в качестве шлюза. Пользователи могут подключаться к серверу с помощью любого нормального
       клиента IRC и видеть их список "друзей в &bitlbee.
| Bluetooth | on | синий | Позволяет общаться с Bluetooth устройствами
| бритва|  | бритва | Позволяет общаться с терминалом Брайля или с программой чтения экрана. Активировать при запросе во время установки
| cgconfig | on | группы libcgroups | Запускает утилиту cgconfigparser, которая анализирует /etc/cgconfig. для настройки иерархии контрольной группы, включая установку разрешений (UID и GID) групп и, возможно, настраиваемых параметров контроллеров. Это облегчает то, что сами при каждом запуске, например при запуске отдельного скрипта оболочки. This script is executable by default but anyway wвкл't do anything until /etc/cgconfig.conf be edited (all lines are commented out as shipped)
| cgmanager | выкл | cgmanager | Starts the cgmanager daemon that provides an alternate way to manage the cвклtrol group hierarchy through D-Bus requests possibly through the cgm front-end utility.
| cgproxy | выкл | cgmanager | Starts the cgproxy daemon, that allows programs and users in a cвклtainer to make cgroup administration requests using DBus calls, sending the user-ids or group-ids as SCM credentials to the cgmanager.
| кгр | on | группы libcgroups | Starts the cgroups rules engine daemвкл that automatically distributes to appropriate control groups the processes that changes their effective UID or GID, applying the rules found in /etc/cgrules.conf. This allows to cвклtinue apply resources control resources on such processes that could otherwise escape it. Этот скрипт исполняемый по умолчанию, но в любом случае выиграл't делать что-нибудь до тех пор, пока /etc/cgrules.conf не будет отредактирован (все строки будут закомментированы как отправленные)
| consolekit | on | ConsoleKit2 | Этот демон используется агентом авторизации polkit's консоли, чтобы проверить привилегии пользователя, желающего перезагрузить или выключить систему, например.
| cpufreq | on | sysvinit-скрипты | Настройки частоты и напряжения ЦП в ядре.
| чашки | on | чашки | Скрипт запуска/выключения для сервера печати CUPS
| cups-browsed | выкл | cups-фильтры | Делает удаленные принтеры доступными локальными.
| днсмак | выкл | днсмак | Запуск/стоп/перезапуск dnsmasq (небольшой DNS/DHCP сервер)
| эспик | | эспик | запускает/останавливает/перезапускает консоль espeakup. Включите, если пользователь запросил речь во время установки или позже набрал громкоговоритель с espeakup
| неудачный 2ban | выкл | неудачный 2ban | start/stopops fail2ban , который сканирует файлы журнала, такие как /var/log/pwdfail и запрещает IP-адрес, что делает слишком много сбоев с паролем, и также обновляет правила брандмауэра, чтобы отклонить IP-адрес.
| font | выкл | kbd | Sets the console fвклt (used in Console mode, not in Graphical mode)
| предохранитель | on | предохранитель | Загрузите модуль предохранителя и смонтируйте файловую систему предохранителя. FUSE - это простой интерфейс для пользовательского пространства для экспорта виртуальной файловой системы в ядро Linux.  FUSE также стремится предоставить безопасный метод для непривилегированных пользователей для создания и монтирования их собственных реализаций файловой системы.
| фенрир | выкл | фенрир | запускает/остановить/перезапустить программу чтения с экрана fenrir, которая может быть запущена после ввода динамика с fenrir.
| font | выкл | kbd | установить пользовательский шрифт консоли
| gpm | вкл | gpm | Сервер General Purpose Mouse позволяет вырезать и вставлять текст с экрана в консоли Linux.
| httpd | выкл | https | Запускает или останавливает веб-сервер Apache
| inet1 | on | сетевые скрипты | Этот скрипт используется для создания различных сетевых интерфейсов.
| inet2 | вкл | сетевые скрипты | Этот скрипт shell загружает всю сетевую систему.
| inetd | вкл | inetd | BSD "суперсервер". Пользователь должен отредактировать /etc/inetd.conf для того, чтобы эти сервисы были действительно использованы.
| Пер_вперёд | выкл | сетевые скрипты | Запустить/остановить пересылку IP-пакетов, необходимых для работы компьютера в качестве маршрутизатора.
| раскладка | on | installer | Загружает карту клавиатур, используемую в режиме Консоли.
| местный | выкл | sysvinit-скрипты | запускает демоны, не запущенные /etc/rc.d/rc.M при загрузке.
| цикл | on | sysvinit-скрипты | Загружает модуль ядра циклических устройств.
| lxc | выкл | lxc | This scripts starts (if cвклfigured to be auto-started) and stops lxc containers.
| мцелог | выкл | мцелог | Запускает журналирование ошибок mcelog. Этот журнал и обрабатывает аппаратные ошибки ЦП на системах x86
| автобус сообщения | on | dbus | Шина сообщений для всей системы D-BUS. Это демон, который отправляет уведомления о системных событиях и других сообщениях, обеспечивая межпроцессорную связь.
| модули | on | sysvinit-скрипты | Compute the kernel modules dependencies and start other scripts that load modules not automatically loaded by eudev, possibly for specific kernel versiвклs
| modules.local | on | sysvinit-скрипты | Загрузить модули не автоматически через eudev
| murmur | выкл | murmur | Запускает/останавливает мурмурский сервер голосового чата для mumble
| mysqld | выкл | mariadb | Начинает/останавливает сервер MariaDB. MariaDB - это ответвление MySQL, полностью совместимое с ним
| сетевой менеджер|  | Менеджер сетей | This is a daemon for automatically switching network cвклnectiвклs to the best available cвклnection. Activated if NetworkManager is chosen to configure the network, during or after installatiвкл
| nfsd | выкл | утилиты | Запускает/останавливает nfs (Network File Server.qq
| ntpd | on | ntp | Запускает остановку ntp ( Net'work Time Protocol).
| блокировка|  | salixtools | Activate numlock вкл the console
| пкмция | выкл | pcmciautils | Скрипт для инициализации подсистемы PCMCIA.
| php-fpm | выкл | php | Запускает PHP демон менеджера процессов FastCGI.
| pulseaudio | выкл | pulseaudio | Запускает пульсирующее аудио по всей системе. Это не рекомендуется в Slint.
| rpc | выкл | rpcbind | Start/stop/restart RPC (remote process communications) daemвклs needed to use NFS. Чтобы запустить NFS сервер, запустите его обязательно.
| самба | выкл | самба | Запустить/остановить/перезапустить файл SMB CIFS Samba и распечатать сервер для клиентов CIFS.  Она позволяет вам сделать файловое пространство или принтеры на хосте Samba доступными для клиентов CIFS (например, ПК под управлением Windows).
| саскатд | выкл | цирус-сасл | saslauthd is a daemon process that handles plaintext authentication requests вкл behalf of the SASL library.  Библиотека CMU Cyrus SASL в основном используется для аутентификации почтовых серверов.
| sendmail | выкл | sendmail | Пуск/стоп/перезапустить MTA Sendmail (почтовой агент или система доставки).
| последовательный | выкл | util-linux | Инициализация и установка последовательных портов на вашей системе
| установленный срок | вкл |util-linux |  Предоставляет командную строку для утилиты setterm для задания атрибутов терминала (главным образом используется для пустого экрана и управления питанием).
| умный | выкл | smartmontools | Запустить/остановить/перезапустить демон smartd, который отслеживает статус S.M.A.R.T. совместимый жесткий диск и сообщает о любых проблемах.
| шт | on | openssh | Запустить/остановить/перезапустить сервер безопасной оболочки
| snmpd | выкл | net-snmp |Запустить/остановить демон net-snmp SNMP (Simple Network Management Protocol)
| syslog | on | sysklogd | Запустить/остановить/перезапустить службу журналирования, которая записывает и ядро и системные'сообщения.
| sysstat | вкл | систат | Сброс системных журналов активности, используемых для расчета статистики производительности
| выступление |  | выступление | запускает/останавливает/перезапускает чтение с экрана громкости, которое может быть запущено после ввода динамика с помощью речи.
| sysvinit | on | sysvinit-скрипты | Этот файл обеспечивает основную совместимость со скриптами в стиле SystemV, обнаруженными во многих бинарных пакетах
| swapinzram | on | swapinzram | Настройте блочное устройство подкачки в оперативной памяти с помощью zram
| syslog | on | syslogd | Запустить/остановить/перезапустить службу журналирования.
| sysstat | выкл | sysstat | Сбросить системные журналы активности.
| timidity | выкл | TiMidity++ | Start/stop/restart the TiMidity++ ALSA sequencer client. TiMidity++ is a software synthesizer.  Он может проигрывать MIDI файлы, конвертируя их в формат PCM или другие форматы аудио файлов.
| udev | on | эвдейский | Этот скрипт инициализирует udev, который заполняет директорию /dev узлами устройств, сканирует устройства,
загружает соответствующие модули ядра и настраивает устройства.
| ulogd | on | ulogd | запускает демон ulogd пользовательского пространства для ведения журнала сетевых фильтров/iptables.
| vde2 | вкл | vde2 | Запустить/остановить/перезапустить переключатель VDE. VDE является виртуальной сетью, поддерживающей ethernet, которая включает в себя такие инструменты, как 'vde_switch' и 'vdeqemu'.
| беспроводной | on | беспроводные инструменты|Этот скрипт настраивает PCI, USB и 32-битные беспроводные устройства Cardbus. Обычно этот скрипт вызывается из rc.inet1, а не запускается напрямую
| yp | on | yptools | Start NIS (Network Information Сервисs). NIS provides network-wide distributiвкл of hostname, username, and other information databases.
|====

Вы можете запустить или остановить службу, используя в качестве root службу ``. Чтобы узнать больше типа `man service`.

== Glossary

Several definitiвклs in this glossary are taken or adapted from  https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiвкл]]Приложение:: An applicatiвкл program (applicatiвкл for short) is
a computer program designed to carry out a specific task typically requested by
end-users.
+
Applications are not generally cвклsidered as part of the operating system, meaning that they can be added to the system after its installation. They
perform non-system-related functiвклs, such as word processing, architectural
design, mechanical design, workstation publishing, or financial analysis.


[[boot]]Засада::
Boot means switch-вкл a computer to start an operating system. Несколько операционных систем
могут быть установлены на одном компьютере. Select which one to load into
RAM and run can be dвклe either by the firmware or by a software named boot
manager (GRUB in Slint's case). The firmware of a computer can support вклe of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiвклs written in a boot sector.
* В режиме EFI оператор ОС представляет собой программу, хранящуюся в исполняемом файле, расположенную в каталоге системного раздела EFI (ESP).

[[ЦП]]CPU::
Группа ЦП или ЦП выполняет инструкции по программам.

[[command]]Команда:: Команда определяется https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] как «директива к <<shell, оболочке>> для выполнения конкретной задачи».
+
Задачей для выполнения может быть <<application, приложение>> или утилита <<utility, >>.
+
Основная структура команд оболочки определена в главе https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell Commands] спецификации POSIX.
+
Примеры команд приведены в <<bash shell>>.

[[console]]Консоль:: Слово "console" относится к началу компьютерных
систем, когда системный администратор набрал команды на устройстве, включая
клавиатуру и принтер, , введенные команды и вывод
с компьютера, который печатается на консоли, обеспечивая лог того и другого.
+
В персональных компьютерах пользователь вводит команды на клавиатуре и их вывод
на экране, которые могут быть отделены от
компьютера или интегрированы в компьютер, как на ноутбуке.

[[device]]Устройство::

Компьютерная периферия или объект, который кажется приложению как таковый.[POSIX]

[[directory]]Каталог::
Каталог - это другое имя папки. Файловые системы используют каталоги для
упорядочения файлов внутри разделов.
+
Каталоги могут содержать файлы, а также другие каталоги. Структура
может быть представлена как верхнее дерево. Директория верхнего уровня
диска называется корневой каталог.  В Linux символ / разделяет
уровней дерева. / только представляет корневой каталог, /home hosts файлы
принадлежащие пользователям, /home/dididier хосты файлов, принадлежащих к dididier.
/root содержит файлы пользователя с именем root (система'с администратором).
Примечание: 'root' может ссылаться на директорию верхнего уровня или систему'с администратором.

[[drive]]Диск::
Диск - это устройство, сохраняющее неволатильные данные, что означает, что данные не
стираются при отключении питания. Примеры: жесткие диски, SSD, USB-стики, SD
карты считыватели, eMMC.
+
Хранение данных можно подключить к накопителю или съемному
например к SD-картам, USB-накопителям и накопителям, подключенным к USB.
+
Операционная система, установленная в съемном носителе или на внешнем накопителе,
портативная: она может быть перемещена с компьютера на другой.

[[display_manager]]Дисплей менеджера::
Дисплей менеджер (или диспетчер логинов) — это программа, которая отображает окно на экране
, на котором запрашивается имя пользователя и пароль пользователя, затем запускает
графическое окружение, выбранное указанным пользователем.

[[encryption]]Шифрование::
Шифрование - это процесс преобразования данных в неузнаваемую форму ("зашифрованную").
Он обычно используется для защиты конфиденциальной информации, чтобы только
уполномоченных лиц могли ее просматривать. Один файл или каталог, раздел также
в целом может быть зашифрован, , что делает его доступным только после того, как
набрал небольшой текст под названием ключевая фраза, хранится в секрете.

[[file]]Файл::
Компьютерный файл - это набор цифровых данных, собранных под тем же именем, записанных на постоянном носителе, — массовое хранилище, например жесткий диск, SSD, DVD, SD-карта или USN палка и обрабатывается в качестве единицы.
+
Файлы могут содержать такие данные, как тексты, изображения, звуки, видео или компьютерные программы.

[[file_system]]Файловая система::
Файловая система — это программа, которая управляет файлами и каталогами в разделе.
Он запоминает местоположение в физическом носителе данных
содержащихся в файлах, позволяя их читать или записывать. Примерами распространенных
файловых систем являются vfat, ntfs, ext4, f2fs. В этой команде перечислены все файловые системы
, позволяющие читать данные, содержащиеся в разделе Linux:
+
----
cat /proc/filesystems|grep -v nodev
----

[[firmware]]Прошивка::
Прошивка — это программное обеспечение, инициализирующее и проверяющее аппаратное обеспечение, затем
выбирает и загружает ОЗУ операционной системы, или запускает программу, называемую системным менеджером
, который будет делать это. Прошивка хранится в неизменяемой памяти
таких устройств, как ROM, EPROM или флэш-памяти. Это первое программное обеспечение, запускаемое
при загрузке компьютера. Он предоставляет меню, позволяющее настроить аппаратное обеспечение и
выбрать в каком режиме (Legacy или EFI) загрузиться, и в каком порядке искать
операционную систему или другие приложения (например, загрузочный менеджер GRUB).

[[kernel]]Kernel::
Ядро Linux — это программное обеспечение в ядре системы Slint, которая обрабатывает
взаимодействия между приложениями и оборудованием.
+
Он представляет себя как один файл, установленный в каталоге /boot. Например, файл /boot/vmlinuz-generic-5.12.11 представляет собой ядро из пакета kernel-generic.
+
При запуске ядро копируется в ОЗУ.

[[initrd]]Initrd::
initrd (более точно initramfs или начальная файловая система RAM для Slint) — это
система Linux, предоставляемая как сжатый архив. При загрузке, сразу же после загрузки ядра
в оперативной памяти, inird также загружается в ОЗУ. Файл /init
запускается: загружает необходимые модули ядра в ОЗУ, регистрирует устройства, возможно
разблокирует корневое устройство, смонтирование файловых систем псевдо, затем переключитесь на корневую файловую систему
для фактического запуска системы.
+
initrd представляет себя как один файл, установленный в каталоге загрузки.
Например, файл initrd-generic-5.12.11 является initrd

[[live_system]]Онлайн система::
Онлайновая система — это операционная система, которая, вместо того, чтобы устанавливаться на устройстве,
например на жестком диске или SSD, находится целиком в <<RAM>>.
+
An initrd is also a live system, and so is a Slint установщик wich is basically an initrd.

[[partition]]Разделы::
Раздел — это раздел носителя, такого как жёсткий диск или SSD.
рассматривает операционную систему как отдельный логический объем, который делает ее
функцией похожей на отдельный носитель.

[[partition_table]]Таблица разделов::
A partition table is the permanent structure recording how information is laid
out on a media, mainly recording the beginning and end of each partition on
the media.
+
The most common types of partition tables are the DOS partition table, initially
used by the MS-DOS operating system, and the GUID Partition Table or GPT, which
allows to handle more partitions and larger drives.

[[program]]Программа::
A prepared sequence of instructions to the system to accomplish a defined task. The term "program" encompasses applications written in the Shell Command Language, complex utility input languages (for example, awk, lex, sed, and so on), and high-level languages. [POSIX]

[[RAM]]RAM::
ОЗУ означает память случайного доступа. Этот тип устройства сохраняет волатильные данные,
что означает, что данные стираются при выключенном питании.

[[shell]]Ракушка:: Программа, которая интерпретирует последовательности ввода текста как команды. Он может работать на входном потоке или может интерактивно запрашивать и считывать команды из терминала. The syntax of the commands
that can be interpretd by the shell can vary along the shell in use but are mainly defined in the the chapter
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2.
Shell Command Language] of the POSIX specification.
+
Slint ships several programs acting as shell, listed in the file /etc/shells. The *bash* shell is used by default.

[[swap]]Поменять::
Область подкачки используется для предварительно хранения данных ранее в оперативной памяти на устройстве
как жёсткий диск или SSD, либо потому, что ОЗУ переполнены, либо
свободного места в ОЗУ, чтобы хранить там наиболее часто используемые данные. Пространство подкачки может
быть разделом на диске типа 'Linux swap' или обычным файлом, сохраненным в
существующем разделе. Существует также 'подмена в zram': в этом случае данные
хранятся в оперативной памяти, но в сжатой форме, к его пригодному размеру ОЗУ.

[[terminal]]Терминал::
Historically a terminal was a physical device composed of a keyboard and a screen
used to type commands and receives responses from a remote computer.
+
Nowadays the commands can be typed in console (or text) mode or in graphical
mode.

[[utility]]Утилита::
Утилита — это программа, вызываемая по имени из оболочки (это также случай <application,applications>>).
+
Utilities are a part of the operating system (but not of the kernel).
They perform system-related functions, such as listing directory contents,
checking file systems, repairing file systems, or
extracting system status information.
+
An utility may be invoked as a separate program that executes in a different
process than the command language interpreter, or it may be implemented as a
part of the command language interpreter.
+
For example, the echo command (the
directive to perform a specific task) may be implemented such that the echo
utility (the logic that performs the task of echoing) is in a separate program;
therefore, it is executed in a process that is different from the command
language interpreter. Practically this means this means that in this case the utility is a program distinct from the shell
+
Conversely, the logic that performs the echo utility
could be built into the command language interpreter; therefore, it could
execute in the same process as the command language interpreter. Such an utility is said "built-in" the shell.

[[virtual_terminal]]Виртуальный терминал::
Виртуальный терминал — это программное обеспечение, моделирующее физический терминал, устройство
, состоящее из клавиатуры и экрана, позволяющее удаленно общаться с компьютером
.
