
=  Slint Handbook (14.2.1)
:toc: left
:toclevels: 2
:toc-title: Вміст
:pdf-themesdir: themes
:pdf-theme: default
:sectnums:

==  Знайомство зі Slint

=== Про Slint

Slint це багатомовний, простий у встановленні, універсальний, дружній до початківців і доступний для незрячих https://uk.wikipedia.org/wiki/%D0%94%D0%B8%D1%81%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%D0%B8%D0%B2_Linux[дистрибутив Linux], що базується на http://www.slackware.com/[Slackware].

Система Slint є повністю функціональною, і може бути адаптована до будь-яких обчислювальних вимог.

==== Особливості

Пропонуються два режими встановлення: Напівавтоматичний (без введення команд Linux), і Експертний для тих, хто хоче більше налаштувань. Також до складу встановлювача входить документація.

Slint є доступним для незрячих користувачів, оскільки надає підтримку мовлення й брайля як під час встановлення, так і під час використання консолі й графічних середовищ.

У всіх системах Slint встановлено широкий асортимент програмного забезпечення для серверів, робочих станцій та ноутбуків, включаючи кілька графічних середовищ: KDE (є необов'язковою), LXDE, MATE, XFCE, та легковагі менеджери вікон. Усі графічні середовища надають простий доступ до всіх програм і можливостей системи, таких як автоматичне монтування знімних пристроїв, сповіщеня про доступні оновлення встановленого програмного забезпечення, доступ до інтернету, вимкнення, перезавантаження, і переведення системи в режим сну. Також вони мають схожі розкладки панелей і меню програм, що забезпечує сумісність.

Обрана мова використовуватиметься для інтернаціоналізованих програм.

Панель Приладів Slint централізує доступ до налаштувань обладнання й системи, пакунків, системних засобів, документації та утиліт.

До складу Slint входить багато програм для створення, перегляду й конвертування документів у різноманітні формати, спілкування електронною поштою, текстового та аудіо чату, відтворення аудіо та відео, надсилання й отримання документів мережею peer to peer, редагування аудіо, відео та графічних документів, розробки програм. Він повністю придатний для використання як сервер у консолі, а також для використання однієї з включених до складу стільниць.

Багато програм доступні для незрячих користувачів. Надається широкий вибір рушіїв перетворення тексту в мовлення (якщо вам потрібні інші, їх можна легко встановити), придатних для використання як у текстовому (консоль), так і у графічному середовищі.

Адміністрування й налаштування вашої системи Slint полегшать кілька внутрішніх засобів.

Безліч програм легко встановлюються як пакунки з програмним забезпеченням за допомогою простої команди, чи кількох кліків. Тисячі пакунків із програмним забезпеченням у вас під рукою!

Користувачі Slint отримують сповіщення про можливість оновлення встановлених пакунків, як тільки вони стають доступними. Їх легко встановити за запитом. Це забезпечує безпеку вашої системи.

Надаються бажані основні налаштування програм, які можна легко змінити.

==== Вміст, версії та модель випуску.

Встановлювач Slint забезпечує лише повне встановлення. Лише стільниця KDE є необов'язковою.

Slint заснований на Slackware, ми схильні надавати нову версію Slint незабаром після випуску версії Slackware .

Однак Slint дотримується моделі постійного часткового оновлення. Це означає що протягом життєвого циклу поточної версії, на додачу до оновлень що усувають проблеми безпеки та містять виправлення значних помилок, деяке програмне забезпечення вибірково оновлюється, щоб надати покращення та додати нові функції. Це стосується програмного забезпечення, що сприяє доступності Slint для незрячих, на кшталт читачів екрана.

Рекомендуємо користувачам одразу переходити на нову версію, після її випуску. До цього часу ми були взмозі надавади інструкції й допоміжні скрипти для оновлення, замість встановлення нової версії з нуля. Ми зробимо все можливе, щоб так лишалося й надалі. Навіть попри те що повне резервне копіювання файлів користувачів, із подальшим їх відновленням після перевстановлення, може бути простішим. Особливо при використанні робочої станції чи ноутбука.

=== Про цей посібник; інші джерела інформації

Цей посібник призначений для нових користувачів Slint, і описує процес встановлення й використання. Концепції й поняття, як ті що специфічні для Slint, так і ті що поширені в інших дистрибутивах Linux, наведені у словнику.

Ми намагаємося адаптувати людей, що прийшли з Windows або MacOS, а також користувачів іншого дистрибутива, на кшталт Ubuntu.

У системі Slint, як правило, наявна документація до встановленого програмного забезпечення. У цьому посібнику ми розглянемо, як отримати до неї доступ.

Доступні й інші джерела інформації:

* Автори програмного забезпечення, що входить до складу Slint, надають її на своїх вебсайтах.
* У багатьох випадках, http://docs.slackware.com/[документація проєкту Slackware], і частково її http://docs.slackware.com/howtos:start[розділи HOWTO], стосуються безпосередньо Slint, але можуть потребувати певної адаптації та оновлення.
* Дистрибутив Arch (ArchWiki), часто надає корисні статі про програмне забезпечення, яке також постачається й у Slint. Наприклад - пошуковий запит "arch wiki mate", приведе вас до https://wiki.archlinux.org/index.php/MATE[цієї сторінки про MATE]. Зауважте: надана інформація може потребувати адаптації, оскільки деякі аспекти Slint і Arch відрізняються. Наприклад, Arch використовує systemd у якості системи ініціалізації, тому програмне забезпечення у Slint та Arch, за замовчуванням може бути налаштоване по-різному.
* І звичайно ж - система пошуку в інтернеті часто може допомогти знайхти відповіді на питання, та інформацію що до усунення проблем.

=== Підтримка

Ви можете отримати допомогу, використовуючи такі канали:

* Поштова конференція Slint є основним каналом підтримки. Щоб підписатися, надішліть електронного листа на адресу slint-request@freelists.org, з темою "subscribe", після чого надайте відповідь на підтверджувального листа, який ви отримаєте. Потім, щоб дізнатися більше, надішліть електронного листа на адресу slint-request@freelists.org, з темою "commands", або "help". Після підписки, для надсилання листів до поштової конференції, використовуйте адресу slint@freelists.org.
* Архів поштової конференції знаходиться https://www.freelists.org/archive/slint[тут].
* IRC: чат каналу #slint на сервері irc.libera.chat (реєстрація непотрібна).
* Mumble: сервер slint.fr (зустріч узгоджується в інших каналах).
* https://forum.salixos.org/viewforum.php?f=44[Форум Slint], люб'язно розміщений нашими друзями Salix (ще один дистрибутив, що походить від Slackware). Потрібна реєстрація.


Щоб дізнатися більше, перегляньте посилання в розділі Інформація у панелі приладів Slint, відвідайте нашу https://slint.fr/wiki/doku.php?id=uk/start[вікі], або введіть у терміналі після встановлення: slint-doc.

=== Переклад, та інша допомога проєкту Slint

Slint потрібні перекладачі! Якщо ви бажаєте взяти участь у боротьбі за переклад, прочитайте інструкції у https://slint.fr/doc/translate_slint.html[Перекласти Slint].

Файли перекладу розміщуються на https://crowdin.com/project/slint[Crowdin].

Якщо ви бажаєте зробити інший внесок у Slint, напишіть до поштової конференції, або киньте рядок на адресу: didierравликslintкрапкаfr. Звичайно ж, запрошуємо й перекладачів приєднатися до поштової конференції!

===  Подяки

Проєкт Slint існує переважно завдяки наполегливій праці перекладачів Slint, та інших учасників. Дякую вам усім!

Дякую George Vlahavas, за його поради й засоби, та учасникам проєкту SlackBuilds.org, які допомагають будувати так багато програмного забезпечення.

Slint базується на Slackware, який представляє Patrick J. Volkerding із учасниками. Дякую! Закликаю всіх користувачів Slint робити внесок у фінансування Slackware, а також робити пожертви на користь проєкта Salix.

Сховища Slint, люб'язно й безкоштовно, розмістив Darren 'Tadgy' Austin. Закликаю всіх користувачів Slint робити внесок у фінансування хоста https://slackware.uk/.

Links for financial contributions: +
https://www.patreon.com/slackwarelinux[Become a Slackware patron] or https://paypal.me/volkerdi[Підтримка Slackware] +
Follow the links on top of http://slackware.uk/slint/x86_64/slint-14.2.1/[this page] to support Slackware UK +
https://salixos.org/donations.html[Donations to Salix]

==  Install Slint

Ця частина посібника описує процес завантаження Slint з інтернету, перевірки цілісності образа ISO із застосуванням контрольної суми, запису ISO на встановлювальний носій, розмітки вашого жорсткого диска, і коротко - процес встановлення.

=== Вимоги

Поточна версія Slint може бути встановлена на комп'ютери, що відповідають таким вимогам:

* Архітектура: x86_64 (64-бітний процесор), також відома як AMD64
* Вільний, або доступний для вивільнення простір на диску (жорсткий диск, SSD, NVME, eMMC): неменший ніж 28 гігабайтів для Напівавтоматичного режима. Повна установка Slint потребує близько 20G без файлів користувачів або додатків.
* Оперативна пам'ять: неменш ніж 2 гігабайта.
* Доступний пристрій DVD або порт USB, прошивка якого підтримує завантаження з носія DVD чи USB. Порожній диск DBD, або носій USB місткістю 4 гігабайти чи більше, який можна використати як встановлювальний носій.

NOTE: Для встановлення Slint, безпечне завантаження має бути вимкнено.

=== Можливості встановлювача

* Встановлювач це "жива система", що працює в оперативній пам'яті. Самочинно він не змінюватиме встановлену систему, лише за запитом.
* Встановлювач повністю доступний для незрячих користувачів, оскільки підтримує Брайль і мовлення, за допомогою читача екрана Speakup.
* До його складу входять усі утиліти, які необхідні досвідченим користувачам щоб підготувати <<drive, диск>>, на який встановлюватиметься Slint.
* Натомість у Напівавтоматичному режимі встановлення, користувачеві потрібно лише відповідати на питання, користуючись у разі потреби контекстною довідкою.
* Встановлювач може звільнити деякий простір для Slint на диску, на якому ви бажаєте встановити його поряд із іншим Linux, за певних умов.
* Можна зробити Slint переносним, тобто здадним працювати на будь-якому комп'ютері, що підтримує завантаження з носія USB, встановивши його на окремий знімний пристрій, що підключається по USB.
* Встановлювач може зашифрувати диск, на якому встановлений лише Slint. Це запобігає крадіжці даних, що містяться на ньому, у разі втрати чи викрадення комп'ютера, або знімного носія.
* Slint можна встановлювати на виділений для нього диск, або поруч з іншою системою.

=== Приготування

<<download_and_verify, Завантаження й перевірка цілісності образа ISO Slint>> +
<<write_the_iso, Запис образа ISO на Встановлювальний Носій>> +
<<make_room_for_Slint, Створення Місця для Slint>> +
<<create_partitions_for_Slint, Створення Розділів для Slint>>

[[download_and_verify]]
====  Завантаження й перевірка цілісності образа ISO Slint

Найновіша версія дистрибутива Slint - 14.2.1.

Найновіший встановлювальний образ ISO завжди доступний у https://slackware.uk/slint/x86_64/slint-14.2.1/iso[цьому каталозі].

[TIP]
====
Якщо ви вже використовуєте версію Slint 14.2.1, немає необхідності у встановленні новіших ISO, оскільки вони містять лише нові можливості встановлювача, а також нові та (або) оновлені пакунки, які ви також можете отримувати, оновлюючи систему.
====

Наведене нижче ім'я файла ISO є лише прикладом, який, під час завантаження, ви адаптовуватимете до поточного імені.

Якщо ви використовуєте Windows, пошук в інтернеті за запитом "перевірка контрольної суми sha256 Windows" підкаже вам, як діяти далі.

Якщо ви використовуєте Linux, можете завантажити образ Iso та його контрольну суму sha256, ввівши:
----
wget https://slackware.uk/slint/x86_64/slint-14.2.2.1/iso/slint64-14.2.1.4.iso
wget https://slackware.uk/slint/x86_64/slint-14.2.1/iso/slint64-14.2.1.4.iso.sha256
----

Щоб перевірити цілісність завантажених файлів, введіть таку команду::
sha256sum -c slint64-14.2.1.4.iso.sha256
результат повинен бути таким:
ГАРАЗД

----
sha256sum -c slint64-14.2.1.4.iso.sha256
----
Результат повинен бути таким: ГАРАЗД +
Інакше - завантажте файли ще раз.

[[write_the_iso]]
====  Запис образа ISO на Встановлювальний Носій

В якості встановлювального носія, може бути використаний накопичувач DVD або USB.

[[make_a_bootable_usb_stick]]
===== Створення Завантажувальної Флешки USB

On a ++Linux++ system, plug in the USB stick, and check it's name with the following command:

----
lsblk -o model,name,size,fstype,mountpoint
----

[WARNING]
====
Уважно перегляньте вивід команди і переконайтеся, що ви не вводитимете ім'я розділа жорсткого диска, замість імені вашої флешки USB.  Увесь попередній вміст флешки USB чи, в разі помилки, розділа жорсктого диска, буде *ВТРАЧЕНО*, *БЕЗ МОЖЛИВОСТІ ЙОГО ВІДНОВЛЕННЯ*.
====

Давайте припустимо, що ім'я флешки USB - /dev/sdb. Її ім'я може бути іншим, тож не копіюйте наосліп наступну команду.  Синтаксис команди для запису ISO Slint на флешку USB, у випадку /dev/sdb, є таким:

----
dd if=slint64-14.2.1.4.iso of=/dev/sdb bs=1M status=progress && sync
----

[NOTE]
====
У наведеній вище команді: *if=* - вказує на розташування ISO Slint, а *of=* - вказує на ім'я флешки USB.  У вашій системі, ці значення можуть бути іншими.
====

On ++Windows++ use an application like http://rufus.akeo.ie/[Rufus].  Вона безкоштовна, і має відкритий вихідний код.

1. Відкрийте програму Rufus у теці, до якої ви її завантажили.
2. Вибір завантажувального диску за допомогою і виберіть зображення для ISO у випадаючому меню.
   Натисніть на піфтограму диска, і виберіть ваш Slint (файл .iso).
3. Щоб гарантувати сумісність флешки з UEFI, виберіть <<file_system, файлову систему>> FAT32.
4. Щоб створити флеш-диск з запитом "Натисніть будь-яку клавішу для завантаження з USB", виберіть опцію Створити розширену мітку та файли іконок.
5. Коли ви робите вибір варіантів, натисніть кнопку Почати роботу, підтвердіть, що ви хочете стерти спалах диску.
6. Почнеться копіювання файла .iso на флешку (процес може тривати кілька хвилин). Після того як Rufus виконає свою роботу, закрийте програму та вилучіть і вийміть флешку.

[[make_a_bootable_DVD_disc]]
=====  Make a Bootable DVD Disc

On a ++Linux++ system insert the DVD and type the following command:

----
growisofs -speed=2 -dvd-compat -Z /dev/sr0=slint64-14.2.1.4.iso
----

Обов'язково вкажіть повний шлях до ISO Slint у вашій файловій системі.

On ++Microsoft Windows 2000/XP/Vista/7++ you can write to a DVD using the application http://infrarecorder.org/[InfraRecorder].  Вона безкоштовна, і має відкритий вихідний код.

On ++Microsoft Windows 7/8/10++ you can use the http://windows.microsoft.com/en-US/windows7/Burn-a-CD-or-DVD-from-an-ISO-file[Windows Disk Image Burner] utility that is shipped with Microsoft Windows.

[[make_room_for_Slint]]
====  Вивільнення Простору для Slint

Рекомендуємо надати у розпорядження Slint комп'ютер або принаймні диск, оскільки це зробить процес встановлення простішим. Потім - пропустити цей крок, і перейти безпосередньо до запуску встановлювача.

Але ви також можете поділитися диском із вже встановленою операційною системою на кшталт Windows, Mac OS, *BSD, або іншим дистрибутивом Linux.

У такому разі, вам знадобиться вільний простір для Slint у кінці таблиці розділів цього диска (після останнього розділу). Для самої системи необхідно принаймні 20 гігабайтів, але вам також знадобиться деякий простір для файлів користувача, і для встановлення інших програм. Стиснення останнього розділу диску може бути зроблене після запуску інсталятора команд linux, якщо ви використовуєте живлення Linux. Також це може зробити встановлювач у Напівавтоматичному режимі, якщо виконуються такі умови:

* На диску використовується Таблиця Розділів GUID (GPT)
* Його останній розділ має <<file_system, файлову систему>> ext.
* На ньому можна вивільнити принаймні 28 гігабайтів.
* Комп'ютер завантажується в режимі EFI (не у Legacy).

Інакше вам доведеться створити вільний простір для Slint перед встановленням, використовуючи `gparted`, або із-під Windows (рекомандовано, якщо Windows встановлено). Однак за деяких умов, Slint може зробити це для вас, як зазначено у розділі
<<Automatic_installation, Встановлення у напівавтоматичному режимі>>.

===== Як вивільнити простір на томі Windows

Вказівки, наведені у
https://docs.microsoft.com/en-us/windows-server/storage/disk-management/shrink-a-basic-volume[цьому документі],
узагальнено нижче.

1. У Windows, відкрийте командний рядок, і введіть:
+
`diskpart`

2. У командному рядку diskpart, введіть:
+
`list volume`
+
Запам'ятайте номер простого тому, який ви бажаєте зменшити.

3. Оберіть том із файловою системою ntfs, який необхідно зменшити, ввівши:
+
`select volume <номер>`

4. Щоб дізнатися максимальний розмір, до якого том можна зменшити, введіть:
+
`shrink querymax`

5. Визначте <розмір> вільного простору в мегабайтах, який ви бажаєте створити. Він не повинен перевищувати максимальний розмір, знайдений попередньою командою. У разі потреби, можете залишити деякий простір на томі Windows, щоб зберігати в ньому більше даних.

6. Введіть таку команду:
+
`shrink desired=<розмір>`
+
Розмір необхідно вказати у мегабайтах. Наприклад для 30 гігабайтів, знаючи що 1 гігабайт дорівнює 1024 мегабайтам, введіть:
+
`shrink desired=30720`
+
Зберігайте достатньо невикористаного простору на Системному томі, щоб уможливити встановлення оновлень Windows.

Альтернативою може бути використання утиліти Керування Дисками: обравши том, який ви бажаєте зменшити, клацніть на ньому правою клавішею мишки, виберіть "стиснути", зачекайте, доки відобразиться максимальний розмір, до якого том можна зменшити, змініть це значення на зручне для вас, залишивши деякий простір для збереження даних, після чого натисніть кнопку стискання.

===== Як вивільнити простір у Linux

Ви можете скористатися http://gparted.org/index.php[gparted], або графічним засобом для керування розділами, що надається вашим дистрибутивом.

TIP: Якщо з останнього розділу на диску, що має таблицю розділів GPT і файлову систему ext4 можна вивільнити 28 гігабайтів, встановлювач може зменшити його для вас.

[[create_partitions_for_Slint]]
====  Створення розділів для Slint

Якщо ви оберете Напівавтоматичний режим встановлення і призначите пристрій для Slint, встановлювач розмітить його для вас. Коли завершите, ви все ще зможете, якщо бажаєте, налаштувати розмітку, за допомогою однієї з нижче наведених утиліт.

У разі використання Експертного режиму встановлення, ви також матимете змогу створити розділи для Slint або до, або під час встановлення.

Якщо ви не маєте досвіду використання Linux, тоді, ймовірно, вам буде простіше зробити це перед встановленням. Ми пропонуємо використовувати для цього http://gparted.org/index.php[gparted]. Gparted може зменшувати існуючі розділи звільнюючи простір, і створювати нові розділи у вивільненому просторі.  Якщо ви маєте системи яку не підтримує Gparted (Microsoft Windows), можете скористатися http://gparted.org/livecd.php[Gparted Live].
До складу встановлювача входять утиліти cfdisk, fdisk, gdisk, cgfdisk, а також parted. Ви можете скористатися ними для розмітки всього диска, чи створити у його вивільненому просторі розділи для Slint.

Для встановлення Slint необхідно:

* Розділ типу Linux розміром принаймні 20 гігабайтів, але краще - більше (рекомендовано принаймні 30 гігабайтів).
* Якщо завантаження відбуватиметься в режимі EFI - розділ типу "EFI System" (код ef00), розміром не менш ніж 100 мегабайтів. Навіть якщо завантаження відбуватиметься у режимі Legacy, мати його не завадить.
* У разі використання таблиці розділів GPT - розділ типу BIOS Boot (ef02) розміром 4 мегабайти, для завантаження в режимі Legacy. Навіть якщо завантаження відбуватиметься в режимі EFI, мати його не завадить.
* У разі потреби - розділ типу "swap". Це особливо рекомендується, якщо ви бажаєте використовувати режим сну, але маєте обсяг оперативної пам'яті менший ніж 8 гігабайтів. Однак після встановлення, ви також матимете змогу налаштувати файл резервної пам'яті.

Також ви можете призначити розділ для /home (але це необов'язково, я цього не роблю), та інші розділи для конкретних випадків використання.

[NOTE]
====
Самому Slint необхідно близько 20 гігабайтів, але рекомендуємо створювати кореневий розділ, розміром 50 гігабайтів. Можливо ви захочете встановити додаткові програми, чи потребуватимете більше місця для збереження ваших файлів.  Якщо бажаєте зберігати картинки, відео, музику, тощо, тоді чим більше місця - тим краще.
====

=== Встановлення Slint

<<Start_of_the_installation, Start of the installation>> +
<<Accessibility_of_the_installer, Доступність of the installer>> +
<<Usage_of_the_installer, Usage of the installer>> +
<<Automatic_installation, Automatic installation>> +
<<Manual_installation, Manual installation>> +
<<Slint_in_an_encrypted_drive, Slint in an encrypted drive>> +
<<first_steps_after_installation, First steps after installation>>

[[Start_of_the_installation]]
==== Початок встановлення

У разі потреби, налаштуйте комп'ютер для завантаження з DVD або USB-флешки, які ви підготували.

Вставте встановлювальний носій (DVD чи USB-флешку), і перезавантажте комп'ютер. Звуковий сигнал слугуватиме орієнтиром для незрячих користувачів, оскільки свідчитиме про появу завантажувального меню.

Запустіть встановлювач, натиснувши Enter.

Спочатку встановлювач перевірить ваші звукові карти.

Це може допомогти встановити одну для роботи за замовчуванням, а також використовувати мовлення під час встановлення, яке необхідне деяким незрячим користувачам.

Якщо встановлювач знайде більше однієї звукової карти, він казатиме для кожної: +
натисніть Enter для вибору цієї звукової карти <ідентифікатор звукової карти> +
Почувши це - натисніть Enter, тим самим підтверджуючи що запропонована звукова карта працює. Це налаштування буде збережено для нової системи у файлі /etc/asound.conf.

На наступному кроці, відповідаючи на питання, ви підтвердите (введенням s) чи заперечите (просто натиснувши Enter), що вам необхідне мовлення під час встановлення. Брайль завжди доступний під час встановлення.

Потім ви обиратимете, підтверджуватимете чи змінюватимете мову, яка використовуватиметься під час встановлення. У подальшому всі екрани відображатимуться обраною мовою, якщо переклад на цю мову завершено.

Якщо вам потрібно додати додаткові параметри ядра для командного рядка завантаження, перед натисненням Enter зробіть наступне:
[NOTE]
====
Майте на увазі що під час введення, використовуватиметься розкладка клавіатури US. +
Ctrl+x означатиме: "Натисніть і утримуйте клавішу Ctrl (Контрол) так, якби це була клавіша Shift, а потім натисніть клавішу X".
====
----
Натисніть клавішу e.
Тричі натисніть стрілку вниз.
Натисніть клавішу End.
Натисніть пробіл.
Введіть параметри ядра (приклади наведено нижче).
Натисніть Ctrl+X для завантаження (Не натискайте Enter!).
Натисніть Enter для завантаження.
----

Наприклад, щоб налаштувати драйвер speakup для вашого апаратного синтезатора, вкажіть параметр ядра наступним чином:
----
speakup.synth=apollo
----
Також можна включити до завантажувального командного рядка налаштування вашого дисплея Брайля:
-----
brltty=<код драйвера>,<пристрій>,<таблиця Брайля>
-----
Наприклад для встановлення пристрою Papenmeier, підключеного по USB, і Української таблиці Брайля, введіть:
-----
brltty=pm,usb:,uk
-----
NOTE: Пристрій брайля, що підключений по USB, завжди повинен розпізнаватися. Але таблиця брайля може бути непідходящою для вас, якщо ви спочатку не вкажете її.

У будь-якому випадку, завантаження почнеться лише після того, як ви натиснете [Enter].

Мовлення й Брайль будуть доступні на початку встановлення.

[[Usage_of_the_installer]]
==== Використання встановлювача

Якщо ви знайомі з командним рядком, можете пропустити цей розділ.

Нижче наведено головне встановлювальне меню:
....
Вас вітає встановлювач Slint! (версія 14.2.1)

Доступні команди (вводьте без лапок):

"doc" - отримати інформацію про можливості встановлювача, а також про його використання.
"auto" - розпочати встановлення у напівавтоматичному режимі.
"setup" - розпочати становлення у експертному режимі.

Рекомендуємо ввести "doc", щоб підготуватися до використання експертного режиму встановлення, або якщо ви бажаєте зашифрувати диск, на якому буде встановлений Slint, Або ж якщо вам потрібно зменшити розмір розділу, щоб вивільнити простір для Slint, поруч з іншою системою.
Після прочитання, ви знову потрапите до меню.
....

Як тільки відобразиться це меню, ви можете розпочати процес встановлення.

Ви читаєте екрани, та вводите команди у <<virtual_terminal, віртуальному терміналі>>. Встановлювач
включає кілька віртуальних терміналів зі спільною фізичною клавіатурою та
екраном, які можна використовувати паралельно.

Встановлювач запускається у віртуальному терміналі 1, що має назву *tty1*, але ви можете перемкнутися на інший. Наприклад, ви можете перемкнутися на *tty2*, натиснувши
*Alt-F2* а потім Enter щоб активувати його, а пізніше - повернутися назад до *tty1*, натиснувши
*Alt-F1*, не втрачаючи при цьому інформацію, що відображається у обох терміналах.
*Alt-F1* означає: "натисніть і утримуйте клавішу *Alt*, а потім - натисніть клавішу *F1*".

Це може бути корисним, якщо необхідно подовжити читання документації під час встановлення.
Наприклад, ви можете перемкнутися на *tty2* щоб розпочати встановлення, перемкнутися на *tty1* щоб
продовжити читання документації, потім знову перемкнутися на *tty1* щоб виконати
наступний утап встановлення.

Також цим можна скористатися для консултування зі словником, під час читання інших документів.

Четвертий віртуальний термінал, або *tty4*, відображає повідомлення, які надають інформацію,
корисну для налагодження. Іншим чином він не використовується.

Встановлювач має кілька режимів взаємодії з вами користувачем:

. За запитом ви вводите команди, та читаєте результат.
. Встановлювач ставить питання і ви вводите відповіді, підтверджуючи їх натисканням Enter.
. Встановлювач відображає меню вибору чи опцій: щоб вибрати одну з них, використовуйте клавіші зі стрілками вгору чи вниз, потім підтвердьте ваш вибір натиснувши Enter або скасуйте натиснувши Escape.
. Встановлювач відображає інформацію на сторінках. Потім - використовуйте клавіші зі стрілками щоб прочитати наступний або попередній рядок, натисніть пробіл для відображення наступної сторінки, Q - щоб зупинити читання документа.

[[Automatic_installation]]
==== Встановлення у Напівавтоматичному режимі

У напівавтоматичному режимі, встановлювач надає параметри за замовчуванням, включаючи графічне середовище (Mate). Після запуску нової системи,
ви зможете переглянути і змінити всі параметри.

Етапи встановлення наведені нижче.

. Для встановлення Slint необхідно неменше ніж 28 гігабайтів дискового простору. Спочатку встановлювач перевірить диски, отримуючи інформацію про їх розмір, і про вільний простір на них. Залежно від результату, це дозволить вам встановити Slint на призначений для нього диск, або у вільний простір на диску.
.. Встановлення на призначений диск.
+
У цьому режимі встановлення, увесь попередній вміст диска буде втрачено. Якщо він містить файли, які ви бажаєте залишити, тоді спочатку збережіть їх у іншому місці!
+
Якщо носій є знімним і підключається через USB, встановлювач може створити переносний Slint, що дозволить вам використовувати його на будь-якому комп'ютері, здатному завантажуватися ія зовнішнього носія USB.
+
За бажанням диск можна зашифрувати, щоб захистити ваші дані від крадіжки, у разі втрати або викрадення диска чи комп'ютера. Оскільки існують важливі застереження, спочатку уважно прочитайте документ Шифрування.

.. Встановлення на диск, спільний із іншою системою. Ви можете встановити Slint, зберігаючи іншу систему, використовуючи для цього лише один диск.
+
Це можливо, якщо диск має вільний, або доступний у його кінці для вивільнення простір, неменший ніж 28 гігабайтів, має таблицю розділів GPT (GUID partition table), і встановлювач завантажено в режимі EFI: за цієї конфігурації завантажуватимуться обидві системи, не заважаючи одна одній.

. Вкажіть розмір основного розділа Slint, і за бажанням - розмір додаткового розділа, а також, у разі потреби, залишіть деякий вільний простір на диску для подальшого використання.
+
Основний розділ, як правило, має файлову систему ext4. Однак якщо встановлення відбуватиметься на карту SD або на пристрій eMMC, вони матимуть файлову систему f2fs.
+
Перед початком встановлення, у вас буде можливість переглянути і змінити вказані вами параметри.
+
Після підтвердження будуть встановлені базові пакунки, що займе кілька секунд.

. Обравши шифрування диска ви вводитимете парольну фразу, яка використовуватиметься для розблокування диска при кожному завантаженні.
. Потім введіть пароль для користувача "root". Це адміністратор системи, який має всі привілеї. Також створіть обліковий запис звичайного користувача, вкажіть, чи потрібен вам доступний Брайлівський вивід, і бажаний режим входу у Slint: текстовий або графічний.
+
[NOTE]
====
Якщо мовою, яка використовується під час встановлення, є Англійська (США), оберіть мову для встановлюваної системи. Інакше встановлювач застосує ту, яка використовується під час встановлення.
====
. Встановлювач спробує встановити з'єднання з інтернетом, щоб запропонувати часовий пояс відповідно до вашого географічного місцярозташування, і пізніше, в разі потреби, встановити віддалені пакунки. Налаштуйте чи підтвердьте запропоноване.
. Потім, у системному розділі, встановлювач створєє файл резервної пам'яті, розмір якого можна легко змінити після встановлення. За замовчуванням, під час кожного завантаження Slint, у zram встановлюватиметься додатковий простір резервної пам'яті у 1.8 рази більший за обсяг фізичної оперативної пам'яті.
. Пакунки встановлюються на диск (набір пакунків KDE лише за запитом). Встановлювач спробує налаштувати з'єднання з інтернетом, щоб завантажити і встановити найновішу версію кожного пакунку, а також пакунки, що були надані після випуску образа ISO. Таким чином, після встановлення вам не доведеться завантажувати і встановлювати нові чи оновлені пакунки.
+
Встановлення всіх пакунків триває від 10 до 40 хвилин, в залежності від обладнання.

. Потім налаштовується система, і встановлюється менеджер завантаження GRUB. Якщо Slint встановлено на призначений для нього диск, він зможе завантажуватися у обох режимах: Legacy та EFI. В іншому випадку, він зможе завантажуватися лише у режимі EFI. У будь-якому разі, завантажувальне меню матиме додатковий завантажувальний запис "відновлення", для виявлення і завантаження встановленої ОС.
. Вам буде запропоновано створити відновлювальний завантажувальний диск на USB-флешці. Можна скористатися ним для завантаження Slint, якщо він невдало завантажується із власного завантажувального меню.

Нарешті, вийміть встановлювальний носій і перезавантажтеся, щоб запустити вашу нову систему Slint.
Перед перезавантаженням, ви можете відобразити попередній перегляд завантажувального меню.

[[Manual_installation]]
==== Встановлення у Експертному режимі

Встановлення у Експертному режимі складається з двох основних етапів.

. Підготовка диска(ів) для встановлення. Він включає: планування розмітки, створення розділів, і в разі потреби - їх форматування, тобто створення на них файлових систем. За бажанням, встановлючач може відформатувати розділи Linux.
. Введіть *setup*, щоб виконати подальшу підготовку, встановлення й налаштування.

===== Підготовка диска(ів) для встановлення.

Якщо можливо, встановіть Slint на призначений лише для нього диск.

Також ви можете встановити його на диск, спільний із іншою системою, але тоді, бажано
завантажуватися в режимі EFI, оскільки в цьому випадку кожна система, маючи власний завантажувач ОС,
не залежатиме від інших, і від їхніх оновлень. Потім необхідно звільнити деякий простір
на диску, для встановлення Slint. Для цього можна скористатися командою "freespece" із встановлювача
Slint, якщо останній розділ на диску має файлову систему ex2, ext3 або
ext4. Інакше - зробіть це із вже встановленої системи.

Якщо можливо, дозвольте комп'ютеру завантажуватися в режимі EFI, і створіть на цільовому диску таблицю розділів GPT (GUID
partition table) для більшої гнучкості.

Для завантаження, як у EFI так і в Legacy, встановлювачем використовується програма GRUB.

Для встановлення Slint на призначений лише для нього диск, необхідно:

* При завантаженні у режимі Legacy з GPT - розділ типу BIOS Boot, який, у даному контексті, необхідний для
GRUB. Розмір - 1 мегабайт. Він
зарезервований
для GRUB, і не потребує форматування.
* При завантаженні в режимі EFI - розділ типу ESP (EFI System Partition) розміром
100 мегабайтів, для зберігання EFI завантажувача ОС. Цей розділ можна створити як у таблиці розділів GPT, так і в
таблиці розділів DOS.
* Для системи - розділ типу Linux, розміром неменше ніж 28 гігабайтів.

У разі використання GPT,
для більшої гнучкості рекомендуємо створити обидва: розділ BIOS Boot, та ESP. Це дозволить завантажувати Slint як у режимі EFI, так і в режимі Legacy.

Інші розділи створювати необов'язково. Якщо ви бажаєте мати розділ swap, він повинен
бути типу Linux swap. Натомість, або додатково, ви можете налаштувати файл резервної пам'яті. 'setup' запропонує встановити його після створення файлової системи
кореневого розділу.

У інсталятора є декілька програм для розділів: cfdisk, fdisk, sfdisk,
cgdisk, gdisk, gdisk, sgdisk, запчастини. Програми з "g" в їх імені
можуть обробляти тільки gpt, дозволені для роботи таблицями розділів DOS, а також GPT. fdisk,
cfdisk і sfdisk можуть обробляти таблиці розділів DOS. In addition, wipefs
(to erase previous partition table and file system signatures) and partprobe
(to inform the kernel of a partition table changes) are available.
Додаток lsblk відображає інформацію про блокування пристроїв і секцій.

Ви можете відформатувати розділи себе, або дозволити інсталятору зробити це для вас. Тут
'format': створити файлову систему для керування файлами у розділі. Ведмідь
пам'ятати, що ESP повинен мати систему жирової файлів, розділ біоського завантаження взагалі без файлу
системи. Для ОС Linux розділів, встановлювач Slint може обробляти ці файли
системних типів: btrfs, ext2, ext4, f2fs, jfs, reiserfs, xfs.

The installer can set up mount points for partitions shared with or used by
Windows to allow access them from Slint. У них має бути файлова система типу
vfat, msdos чи ntfs, встановлена Windows або створено перед запуском налаштувань.

===== Керування діями установки.

Програма налаштування відображає меню з цими матеріалами або кроками:
....
KEYMAP для переформування вашої клавіатури (опціонально)
ADDSWAP для перезапису розділу(ів) свопу камер (необов'язково)
TARGET для налаштування цільових розділів
SOURCE для вибору джерела медіа, що містить пакети програмного забезпечення
ВСТАНОВИТИ для встановлення програмних пакетів
CONFIGURE для налаштування вашої системи Slint.
....

Ці записи прокоментуються нижче. TARGET, SOURCE, INSTALL і CONFIGURE
кроки є обов'язковими і повинні виконуватися в цьому порядку.

* KEYMAP можна використовувати для зміни карти клавіатури для початку.
* ADDSWAP може використовуватись для налаштування розділу(ів). Замість цього ви можете встановити файл підкачки і налаштувати простір для зміни темпу Zram.
* У TARGET кроці інсталятору спочатку запитав, який розділ Linux буде містити кореневий (/) каталог, потім запитує, якщо ви хочете встановити файлову систему в ньому. Ви SHOULD погоджуєтесь, якщо ще не зроблено, ПОЧАТОК ЗНАЧЕННЯ БУДЬТЕ ПОЧАТИСЬ на кроці INSTALL через відсутність місця для встановлення пакетів. Потім виберіть файлову систему серед зазначених пропозицій.
+
Інсталятор тоді перелічує інші розділи Linux, і встановлює для кожного з них, якщо хочете використати
в Slint точку монтування і файловій системі.
* В кроці SOURCE виберіть медіа, що містить пакети програмного забезпечення, які будуть встановлені. Це, швидше за все, буде той, що містить інсталятор.
* У INSTALL кроку всіх пакетів, включених до установки медіа, встановлюються крім пакунків KDE, якщо вам не дозволено'.
* У кроці інсталятора налаштовує нову систему на Ваш смак. Це включає в себе наступні налаштування або параметри:
+
** Зробіть кнопку врятування USB.
** Встановити та налаштувати менеджер завантаження GRUB і пов'язане з ним завантаження ОС.
** Виберіть погоду або не використовуйте мишку на консолі.
** Налаштування мережі.
** Вирішіть, яку службу потрібно запустити під час запуску.
** Оберіть, якщо апаратний годинник використовує UTC або локальний час, встановіть часовий пояс.
** Виберіть менеджер входу: режим консолі або графічний.
** Виберіть стандартну графічну сесію.
** Встановіть мову за замовчуванням та регіональний варіант в установленій системі. Деякі пакети вказані з обраною мовою будуть встановлені.

Все готово, вилучіть медіа файли інсталяції та перезавантажте, щоб запустити Slint.

[[Slint_in_an_encrypted_drive]]
==== Сліпий в зашифрованому диску.

У режимі автоматичного встановлення пропонує шифрувати диск, де він встановлює
Слінт, якщо ви присвячені Slint. Якщо ви згодні, при кожному завантаженні завантажувача GRUB попросить у вас парольну фразу
, яку ви набрали під час установки, щоб розблокувати диск, до
, що відображається меню завантаження. Be aware that unlocking the drive will take a few
seconds (about ten seconds).

Маючи зашифрований диск, запобігає прихованню даних, що міститься у випадку
втрати або крадіжки машини, або на змінному диску. Але це виграло't захистить вас, якщо комп'ютер перестане працювати і залишатиметься без нагляду, тільки
якщо машина була повністю вимкнена!

Під час встановлення системний розділ Slint буде зашифровано, а також
додаткову секцію, яку ви можете попросити.

Система Slint (або root) має бути названа: /dev/mapper/cryproot одноразово
відкрита, якщо вона була зашифрована.

Це відображається цією командою:

----
Назва lsblk -lpo, fstype,mountpoint | сірка / $
----

Що дає таке:
----
/dev/mapper/cryptroot ext4 /
----

Замість цієї команди:

----
Назва lsblk -lpo, fstype,mountpoint | зелений/dev/sda3
----

Подарок:

----
/dev/sda3             cryptoLUKS
----

/dev/sda3 тепер є "raw" секцією, яка включає в себе так званий "LUKS заголовок"
що вам ніколи не буде потрібно, і ніколи не буде потрібен напряму.  Програмі
потрібно для шифрування чи розшифрування розділу/dev/mapper/cryptroot, які
насправді хостуть ваші дані (у цьому прикладі системи Slint).

[WARNING]
====
Якщо ви забудете парольну фразу на диску буде невиправно втрачено!
Так запишіть або запишіть цей парольну фразу і покладіть запис на безпечне місце
як тільки це зроблено.

Машини помирають. Якщо це відбувається, і воно зашифровано ваші дані будуть втрачені.
Отже, регулярне резервне копіювання важливих даних не є обов'язковими.

Також створити резервну копію заголовка lus, що ви зможете відновити з будь-якої причини
розділ слабо буде пошкоджено з будь-якої причини. The command could be in our
example:
----
luksHeaderBackup /dev/sda3 --header-backup-file <file>
----
де <file> - це назва файлу резервної копії, який ви зберігатимете в надійному місці.

Після цього вам доведеться відновити резервну копію, тип:
----
luksHeaderRestore /dev/sda3 --header-backup-file <file>
----

Дон't змінити розмір секції зашифрованого диску, як після того, як він буде
остаточно заблоковано і всі дані, які він містить буде втрачений! Якщо вам дійсно потрібно більше місця, то вам потрібно буде зарезервувати всі файли, які ви
хочете зберегти, потім встановіть заново і відновіть резервні копії.

Оберіть надійну фразу, щоб на злодій знадобилося надто багато часу для
виявилося, що вона варта уваги.

Ніколи не загадка з так званим "LUKS-заголовком" розміщений на необробленому місці
(третя, як це. . /dev/sda3 для необробленого секції на верху системного розділу Slint
).  Практика: don't створює файлову систему в цьому розділі,
нехай't робить його частиною масиву RAID, і загалом дон't записати: всі дані
будуть безповоротно втрачені!
====

Для уникнення слабких секретних фраз інсталятора потрібно включити парольну фразу:

. Не менше 8 символів.
. Тільки не враховані в нижньому регістрі та великі літери, цифри від 0 до 9, пробіл та наступні знаки пунктуації:
+
----
 ' ! " # $ %  & ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
----
+
Це гарантує, що навіть нова клавіатура буде мати всі символи
щоб ввести парольну фразу.

. Принаймні один цифр, одна буква нижнього регістру, одна буква та один символ пунктуації.

GRUB передбачає, що клавіатура "нас" використовується при наборі секретної фрази.
З цієї причини, якщо під час встановлення ви використовуєте іншу карту клавіатури, перед
запитувати парольну фразу встановлювача встановлюватиме карту клавіатури на "нас", і
після запису він відновив раніше використаний. У цьому випадку
інсталятор також пишеться про кожен введений символ секретної фрази, як це може
відрізнятися від того, що написано на ключі.


Додаток криптоап використовується для шифрування диску. Щоб знати більше типу
після встановлення: +
-----
man cryptsetup
-----
і дізнатися ще більше: https://gitlab.com/cryptsetup/cryptsetup/-/wikis/FrequentlyAskedQuestions[це ЧАП].

[[first_steps_after_installation]]
==== Перші кроки після встановлення

Ось перші завдання, які потрібно виконати після встановлення

У цьому документі весь текст після # символів є коментарями запропонованих
команд, а не введені.

===== Початкове оновлення програмного забезпечення

Після установки система повинна бути оновлена, щоб отримати останню версію
у наданих версію кожного програмного забезпечення, як і нове програмне забезпечення, надане з часу
релізу ISO. Це особливо необхідно, якщо під час встановлення підключення до мережі
відсутнє як тільки були встановлені пакунки в засобах розповсюдження
, вони можуть бути застарілими.

Більшість команд, набраних нижче запитом адміністративне право, пов'язане з
особливим обліковим записом з назвою 'root', для яких ви записали пароль
під час встановлення.

Щоб виконати команду як 'root', перший тип
----
Су -
----
then issue the password for root and press Enter before type the command.

Це замінює «sudo», що використовується в інших розподілах.

When you are done issuing commands as 'root', press Ctrl+d or type 'exit' to get
back your "regular user" status.

Щоб оновити, введіть корінь в консолі або графічний термінал :
----
slapt-get --add-keys # retrieve the keys to authenticate the packages
slapt-get -u # update the list of packages in the mirrors
slapt-get --install-set slint # get the new packages
slapt-get --upgrade # Get the new versions of installed packages
dotnew # lists the changes in configuration files
----
При використанні dotnew, погодиться замінити всі старі файли конфігурації на нові.
Це безпечно, як ви зробили't зробить будь-яке налаштування поки що.

Крім того, ви можете використовувати ці графічні фронти: gslapt замість
slapt-get, та dotnew-gtk замість dotnew.

Щоб дізнатися більше про отримання дробів, наберіть:
----
man slapt-get
----
або як root-права:
----
slapt-get --help
----
і прочитати /usr/doc/slapt-get*/README.slaptgetrc.Slint

===== Конфігурація

Ось комунальні послуги, які ви можете використовувати для налаштування вашої системи Slint після
встановлення. They are presented in further details in chapter <<Manage_your_system, Керування системою>>.

Якщо ж ці комунальні підприємства не будуть вважатися кореневими. Щоб стати суперником
, тобто отримати статус 'admin' і права доступу типу "su -" корінь'с гасло.
Щоб повернути регулярний статус користувача, слід пресувати Ctrl+d або тип за вихід.

Більшість утилітів мають командний рядок та графічну версію. На командному рядку
знаходиться перша версія. Якщо в іншому випадку всі команди мають бути
типів в якості root.

*Загальні налаштування*

* Для управління користувачами: налаштування користувачів або налаштування gtkusers
* Щоб змінити мову і регіон: localesetup або gtklocalesetup
* Щоб змінити налаштування клавіатури та метод вводу: клавіатурні налаштування або gtkkeyboardboardsettings
* Щоб налаштувати дату, час або часовий пояс: налаштування годинник і gtklocklockup.
* Щоб вибрати, які послуги запускаються при завантаженні: servicesetup і gtkservicesetup.
* Щоб (пере)налаштувати мережу: налаштування мережі.
* Щоб розпочати роботу в текстовому або графічному режимі, а в попередньому випадку менеджер логів: вибір
* Щоб вибрати робочий стіл або графічну сесію: сесіон-вибір (як звичайний користувач)
* Якщо KDE встановлений для відображення або приховування своїх додатків на іншому комп'ютері'меню показати: show-kde-apps чи hide-kde-cde-apps.

*Налаштування спеціальних можливостей*

Щоб вибрати і увімкнути інструмент читання з консольного екрану або вимкнути всі з них як root:
----
динамік-з
----

From Slint version 14.2.1 onward the first regular user created during installation will have speech and braille already enabled in the installed system, if speech was used and braille requested during installation. Інші користувачі повинні відмітити або зробити додаткові налаштування, як зазначено нижче.

Для включення braille:

. Робіть виконуваний файл /etc/rc.brltty вводити як root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Зробіть себе учасником групи Брайлля, вводячи як кореневий:
+
----
ім'я користувача - G Брайль -G
----
+
У команді вище, замініть ім'я користувача на ім'я користувача.
. Потім відредагуйте як кореневий файл /etc/brltty.conf для того, щоб включити ваші налаштування.

Щоб увімкнути звук на системному рівні як права root:
----
вибір логіну
----
та виберіть один з режимів логіна, що сповіщає: текст, світло або gdm

Для увімкнення мови в графічних середовищах як звичайний тип користувача як цей користувач:
----
орка
----
Далі програма читання екрана Orca почне говорити наступного разу, коли ви запустите графічне
середовище

Щоб вимкнути звук в графічних середовищах замість цього:
----
орка офф
----

==  Використання Slint

У цьому розділі присутні відповідні розділи ви можете взаємодіяти з вашою Slint системою за її допомогою
, щоб виконати те, що вам потрібно.

=== Що таке система Slint?

Slint є набором програм, який приблизно належить до цих категорій:

* The operating system, made of the Linux <<kernel, kernel>> and <<utilities, utilities>>. It acts as an interface between the user, the applications and the hardware.
* <<Applications, додатки>> , які виконують завдання, які хочуть виконати користувачі.

Сліп може бути використаний в двох режимах, відмінний від вигляду екрану
і способу взаємодії з системою:

* У текстовому режимі ви вводите команди, які інтерпретуються <<shell>>. Ці команди можуть запустити корисність або застосунок. Текстовий режим також називається <<console, режим консолі>>. In this mode the screen only displays the commands and their output in a (usually black) background.
* У графічному режимі графічні елементи, такі як вікна, панелі чи іконки, відображаються на екрані, загалом пов'язані з додатками чи використаннями. Користувач взаємодіє з цими елементами за допомогою миші або клавіатури.

Команди можна також надрукувати в графічному режимі всередині вікна, пов’язаного з
 <<terminal, терміналом>> , в якому запускається оболонка.

=== Як запускається Slint

Після установки програмне забезпечення для встановлення ISO або завантаження
з віддалених сховищ встановлено на <<drive, диск>>.

Коли ви завантажуєте Slint, <<firmware, прошивка>> перша перевіряє апаратне забезпечення і потім
шукає програму, яка називається завантажувач ОС (часто має назву завантажувача з завантаженням пам'яті), яку він
починається.

В техніці може бути кілька завантажувачів ОС. У цьому випадку
прошивка дозволяє користувачеві вибрати, який з них починатися в меню.

In Slint the
software that makes and install a boot loader is GRUB.Actually the boot loader
built by GRUB is also a boot manager, as it allows to choose which OS to start if
several are installed.

The OS loader built by GRUB can be installed in a boot
sector (in case of Legacy booting) or in an EFI System Partition or ESP (in
case of EFI booting).

The aim of the Slint loader is to start the Slint system. Щоб це зробити спершу завантажує в
оперативну пам'ять <<kernel, ядро>>, а потім <<initrd, всередину>>, що в свою чергу,
ініціалізує систему Слінт.

В останньому кроці цієї ініціалізації користувач запрошений до "увійти", у
інші слова, щоб підключити себе до системи і взяти руку на неї. Для
перевірити ім'я користувача перший тип'з ім'ям користувача, а потім пароль, якому
валідності перевіряється. Зважаючи на інші дистрибутиви Лінукс, такі
дозволяють цьому користувачеві отримувати доступ до одного'файлів , але не з інших користувачів.

Під час встановлення ви обрали запуск Slint в текстовому або графічному режимі.

* Якщо ви обрали C для <<console, консолі>> після ініціалізації системи, якого ввели користувач (або увійде) ваш пароль, кожен вхідний запис підтверджено натискаючи клавішу Enter і ви можете набирати команди.
* Якщо ви обрали G (графічний) ви вводите таку ж інформацію в <<display_manager, Диспетчері сторінок сторінок>> або менеджер входів, які тоді запускаються на <<graphical_environment, графічне середовище>>.

Після встановлення, якщо ви зможете змінити режим введення як кореневий `вибрати`,
в режимі консолі, а також в графічному режимі в <<terminal, терміналі>>). Ця команда
дозволяє Вам вибирати `текст` (синонім режиму консолі), або, для
графічного режиму, серед декількох менеджерів дисплеїв. Вибір буде ефективним
при наступному завантаженні комп'ютера.

We will now present the graphical environments, then how to use a shell.

=== Графічні середовища

<<the_windows, The windows>> +
<<the_work_spaces, The work spaces>> +
<<the_desktop, The desktop>> +
<<the_top_panel, The top panel>> +
<<the_bottom_panel, The bottom panel>> +
<<the_slint_control_center, The Slint Control Center>> +
<<graphical_terminals, Graphical terminals>> +
<<key_bindings, Key bindings>>

Повнофункціональне графічне середовище включає в себе декілька компонентів, з якого менеджер вікна, який розміщує вікна на екрані, пов&#039;язаних з додатками, переміщеннями, змінювати розмір і закривати ці вікна.

Slint дозволяє використовувати декілька графічних середовищ: BlackBox, Fluxbox, KDE, LXDE та MATE, TWM, XFCE і WindowMaker. Це питання вподобання, яке ви обрали.

KDE, LXDE MATE і XFCE є повноцінними функціями комп'ютера, в основному
Керування вікнами, але включені до панелі з меню програми. All allow you to
access your documents and applications, generally opened in a window, include a panel and a menu.

Графічне середовище за замовчуванням може бути змінене за замовчуванням набирання звичайного користувача `session-chooser`. Графічний режим ви також можете вибрати при вході в систему.

Зараз ми описати компоненти матового десктопу, який є типовим і є також найбільш доступним з мовлення та брайлі. Інші повноцінні настільні комп'ютери мають схожі функції.

Використовуючи мишу, ви можете відкрити можливості кожного компонента, що виконує чи симулює правою кнопкою миші або лівою кнопкою миші. Переміщуйте чи видаляйте більшість компонентів, змінюйте їх та додавайте нові компоненти таким же чином.

Ці компоненти можуть досягнути переміщення миші, а також за допомогою ярликів клавіатури. Ми вказуємо розташовані всередині дужок ярлики клавіатури, що дозволяють її досягти, іншими словами, зосередити увагу на кожному елементі. Ми також підсумовуємо <<key_bindings, ключові прив'язки>> для стільниці Mate (використовується менеджер вікон Marco за замовчуванням) і що використовується для менеджера вікон Compiz.

[TIP]
====
Можна відкрити більшість функцій програм та інших компонентів Slint з правом, середнім або лівою кнопкою миші.  Наприклад, клацаючи по панелі заголовок, панель зліва і справа між вікнами, значок в панелі або на порожньому місці екрану.
====
[[the_windows]]
==== Вікна

A window is a rectangular area associated with an application. Windows можна переміщувати, змінювати розміри копії, відновити, відновити, закрити (припинити роботу додатків) за допомогою ярликів миші або клавіатури.

[[the_work_spaces]]
==== Робочий простір

To allow having a lot of windows opened in an orderly fashion, the graphical environment provide several work spaces and allow to switch between them. Кожен робочий простір буде відображати однаковий робочий стіл і панелей, але вікна можуть бути розміщені в певному робочому просторі або у всіх з них. Цей параметр доступний з правою кнопкою миші на верхньому краю вікна. Можна переключитися на іншу робочу область можна виконати натискання на її місце в нижній панелі екрану, у перекладі робочого простору, як показано нижче.

[[the_desktop]]
==== Робочий стіл

На екрані він охоплює весь екран, на якому можна покласти інші компоненти, у разі "Маті" і як доставлені у Slint зверху, і нижні панелі, і чотири піктограми, які зверху дає змогу відкрити у вікнах:

* кореневий каталог у файловому менеджері
* ваш домашній каталог в файловому менеджері
* центр керування Slint
* смітник можуть, де розміщуються файли, які ви маєте намір видалити, але зробив ще'.

Windows програма, яку ви починаєте, а також вставляєте на робочий стіл.

Mate includes two panels, which presents themselves as slim rectangular horizontal areas, one at the top and one at the bottom of the screen.

Натиснувши Ctrl + Alt+Tab дозволити циклу між робочим столом, верхньою та нижньою панелями

Натиснення клавіші Alt+Tab дозволяє циклічно між вікнами на робочому столі.

[[the_top_panel]]
==== Верхня панель

Вона представляє зліва направо,

* Три меню:
** Меню додатків, для якого можна відкрити клавішу Alt+F1. А звідти ви можете відкрити інші меню за допомогою кнопки зі стрілкою. Можна використовувати клавіші зі стрілками, щоб відкрити меню іншого.
** A Places menu.
** Системне меню, яке надає доступ до налаштування підменю, Центру управління постаті та кнопок для отримання допомоги по робочому столу, заблокувати екран, закрити сеанс і закрити комп'ютер.
* Додатки запускають для тимчасових термінів, файловий менеджер caja, email клієнт thunderbird, firefox, текстовий редактор Geany.
* Сповіщення, яке може збирати яблука такі як менеджер Bluetooth, звуковий мікшер, мережевий менеджер і "оновлення" notifier.
* Годинник і календар.
* Блокування екрана.
* Закриття діалогового вікна сесії.
* Діалог завершення роботи.

[TIP]
====
* Щоб налаштувати панель своїм вподобанням: клацніть правою кнопкою миші на пустій області на панелі.
* Якщо ви хочете перемістити предмет в панелі: натисніть кнопку клацнути по елемента, перетягніть мишу, за нею слідують за мишкою, поки не буде випущено середню кнопку.
* Для контекстуальної довідки натисніть F1
====

[[the_bottom_panel]]
==== Нижня панель

Вона присутня зліва направо:

* Список вікон, які можуть бути налаштовані правою кнопкою миші на рядку трьох вертикальних точок на початку і вибором налаштувань. Це також дозволяє запустити системний монітор у вікні.
* *показати кнопку на робочому столі*. Ліворуч ви згорнете всі вікна, натиснувши ще раз, відновить вікна в попередньому стані.
* Перемикач робочого простору або пасиджу. Він дозволяє перемикатися з робочого простору на іншу і переміщувати вікна з робочої області на іншу за допомогою перетягування краплі.

Віконні менеджери налаштовані в Slint, щоб бути придатними для без змін. Однак ви не зможете переналаштувати їх на свої вподобання. Цей спосіб залежить від менеджера вікон до вікон. Для отримання додаткової інформації: http://docs.slackware.com/en:user_settings[Налаштування].

[[the_slint_control_center]]
====  Центр керування Slint

Закінчимо цю інструкцію до Slint's приводить Slint контрольний центр. You can display it from the application menu on the top panel or clicking on its icon in the desktop or typing qcontrolcenter in a "Run..." dialog raised with Alt+F2

Метою панелі управління є зібрати програми, що корисні для системної адміністрації, Документація та налаштування в узгодженій моді у всіх менеджерах вікон.  Якщо натиснути на категорію в лівому меню, ви можете відобразити відповідні додатки на правій панелі.  Ми презентуємо їх у форматі таблиці.  Це дасть нам можливість представити інструменти адміністрування з графічним інтерфейсом користувача.

Більшість адміністративних інструментів слід використовувати з адміністративними привілеями.  Вам буде запропоновано ввести пароль облікового запису root для запуску інструменту.

[options="autowidth"]
|====
<|**Категорія** <|**Інструмент** <|**Призначення і коментарі**
<|Додатки <|Dotnew <|Цей інструмент дозволяє вам керувати новим (названо _щось. колода_ отже назва інструменту) та старі файли конфігурації після оновлення деяких пакетів.  Це'хороша звичка працювати після оновлення.  Він скаже вам, чи є щось піклуватися про себе, а потім представити вам вибір дій.
<|Додатки <|Gslapt Package Manager <|Gslapt is a graphical front-end to slapt-get.  It is a handy tool to perform <<software_management, software management in Slint>>.  It allows you to search for, install, remove, upgrade, and configure software packages.
<|Додатки <|Sourcery SlackBuild Manager <|Sourcery is a graphical front-end to slapt-src.  It allows you to search for SlackBuilds scripts that it can then use to automate the build process and installation of software packages.  It can also remove and reinstall packages on your system.
<|Додатки <|Application Finder <|Find and launch the applications installed on your system.  The search field is very handy to find applications in comparison to manually searching the application menu.
<|Hardware <|Printer Setup <|Used to set up any connected printer.  It is a front-end to the CUPS print server, which is running by default in Slint.
<|Обладнання <|Cups Print Control <|This application allows you to configure the CUPS service, manage printers, and control print jobs through a web browser.
<|Обладнання <|Keyboard <|This tools allows you to set the keyboard type, key map, and enable the SCIM service.  SCIM helps by allowing you to type characters for which there is no key on the keyboard (like in many Asian languages).
<|Information <|SlackDocs Website <|The documents in this wiki are primarily intended for a Slackware user, but many of them are useful for a Slint user.  **Caution:**  Some of the listed tools, like slackpkg, should **not** be used in Slint.
<|Інформація про нас <|Slackware Documentation <|This documentation can be also useful for Slint users.  Slint is based on Slackware.
<|Інформація про нас <|Slint Documentation <|This gives local access to documents also available on Slint's website.
<|Інформація про нас <|Slint Forum <|People whose native language is not English may also post in the localized Salix forums.
<|Інформація про нас <|Slint Website <|The Slint website provides documentation, links, and a way to find the ISOs and packages.
<|Інформація про нас <|System Information <|This tool collects information about your computer, such as its connected devices (internal and external), and displays it all in one place.  It can also do system bench marking.
<|Settings <|System clock <|This tool allows you to set system clock.
<|Налаштування <|Hostnames <|This tool allows you to associate IP addresses with domain names and host names
<|Налаштування <|System Language <|This tool allows you to set the system locale (language and geographic peculiarities), so that the applications you use will display information in this locale (if available).
<|System <|System Clock <|This tools allows you to set the time zone, choose if the clock should be synchronized with Internet servers (this is recommended but of course needs an Internet connection), and if not, set the date and time.
<|Система <|Hostnames <|This tool allows you to configure the system hostname. It is useful if you use your Slint installation as a server, on a local area network, or on the Internet.  The hostname helps networked computers identify each other by a common name if a domain name system service is not in use.
<|Система <|Rebuild Icon Cache <|This utility rebuilds the icon cache, which is a file registering all icons in the system, allowing them faster access. Run it when new icons are installed on your system.
<|Система <|System Services <|This tool allows you to choose which services will be enabled at startup.  For instance, Bluetooth, the CUPS print server, or a web server.  Only use it to change the defaults settings if you know what you are doing.
<|Система <|Users and Groups <|This tool allows you to add, remove, and set up user accounts and groups. It is mostly useful on multi-user systems.
<|Система <|GUEFI Boot Manager <|This tool is a graphical front end to the efibootmanager command.  It allows editing of the EFI firmware's boot menu.  Actions such as adding, removing, or changing menu item order.
<|Система <|MATE system monitor<|This tool displays information about the system, like the process, resources usage (RAM, CPU, network traffic) and file systems usage.
|====

[[graphical_terminals]]
==== Термінали

Ви можете набирати команди в графічному режимі як у режимі консолі, якщо ви відкриєте в ньому вікно
з терміналом. In Mate you can just press Ctrl+Alt+t, or click
on the mate-terminal icon on the top panel, or open a "Run... " dialog pressing
Alt+F2 then typing `mate-terminal` in the small window that opens.

Більша частина відомостей під командним рядком і оболонкою в режимі Консолі
також застосовується для введення команд в терміналі. Ви можете закрити термінал
натиснути Alt+F4 як у будь-якому іншому вікні.

[[key_bindings]]
==== Прив'язки ключів

Тут ми представляємо стандартні ключові прив'язки для менеджера відео Compiz і Mate desktop, і як налаштувати їх.

[NOTE]
====
When a key binding includes one or more **+** sign, press then hold from left to right the keys before the last one like a `Shift` key, then press the last key.
====
===== Прив'язки клавіш для стільниці Mate

При використанні Mate у Slint, деякі ключові зв’язки збігаються з іншими
керівниками відео Marco або Compiz. перераховані нижче:
----
Alt+Tab Цикл між вікнами
Shift+Alt+Tab Цикл між вікнами
клавіші + Alt+Tab Цикл між панелями і екраном
Shift+Alt+Tab Цикл між панелями і екраном
----
Якщо ви в графічному середовищі, ви можете переключитись на неї і на консоль.
Нехай's скажуть що ви хочете використовувати tty2 (tty1 зайняти):
Натисніть `Ctrl+Alt+F2`, і потім увійдіть. +
Натисніть `Ctrl+Alt+F7` щоб повернутися до графічного середовища.

Ці ж загальні ключі використовуються у всіх графічних середовищах,
за кількома винятками, для Mod1 - загалом ключ Alt зліва: +
----
Mod1+F1 піднімає меню застосунку.
Mod1+F2 викликає 'run..." діалог, але в Fluxbox (починається lxterminal замість це).
----
Також у Fluxbox:
----
Mod1+F3 restarts Fluxbox.
Mod1+F4 закриває вікно із фокусом.
----
Панель'меню додатка має той же макет у всіх доступних
графічних середовищах відправлено, але MATE. Зверху внизу:

Terminal emulator: `mate-terminal` in MATE, elsewhere `lxterminal` by default +
File manager: `Caja` in MATE elsewhere `PCManfm` by default +
Web browser: `Firefox` by default +
Mail client: `Thunderbird` by default +
Preferences +
Slint Dashboard (non accessible yet as it's a Qt4 app) +
Applications sorted by category +
Run dialog +
Logout dialog (also allows shut down and reboot)

Можна використовувати клавіші зі стрілками для переміщення в меню.

У MATE, верхня панель включає в себе зліва направо:

меню (Додатки, потім Місця, далі +
лаунчери для терміналу, caja (менеджер файлів), Firefox, Thunderbird і geany
текстовий редактор. +
На правій стороні залишається вправо праворуч:
області сповіщень +
кнопка блокування екрану +
кнопка виходу з системи +
половина або перезавантажити.

Нижня панель зліва направо:

список вікон +
плагін "desktop" +
перемикач робочого простору.

Все ще в Mate, частково зрячі користувачі можуть використовувати вікно compiz замість
або marco, який за замовчуванням.

Як звичайний користувач, наберіть:
----
gsettings set org.mate.session.required-components windowmanager compiz
----
Щоб повернутися у марко:
----
gsettings set org.mate.session.required-components windowmanager marco
----
Ці налаштування набудуть чинності на наступному початку сесії Мат.

Або щоб змінити лише для поточного типу сесії:
----
компіляція --заміна &
----
і щоб повернутися до марко:
----
marco --заміна &
----
Заміна негайно буде ефективною

Цей параметр також доступний графічно з налаштувань матерії, у категорії
Windows .

Ви можете отримати доступ до певних параметрів Compiz:
----
ccsm &
----
===== Прив'язки клавіш для менеджера вікон Compiz

In the default settings indicated below the key or mouse buttons are
named like this:

Super: Windows key on most keyboards +
Button1: Left Mouse Button (if used with the right hand) +
Button2: Centre Mouse Button, or click with the scroll wheel) +
Button3: Right Mouse Button (if used with the right hand) +
Button4: Scroll Wheel Up +
Button5: Scroll Wheel Down
Button6: (I don't know, I thought that was on mouses for gamers) +

The default settings listed below by category can be changed from the
CCSM. We indicate the short name of the plugin between square brackets.

. Category General
+
[core] General options, tab "key bindings": +
close_window_key = Alt+F4 +
raise_window_button = Control+Button6 +
lower_window_button = Alt+Button6 +
minimize_window_key = Alt+F9 +
maximize_window_key = Alt+F10 +
unmaximize_window_key = Alt+F5 +
window_menu_key = Alt+space +
window_menu_button = Alt+Button3 +
show_desktop_key = Control+Alt+d +
toggle_window_shaded_key = Control+Alt+s +
+
[matecompat] Mate Compatibility +
main_menu_key = Alt+F1 +
run_key = Alt+F2 +

. Category Accessibility
+
[addhelper] Dim inactive (less light on non focused windows) +
toggle_key = Super+p +
+
[colorfilter] (Filter color for accessibility purposes) +
toggle_window_key = Super+Alt+f +
toggle_screen_key = Super+Alt+d +
switch_filter_key = Super+Alt+s +
+
[ezoom] Enhanced Zoom Desktop +
zoom_in_button = Super+Button4 +
zoom_out_button = Super+Button5 +
zoom_box_button = Super+Button2 (zoom out to go back to normal) +
+
[neg] Negative (toggle inverse colors of the window or screen) +
window_toggle_key = Super+n +
screen_toggle_key = Super+m +
+
[obs] Opacity, Brightness and Saturation adjustments +
opacity_increase_button = Alt+Button4 +
opacity_decrease_button = Alt+Button5 +
+
[showmouse] (Increase visibility of the mouse pointer) +
initiate = Super+k +

. Category Window Management
+
[move] Move window +
initiate_button = Alt+Button1 (hold Button1 while moving the mouse) +
initiate_key = Alt+F7 (Esc to stop moving) +
+
[resize] Resize window +
initiate_button = Alt+Button 2 (hold Button2 while moving the mouse) +
initiate_key = Alt+F8 (Esc to stop moving) +
+
[switcher] Application switcher (switch between windows or panels and
                                 the desktop) +
next_window_key = Alt+Tab (cycle between windows) +
prev_window_key = Shift+Alt+Tab +
next_panel_key = Control+Alt+Tab (cycle between panels and desktop) +
prev_panel_key = Shift+Control+Alt+Tab +


===== Як додати користувацька клавіатура для Mate.

Let's take an example: we want that Alt+F3 starts firefox.
введіть в терміналі або в команді запуску (натисніть Alt+F2):
----
підключитися до ключових параметрів матриці
----
У новому вікні можна використовувати стрілки вниз і вгору для
навігації у списку існуючих посилань клавіш.

Щоб встановити нове прив'язування клавіш, натисніть Tab двічі, щоб поставити курсор на додавання, потім
натисніть Enter. У маленькому діалоговому вікні з'явилося ім'я
спеціального набору клавіш, наприклад, firefox, press Tab, введіть ім'я для
пов'язаної з командою, у цьому випадку firefox, а потім натисніть вкладку двічі, щоб
поставити курсор на застосовується і натисніть клавішу Enter.

Щоб активувати нове прив'язування клавіш, перейдіть до тих пір, поки її не знайдете в
нижній частині списку, пресує клавішу Alt+F3.

Наступного разу при введенні Alt+F3, що має почати Firefox

=== Shell

NOTE: Цей розділ є коротким встудом. Більш детальна інформація надається в документі https://slint.fr/doc/shell_and_bash_scripts.html[Скрипти Shell і bash], в основному позичених в SUSE.

Коли комп'ютер запускається в режимі консолі, після того як виконав введення імені користувача та пароля <<shell, оболонка>> відображає "запит" на зразок нижче: +
`didier@darkstar:~$` +
У прикладі:

* `дідько` є іменем користувача
* `затемнити зірку` ім'я машини
* нахил `~` представляє домашній каталог користувача, в цьому прикладі `/home/didier`
* знак `$` вказує на те, що користувач є "звичайним" не "супер користувач" (дивіться нижче).

Потім курсор розташований після підказки.

Користувач тепер може ввести команду на рядку (таким чином ім'я "командний рядок") і підтвердити її натискання Enter. Машина then analyzes the command and execute it if valid, else output a message like for instance "command not found". Ти можеш редагувати команду перед натисненням Enter використовуючи стрілки ліворуч і праворуч та клавіші Backspace (Home, End і Del.

Під час виконання команди можуть відображати вихід на екрані чи ні. У всіх випадках після виконання командного рядка буде відображатися знову в новому рядку, мається на увазі, що оболонка очікує наступної команди, яка буде введена.

Для цієї роботи користувачу необхідно дізнатися, які команди доступні та їх синтаксис. Деякі команди виконуються самою оболонкою, інші починають зовнішні програми. Нижче надаватимуться кілька прикладів команд, в https://slint.fr/doc/shell_and_bash_scripts.html[Снаряд і основних скриптів]

Several shells are available for Linux to choose from; in Slint the shell used by default is named *bash*.

Для забезпечення роботи декількох програм одночасно Linux надає декілька «віртуальних консолей», а потім одну й ту ж клавіатуру і екран, номер один з одного. Initially the system starts in the console (or virtual terminal) number one also called *tty1* (the name tty is an abbreviation of "teletype"). Звідси користувач може переключитися на іншу або на іншу консоль; наприклад, переключитися на для: Alt+F2, де інша оболонка знову запитає користувача's ім'я користувача та пароль. Щоб переключитись на tty1, просто натисніть Alt+F1. За замовчуванням у Slint шість тонких доступних, але це можна змінити редагування файлу /etc/inittab.

Коли оболонка використовується в графічному середовищі (в графічному терміналі), її поводить так само, але запит трохи відрізняється, як ілюстровано нижче: +
`діарер [~]$` +

Ви можете переключатися туди-сюди між консоллю та графічним середовищем:

* З графічного середовища натискання для прикладу Ctrl+Alt+F3, щоб перейти до tty3. При першому вході в tty, вам доведеться ввести свій логін і пароль.
* З консолі або tty натисніть Alt+F7, якщо графічне середовище вже запущено, інакше наберіть `початковий текст` , щоб запустити його.

==== Друк команд як корінь

*Коренем* є умовним ім'ям "супер користувач", який має всі права виконувати адміністративні завдання, включаючи тих, що можуть зашкодити або навіть руйнувати систему.

Ви можете (але це не рекомендується для початківців) входити безпосередньо як root. Для виконання цього типу *root* як користувач, а потім root's пароль.
Щоб повідомити вас (і попередити вас про пов'язані ризики і обов'язки), запит буде виглядати так: +
*root@darkstar:s~#* +
символ # (знак числа, також часто називаються хеш) вказує на те, що команди будуть введені як кореневий (не як звичайний), з пов'язаними правами, але також ризиками та обов'язками.

If you are already logged as regular user, you can "become root"  typing: +
*su -* +
then pressing Enter. У цій команді, `су` (який стоїть fr "Super User") є ім'ям команди, і персонаж *-* (дефіс мінус, також називається minus) говорить про те, що ви відкриваєте "login shell": вас спочатку запитають root's пароль, тоді буде направлено в його домашній каталог /home/root як якщо б ви увійшли в режим root під час запуску. Це дозволить уникнути випадкового переписування файлів у домашній каталозі як звичайний користувач (/home/didier в прикладі), що спричиняє проблеми пізніше.

=== Як вирішити проблеми блокування

Блокуючи проблему" ми маємо на увазі проблему, яка не дозволяє використовувати Slint" наступним чином:

* Система не вдається завантажити.
* Система завантажує, але послідовність запусків буде перервана до завершення. Це може статися, наприклад, якщо кореневий розділ системи't буде змонтований через помилку в /etc/fstab пошкоджена коренева файлова система або відсутній модуль ядра для монтування кореневого розділу, або система успішно завантажує, але ви не можете'пам'ятати пароль для root.

Якщо система повністю не впорається з завантаженням, спробуйте виконати кожне з рішень нижче в послідовності, доки не спрацює.

. Якщо це відбувається після оновлення ядра, спробуйте другий запис boot замість першої.
. Використовувати останній запис завантаження меню GRUB. Він зміг знайти Slint і дозволити почати його.
. Спробуйте запустити звантажувальний режим, який ви замовили в кінці встановлення.
. Переходимо до Slint, щоб виправити його, як пояснено нижче.
. Попросіть допомоги по електронній пошті slint@freelists.org , що надає всю інформацію, яка може допомогти дослідити проблему. Якщо це ще не зроблено, спочатку підпишіться на розсилку по електронній пошті slint-request@freelists.org з темою 'subscribe', та дайте відповідь на електронну пошту, яку ви отримаєте. Лише якщо у вас є проблема з використанням електронної пошти, зверніться до довідки в IRC канал #slint, сервер. libera.chat та залишайтеся в каналі, поки хтось не відповість.

Якщо послідовність старт-п буде перервана, стрибніть в Slint з його інсталятора, щоб спробувати вирішити проблему. Insert or plug-in the installation media (USB stick or DVD where you have written the installation ISO)  then follow the instructions below.

. Запустити інсталятор.
. Як тільки зайшов кореневий каталог, то він перелічує диски та розділи, наберіть:
+
----
lsblk -lpo name,size,fstype
----
. Знайти в ім'я кореневої секції Slint, перевіряючи їх розмір та тип файлової системи, позначений FSTYPE.
. Перевірте, чи він хороший. Якщо це /dev/sda3, тип:
+
----
монтувати /dev/sda3 /mnt
кот /mnt/etc/slint-версію
----
+
[NOTE]
====
Якщо файлова система кореневої секції Slint здається зіпсованою, не't монтувати його, але спробувати виправити цю команду:
----
fsck <name of the root partition>
----
І якщо це вдасться перезавантажити.
====
+
Припустимо, що ви встановили Slint64-14.21 результат має бути:
+
*Slint 14.2.1*
+
Якщо вихід даних не знайдено, секція не є позначеною для Вас. У цьому випадку лише друкуйте:
+
----
umount /mnt
----
+
потім спробувати ще одне, повертаючись до списку дисків та перегороджень.
+
Інше, пов'яжіть підключення до псевдо-файлових систем /dev, /proc і /sys в системі Slint, друкуючи:
+
----
монтувати -B /dev /mnt/dev
монтувати -B /proc /mnt/proc
монтувати -B /dev /mnt/sys
----
+
Випустіть наступну команду, щоб "стрибнути до" вашого Slint:
+
----
chroot /mnt
----
+
chroot означає "змінити корінь (системи)": ми більше немає в інсталяції, але зараз у самому Slint. Тут ви можете змінити систему для вирішення проблеми. Ось кілька прикладів:

* Запустити "update-grub".

* Запустити "Gub-emu".

* Переінсталюйте GRUB за допомогою команди "grub-install drivename", було водієм де потрібно встановити Slint. Перед тим, як це зробити, якщо ви завантажите у режимі EFI введіть спочатку "монтувати /boot/efi".

* Введіть "passwd", щоб змінити пароль для root.

* Видалити, встановити або оновити пакети.

. Після завершення видаліть установку медіа, потім наберіть:
+
----
вийти
перезавантаження
----

[[Accessibility]]
== Accessibility

Якщо ви вирішили продовжити промову при запиті на початковій установці, він буде увімкнений
для запуску в консолі, як у графічному середовищі.

=== Використання брайля у Slint

Slint включає програмне забезпечення для роботи дисплеїв Брайля.

Ваші налаштування, зроблені перед завантаженням на командному рядку чи пізніше, записуються у встановлену систему в
/etc/brltty.conf.

Логічний посібник для brltty доступний англійською, Французька і
португальська мова в декількох форматах, включаючи звичайний текст (txt) на цій URL-адресі:
https://mielke.cc/brltty/doc/Manual-BRLTTY/

Якщо Брайль не був включений під час встановлення або був відключений, щоб включити його:

. Робіть виконуваний файл /etc/rc.brltty вводити як root:
+
----
chmod 755 /etc/rc.d/rc.brltty
----
. Зробіть себе учасником групи Брайлля, вводячи як кореневий:
+
----
ім'я користувача - G Брайль -G
----
+
У команді вище, замініть ім'я користувача на ім'я користувача.

Щоб вимкнути тип Брайля як root:
----
chmod 64 /etc/rc.d/rc.brltty
----

=== Мовлення в графічних середовищах

Як нагадування про це в графічних середовищах, за допомогою програми зчитування екрана Orca увімкнена тип:
----
орка
----

Щоб знати, як використовувати Orca, включно з його певними прив'язками до ключів, наберіть:
----
людина-орка
----

Коротше кажучи, в графічному середовищі, в графічному режимі:
----
Insert+Space: запустіть діалог налаштування орки.
Insert+S: активувати або деактивувати вокальний синтез.
Insert+H: активує режим навчання. У цьому режимі:
   натисніть клавішу для прослуховування своєї функції
   F1: щоб почути документацію читача екрану
   F2: перерахувати ярлики клавіатури для Orca
   F3: перерахувати клавіатуру для поточного додатку
   Esc: кінець режиму навчання
----

=== Голоси й рушії перетворення тексту в мовлення, що входять до складу Slint.

Наступні TTS (текст для синтезу мовлення) відправляються в
Slint64-14.2.1. , кожен з безліччю голосів, назва: +
espeak-ng +
flite +
піцо +
mbrola +
RHVoice +

У більшості випадків ці TTS і пов’язані голоси і мови
керуються голосовим диспетчером через його так звані "модулі" (грубо кажучи,
модуль підключений до TTS).

Користувальницькі комунальні послуги можуть відповісти на кілька питань щодо
синтезаторів, голосів та мов. Набираю Spd-list показує наступне:
----
Цей скрипт перелічує мови й синтезатори для застосунків
покладається на програму мовлення Диспетчер, наприклад Orca або мова мовлення. Кожна команда нижче відповідає на питання, на яке слід.
Не введіть лапки, що оточують команду.
"/usr/bin/spd-list" usage?
"/usr/bin/spd-list -s" available synthesizers?
"/usr/bin/spd-list -l" available languages codes?
"/usr/bin/spd-list -ls <synthesizer>" languages available for this synthesizer?
"/usr/bin/spd-list -sl <language code>" synthesizers providing voices in this language?
The language code has most often two characters, like 'en' 'es' or 'fr'
----
Всі перераховані голоси доступні в Orca та в мовленні, а також fenrir, якщо налаштовано на використання мови -dispatcher.

Ви можете отримати додаткові голоси за фліту і Мбролу, пов'язані з
модулями flite-generic та espeak-ng-mbrola generic.

Ви завжди можете знати, які встановлені або не вводити як корінь з цих команд:
----
slapt-get --search mbrola-Голос
slapt-get --search flite-voice
----
а потім встановіть один з пристроїв, наприклад,
----
млявий отримувач -i мброла-результатит2
----
На додачу до вільних (як у вільних пивах) голоси відправляється у Слінт,
Ви можете придбати голоси: +
voxin, https://oralux.org/voice.php +
voxygen, надіславши повідомлення contact@hypra.fr

Більше голосів і синтезаторів можуть бути доступні пізніше, це буде оголошено на
Slint розсилці і цей http://slackware.uk/slint/x86_64/slint-14.2.1/ChangeLog.txt[журнал змін]

Ярлики на клавіатурі для графічних середовищ перераховані в <<key_bindings, поєднання клавіш>>.

=== Менеджери входу й мовлення

Двох графічних менеджерів для входу доступні з мови за допомогою Orca: lightdm або gdm, останні рекомендується в повній доступності.

Гдм, що вказує спочатку на поле користувача. Введіть користувача. або
ім'я користувача, потім введіть пароль і введіть його.

За допомогою клавіш можна отримати доступ до інших функцій Gdm через ярлики. У
Англійському: +
Alt+A: дії (завершення або перезавантаження) +
Alt+E: Меню сесії +
Alt+L: змінити мову, для наступної сесії, а може й далі
сесії, можливо й для самого гравця. +
Alt+T: Тема. +
Ви можете використовувати клавішу Tab для навігації серед вхідних полів, а також клавішу
внизу для меню.

Для ввімкнення чи вимкнення звуку на F4. Спочатку курсор
знаходиться в полі пароля. Натисніть Tab належить до "push для входу",
потім до користувача's список або "комбінованих". У цьому списку натиснений простір
відображається вибраному користувачеві. Використовуйте клавіші зі стрілками для вибору іншого
і потім введіть відповідний пароль. Натомість обираючи "Інше..."
додає поле, в якому ви можете ввести ім'я користувача без списку.
Все ще у легкому, F10 піднімає меню з можливістю перезавантаження або вимкнення,
і Alt+F4 підключає безпосередньо інтерфейс з вимкненим або скасовує кнопки.

=== Вибір консольного читача екрана

Slint забезпечує ці консольні екрани: +
espeakup +
speehd-up +
fenrir

Додатково можна використовувати декілька апаратних синтезів мовлення в
режимі консолі, з використанням гучності.

To choose a screen reader run as root this command:
----
динамік-з
----
Це вивід без аргументу:
----
root[~]# speak-with
Usage: /usr/sbin/speak-with <screen reader> or <hard synthesizer> or none
Виберіть зчитувач на консольному екрані to talk with among:
  espeakup (Console screen reader connecting espeak-ng and speakup)
  fenrir (Modular, flexible and fast console screen reader)
  speechd-up (Console screen reader connecting Speech Dispatcher and speakup)
or use one of the supported hard synthesizers:
  acntsa apollo audptr bns dectlk decext ltlk soft spkout txprt
or type  "/usr/sbin/speak-with none" to mute all screen readers.
root[~]#
----
Показані апаратні синтезатори мовлення є доступними в
запущеному ядра або відправлені в якості модулів.

Приклад команд і виведення:

----
root[~]# гучний зв'язок з звуком
Початок мовлення
Чи повинні також починатися при наступному завантаженні? [Y/n]
OK
коріння [~]# Готово.
----
Як тільки ви введете команду, читачі з екрана
зупиниться, і мовлення почнуть говорити.

Якщо ви відповідаєте Y (за замовчуванням) на питання: +
голосове введення тексту також буде почнеться при наступному завантаженні? +
глядацький режим буде продовжувати використовувати при наступному завантаженні. +
Якщо замість цього ви відповідаєте на n читача з екрану, що використовувався перед друком мови
після наступного завантаження.

Інші приклади:

----
root[~]# динамік з apollo
Зупинка мовлення...
Чи варто apollo використовувати під час наступного завантаження? [Y/n]
OK
коріння [~]# Готово.

root[~]# гучний консоль без імені
Ви також хочете заглушити консоль при наступному завантаженні? [Y/n]
OK
root[~]#
----

=== Налаштування консольного читача екрана.

Синтезатор мовлення Slint використовує динамік і забезпечує espeakup
та голосові читання з екрану.

Ви можете зберегти внесені параметри, наприклад, для збільшення швидкості
або зниження рівня обчислень або гучності звуку. Просто пишіть як root:
зберігати гучність. This saves all current settings, including those specific to the
hardware synthesizer in use, case occurring.

Усі ці налаштування будуть відновлені при наступному завантаженні: сценарії запуску
rc.espeakup та rc.speechd-up запускають команду, які викликають відновлення динаміків.

Якщо ви цього не зробите'щоб відновити збережені налаштування, введіть root: +
chmod -x /usr/sbin/speakup-restore

Якщо вони відновили свій ROOT: +
chmod +x /usr/sbin/speakup-restore

Ось деякі ключові прив'язки для розмовних налаштувань, а також голосових налаштувань:
----
spk key_f9 punctuation_level_decrease
spk key_f10 punctuation_level_increase
spk key_f11 reading_punctuation_decrease
spk key_f12 reading_punctuation_increase
spk key_1 e_decrease (не працює із стандартним розширенням)
spk key_2 volume_increase (не працює з голосовим вкладом)
spk key_f_3 pitch_decrease (не працює з письмовим вгору)
spk key_4 pit_4 гноєм (працює зі словами
key_5 rate

----
У таблиці над запасом видання є капсих-ключ, або нуль біля цифрової
клавіатури. Наприклад, щоб збільшити ставку, яку можна натиснути та утримувати клавішу
CapsLock і натиснути клавішу 6.

Деякі параметри доступні лише для певних апаратних синтезів не
мають пов'язані прив'язки до ключів. Потім для встановлення нового значення, яке ви перегукуєте в
/sys/accessibility/speakup/<synth>/<parameter>

Наприклад, щоб змінити голос у використанні на apollo 2, ви можете написати: +
echo 2 > /sys/accessibility/apollo/voice

режим глибокого мовлення також збереже цей параметр.

Розказує: я ніколи не використовував апаратний синтезатор мов, тому пояснення нижче це
тільки припущення, засноване на синомовець _apollo, узгодження з
посібником, знайдено в: +
https://archive.org/stream/DolphinApollo2Manual/Dolphin_Apollo_2_Manual_djvu.txt

[[desktop_keys]]
==== Розмивати настільні ключі

Майже всі ключі, перераховані нижче, розташовані на числовому ключі.
Вставка або 0 кнопка на клавіатурі діє як зміна ключа. Наприклад,
У двох значить "утримуйте натиснуту клавішу, яка Shift і натисніть клавішу 2".
Тримайте вимк. вимк, щоб увімкнути гучність.

Копія: ці ключові прив'язки можуть бути використані за допомогою жорстких синтезаторів і за допомогою
espeakup, а також за допомогою мовлення. Однак налаштування гучності або
мовлення з використанням клавіш недоступне для розпізнавання мовлення.

Перші ключі:
----
PrintScreen    Toggle speakup on/off
Ins F1         Speakup Help (press Space to exit the help)
----

Ключі, які використовуються для перегляду на екран:
----
1/2/3          Say Previous/Current/Next character
Shift PageUp   Say first character
Shift PageDown Say last character
4/5/6          Say Previous/Current/Next word
5 twice        Spell current word
Ins 5          Spell Current Word phonetically
7/8/9          Say Previous/Current/Next line
Ins 4          Say from left edge of line to reading cursor.
Ins 6 прокажуть від читання курсору до правого краю лінії.
У 8 береться з верхньої частини екрана до курсору.
Ins плюс скачати від читання лінії курсору до нижньої частини екрану.
плюс згадка про весь екран.
У r r r говорити, що все подвоєння
точка
 говорити позицію
Ins крапка
Ins мінус hex і десяткових значень.
мінус курсор читання парком (перемикач ну)
Пересунути курсор на 9 переміщення курсору читання у верхній частині екрана (вставляє)
У 3 направляти курсор читання в нижній частині екрана (вставляти pgdn)
У правий край екрана (вставляємо)
У один спосіб читання курсору на правий край екрана (вставляти)
Рухайте курсор читача курсора 1 в останню чергу рядка.
зірочка Перемикання курсору
Ins asterisk n<x|y go to line (y) або стовпець (x). Де «n» - це будь-яке
               значення рядка або стовпця для поточного екрану.
Ins f2         Set window
Ins f3         Clear window
Ins f4         Enable window
----

Інші ключі:
----
Ins f5 Edit деякі
Ins 6 Edit більшість
Ins f7 Edit delim
Ins
 Ins 8 Edit repeat
Ins f9 Edit exnum

Enter Shut up (поки інший ключ не вдаряться) і синхронізувати курсор.
Ins Enter Shut (до перемикання на назад)

коса позначки і обрізати екранний регіон.
В будь-якій консолі, вставленій області, яка знаходиться в консолі.
----
==== Ключі зі спинкою ноутбука

These key bindings (for US keyboard layout) don't need a numeric keypad.
Якщо є такий, то використовуйте <<desktop_keys, динамічні кнопки>> легше використовувати
, особливо якщо використовується інша розкладка клавіатури, ніж США.

Клавіша CapsLock працює як клавіша Shift. +
, Наприклад, CapsLock 2 означає "утримуйте клавішу CapsLock як клавішу Shift і натисніть клавішу 2". +
Тримайте вимк. ВИМК.

Копія: ці ключові прив'язки можуть бути використані за допомогою жорстких синтезаторів і за допомогою
espeakup, а також за допомогою мовлення. Однак налаштування гучності або
мовлення з використанням клавіш недоступне для розпізнавання мовлення.

Перші ключі:
----
PrintScreen          Toggle speakup on/off
CapsLock F1          Speakup Help (press Space to exit)
----

Ключ використовується для огляду на екран:
----
CapsLock m/comma/dot Say Previous/Current/Next character
CapsLock PageUp Say 1-го символу
Поточний символ
Останній символ CapsLock j/k/l Say Previous/Current/Next word
CpasLock k двічі активний слово
CapsLock u/i/o Say Previous/Current/Next line
CapsLock h Say Say Say Say Stager.
CapsLock semicolon Say від читання курсору на праве краю лінії
CapsLock y Say з верхньої частини екрану для читання курсора.
CapsLock p для читання лінії курсору в нижній частині екрану.
Capslock апостроф сказав увесь екран.
Capslock r читає всі документи.
CapsLock n ay положення
Властивості CapsLock Say атрибути
CapsLock мінус park читання (діяти)
CapsLock f2 Set window
CapsLock f3 Clear вікна
CapsLock f4 Enable
----
Інші ключі:
----
CapsLock f5 Редагувати деякі
CapsLock f6 Редагувати найбільше
CapsLock f7 Редагувати роздільник
CapsLock f8 Repeat f8 Repeat edit
Shift CapsLock f9 Edit exnum
----

=== Як змусити emacs розмовляти

Ти можеш використовувати або емакет або мовлення. Щоб увімкнути або вимкнути один з
типу як звичайний або одна з цих команд:

switch-on emacspeak +
switch-on speechd-el +
switch-off emacspeak +
switch-off speechd-el +

Потім просто наберіть: +
емаків

Увімкнення одного з цих програм вимикає інше.

[[Manage_your_system]]
== Manage your system

[[software_management]]
=== Керування програмним забезпеченням у Slint.

<<The_basics, The basics>> +
<<Keep_your_system_up_to_date, Keep your system up to date>> +
<<Kernel_upgrades, Kernel upgrades>> +
<<Get_additional_applications, Get additional applications>> +
 <<slapt_src, Usage of slapt-src>> +
 <<sbopkg, Usage of sbopkg>> +

[[The_basics]]
==== Основи

Slint програмне забезпечення забезпечується у вигляді пакетів. Пакет - це набір файлів, що надаються в стиснутому архіві, накладеному разом, щоб забезпечити необхідність програмного забезпечення. Пакунки включені в інсталяцію ISO і збережені на віддалених серверах, з яких вони можуть бути завантажені та встановлені. Installing a package means extract the files from the archive file and copy them to some directory of the system.

Встановлення та видалення програмного забезпечення записуються в текстові файли бази даних:
----
/var/log/packages
/var/log/removed_packages
/var/log/scripts
/var/log/removed_scripts
----
Файли в каталозі інформації про пакети, в основному їх вміст: список файлів, в якому він знаходиться, і де вони встановлені.

Основні команди управління пакетами наведені нижче. У кожного з них є пов'язані сторінки чоловіків.

Ці команди потребують адміністративних прав, пов’язаних з певним обліковим записом 'root', для якого ви вказали пароль під час встановлення Slint.

Щоб видати команду 'root', перший тип 'su -', потім введіть пароль для команди 'root і наберіть його.

Наведені нижче команди можна запускати з графічного терміналу або в консолі, але засліплений, що працює лише в графічному середовищі.
----
Встановіть pkg # для встановлення пакету, який зберігається локально.
видаляйте файл # для видалення встановленого пакету.
upgradepkg # щоб замінити встановлений пакет іншим (загалом з тією ж назвою, як і з іншою версією).
slapt-get # для встановлення, видалення, оновлення пакетів збережених в репозиторіях, перерахованих в /etc/slapt-get/slap-getrc
----
Пакети, що передаються в інсталяції ISO приходять з репозиторіїв, перелічених в /etc/slapt-get/slapt-getrc

Зробіть себе улюбленим: прочитайте коментарі в /etc/slapt-get/slapt-getrc and /usr/doc/slapt-get-0.10.2t/README.slapgetrc.Slint в встановленій системі.

Після встановлення Slint, ви'll буде повідомлено про оновлення встановлених пакетів, які надходять з репозиторіїв, перерахованих в /etc/slapt-gett-getrc

Ви можете встановити додаткові пакунки за допомогою роздачі у командному рядку або gslapt графічної програми, якщо збережено до репозиторію, вказаного в /etc/slapt-get/slapt-getc

slapt-get і gslapt забезпечить функцію пошуку, яка допомагає шукати пакети.

WARNING: ви можете використовувати slapt-get, gslapt і removepkg для видалення встановлених пакетів, але не видаляйте пакети, відправлені в Slint ISO, навіть якщо ти їх взагалі не використовуєш. Видалення включеного пакету не призведе до збільшення продуктивності та може запобігти запуску інших програм. Крім того, якщо ви додали пакет не включений у Slint, який ви можете видалити, але будьте обережні, що віддалений пакет не буде залежним від інших, які ви також встановили і має намір продовжувати використання.

[[Keep_your_system_up_to_date]]
==== Тримати систему в актуальному стані

Зберігайте вашу систему безпечним встановленням оновлень програмного забезпечення, наданих Slint, як тільки вони стануть доступними'

Усі оновлення перераховані в журналі змін: http://slackware.uk/slint/x86_64/slint-14.2.1/ChangeLog.txt

Після установки Slint, або зміни у файлі /etc/slapt-get/slapt-getr виконайте цю команду один раз:
----
slapt-get --add-keys
----

Щоб синхронізувати локальний список доступних пакетів з тим репозиторієм, ця команда автоматично запускається кожні дві години:
----
slapt-get -u
----
Ви також можете запустити його вручну

Це, звичайно, вимагає, щоб машина була підключена до інтернету.

Щоб звантажити і встановити оновлені або перебудовані пакунки виконуються як root
наступною командою:
----
slapt-get --upgrade
----
Альтернативно ви можете також використовувати gslapt, графічну фронтенд для виштовхування.

Щоб отримати нові пакети, перераховані в журналі змін як "Додані", тип:
----
slapt-get -i <package name>
----
або для того, щоб переконатися, що ви встановили всі пакети, відправлені у Slint, включаючи ті, що додали в репозиторій після установки Slint, тип:
----
slapt-get --install-set slint
----

На робочому столі, невелика іконка відображається в області сповіщень (верхня панель в MATE) для повідомлення про доступні оновлення програмного забезпечення. Просто натисніть ліву кнопку на неї і дотримуйтесь згаданих інструкцій.

Майте на увазі, що деякі пакети з чорним списком у
/etc/slapt-getrc, тобто не можуть бути автоматично оновлені або
встановлені.

[[Ядро_upgrades]]
==== Оновлювати ядро

Нові явища надаються щоразу, коли необхідно, або для виправлення безпеки, або покращення.

Зазвичай ручне втручання користувача є необхідним, коли це станеться, але це може бути корисно для розуміння як оновлення ядра і що робити якщо відбувається щось несподіване.

Кілька пакетів містять файли, пов'язані з кожним ядром, а саме: ядро універсальні, ядрові модулі, джерела ядра, заголовки ядра тощо. джерела ядрах і заголовки ядер включають файли, які використовуються для побудови програмного забезпечення, необхідні тільки загальні модулі ядра і ядра, необхідні для запуску системи Slint.

Файли модулів пакунку запускають диких модулів, що називаються модулями, які є частинами коду, які "під'єднані" ядро для забезпечення певної функції або обробки конкретного обладнання.

Як тільки встановлюється пакет ядра і пакет з асоційованих ядра модулів. скрипт
/sbin/wrapupgradepkg побудував <<initrd, initпі>> , пов'язаний з цим ядром (модулями, взяті з
пакунку Ядро) і встановлює його поруч з ядром в каталозі /boot .

Тоді попередні явища (не використовуються в момент оновлення) видаляються.

Потім скрипт оновлює файл конфігурації GRUB /boot/grub/grub.cfg, прочитано завантажувачем ОС для запуску завантаження під час завантаження.

У меню завантаження містяться щонайменше два записи завантаження і вказують, що слід використовувати ядро і асоційовану в них. Згори дригу:

* Запис завантаження для запуску Slint, використовуючи нове ядро, яке тільки що було встановлено.
* При оновленні використовується можливість завантаження Slint, використовуючи ядро під час оновлення.

Це забезпечить своєрідну "захисну мережу" у разі, якщо Slint завантажить't завантажується з новим ядром:
у цьому випадку тільки один раз, коли меню завантаження відображається для запуску Slint з попереднім ядром

Перед перезавантаженням ви можете переглянути меню запуску, набирати як root:
----
grub-emu
----
Потім відображається меню завантаження з емулятивним або "фальшивою", з тим самим макетом, що й реальний, який
відображатиметься при завантаженні.

Ви можете переміщатися в ньому за допомогою клавіш зі стрілками внизу, щоб виділити їх (повернути фокус) запис завантажування, за допомогою якого можна побачити деталі, натиснувши "e". Ви можете повернутися до меню за допомогою клавіші Escape.

To exit from grub-emu press c then type *exit* and press Enter.

[[Get_additional_applications]]
==== Отримати додаткові додатки

Якщо додаток, який ви хочете, не встановлений і не доступний в одному з репозиторіїв, включених в /etc/slapt-getrc ви можете створити для нього пакет, який ви можете отримати в будь-якому пакеті, використовуючи будівельний матеріал, наданий волонтерами @ https://slackbuilds.org. Щоб знати інструкцію, прочитайте https://slackbuilds.org/howto/ і https://slackbuilds.org/faq/

Пакети, побудовані таким чином, повинні бути сумісні з Slint.

Два додатки дозволяють створювати та встановлювати пакети, використовуючи будівельні матеріали https://slackbuilds.org: *slapt-src* і *sbkg*. Якщо ви не звикли до sbopkg, ми рекомендуємо використовувати slapt-src, щоб дізнатись більше. Однак одночасно повинні працювати і надавати ті ж результати і використовувати в якості root.

Детальну інформацію ми опишемо плавний пробіл.

[[slapt_src]]
===== Використання слідів slapt-srcrc

Скрипт конфігурації за замовчуванням для slapt-src дорівнює /etc/slapt-get-getrc та містить вміст:
----
BUILDDIR=/tmp/slapt-src
PKGEXT=txz
SOURCE=https://slackbuilds.org/slackbuilds/14.2/
----
Отже:

* Всі будівельні матеріали і пакети перейдуть в /tmp/slapt-src
* Імена пакетів, збудованих в .txz
* Збірка отримана з репозиторію https://slackbuilds.org/slackbuilds/14.2/

Ось вивід команди *slapt-src --help*:
----
Використання: slapt-src [option(s)] [action] [slackbuild(s)]
  -u, --update update локального кешу віддалених slackbuilds
  -U, --upgrade-all upgrade всі встановлені slackbuilds
  -l, --list list доступний збірки slackbuilds
  -e, --clean каталог збірки
  -s, --search доступний використовуючи використовуючи slackbuilds
  -w, --показати вказані кульки
  -i, --встановлюю вхід, збірка, і встановіть вказану slackbuild(s)
  -b, --build тільки витягти і побудувати вказану slackbuild(s)
  -f, --fetch only fetch the specified slackbuild(s)
  -v, --version
  -h, --help
 Параметри:
  -y, --так. Не запитувати
  -t, --імітація того, що буде зроблено
  -с, --config=FILE використовувати вказаний файл конфігурації
  -n, --no-dep не шукати залежності
  -p, --postprocess=CMD запустити вказану команду в згенерованому пакунку
  -B, --build-only доступно тільки для --upgrade-all
  -F, --fetch-only застосовувати тільки для --upgrade-all
----

Нехай'коментар деяких з цих варіантів:

* Використовуйте -u або - оновлювати кожен раз, щоб оновити список пакетів, які можуть бути побудовані та встановлені. Ця команда виконує команду в файлі /tmp/slapt-src/slackbuilds_data, замінюючи в попередній кейс.
* Використовуйте HTML, щоб зберегти місце на диску, видаливши більшість файлів у /usr/src/slapt-src/
* *не* використовувати -U, але зі списком можливі оновлення або пониження без підтвердження: підтвердження призведе до заміни всіх пакетів Slint один на іншу версію, якщо вона доступна в віддаленому репозиторії, можливо робота програмного забезпечення не сумісна з іншою версією.
* -i може також оновити пакунок за допомогою https://slackbuilds.org, якщо супроводжуючий скрипт SlackBuild було оновлено, змінивши змінну VERSION.
* Використовуйте -f для завантаження файлів в https://slackbuilds.org для цільового програмного забезпечення. Це може бути корисно, якщо ви хочете перевірити матеріал, або налаштувати збірку. For instance let's assume you want to fetch the build material for the software *mxml*. Ця команда нижче надає деяку інформацію про програмне забезпечення і яку файли зберігаються в https://slackbuilds.org:
+
----
slapt-src --show mxml
SlackBuild Name: mxml
SlackBuild Version: 3.1
SlackBuild Category: libraries/mxml/
SlackBuild Description: mxml (Lightweight xml parsing library)
SlackBuild Files:
 README
 mxml.SlackBuild
 mxml.info
 slack-desc
----
+
Тепер завантажуйте ці файли, а також архів з репозиторію upstream за допомогою наступної команди:
+
----
slapt-get -f mxml
----
+
Знання з виходу попередньої команди, що файли зберігаються в бібліотеках підкаталогів/mxml, ви можете перевірити, які файли були завантажені цією командою:
+
----
ls -1 /tmp/slapt-src/libraries/mxml
mxml-3.1.tar.gz
mxml.SlackBuild
mxml.info
slack-desc
----
* Використовуйте -b, якщо ви хочете створити пакет, але ще не встановити. У прикладі вище програму буде зберігатися в /tmp/slapt-src/libraries/mxml, так що ви зможете встановити його після вводу:
+
----
upgradepkg --install-new /tmp/slapt-src/libraries/mxml/xml*txz
----
+
* Використовуйте -c, якщо ви хочете використовувати файл конфігурації замість стандартного /etc/slapt-get/slap-getc

[[sbopkg]]
===== Usage of sbopkg

WARNING: в деяких випадках програмне забезпечення доставляється через Slint, а також є доступним і в https://slackbuilds.org , але з іншим ім'ям, яке може призвести до проблем. Ці розбіжності вирішуються при використанні slapt-src, але поки що не використовується sbopkg.

Перед використанням sbopkg, прочитайте його файл і її людина, що друкує корінь: *sbopkg --help* і *man sbopkg*

Коротко, якщо використовувати лише командний рядок, як root:

* синхронізуйте локальне сховище з віддаленим сховищем:
+
----
софкг -r
----
* написати список залежностей в правильному порядку для створення та встановлення їх перед необхідним програмним забезпеченням:
+
----
sqg -p <package name>
----
Файл черги з назвою /var/lib/sbopkg/queues/<package name>.sqf буде записаний

Якщо черги не містяться, то файл не буде записаний

* побудувати та встановити залежності, потім потрібне програмне забезпечення:
+
----
sbopkg -i <package name>
----
Якщо файл черги існує для цього пакету, оберіть його при запиті.

Якщо пакет який був встановлений у файлі черги, він буде пропущений.

В результаті якщо ви хочете оновити пакет, вже встановлений за допомогою sbopkg, вам доведеться видалити його
перед побудовою і встановленням нового.

Майте на увазі, що побудова і встановлення пакунків такий спосіб може іноді призвести до проблем, таких як відсутні залежності або конфлікти з встановленими пакетами: компоненти, які використовуються для створення пакунків, забезпечені волонтерами, які не можуть перевірити результати в кожній можливій конфігурації.

WARNING: Якщо ви не можете знайти пакунок для програмного забезпечення, яке вам не потрібно, або речі для створення однієї @ https://slackbuilds.org- ви можете спробувати створити і встановити це програмне забезпечення вручну, випустивши команди ". налаштувати && зробити && зроблення". Уникати цього, у міру створення програмного забезпечення та встановлення цього способу не буде керувати системою Slint пакетів управління і пов'язаними з цим інструментами.

Швидше, просто опублікуємо питання або запит на розсилку Slint, і ми спробуємо допомогти, можливо додаємо цей пакет в репозиторій. Після виконання (це буде оголошено у списку розсилки), щоб встановити його тип як кореневий з тих команд:
----
slapt-get -i <package name>
slapt-get --install-set Slint
----

=== Керування користувачами та групами.

Для управління користувачами і групами надається дві команди:

* Команда _налаштування_ (TUI)
* Команда _gtkusersetup_ (GUI) з піктограмою в Slint Control Center, категорія системи)

Ці команди дозволяють вам додавати або видаляти користувачів і групи користувачів, а також додавати користувачів до груп.

Пам’ятайте, що кожен обліковий запис користувача за замовчуванням пов'язаний з ним у каталозі /home . For instance if you add a user *leonie*, a /home/leonie folder will be created, to which only this user (and root) will be allowed to access.

=== Зміна основної мови системи

Для цього надаються дві команди:

* Команда _localesetup_ (TUI).
* Команда _gtklocalesetup_ (GUI) з піктограмою в Slint центрі керування, категорія налаштувань.

Майте на увазі, що ці налаштування змінює мову інтерфейсів програм, якщо вони інтернаціоналізовані, а не карту клавіатури (див. нижче).

Крім того, локалізовані пакунки (якщо вони доступні) відповідно до обраної мови вже встановлені в кінці установки Slint. Якщо потім змінити типову мову, вам потрібно буде встановити відповідні локалізовані пакети, якщо ви бажаєте.

Локалізоване означає, що "надається в даній місцевості", локаль є мовою, а також особливостями, пов’язаною з географічною зоною. Наприклад, португальська мова розмовляла в Португалії та Бразилії. В локалізованих пакетах l10n - це абревіатура "локалізація", що означає "буква l, 10 інших букв N".

Локалізовані пакети включені для багатьох мов. Їхня назва - базова назва пакету, дефіс, потім код мови. Ми перерахуємо нижче базових імен локалізованих пакетів:
[options="autowidth"]
|====
| Базова назва пакунку | Опис
| аспель | списки слів для перевірки правопису
| calligra-l0n | локалізований офісний пакет Calligra
| kde-l10n | локалізований робочий стіл KDE
| лібреофіс-l0н | локалізований офісний пакет
| libreoffice-help | локалізована допомога для LibreOffice
|====

Щоб знайти локалізований пакет, введіть в терміналі емулятор як корінь (наприклад kde-l10n): +
`spi libreoffice`

Це буде показувати список всіх локалізованих пакетів LibreOffice. Знайдіть того що хочете і встановіть його. Наприклад, для Перської мови код `fa` (короткий для Farsi), таким чином, щоб встановити його тип: +
`spi -i libreoffice-l0n-fa`

Якщо ви надаєте перевагу, ви можете використати `кляктейль`. Потім введіть назву пакунку в поле пошуку, щоб відобразити всі локалізовані пакунки libreoffice.

=== Зміна розкладки клавіатури

Ви можете змінити стандартну ключову мапу, що використовується в графічному режимі:

* Команда _клавіатура_ (TUI)
* Команда _gtkkeyboardsetup_ (GUI) з іконкою в Центрі керування Slint, категорія обладнання.

These commands also allow you to choose if numlock should be enabled when the system is started, and if the SCIM (input method) should be enabled at system startup.

Якщо ви використовуєте панель керування вікнами, ви також можете зробити цей параметр доступним натисненням правої кнопки на клавіатурі (що відображається за замовчуванням, як два літер код карти клавіатури в використанні). KDE і Xfce мають для цього особливі інструменти.

На командному рядку, але все ще для графічного режиму використовуйте замість setxbmap

Наприклад, щоб встановити розкладку клавіатури для української у графічному режимі, просто введіть як звичайний користувач: +
`setxkbmap -ua`

Щоб дізнатися більше, прочитайте людину сторінку для setxkbmap.

=== Встановлення принтера

У Slint сервер друку CUPS керує принтерами та друком завдань. У своїй стандартній конфігурації, записаний в файл /etc/cups/cupsd. у випадку, тільки користувачі, що належать до `sys` (короткий для _системи_) можуть виконувати адміністративні завдання, подобається додавання або видалення принтера.

Для простого налаштування (принтер прикріплений до настільного або ноутбука, а не використовується між машинами), вам просто потрібно додати одного користувача (який буде керувати принтерами) до `sys` групи. Наприклад додавання користувача _дільника_ до групи `sys` можна зробити два способи:

* В режимі консолі або на основі емулятора термінала стає коренем з `Су` і введіть:
+
`gpasswd --add didier sys`
+
* У графічному режимі з Центру керування Slint, натисніть на користувачів та групи (системна категорія), виберіть користувача і натисніть на Властивості, а потім на вкладці Групи перевірити `sys`. Або другий спосіб округлення (виберіть групу, а потім додайте до неї користувача).

Існує декілька способів додати і налаштувати принтер (це робиться користувачем групи `sys`):

* З Центру керування Slint, а складність категорії натисніть на Налаштування принтера, щоб відобразити графічний інтерфейс з можливістю простого налаштування...
* ... Або натисніть на Cups Print Управління веб-інтерфейсом для сервера CUPS. Також ви можете відобразити веб-інтерфейс до CUPS сервера ввівши `localhost:631` в поле адреси веб-браузера.
* If you have a Hewlett Packard device, make a right click on the *hp* logo in the notification area of the panel.

NOTE: Щоб зробити будь-яке налаштування CUPS сервера потрібно працювати. Він запущений, коли ви запускаєте Slint, якщо служба `чашки` в позначені серед системних сервісів (вона перевіряється за замовчуванням у Slint).

=== Налаштування звуку


У Slint застосунках або відправляють свої звукові дані до ALSA або в PulseAudio.

In the latter case PulseAudio in turn sends the output stream to an ALSA mixer which direct it to the sound cards.

As a result, a setting like an output sound volume can always be done by an ALSA mixer, and also by a PulseAudio mixer but only in case the application sends its sound output to PulseAudio.

Зараз ми презентуємо програму, що може використовуватися для зміни параметрів звуку

==== pavucontrol (для PulseAudio)

`pavucontrol` розшифровується як PulseAudio Control і є графічним додатком. You can start it from a terminal or application menu, or doing a right click on the sound mixer icon on the top panel of Mate. Насправді він дозволяє використовувати більше параметрів, ніж просто контроль гучності, потрібен час для вивчення всіх її функцій.

Ви також можете використовувати аплет контролю гучності в області сповіщень панелі: лівий клік дозволяє змінювати об'єм, клацніть правою кнопкою миші дає доступ до інших налаштувань і дозволяє запустити pavucontrol мікшер.

[[Sound_on_the_command_line]]

==== alsamixer  (for ALSA)

alsamixer - це ncurses додаток, що забезпечує напівавторинний інтерфейс користувача.

Щоб використовувати його тип: в консолі або в графічному терміналі:
----
alsamixer
----
тоді:

* Використовуйте клавішу вгору для збільшення гучності на 5%
* Використовуйте клавішу вниз для зменшення гучності на 5%
* натисніть Esc для виходу з додатку.

==== amixer (для ALSA)
Команда є форма:
----
amixer <arguments>`
----
Наприклад, щоб встановити основний обсяг на 70% тип:
----
Майстер sset amixer 70%
----
Щоб дізнатися більше, наберіть одну з цих команд:
----
людина-аміксер
мікрос -г
----
==== сам (оператор Speechly Alsa Mixer)
сама дозволяє вибирати звукову карту для роботи, коли на вашому комп'ютері є більше
таких пристроїв. +
Коли він є тільки один, він безпосередньо представляє різні мікшери
для конфігурації.

Усі виділення, це звукові картки, мікшери або дана властивість
 специфічний мікшер вибираються шляхом прокручування доступних опцій, використовуючи стрілки вгору та вниз, потім введіть бажаний: +
`q` залиште список вибору та / або вийти. +
`Shift-q` виходить з програми звідусіль. +
`F1` Показує будь-яку додаткову інформацію, якщо доступно.

Коли відомо ім'я бажаного варіанту, можна замість цього натиснути його
першу літеру. Перша літера навігації нечутлива до регістру.
Після цього ви потрапите до першого вибору, починаючи з натиснутого
листа.  Натиснувши цю ж літеру, ви знову перемістите вас на наступну опцію
почнеться з цієї літери в параметрі ifif, більш ніж одного типу.
Повторення букви буде циклічно серед усіх цих варіантів, які починаються з цієї
літери.

Настроювані функції мікшера можуть бути перераховані натисненням f1. +
їх представляють як список виборів, що відображають на короткий час всю відповідну інформацію. .
"Обсяг відтворення від 84 відсотків" параметр, щоб зменшити гучність відтворення
настройку гучності відтворення.  Як бачите, це також вказує на те, що таке
поточний параметр.

NOTE: Сам не працює правильно у графічному терміналі. Скористайтеся нею в консолі.

==== паміксер і понімікс (для PulseAudio)
Ці вміння схожі, з комментами в цій формі:
----
pamixer <arguments>
ponymix <arguments>
----
Наприклад, щоб встановити гучність на 70% для типового різновиду цієї команди:
----
pamixer --set-volume 7
встановлювання-гучність 8O
----
Щоб дізнатися більше типу:
----
pamixer -h
ponymix --help
----

==== pacmd і pactl (для PulseAudio)

Both of these command line applications control a running PulseЛяdio daemon.

WARNING: типізована лише пасма викликає інтерактивний діалог. Натисніть Ctrl+d, щоб вийти з нього, але не завершувати роботу з пакетом, який би вбив PulseAudio!

Знайте більше:
----
man pactl
man pacmd
pactl --help
pacmd --help
----

==== Зберегти та відновити рівень звуку

Просто зробіть файл виконуваним /etc/rc.d/rc.alsa виконуваним. Корінь:
----
chmod /etc/rc.d/rc.alsa
----
Під час запуску, цей скрипт відновить попередні налаштування звуку, якщо
вони були раніше збережені, інші встановлять типові гучність і зберігатимуть
їх, так що вони будуть відновлені при наступному перезавантаженні.

If you don't want that this script to set the default volume type as root:
----
сенсорний /var/lib/alsa/no.asound.state
----

Ви можете змінити стандартні рівні звуку за допомогою alsamixer або amixer
потім набирати права суперкористувача :
----
магазин alsactl
----
Після наступного запуску сценарій буде відновлювати їх.

Знайте більше:
----
man alsactl
----
=== Налаштування мережі

Якщо ви зробили'налаштуйте параметри мережі під час встановлення Slint, перший
стати корінням - набравши `Су -` або в консолі, або в графічному
терміналі, як в терміналі, потім введіть кореневий пароль.

Програмі налаштування мережі зроблено сценарієм `мережа`.
So you would just type the command `netsetup` in that
same terminal, where you've just aquired root privileges.
Спочатку ви попросите ім'я хоста вашого комп'ютера. ви можете вибрати будь-яке
ім'я, але зауважте, що воно має бути єдиним словом.
Тоді вас запитують доменне ім'я. Якщо машина не є сервером
, ви можете вибрати будь-кого.
Після цього вам буде запитано, як Ваш комп'ютер з'єднується з мережею. Якщо
у вас немає хорошої причини (не і ви знаєте, що робите), залишити
на пристрої `NetworkManager` , щоб автоматично налаштувати мережу.

Для дротових підключень, їх буде достатньо, щоб підключитись при наступному завантаженні
автоматично.

Щоб налаштувати бездротове з'єднання, дві команди доступні за допомогою
командного рядка.

Знову ж таки, ви можете набирати команди безпосередньо на консолі або в
графічному терміналі, як у терміналі парного терміну. Введіть їх як звичайного користувача не як.
Якщо ви виконували ці вказівки і вже отримали рут, ви просто
надрукуєте `` щоб отримати звичайний статус користувача.

The two mentioned commands are `nmtui` (dialog boxes) or `nmcli` (pure command line),
both are accessible.

Якщо ви надаєте перевагу роботі над командним рядком, спершу прочитайте документацію nmcli.
Просто введіть `nmcli --help` і `man nmcli`,
щоб дізнатися всі деталі.
While `nmcli` offers more possibilities, in most use-cases the functionality
of `nmtui` will be sufficient for setting up your wireless network, so we will
describe it here:

Використовуючи `nmtui`, ви можете переміщатися за допомогою клавіш для вкладок і стрілок.
Ви будете запропоновані три варіанти: +
`Редагувати підключення` +
`Активувати підключення` +
`Встановити системну назву` +

Якщо ще не встановлено бездротове з’єднання, оберіть `Активувати`.
Починаючи з самого низу, спочатку будуть показані дротові з'єднання (якщо такі є),
після чого буде доступно бездротові мережі.
Навігація з клавішами стрілок вниз і вгору для вибору потрібної мережі,
потім просто введіть Enter: ймовірно буде запитано пароль або ключ шифрування.
Введіть це, використовуйте клавішу вкладки щоб підтвердити, а потім вийдіть і зроблено.

У графічному режимі, замість `nmcli` або `nmtui` ви можете користуватися додатком
`nm-connection-editor`.

=== Керування сервісами

Якщо ви використовуєте режим вручну, вам було запитано, які системні служби активуються при запуску системи. +
Якщо ви використали настройки за замовчуванням авто

В обох випадках ви можете змінити ці налаштування кількома способами:

* Запуск як корінь команди `servicesetup` (TUI)
* In graphical mode only, using `gtkervicesetup`, accessible from the Slint Control Center, category System or typing Alt+F2 to raise a "Run..." dialog then tррing *gtksetrvicesetup*.
* ROOT виконання відповідного сценарію (chmod 755 <path to the script> або невиконуваний (chmod 644 <path to the script>). Наприклад, виконати помилку ви можете ввести `chmod 755 /etc/rc.d/rc.fail2ban`

[IMPORTANT]
====
Змінюйте стандартні налаштування лише якщо ви знаєте, що робите.
====

Сервіси керуються скриптами, ім'я яких починається з `rc.` в каталозі /etc/rc.d/. Наприклад, сервіс acpi управляється скриптом shell /etc/rc.acpi. Більшість послуг активуються при запуску, якщо виконаний відповідний скрипт. У таблиці нижче ми вказуємо, чи активована програма запуску (`` у стовпці А) або ні (`поза` у стовпці А). Якщо стовпець порожній, то активація послуг залежить від вибору, зробленого під час встановлення. В стовпці `` означає, що в режимі автоматичної установки послуга активована послуга, інакше активується при виборі користувача під час встановлення. Колонка пакунків вказує, який набір програм надає скрипт, відповідний сервісу, служби, трапляється регістр

[options="autowidth"]
|====
| *Service* | *A* | *Пакет* | *Призначення і коментарі*
| acpi | on | кислота | Розширені налаштування та інтерфейс живлення дозволяють наприклад керувати живленням або перезавантажити, натиснувши на кнопку
| alsa | on | alsa-utils | Вкажіть типові параметри звуку або відновіть збережені
| alsa-oss | вимкнено | alsa-utils | Модулі ядра ALSA LES. У мотових випадках вимкнено не корисно, якщо на Slint.
| аталек | вимкнено | ретатал | Дозволяє Unix-подібній операційній системі служити як файл, друкувати та часові сервери для Macintosh комп'ютерів.
| автоналаштування | вимкнено | автоналаштування | Автовизначення на основі кернеля для Linux
| bind | вимкнено | bind | Ім'я-сервер. Більшість користувачів буде покладатися на віддалений. Увімкніть його, якщо ви хочете запустити DNS-сервер в цій системі.
| bitlbee | on | bitlbee | BitlBee це IRC демон, який може говорити з мережами миттєвого обміну повідомленнями
       і діє як шлюз. Користувачі можуть підключатися до сервера з будь-яким звичайним
       клієнтом IRC і переглядати свій «друзі списку» в &бітрейт.
| bluetooth | on | блез | Дозволяє обмінюватися даними з пристроями bluetooth
| цеглини|  | цеглини | Дозволяє спілкуватися з терміналом Брайля або зчитуванням екрану. Активовано, якщо запит на встановлення
| cgconfig | on | групи libcgroups | Запускає утиліту cgconfig, що аналізує /etc/cgconfig. напроти налаштування ієрархії керуючих груп, у тому числі встановлення дозволів (UID та GID) для груп, що можуть змінювати параметри контролерів. Це вірює те, що ми робимо при кожному запуску, наприклад, він запускає окремі скрипти оболонки. This script is executable by default but anyway wвкл't do anything until /etc/cgconfig.conf be edited (all lines are commented out as shipped)
| процесор | вимкнено | процесор | Starts the cgmanager daemon that provides an alternate way to manage the cвклtrol group hierarchy through D-Bus requests possibly through the cgm front-end utility.
| проксі | вимкнено | процесор | Starts the cgproxy daemon, that allows programs and users in a cвклtainer to make cgroup administration requests using DBus calls, sending the user-ids or group-ids as SCM credentials to the cgmanager.
| гряжчик | on | групи libcgroups | Starts the cgroups rules engine daemвкл that automatically distributes to appropriate control groups the processes that changes their effective UID or GID, applying the rules found in /etc/cgrules.conf. This allows to cвклtinue apply resources control resources on such processes that could otherwise escape it. Цей скрипт виконуваний за замовчуванням, але в будь-якому випадку виграш't зробить що-небудь до /etc/cgrules.conf (всі рядки прокоментуються як відправлене)
| consolekit | on | ConsoleKit2 | Ця демона використовується системою polkit'для перевірки привілеїв користувача, що бажає перезавантажитись або завершити систему, наприклад.
| процесор | on | писемності сисвінітів | Налаштування частоти процесора і напруги масштабування в ядрі.
| чашки | on | чашки | сценарій запуску/вимкнення для сервера друку CUPS.
| cups-browsed | вимкнено | кекс-фільтри | Зробити доступним віддалені принтери доступними локально.
| dnsmask | вимкнено | dnsmask | Запустити/stop/restart dnsmasq (маленький DNS/DHCP-сервер)
| еспікація | | еспікація | почати/зупинити/перезапустити зчитувач консольного екрану espeakup. На випадок, якщо користувач видав запит мови під час встановлення або пізніше введений динамік з espeakup
| відмова 2 бан | вимкнено | відмова 2 бан | start/Зупиняє збої в бані, який сканує файли журналів як /var/log/pwdfail і забороняє IP з помилками паролю, та також оновлення брандмауера для відхилення IP-адреси.
| font | вимкнено | kbd | Sets the console fвклt (used in Console mode, not in Graphical mode)
| запалення | on | запалення | Завантажте fuse модуль та монтуйте файлову систему керування польотами. FUSE - це простий інтерфейс для програм, що експортують віртуальну файлову систему в ядро, що використовується Linux.  FUSE також спрямований на надання безпечного методу для створення та монтування своїх власних реалізацій файлової системи.
| фенрір | вимкнено | фенрір | початок/зупинка/перезавантажити зчитувач з екрана fenrir, який може бути розпочато після встановлення вихідного коду з fenrir.
| font | вимкнено | kbd | налаштувати шрифт для консолі
| gpm | вкл | gpm | Загальний сервер Purpose миші дозволяє вирізати і вставляти текст з екрану на консолі Linux.
| httpd | вимкнено | https | Запускає або припинить роботу веб-сервера Apache
| бездіяльність1 | on | мережні скрипти | Цей сценарій використовується для викладання різних мережевих інтерфейсів.
| не2 | вкл | мережні скрипти | Цей скрипт завантажує усю мережеву систему.
| inetd | вкл | inetd | BSD демон "super-server". Користувач повинен редагувати /etc/inetd.conf для надання послуг.
| ip_уперед | вимкнено | мережні скрипти | Запускати переадресацію IP-пакетів, необхідних для того щоб ваш комп'ютер діяв як маршрутизатор.
| карта ключів | on | installer | Завантажує клавіатурну карту яка використовується в режимі Консолі.
| місцевий | вимкнено | писемності сисвінітів | починається демони не запущено до/etc/rc.d/rc.M в часі завантаження.
| зациклити | on | писемності сисвінітів | Завантажує модуль ядра циклів.
| тип lxc | вимкнено | тип lxc | This scripts starts (if cвклfigured to be auto-started) and stops lxc containers.
| мселога | вимкнено | мселога | Запускає журнал помилок mcelog апарата. Це логи і обробляє апаратні помилки ЦП на системах x86
| автобус повідомлень | on | dbus | Система системного повідомлення DBUS. Це демон, який транслює повідомлення про події системи та інші повідомлення, забезпечує комунікацію між процесами.
| модулі | on | писемності сисвінітів | Compute the kernel modules dependencies and start other scripts that load modules not automatically loaded by eudev, possibly for specific kernel versiвклs
| локальні модулі | on | писемності сисвінітів | Завантажити модулі не завантажені автоматично через eudev
| murmur | вимкнено | murmur | Запустити/зупинити мурмутника голосового чату для м'юмбаргу
| mysqld | вимкнено | mariadb | Запустити/зупинити сервер MariaDB. MariaDB є форком повністю сумісного з ним
| мережевий менеджер|  | Мережевий менеджер | This is a daemon for automatically switching network cвклnectiвклs to the best available cвклnection. Activated if NetworkManager is chosen to configure the network, during or after installatiвкл
| nfsd | вимкнено | німба присипування | Запустити/зупинити nfs (Мережевий сервер.qq
| ntpd | on | ntp | Запускає ntp ( Мереж'робочий час протокол).
| цифровий замок|  | salixtools | Activate numlock вкл the console
| шм | вимкнено | pcmciautils | Скрипт для ініціалізації підсистеми PCMCIA.
| php-fpm | вимкнено | php | Запускає PHP-демон FastCGI Process daemon.
| pulseaudio | вимкнено | pulseaudio | Запускає пульсаційну систему аудіо. Не рекомендується в Slint.
| rpc | вимкнено | rpcbind | Start/stop/restart RPC (remote process communications) daemвклs needed to use NFS. Щоб запустити NFS-сервер, розпочати це є обов'язковим.
| Самба | вимкнено | Самба | Запустити/зупинити файл Samba SMB CIFS і роздрукувати сервер для клієнтів CIFS.  Дозволяє робити файл простору або принтери на хості Samba доступними для клієнтів CIFS (наприклад, для PC, які працюють Windows).
| салотт | вимкнено | кірус-ссл | saslauthd is a daemon process that handles plaintext authentication requests вкл behalf of the SASL library.  Бібліотека CMU Cyrus SASL зазвичай використовується для автентифікації на поштових серверах.
| відправник | вимкнено | відправник | Запустити/зупинити/перезапустити Sendmail MTA (поштовий агент або систему доставки).
| послідовний | вимкнено | util-linux | Ініціалізує і встановлює послідовні порти у вашій системі
| значення | вкл |util-linux |  Забезпечує командний рядок для встановлення опцій терміналу властивостей (в першу чергу використовується для очищення екрану та керування живленнями).
| розумний | вимкнено | smartmontools | Запустити/зупинити смартфона демона, що стежить за статусом S.M.A.R.T. сумісний жорсткий диск та доповідає про будь-які проблеми.
| шд | on | пиріг | Запустити/зупинити/перезапустити безпечний сервер
| snmpd | вимкнено | витримка |Запустити/зупинити службу net-snmp SNMP (Simple Management Network Protocol)
| syslog | on | sysklogd | Запуск/зупинка запуску системної служби журналювання ядра та системи'веде повідомлення.
| sysstat | вкл | захід | Скидання логів активності системи, використовуватиметься для обчислення статистики продуктивності
| говорити |  | говорити | початок/зупинка/перезапуск зчитування екранів з мовлення, яке може бути розпочато після того, як почнеться установка виводить мовний звук.
| сисвініт | on | писемності сисвінітів | Цей файл забезпечує базову сумісність з запущеними скриптами системного стилю знайдених у багатьох двійкових пакетах
| swapinzram | on | swapinzram | Настройка пристрою своп в ОЗУ за допомогою zram
| syslog | on | syslogd | Запуск/зупинка/перезавантажити системні служби журналювання.
| sysstat | вимкнено | sysstat | Скинути журнали активності системи.
| боязкість | вимкнено | TiMidity++ | Start/stop/restart the TiMidity++ ALSA sequencer client. TiMidity++ is a software synthesizer.  Він може програвати файли MIDI, перетворюючи їх на дані форматів PCM на інші аудіо-файли.
| udev | on | евдев | Цей скрипт ініціалізує udev, яка заповнює каталог /dev вузлів пристрою, сканує для пристроїв,
завантажує відповідні модулі ядра і налаштовує пристрій.
| ulogd | on | ulogd | запускає користувацький простір ulogd демона для мережевого фільтра/iptables пов'язаного з журналом.
| vde2 | вкл | vde2 | Запустити/stop/restart перемикач VDE. VDE є ethernet сумісною віртуальною мережею, яка включає в себе інструменти, такі як 'vde_switch' та 'vdeqemu'.
| бездротовий доступ | on | бездротові інструменти|Цей сценарій встановлює для ПК та 32-бітних бездротових пристроїв у картонному автобусі. Зазвичай ця писемність називається з rc.inet1 замість того, щоб запускати безпосередньо
| yp | on | yptools | Start NIS (Network Information Послугаs). NIS provides network-wide distributiвкл of hostname, username, and other information databases.
|====

Ви можете запустити або перестати службу, використовуючи як root-права, `службу`. Щоб дізнатися більше типу `службу`.

== Словник

Several definitiвклs in this glossary are taken or adapted from  https://en.wikipedia.org/wiki/Main_Page[Wikipedia] and https://pubs.opengroup.org/onlinepubs/9699919799/[POSIX]

[[applicatiвкл]]Програма:: An applicatiвкл program (applicatiвкл for short) is
a computer program designed to carry out a specific task typically requested by
end-users.
+
Applications are not generally cвклsidered as part of the operating system, meaning that they can be added to the system after its installation. They
perform non-system-related functiвклs, such as word processing, architectural
design, mechanical design, workstation publishing, or financial analysis.


[[boot]]Завантаження::
Boot means switch-вкл a computer to start an operating system. Деякі операційні
можуть бути встановлені на одному комп'ютері. Select which one to load into
RAM and run can be dвклe either by the firmware or by a software named boot
manager (GRUB in Slint's case). The firmware of a computer can support вклe of following booting mode, or both:
+
* In the Legacy or BIOS mode the OS is loaded executing the instructiвклs written in a boot sector.
* У режимі EFI завантажувач для ОС - це програма, яка зберігається у виконуваному файлі, розташованому в каталозі розділу системи EFI (ESP).

[[ЦП]]CPU::
ЦП або Центральний процесор виконує інструкції програм.

[[command]]Команда:: Команда визначається https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_104[POSIX] як "директива <<shell, оболонці>> для виконання конкретного завдання ".
+
Завдання для виконання може бути <<application, додатком>> або <<utility, утилітою>>.
+
Базова структура команд shell визначена у розділі https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09[2.9 Shell Commands] специфікації POSIX.
+
Приклади команд удаються в <<bash shell>>.

[[console]]Консоль:: Слово "консоль" означає початок систем
комп’ютера, коли системний адміністратор надрукував команди на пристрої, включаючи
клавіатуру і принтер, пов'язані з комп'ютером, команди введені і на виході
з комп'ютера роздрукованого на консолі, містять у собі журнал обох.
+
У особистих комп'ютерах користувач введе команди на клавіатурі і її виведення
на екрані, які можна розділяти або інтегруватись на
комп’ютер як у ноутбуці.

[[device]]Пристрій::

Комп'ютер периферійний або об'єкт, який виглядає в програмі як такий.[POSIX]

[[directory]]Каталог::
Директорія - це інша назва теки. Файлові системи використовують
папки для організації файлів в розділах.
+
Директорії можуть містити файли, а також інші каталоги. Отримана
структура може бути представлена як дерево upside-down. Каталог
на верхньому рівні є кореневим каталогом автомобіля.  В Linux персонаж / розділяє
рівні дерева. / один з кореневих каталогів, /home розмістив файли
які належать користувачам, /home/didier hosts, які належать власнику користувачів.
/root розміщує файли користувача root (система'адміністратор).
Примітка: "root" може посилатись на каталог верхнього рівня, або на систему'адміністратора.

[[drive]]Драйв::
Диск це пристрій, який зберігає неволатильні дані, тобто дані не будуть
стерті після вимкнення живлення. Приклади: жорсткі диски, SSD, USB стіки, SD
карти і зчитування eMMC.
+
Носій даних можна остаточно зберегти до диску чи до нього
, такі як SD-карти, палички USB та під'єднується через USB.
+
Встановлена операційна система у змінних носіях або зовнішньому диску вказано
портативно: її можна перемістити з комп'ютера на інший.

[[display_manager]]Дисплей::
Менеджер по відображенню (або менеджер входів) є програмним забезпеченням, що відображає вікно на екрані
, в якому він запитує ім'я користувача і пароль користувача, потім запускається
графічне середовище обране користувачем на тому ж місці.

[[encryption]]Шифрування::
Шифрування це процес перетворення даних в нерозпізнаний ("зашифрований")
форму. Зазвичай використовується для захисту конфіденційної інформації, тому лише
авторизованих осіб можуть переглядати її. Один файл або каталог, розділ також
у вигляді зашифрованого диску, який робить його доступним тільки після того, як
ввели маленький текст, під назвою секретна фраза, зберегти секрет.

[[file]]Файл::
Комп'ютерний файл - це набір цифрових даних, зібраних під тим самим іменем, записаних на постійному носії зберігання, називається масове сховище, наприклад важкий диск, SSD, DVD, SD-карта або USN палички і обробляється як одиниця.
+
Файли можуть містити дані, такі як тексти, зображення, звуки, відео чи комп'ютерні програми.

[[file_system]]Файлова система::
Файлова система - це програмне забезпечення, яке управляє файлами і каталогами в розділі.
Він використовує розташування у фізичних носіях даних, що міститься у файлах, що дозволяє їх читати або писати.
Прикладами зазвичай,використаних файлових систем є vfat, ntfs, ext4, f2fs. Ця команда спискає всі файли
системи що дозволяють читати дані, що містяться в секції Linux:
+
----
кіт /proc/filesystems|зелені -v вузли
----

[[firmware]]Прошивка::
Прошивка - це програмне забезпечення яке ініціалізує та перевіряє обладнання, а потім
вибирає і завантажує ОЗУ операційну систему, або починається програмне забезпечення під назвою
менеджер завантажень, який буде це робити. Прошивка зберігається в немінній пам'яті
пристроях, наприклад ROM, EPROM або флеш-пам'яті. Це перший запуск програмного забезпечення при
при завантаженні комп'ютера. Він надає меню з можливістю налаштування обладнання і
, виберіть в якому режимі (Застарілий або EFI) для завантаження, і в якому порядку шукати
операційну систему або іншу програму (як менеджер завантажень GRUB).

[[kernel]]Kernel::
Ядро Лінукса - це програмне забезпечення для ядра системи Slint, яка обробляє
взаємодію між додатками та обладнанням.
+
Вона представляє себе як один файл, встановлений в каталозі /boot. Наприклад, файл /boot/vmlinuz-generic-5.12.11 - це ядро, що починається з ядра.
+
На початку ядра скопійовано до пам'яті (RAM).

[[initrd]]Initrd::
За допомогою інтитрангу (більш точним чином initramfs або початковою файловою системою RAM для Slint) є
система Linux, що надається як стиснутий архів. Під час завантаження, одразу після того, як ядро
ядро було завантажено і в оперативну пам'ять. Її файл /init
запущених: він завантажує необхідні модулі ядра у оперативну пам'ять, реєструє пристрої, можливо
розблокування кореневого пристрою, монтувати псевдо-файлову систему, потім переключитися на кореневу систему
, щоб запустити систему.
+
Дитина представляє себе як один файл, встановлений у завантаженні папки.
Наприклад, файл initrd-generic-5.12.11 є initron

[[live_system]]Жива система::
Жива система - це операційна система, яку замість встановлення на пристрої
шляхом жорсткого диска або SSD, лежить повністю у <<RAM>>.
+
An initrd is also a live system, and so is a Slint інсталятор wich is basically an initrd.

[[partition]]Розділ::
Розділ - це розділ зберігання медіа, таких як жорсткий диск або SSD.
розглядати операційну систему як окремий логічний об'єм, що робить її
подібною до окремих засобів масової інформації.

[[partition_table]]Таблиця розділів::
A partition table is the permanent structure recording how information is laid
out on a media, mainly recording the beginning and end of each partition on
the media.
+
The most common types of partition tables are the DOS partition table, initially
used by the MS-DOS operating system, and the GUID Partition Table or GPT, which
allows to handle more partitions and larger drives.

[[program]]Програма::
A prepared sequence of instructions to the system to accomplish a defined task. The term "program" encompasses applications written in the Shell Command Language, complex utility input languages (for example, awk, lex, sed, and so on), and high-level languages. [POSIX]

[[RAM]]RAM::
ОЗП означає Пам'ять Випадкового Доступу. Цей вид пристрою зберігає мінливі дані,
означає, що дані будуть стерті при вимкненому живленні.

[[shell]]Оболонка:: Програма, яка інтерпретує послідовність введення тексту як команди. Він може працювати на вхідному потоці або може інтерактивно запитувати команди і читати команди з терміналу. The syntax of the commands
that can be interpretd by the shell can vary along the shell in use but are mainly defined in the the chapter
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[2.
Shell Command Language] of the POSIX specification.
+
Slint ships several programs acting as shell, listed in the file /etc/shells. The *bash* shell is used by default.

[[swap]]Поміняти::
Обміняти місце для зберігання даних, раніше в оперативній пам'яті пристрою
типу жорсткого диску чи SSD, або через те, що оперативна пам'ять стануть повними або
вільним простором у оперативній пам'яті для зберігання найбільш часто використовуваних даних. The swap space can
be a partition on a drive of type 'Linux swap' or a regular file stored in an
an existing partition. Також є 'swap in zram': у даному випадку дані
зберігаються в оперативній пам'яті, але у стиснутому вигляді, до придатного розміру оперативної пам'яті.

[[terminal]]Термінал::
Historically a terminal was a physical device composed of a keyboard and a screen
used to type commands and receives responses from a remote computer.
+
Nowadays the commands can be typed in console (or text) mode or in graphical
mode.

[[utility]]Службові програми::
Уміння - це програма, яка може бути викликана іменем з оболонки (це також трапляється з деяких <application,applications>>).
+
Utilities are a part of the operating system (but not of the kernel).
They perform system-related functions, such as listing directory contents,
checking file systems, repairing file systems, or
extracting system status information.
+
An utility may be invoked as a separate program that executes in a different
process than the command language interpreter, or it may be implemented as a
part of the command language interpreter.
+
For example, the echo command (the
directive to perform a specific task) may be implemented such that the echo
utility (the logic that performs the task of echoing) is in a separate program;
therefore, it is executed in a process that is different from the command
language interpreter. Practically this means this means that in this case the utility is a program distinct from the shell
+
Conversely, the logic that performs the echo utility
could be built into the command language interpreter; therefore, it could
execute in the same process as the command language interpreter. Such an utility is said "built-in" the shell.

[[virtual_terminal]]Віртуальний термінал::
Віртуальний термінал - це програмне забезпечення, яке симулює фізичний термінал, пристрій
складається з клавіатури і екрана, що дозволяє дистанційно спілкуватися за допомогою
комп"ютера.
